import type { QA } from "./types";

export const ARTE: QA[] = [
  { id: "arte_A_001", topic: "arte", letter: "A", question: "Con la A: Técnica pictórica con pigmentos diluidos en agua.", answer: "Acuarela" },
  { id: "arte_A_002", topic: "arte", letter: "A", question: "Con la A: Arte y técnica de diseñar y construir edificios.", answer: "Arquitectura" },
  { id: "arte_A_003", topic: "arte", letter: "A", question: "Con la A: Pieza cerámica decorativa típica en España y Portugal.", answer: "Azulejo" },
  { id: "arte_A_004", topic: "arte", letter: "A", question: "Con la A: Producción manual de objetos con valor estético y cultural.", answer: "Artesanía" },
  { id: "arte_A_005", topic: "arte", letter: "A", question: "Con la A: Estilo que no representa la realidad de forma literal.", answer: "Abstracto" },
  { id: "arte_A_006", topic: "arte", letter: "A", question: "Con la A: Pintura de secado rápido usada en arte contemporáneo.", answer: "Acrílico" },
  { id: "arte_A_007", topic: "arte", letter: "A", question: "Con la A: Imagen distorsionada que se corrige desde un ángulo.", answer: "Anamorfosis" },
  { id: "arte_A_008", topic: "arte", letter: "A", question: "Con la A: Mesa o plataforma elevada donde se realizan ofrendas religiosas.", answer: "Altar" },
  { id: "arte_A_009", topic: "arte", letter: "A", question: "Con la A: Pintora barroca italiana conocida por sus representaciones de heroínas bíblicas.", answer: "Artemisia" },
  { id: "arte_A_010", topic: "arte", letter: "A", question: "Con la A: Cueva cántabra con arte rupestre prehistórico.", answer: "Altamira" },
  { id: "arte_A_011", topic: "arte", letter: "A", question: "Con la A: Conjunto palaciego con decoración nazarí en Granada.", answer: "Alhambra" },
  { id: "arte_A_012", topic: "arte", letter: "A", question: "Con la A: Institución cultural asociada a exposiciones y debate artístico.", answer: "Ateneo" },
  { id: "arte_A_013", topic: "arte", letter: "A", question: "Con la A: Estilo decorativo del siglo XX .", answer: "ArtDeco" },
  { id: "arte_A_014", topic: "arte", letter: "A", question: "Con la A: Representación simbólica de ideas mediante figuras.", answer: "Alegoría" },
  { id: "arte_A_015", topic: "arte", letter: "A", question: "Con la A: Princesa cretense que ayudó a Teseo a salir del laberinto del Minotauro.", answer: "Ariadna" },
  { id: "arte_B_001", topic: "arte", letter: "B", question: "Con la B: Estilo europeo del siglo XVII de dramatismo y movimiento.", answer: "Barroco" },
  { id: "arte_B_002", topic: "arte", letter: "B", question: "Con la B: Género pictórico de naturalezas muertas.", answer: "Bodegón" },
  { id: "arte_B_003", topic: "arte", letter: "B", question: "Con la B: Término que designa las artes visuales como pintura, escultura y arquitectura.", answer: "BellasArtes" },
  { id: "arte_B_004", topic: "arte", letter: "B", question: "Con la B: Dibujo preliminar antes de una obra final.", answer: "Boceto" },
  { id: "arte_B_005", topic: "arte", letter: "B", question: "Con la B: Escultura de cabeza y torso.", answer: "Busto" },
  { id: "arte_B_006", topic: "arte", letter: "B", question: "Con la B: Escuela alemana clave en diseño y arquitectura moderna.", answer: "Bauhaus" },
  { id: "arte_B_007", topic: "arte", letter: "B", question: "Con la B: Escultor barroco italiano autor del Éxtasis de Santa Teresa.", answer: "Bernini" },
  { id: "arte_B_008", topic: "arte", letter: "B", question: "Con la B: Pintor renacentista italiano autor de El nacimiento de Venus.", answer: "Botticelli" },
  { id: "arte_B_009", topic: "arte", letter: "B", question: "Con la B: Pintor flamenco del siglo XVI conocido por La torre de Babel.", answer: "Bruegel" },
  { id: "arte_B_010", topic: "arte", letter: "B", question: "Con la B: Estilo de mosaicos e iconos del Imperio Bizantino.", answer: "Bizantino" },
  { id: "arte_B_011", topic: "arte", letter: "B", question: "Con la B: Mueble español decorativo  del Renacimiento.", answer: "Bargueño" },
  { id: "arte_B_012", topic: "arte", letter: "B", question: "Con la B: Edificio religioso de gran tamaño con planta rectangular y naves laterales.", answer: "Basílica" },
  { id: "arte_B_013", topic: "arte", letter: "B", question: "Con la B: Técnica textil de tintado por reservas con cera.", answer: "Batik" },
  { id: "arte_B_014", topic: "arte", letter: "B", question: "Con la B: Aleación de cobre y estaño usada en escultura desde la antigüedad.", answer: "Bronce" },
  { id: "arte_B_015", topic: "arte", letter: "B", question: "Con la B: Danza clásica de origen francés con movimientos codificados y puntas.", answer: "Ballet" },
  { id: "arte_C_001", topic: "arte", letter: "C", question: "Con la C: Vanguardia que fragmenta la forma; asociada a Picasso y Braque.", answer: "Cubismo" },
  { id: "arte_C_002", topic: "arte", letter: "C", question: "Con la C: Iglesia principal de una diócesis, sede del obispo.", answer: "Catedral" },
  { id: "arte_C_003", topic: "arte", letter: "C", question: "Con la C: Pintor italiano barroco conocido por su uso dramático de luz y sombra.", answer: "Caravaggio" },
  { id: "arte_C_004", topic: "arte", letter: "C", question: "Con la C: Parte superior decorada de una columna.", answer: "Capitel" },
  { id: "arte_C_005", topic: "arte", letter: "C", question: "Con la C: Estructura arquitectónica semiesférica.", answer: "Cúpula" },
  { id: "arte_C_006", topic: "arte", letter: "C", question: "Con la C: Arte de modelar y cocer arcilla.", answer: "Cerámica" },
  { id: "arte_C_007", topic: "arte", letter: "C", question: "Con la C: Arte de la escritura bella y expresiva.", answer: "Caligrafía" },
  { id: "arte_C_008", topic: "arte", letter: "C", question: "Con la C: Técnica que combina recortes y materiales en una obra.", answer: "Collage" },
  { id: "arte_C_009", topic: "arte", letter: "C", question: "Con la C: Contraste fuerte de luz y sombra en pintura.", answer: "Claroscuro" },
  { id: "arte_C_010", topic: "arte", letter: "C", question: "Con la C: Uso expresivo del color.", answer: "Cromatismo" },
  { id: "arte_C_011", topic: "arte", letter: "C", question: "Con la C: Arte donde la idea prima sobre el objeto.", answer: "Conceptual" },
  { id: "arte_C_012", topic: "arte", letter: "C", question: "Con la C: Arte audiovisual que combina imagen en movimiento y sonido.", answer: "Cine" },
  { id: "arte_C_013", topic: "arte", letter: "C", question: "Con la C: Arte del cartel, clave en diseño gráfico.", answer: "Cartelismo" },
  { id: "arte_C_014", topic: "arte", letter: "C", question: "Con la C: Columna con forma de figura humana .", answer: "Cariatide" },
  { id: "arte_C_015", topic: "arte", letter: "C", question: "Con la C: Enfoque artístico centrado en el color.", answer: "Colorismo" },
  { id: "arte_D_001", topic: "arte", letter: "D", question: "Con la D: Técnica base de línea y forma para representar o diseñar.", answer: "Dibujo" },
  { id: "arte_D_002", topic: "arte", letter: "D", question: "Con la D: Pintor surrealista español autor de La persistencia de la memoria.", answer: "Dalí" },
  { id: "arte_D_003", topic: "arte", letter: "D", question: "Con la D: Proceso de planificación y creación de objetos funcionales y estéticos.", answer: "Diseño" },
  { id: "arte_D_004", topic: "arte", letter: "D", question: "Con la D: Aplicación de oro en retablos y artes decorativas.", answer: "Dorado" },
  { id: "arte_D_005", topic: "arte", letter: "D", question: "Con la D: Obra compuesta por dos paneles.", answer: "Díptico" },
  { id: "arte_D_006", topic: "arte", letter: "D", question: "Con la D: Tejido decorativo asociado a artes textiles.", answer: "Damasco" },
  { id: "arte_D_007", topic: "arte", letter: "D", question: "Con la D: Artista renacentista italiano autor de La última cena y La Gioconda.", answer: "DaVinci" },
  { id: "arte_D_008", topic: "arte", letter: "D", question: "Con la D: Transición gradual entre tonos o colores.", answer: "Degradado" },
  { id: "arte_D_009", topic: "arte", letter: "D", question: "Con la D: Técnica de goteo de pintura asociada a Pollock.", answer: "Dripping" },
  { id: "arte_D_010", topic: "arte", letter: "D", question: "Con la D: Término italiano para catedral, como el Duomo de Florencia.", answer: "Duomo" },
  { id: "arte_D_011", topic: "arte", letter: "D", question: "Con la D: Arte de escribir obras teatrales.", answer: "Dramaturgia" },
  { id: "arte_D_012", topic: "arte", letter: "D", question: "Con la D: Orden arquitectónico clásico griego.", answer: "Dórico" },
  { id: "arte_D_013", topic: "arte", letter: "D", question: "Con la D: En pintura, separación de color .", answer: "División" },
  { id: "arte_D_014", topic: "arte", letter: "D", question: "Con la D: Efecto visual de expansión; se usa en composición .", answer: "Dilatación" },
  { id: "arte_D_015", topic: "arte", letter: "D", question: "Con la D: Tensión sonora en música; influye en arte audiovisual y escénico.", answer: "Disonancia" },
  { id: "arte_E_001", topic: "arte", letter: "E", question: "Con la E: Arte de crear formas en tres dimensiones.", answer: "Escultura" },
  { id: "arte_E_002", topic: "arte", letter: "E", question: "Con la E: Movimiento que deforma para expresar emoción.", answer: "Expresionismo" },
  { id: "arte_E_003", topic: "arte", letter: "E", question: "Con la E: Transición suave de sombras; técnica asociada a DaVinci.", answer: "Esfumado" },
  { id: "arte_E_004", topic: "arte", letter: "E", question: "Con la E: Imagen impresa; grabado o litografía.", answer: "Estampa" },
  { id: "arte_E_005", topic: "arte", letter: "E", question: "Con la E: Técnica de color vitrificado en metal o cerámica.", answer: "Esmalte" },
  { id: "arte_E_006", topic: "arte", letter: "E", question: "Con la E: Concepto en arte cinético y performance .", answer: "Energía" },
  { id: "arte_E_007", topic: "arte", letter: "E", question: "Con la E: Técnica con cera caliente y pigmentos.", answer: "Encausto" },
  { id: "arte_E_008", topic: "arte", letter: "E", question: "Con la E: Reflexión sobre belleza y arte.", answer: "Estética" },
  { id: "arte_E_009", topic: "arte", letter: "E", question: "Con la E: Torre de hierro de 300 metros construida en París para la Exposición Universal de 1889.", answer: "Eiffel" },
  { id: "arte_E_010", topic: "arte", letter: "E", question: "Con la E: Pintor cretense del siglo XVI afincado en Toledo, autor de El entierro del conde de Orgaz.", answer: "ElGreco" },
  { id: "arte_E_011", topic: "arte", letter: "E", question: "Con la E: Recurso de perspectiva para cuerpos en ángulo.", answer: "Escorzo" },
  { id: "arte_E_012", topic: "arte", letter: "E", question: "Con la E: En arte, mirada cultural; influencia en museos y colecciones.", answer: "Etnografía" },
  { id: "arte_E_013", topic: "arte", letter: "E", question: "Con la E: Artesano especializado en muebles finos.", answer: "Ebanista" },
  { id: "arte_E_014", topic: "arte", letter: "E", question: "Con la E: Capa gruesa de pintura .", answer: "Empaste" },
  { id: "arte_E_015", topic: "arte", letter: "E", question: "Con la E: Diseño visual de un escenario teatral o audiovisual.", answer: "Escenografía" },
  { id: "arte_F_001", topic: "arte", letter: "F", question: "Con la F: Pintura mural sobre yeso húmedo.", answer: "Fresco" },
  { id: "arte_F_002", topic: "arte", letter: "F", question: "Con la F: Movimiento de color intenso .", answer: "Fauvismo" },
  { id: "arte_F_003", topic: "arte", letter: "F", question: "Con la F: Arte y técnica de capturar imágenes con luz.", answer: "Fotografía" },
  { id: "arte_F_004", topic: "arte", letter: "F", question: "Con la F: Vanguardia que celebra velocidad y modernidad.", answer: "Futurismo" },
  { id: "arte_F_005", topic: "arte", letter: "F", question: "Con la F: Estilo artístico que representa formas reconocibles de la realidad.", answer: "Figuración" },
  { id: "arte_F_006", topic: "arte", letter: "F", question: "Con la F: Arte andaluz  con fuerte componente escénico.", answer: "Flamenco" },
  { id: "arte_F_007", topic: "arte", letter: "F", question: "Con la F: Trabajo artístico del metal a golpes.", answer: "Forja" },
  { id: "arte_F_008", topic: "arte", letter: "F", question: "Con la F: Construcción arquitectónica que expulsa agua, común en plazas y jardines.", answer: "Fuente" },
  { id: "arte_F_009", topic: "arte", letter: "F", question: "Con la F: Artista italiano del siglo XX conocido por hacer cortes en lienzos.", answer: "Fontana" },
  { id: "arte_F_010", topic: "arte", letter: "F", question: "Con la F: Pieza decorativa antigua; joyería y artes aplicadas.", answer: "Fíbula" },
  { id: "arte_F_011", topic: "arte", letter: "F", question: "Con la F: Material usado en artes textiles y contemporáneas.", answer: "Fieltro" },
  { id: "arte_F_012", topic: "arte", letter: "F", question: "Con la F: Publicación artesanal ligada a cultura visual.", answer: "Fanzine" },
  { id: "arte_F_013", topic: "arte", letter: "F", question: "Con la F: Ciudad italiana de la Toscana, cuna del Renacimiento.", answer: "Firenze" },
  { id: "arte_F_014", topic: "arte", letter: "F", question: "Con la F: Patrón repetido; inspiración en arte digital.", answer: "Fractal" },
  { id: "arte_F_015", topic: "arte", letter: "F", question: "Con la F: Trabajo ornamental fino, especialmente en metal.", answer: "Filigrana" },
  { id: "arte_G_001", topic: "arte", letter: "G", question: "Con la G: Estilo medieval de arcos apuntados y grandes vidrieras.", answer: "Gótico" },
  { id: "arte_G_002", topic: "arte", letter: "G", question: "Con la G: Técnica de impresión desde una matriz .", answer: "Grabado" },
  { id: "arte_G_003", topic: "arte", letter: "G", question: "Con la G: Arquitecto catalán del modernismo .", answer: "Gaudí" },
  { id: "arte_G_004", topic: "arte", letter: "G", question: "Con la G: Pintor español autor de Los fusilamientos del 3 de mayo y La maja desnuda.", answer: "Goya" },
  { id: "arte_G_005", topic: "arte", letter: "G", question: "Con la G: Obra de Picasso sobre la guerra.", answer: "Guernica" },
  { id: "arte_G_006", topic: "arte", letter: "G", question: "Con la G: Arte urbano en muros y espacios públicos.", answer: "Grafiti" },
  { id: "arte_G_007", topic: "arte", letter: "G", question: "Con la G: Uso de formas geométricas en composición y diseño.", answer: "Geometría" },
  { id: "arte_G_008", topic: "arte", letter: "G", question: "Con la G: Espacio de exhibición y venta de arte.", answer: "Galería" },
  { id: "arte_G_009", topic: "arte", letter: "G", question: "Con la G: Tipo de cerámica de alta cocción.", answer: "Gres" },
  { id: "arte_G_010", topic: "arte", letter: "G", question: "Con la G: Tapiz decorativo de tradición europea.", answer: "Gobelino" },
  { id: "arte_G_011", topic: "arte", letter: "G", question: "Con la G: Imprimación para preparar lienzos.", answer: "Gesso" },
  { id: "arte_G_012", topic: "arte", letter: "G", question: "Con la G: Primer libro de la Biblia que narra la creación del mundo.", answer: "Génesis" },
  { id: "arte_G_013", topic: "arte", letter: "G", question: "Con la G: Estilo basado en gesto y trazo .", answer: "Gestual" },
  { id: "arte_G_014", topic: "arte", letter: "G", question: "Con la G: Manufactura francesa famosa por tapices .", answer: "Gobelins" },
  { id: "arte_G_015", topic: "arte", letter: "G", question: "Con la G: Arte del grabado en piedras preciosas.", answer: "Glíptica" },
  { id: "arte_H_001", topic: "arte", letter: "H", question: "Con la H: Museo de SanPetersburgo con colecciones de arte.", answer: "Hermitage" },
  { id: "arte_H_002", topic: "arte", letter: "H", question: "Con la H: Estilo que busca apariencia fotográfica.", answer: "Hiperrealismo" },
  { id: "arte_H_003", topic: "arte", letter: "H", question: "Con la H: Pintor renacentista alemán conocido por retratar a Enrique VIII de Inglaterra.", answer: "Holbein" },
  { id: "arte_H_004", topic: "arte", letter: "H", question: "Con la H: Artista británico del siglo XVIII conocido por sus series satíricas de grabados.", answer: "Hogarth" },
  { id: "arte_H_005", topic: "arte", letter: "H", question: "Con la H: Artista japonés del siglo XIX autor de La gran ola de Kanagawa.", answer: "Hokusai" },
  { id: "arte_H_006", topic: "arte", letter: "H", question: "Con la H: Relacionado con el arte de la Grecia antigua.", answer: "Helénico" },
  { id: "arte_H_007", topic: "arte", letter: "H", question: "Con la H: Instrumento de trabajo artístico .", answer: "Herramienta" },
  { id: "arte_H_008", topic: "arte", letter: "H", question: "Con la H: Elemento básico de artes textiles.", answer: "Hilo" },
  { id: "arte_H_009", topic: "arte", letter: "H", question: "Con la H: Material en escultura, arquitectura y forja.", answer: "Hierro" },
  { id: "arte_H_010", topic: "arte", letter: "H", question: "Con la H: Material usado en arte popular y objeto encontrado.", answer: "Hojalata" },
  { id: "arte_H_011", topic: "arte", letter: "H", question: "Con la H: Obras que mezclan medios: foto, pintura, video.", answer: "Híbrido" },
  { id: "arte_H_012", topic: "arte", letter: "H", question: "Con la H: Técnica de líneas paralelas en dibujo y grabado.", answer: "Hachurado" },
  { id: "arte_H_013", topic: "arte", letter: "H", question: "Con la H: Equipo para cocer cerámica y vidrio.", answer: "Horno" },
  { id: "arte_H_014", topic: "arte", letter: "H", question: "Con la H: Filosofía que busca el placer como fin último de la vida.", answer: "Hedonismo" },
  { id: "arte_H_015", topic: "arte", letter: "H", question: "Con la H: Factor que afecta conservación de obras.", answer: "Humedad" },
  { id: "arte_I_001", topic: "arte", letter: "I", question: "Con la I: Movimiento francés centrado en luz y pincelada.", answer: "Impresionismo" },
  { id: "arte_I_002", topic: "arte", letter: "I", question: "Con la I: Imagen religiosa pintada sobre tabla en la tradición ortodoxa.", answer: "Icono" },
  { id: "arte_I_003", topic: "arte", letter: "I", question: "Con la I: Disciplina que estudia el significado de los símbolos en obras de arte.", answer: "Iconografía" },
  { id: "arte_I_004", topic: "arte", letter: "I", question: "Con la I: Dibujo aplicado a libros, prensa y comunicación visual.", answer: "Ilustración" },
  { id: "arte_I_005", topic: "arte", letter: "I", question: "Con la I: Obra que ocupa un espacio y crea experiencia.", answer: "Instalación" },
  { id: "arte_I_006", topic: "arte", letter: "I", question: "Con la I: Técnica de incrustación decorativa en madera.", answer: "Intarsia" },
  { id: "arte_I_007", topic: "arte", letter: "I", question: "Con la I: Edificio y también institución que encargó gran arte histórico.", answer: "Iglesia" },
  { id: "arte_I_008", topic: "arte", letter: "I", question: "Con la I: Tecnología que difundió imágenes y textos .", answer: "Imprenta" },
  { id: "arte_I_009", topic: "arte", letter: "I", question: "Con la I: Referencia a arte andino precolombino.", answer: "Inca" },
  { id: "arte_I_010", topic: "arte", letter: "I", question: "Con la I: Técnica de pintura con capas gruesas .", answer: "Impasto" },
  { id: "arte_I_011", topic: "arte", letter: "I", question: "Con la I: Decoración insertando materiales en una superficie.", answer: "Incrustación" },
  { id: "arte_I_012", topic: "arte", letter: "I", question: "Con la I: Conjunto de imágenes simbólicas de una cultura.", answer: "Imaginario" },
  { id: "arte_I_013", topic: "arte", letter: "I", question: "Con la I: Creación artística sin planificación previa, común en performance y jazz.", answer: "Improvisación" },
  { id: "arte_I_014", topic: "arte", letter: "I", question: "Con la I: Estilo/periodo artístico vinculado a IsabelII en España .", answer: "Isabelina" },
  { id: "arte_I_015", topic: "arte", letter: "I", question: "Con la I: Actitud de romper imágenes/símbolos establecidos.", answer: "Iconoclasta" },
  { id: "arte_J_001", topic: "arte", letter: "J", question: "Con la J: Objeto de cerámica/vidrio usado en artes decorativas.", answer: "Jarrón" },
  { id: "arte_J_002", topic: "arte", letter: "J", question: "Con la J: Pieza de orfebrería con valor artístico.", answer: "Joya" },
  { id: "arte_J_003", topic: "arte", letter: "J", question: "Con la J: Influencia del arte japonés en artistas europeos del XIX.", answer: "Japonismo" },
  { id: "arte_J_004", topic: "arte", letter: "J", question: "Con la J: Orden arquitectónico clásico con volutas.", answer: "Jónico" },
  { id: "arte_J_005", topic: "arte", letter: "J", question: "Con la J: Objeto de diseño y cultura visual.", answer: "Juguete" },
  { id: "arte_J_006", topic: "arte", letter: "J", question: "Con la J: Espacio diseñado; arte paisajístico.", answer: "Jardín" },
  { id: "arte_J_007", topic: "arte", letter: "J", question: "Con la J: Artista estadounidense conocido por pintar banderas y números.", answer: "Jasper" },
  { id: "arte_J_008", topic: "arte", letter: "J", question: "Con la J: Ciudad andaluza; carteles y cultura visual del flamenco.", answer: "Jerez" },
  { id: "arte_J_009", topic: "arte", letter: "J", question: "Con la J: Sistema de escritura egipcia con valor artístico.", answer: "Jeroglífico" },
  { id: "arte_J_010", topic: "arte", letter: "J", question: "Con la J: Material usado en arte y joyería .", answer: "Jade" },
  { id: "arte_J_011", topic: "arte", letter: "J", question: "Con la J: Cerámica inglesa azul/blanca asociada a Wedgwood.", answer: "Jasperware" },
  { id: "arte_J_012", topic: "arte", letter: "J", question: "Con la J: En pintura, unión entre piezas o paneles .", answer: "Junta" },
  { id: "arte_J_013", topic: "arte", letter: "J", question: "Con la J: Tema religioso representado en arte sacro.", answer: "Jubileo" },
  { id: "arte_J_014", topic: "arte", letter: "J", question: "Con la J: Baile tradicional; arte escénico regional.", answer: "Jota" },
  { id: "arte_J_015", topic: "arte", letter: "J", question: "Con la J: Arte de crear adornos con metales y gemas.", answer: "Joyería" },
  { id: "arte_L_001", topic: "arte", letter: "L", question: "Con la L: Técnica de impresión desde piedra o plancha.", answer: "Litografía" },
  { id: "arte_L_002", topic: "arte", letter: "L", question: "Con la L: Soporte textil para pintura.", answer: "Lienzo" },
  { id: "arte_L_003", topic: "arte", letter: "L", question: "Con la L: Elemento clave en pintura, fotografía y cine.", answer: "Luz" },
  { id: "arte_L_004", topic: "arte", letter: "L", question: "Con la L: Nombre de pila del artista renacentista autor de La Gioconda.", answer: "Leonardo" },
  { id: "arte_L_005", topic: "arte", letter: "L", question: "Con la L: Museo parisino con obras icónicas.", answer: "Louvre" },
  { id: "arte_L_006", topic: "arte", letter: "L", question: "Con la L: Figura cultural; influye en teatro y artes escénicas españolas.", answer: "Lorca" },
  { id: "arte_L_007", topic: "arte", letter: "L", question: "Con la L: Objeto de diseño; también en instalaciones.", answer: "Lámpara" },
  { id: "arte_L_008", topic: "arte", letter: "L", question: "Con la L: Técnica decorativa con capas de laca.", answer: "Lacado" },
  { id: "arte_L_009", topic: "arte", letter: "L", question: "Con la L: Elemento poético; relación con artes escénicas y visuales.", answer: "Lírica" },
  { id: "arte_L_010", topic: "arte", letter: "L", question: "Con la L: Relacionado con línea en dibujo y composición.", answer: "Lineal" },
  { id: "arte_L_011", topic: "arte", letter: "L", question: "Con la L: Hoja/soporte para dibujo o grabado.", answer: "Lámina" },
  { id: "arte_L_012", topic: "arte", letter: "L", question: "Con la L: Arte que interviene paisaje natural.", answer: "LandArt" },
  { id: "arte_L_013", topic: "arte", letter: "L", question: "Con la L: Tratamiento de luz en pintura .", answer: "Luminismo" },
  { id: "arte_L_014", topic: "arte", letter: "L", question: "Con la L: Motivo geométrico de tradición islámica en España.", answer: "Lacería" },
  { id: "arte_L_015", topic: "arte", letter: "L", question: "Con la L: Herramienta básica para dibujo.", answer: "Lápiz" },
  { id: "arte_M_001", topic: "arte", letter: "M", question: "Con la M: Institución que conserva y exhibe arte.", answer: "Museo" },
  { id: "arte_M_002", topic: "arte", letter: "M", question: "Con la M: Pintura realizada sobre paredes.", answer: "Mural" },
  { id: "arte_M_003", topic: "arte", letter: "M", question: "Con la M: Estilo fin XIX-XX; en España, ligado a Cataluña.", answer: "Modernismo" },
  { id: "arte_M_004", topic: "arte", letter: "M", question: "Con la M: Pintor francés del siglo XX conocido por sus recortes de papel de colores.", answer: "Matisse" },
  { id: "arte_M_005", topic: "arte", letter: "M", question: "Con la M: Artista renacentista italiano autor del David y la Capilla Sixtina.", answer: "MiguelAngel" },
  { id: "arte_M_006", topic: "arte", letter: "M", question: "Con la M: Composición con pequeñas piezas .", answer: "Mosaico" },
  { id: "arte_M_007", topic: "arte", letter: "M", question: "Con la M: Estilo que reduce formas a lo esencial.", answer: "Minimalismo" },
  { id: "arte_M_008", topic: "arte", letter: "M", question: "Con la M: Pintor francés del siglo XIX autor de El almuerzo sobre la hierba.", answer: "Manet" },
  { id: "arte_M_009", topic: "arte", letter: "M", question: "Con la M: Material clásico de escultura.", answer: "Mármol" },
  { id: "arte_M_010", topic: "arte", letter: "M", question: "Con la M: Apoyo económico a artistas .", answer: "Mecenazgo" },
  { id: "arte_M_011", topic: "arte", letter: "M", question: "Con la M: Obra basada en un solo color dominante.", answer: "Monocromo" },
  { id: "arte_M_012", topic: "arte", letter: "M", question: "Con la M: Imitación de la realidad; concepto estético clásico.", answer: "Mímesis" },
  { id: "arte_M_013", topic: "arte", letter: "M", question: "Con la M: Cómic japonés; cultura visual global.", answer: "Manga" },
  { id: "arte_M_014", topic: "arte", letter: "M", question: "Con la M: Material base en escultura y artes aplicadas.", answer: "Madera" },
  { id: "arte_M_015", topic: "arte", letter: "M", question: "Con la M: Pintor barroco español conocido por sus Inmaculadas y escenas de niños.", answer: "Murillo" },
  { id: "arte_N_001", topic: "arte", letter: "N", question: "Con la N: Estilo que recupera lo clásico .", answer: "Neoclasicismo" },
  { id: "arte_N_002", topic: "arte", letter: "N", question: "Con la N: Representación fiel de la naturaleza y la vida.", answer: "Naturalismo" },
  { id: "arte_N_003", topic: "arte", letter: "N", question: "Con la N: Estructura prehistórica de Menorca .", answer: "Naveta" },
  { id: "arte_N_004", topic: "arte", letter: "N", question: "Con la N: Figura egipcia; busto icónico del arte antiguo.", answer: "Nefertiti" },
  { id: "arte_N_005", topic: "arte", letter: "N", question: "Con la N: Género del desnudo en pintura y escultura.", answer: "Nudo" },
  { id: "arte_N_006", topic: "arte", letter: "N", question: "Con la N: Iconografía de SemanaSanta; imaginería española.", answer: "Nazareno" },
  { id: "arte_N_007", topic: "arte", letter: "N", question: "Con la N: Espacio longitudinal de una iglesia .", answer: "Nave" },
  { id: "arte_N_008", topic: "arte", letter: "N", question: "Con la N: Relato en imágenes: cómic, pintura histórica, cine.", answer: "Narrativa" },
  { id: "arte_N_009", topic: "arte", letter: "N", question: "Con la N: Material/luz usado en arte contemporáneo.", answer: "Neón" },
  { id: "arte_N_010", topic: "arte", letter: "N", question: "Con la N: Material decorativo usado en incrustaciones.", answer: "Nácar" },
  { id: "arte_N_011", topic: "arte", letter: "N", question: "Con la N: Colecciones nacionales  como idea de patrimonio.", answer: "Nacional" },
  { id: "arte_N_012", topic: "arte", letter: "N", question: "Con la N: Referencia cultural; poesía en diálogo con artes visuales .", answer: "Neruda" },
  { id: "arte_N_013", topic: "arte", letter: "N", question: "Con la N: Estilo de pintura tradicional japonesa moderna.", answer: "Nihonga" },
  { id: "arte_N_014", topic: "arte", letter: "N", question: "Con la N: Escuela pictórica italiana  y tradición artística.", answer: "Nápoles" },
  { id: "arte_N_015", topic: "arte", letter: "N", question: "Con la N: Estilo modernista internacional .", answer: "Nouveau" },
  { id: "arte_Ñ_001", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: País con patrimonio artístico enorme.", answer: "España" },
  { id: "arte_Ñ_002", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Elemento gráfico en diseño y museografía.", answer: "Señal" },
  { id: "arte_Ñ_003", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Formación rocosa; motivo en paisaje.", answer: "Peñón" },
  { id: "arte_Ñ_004", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Fecha de una obra; parte de fichas de museo.", answer: "Año" },
  { id: "arte_Ñ_005", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Motivo de paisaje  en pintura.", answer: "Cañón" },
  { id: "arte_Ñ_006", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Tema en retratos y escenas costumbristas.", answer: "Niñez" },
  { id: "arte_Ñ_007", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Tema/luz en pintura  .", answer: "Mañana" },
  { id: "arte_Ñ_008", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Compañías teatrales y de danza.", answer: "Compañía" },
  { id: "arte_Ñ_009", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Tema surrealista y simbólico.", answer: "Sueño" },
  { id: "arte_Ñ_010", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Formato pequeño: miniatura.", answer: "Pequeño" },
  { id: "arte_Ñ_011", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Paisaje rural.", answer: "Cañada" },
  { id: "arte_Ñ_012", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Arte en educación: talleres y academias.", answer: "Enseñanza" },
  { id: "arte_Ñ_013", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Pigmento azul.", answer: "Añil" },
  { id: "arte_Ñ_014", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Objeto festivo; artes populares.", answer: "Piñata" },
  { id: "arte_Ñ_015", topic: "arte", letter: "Ñ", question: "Contiene la Ñ: Contexto histórico de patronazgo.", answer: "Señorío" },
  { id: "arte_O_001", topic: "arte", letter: "O", question: "Con la O: Técnica pictórica con pigmentos y aceite.", answer: "Óleo" },
  { id: "arte_O_002", topic: "arte", letter: "O", question: "Con la O: Arte de trabajar metales preciosos.", answer: "Orfebrería" },
  { id: "arte_O_003", topic: "arte", letter: "O", question: "Con la O: Arte óptico con efectos visuales.", answer: "OpArt" },
  { id: "arte_O_004", topic: "arte", letter: "O", question: "Con la O: Decoración aplicada a superficies y objetos.", answer: "Ornamento" },
  { id: "arte_O_005", topic: "arte", letter: "O", question: "Con la O: Pigmento terroso muy usado desde prehistoria.", answer: "Ocre" },
  { id: "arte_O_006", topic: "arte", letter: "O", question: "Con la O: Tema de paisaje; también motivo orientalista.", answer: "Oasis" },
  { id: "arte_O_007", topic: "arte", letter: "O", question: "Con la O: Abertura circular en arquitectura .", answer: "Oculus" },
  { id: "arte_O_008", topic: "arte", letter: "O", question: "Con la O: Género poético; diálogo con artes escénicas y visuales.", answer: "Oda" },
  { id: "arte_O_009", topic: "arte", letter: "O", question: "Con la O: Hueco en escultura o arquitectura; recurso de volumen.", answer: "Oquedad" },
  { id: "arte_O_010", topic: "arte", letter: "O", question: "Con la O: Monumento vertical de tradición egipcia y urbana.", answer: "Obelisco" },
  { id: "arte_O_011", topic: "arte", letter: "O", question: "Con la O: Muralista mexicano del siglo XX, parte del movimiento muralista junto a Rivera y Siqueiros.", answer: "Orozco" },
  { id: "arte_O_012", topic: "arte", letter: "O", question: "Con la O: Arte japonés de plegado de papel.", answer: "Origami" },
  { id: "arte_O_013", topic: "arte", letter: "O", question: "Con la O: Arte escénico musical; relación con ópera y cine.", answer: "Orquesta" },
  { id: "arte_O_014", topic: "arte", letter: "O", question: "Con la O: Contraste visual  en composición.", answer: "Oposición" },
  { id: "arte_O_015", topic: "arte", letter: "O", question: "Con la O: Arte fuera de circuitos académicos .", answer: "Outsider" },
  { id: "arte_P_001", topic: "arte", letter: "P", question: "Con la P: Pintor español del siglo XX, cofundador del cubismo y autor del Guernica.", answer: "Picasso" },
  { id: "arte_P_002", topic: "arte", letter: "P", question: "Con la P: Museo nacional en Madrid con grandes colecciones.", answer: "Prado" },
  { id: "arte_P_003", topic: "arte", letter: "P", question: "Con la P: Arte de aplicar pigmentos sobre un soporte.", answer: "Pintura" },
  { id: "arte_P_004", topic: "arte", letter: "P", question: "Con la P: Técnica para representar profundidad en un plano.", answer: "Perspectiva" },
  { id: "arte_P_005", topic: "arte", letter: "P", question: "Con la P: Arte de acción en vivo.", answer: "Performance" },
  { id: "arte_P_006", topic: "arte", letter: "P", question: "Con la P: Movimiento que usa iconos de consumo y cultura popular.", answer: "PopArt" },
  { id: "arte_P_007", topic: "arte", letter: "P", question: "Con la P: Herramienta para pintar.", answer: "Pincel" },
  { id: "arte_P_008", topic: "arte", letter: "P", question: "Con la P: Sustancia que aporta color a una obra.", answer: "Pigmento" },
  { id: "arte_P_009", topic: "arte", letter: "P", question: "Con la P: Capa superficial por envejecimiento, común en bronce.", answer: "Pátina" },
  { id: "arte_P_010", topic: "arte", letter: "P", question: "Con la P: Estilo español con decoración abundante .", answer: "Plateresco" },
  { id: "arte_P_011", topic: "arte", letter: "P", question: "Con la P: Aplicación de varios colores en escultura/retablos.", answer: "Policromía" },
  { id: "arte_P_012", topic: "arte", letter: "P", question: "Con la P: Tabla o conjunto de colores usados por un artista.", answer: "Paleta" },
  { id: "arte_P_013", topic: "arte", letter: "P", question: "Con la P: Soporte para dibujo, grabado y collage.", answer: "Papel" },
  { id: "arte_P_014", topic: "arte", letter: "P", question: "Con la P: Entrada arquitectónica con columnas y decoración.", answer: "Pórtico" },
  { id: "arte_P_015", topic: "arte", letter: "P", question: "Con la P: Grabador italiano famoso por arquitecturas imaginarias.", answer: "Piranesi" },
  { id: "arte_Q_001", topic: "arte", letter: "Q", question: "Contiene la Q: Siglo XV italiano clave del Renacimiento.", answer: "Quattrocento" },
  { id: "arte_Q_002", topic: "arte", letter: "Q", question: "Contiene la Q: Idea de quintaesencia en alegorías.", answer: "Quintessencia" },
  { id: "arte_Q_003", topic: "arte", letter: "Q", question: "Contiene la Q: Balance en composición visual.", answer: "Equilibrio" },
  { id: "arte_Q_004", topic: "arte", letter: "Q", question: "Contiene la Q: Técnica.", answer: "Acuarela" },
  { id: "arte_Q_005", topic: "arte", letter: "Q", question: "Contiene la Q: Profesional del diseño de edificios.", answer: "Arquitecto" },
  { id: "arte_Q_006", topic: "arte", letter: "Q", question: "Contiene la Q: Elemento urbano de diseño.", answer: "Marquesina" },
  { id: "arte_Q_007", topic: "arte", letter: "Q", question: "Contiene la Q: Plan previo de una obra.", answer: "Esquema" },
  { id: "arte_Q_008", topic: "arte", letter: "Q", question: "Contiene la Q: Tema representado en pintura/escultura/ilustración.", answer: "Quijote" },
  { id: "arte_Q_009", topic: "arte", letter: "Q", question: "Contiene la Q: Criatura/idea fantástica representada en arte.", answer: "Quimera" },
  { id: "arte_Q_010", topic: "arte", letter: "Q", question: "Contiene la Q: Grupo de cinco músicos; arte escénico.", answer: "Quinteto" },
  { id: "arte_Q_011", topic: "arte", letter: "Q", question: "Contiene la Q: Elemento arquitectónico.", answer: "Arquitrabe" },
  { id: "arte_Q_012", topic: "arte", letter: "Q", question: "Contiene la Q: Centauro mitológico representado en arte.", answer: "Quirón" },
  { id: "arte_Q_013", topic: "arte", letter: "Q", question: "Contiene la Q: Medida de pureza en orfebrería.", answer: "Quilates" },
  { id: "arte_Q_014", topic: "arte", letter: "Q", question: "Contiene la Q: Movimiento en danza/toros representado en artes.", answer: "Quiebro" },
  { id: "arte_Q_015", topic: "arte", letter: "Q", question: "Contiene la Q: Género musical; en arte, “quodlibet” pictórico.", answer: "Quodlibet" },
  { id: "arte_R_001", topic: "arte", letter: "R", question: "Con la R: Periodo artístico europeo .", answer: "Renacimiento" },
  { id: "arte_R_002", topic: "arte", letter: "R", question: "Con la R: Estilo decorativo del siglo XVIII.", answer: "Rococó" },
  { id: "arte_R_003", topic: "arte", letter: "R", question: "Con la R: Estilo medieval de arcos de medio punto y piedra.", answer: "Románico" },
  { id: "arte_R_004", topic: "arte", letter: "R", question: "Con la R: Estilo que representa la realidad sin idealizar.", answer: "Realismo" },
  { id: "arte_R_005", topic: "arte", letter: "R", question: "Con la R: Estructura decorada detrás del altar, típica en España.", answer: "Retablo" },
  { id: "arte_R_006", topic: "arte", letter: "R", question: "Con la R: Género que representa a una persona.", answer: "Retrato" },
  { id: "arte_R_007", topic: "arte", letter: "R", question: "Con la R: Pintor renacentista italiano autor de La escuela de Atenas y numerosas Madonnas.", answer: "Raffaello" },
  { id: "arte_R_008", topic: "arte", letter: "R", question: "Con la R: Pintor barroco español del siglo XVII conocido por sus escenas de martirios.", answer: "Ribera" },
  { id: "arte_R_009", topic: "arte", letter: "R", question: "Con la R: Poeta; diálogo con artes visuales .", answer: "Rilke" },
  { id: "arte_R_010", topic: "arte", letter: "R", question: "Con la R: Escultura que sobresale de un fondo.", answer: "Relieve" },
  { id: "arte_R_011", topic: "arte", letter: "R", question: "Con la R: Proceso de conservar y reparar obras.", answer: "Restauración" },
  { id: "arte_R_012", topic: "arte", letter: "R", question: "Con la R: Repetición/variación visual; también musical y escénico.", answer: "Ritmo" },
  { id: "arte_R_013", topic: "arte", letter: "R", question: "Con la R: Técnica cerámica japonesa.", answer: "Raku" },
  { id: "arte_R_014", topic: "arte", letter: "R", question: "Con la R: Motivo ornamental típico del rococó.", answer: "Rocaille" },
  { id: "arte_R_015", topic: "arte", letter: "R", question: "Con la R: Tema romántico de ruinas en pintura y arquitectura.", answer: "Ruina" },
  { id: "arte_S_001", topic: "arte", letter: "S", question: "Con la S: Movimiento que explora sueños y subconsciente.", answer: "Surrealismo" },
  { id: "arte_S_002", topic: "arte", letter: "S", question: "Con la S: Estilo que usa símbolos para ideas abstractas.", answer: "Simbolismo" },
  { id: "arte_S_003", topic: "arte", letter: "S", question: "Con la S: Basílica barcelonesa de Gaudí.", answer: "SagradaFamilia" },
  { id: "arte_S_004", topic: "arte", letter: "S", question: "Con la S: Ciudad con gran patrimonio barroco y museos.", answer: "Sevilla" },
  { id: "arte_S_005", topic: "arte", letter: "S", question: "Con la S: Técnica de difuminado; se asocia a DaVinci.", answer: "Sfumato" },
  { id: "arte_S_006", topic: "arte", letter: "S", question: "Con la S: Siglo XVII italiano, clave del barroco.", answer: "Seicento" },
  { id: "arte_S_007", topic: "arte", letter: "S", question: "Con la S: Técnica de impresión con malla .", answer: "Serigrafía" },
  { id: "arte_S_008", topic: "arte", letter: "S", question: "Con la S: Contenedor funerario con decoración escultórica.", answer: "Sarcófago" },
  { id: "arte_S_009", topic: "arte", letter: "S", question: "Con la S: Contorno de una forma; recurso en diseño.", answer: "Silueta" },
  { id: "arte_S_010", topic: "arte", letter: "S", question: "Con la S: Correspondencia equilibrada de formas en composición.", answer: "Simetría" },
  { id: "arte_S_011", topic: "arte", letter: "S", question: "Con la S: Forma poética; relación con artes escénicas y visuales.", answer: "Soneto" },
  { id: "arte_S_012", topic: "arte", letter: "S", question: "Con la S: Artista venezolano del siglo XX conocido por sus obras cinéticas.", answer: "Soto" },
  { id: "arte_S_013", topic: "arte", letter: "S", question: "Con la S: Figuras proféticas en iconografía renacentista.", answer: "Sibilas" },
  { id: "arte_S_014", topic: "arte", letter: "S", question: "Con la S: Conjunto de asientos tallados en coros de catedrales.", answer: "Sillería" },
  { id: "arte_S_015", topic: "arte", letter: "S", question: "Con la S: Plantilla para grafiti y arte urbano.", answer: "Stencil" },
  { id: "arte_T_001", topic: "arte", letter: "T", question: "Con la T: Pintor veneciano del Renacimiento autor de La Venus de Urbino.", answer: "Tiziano" },
  { id: "arte_T_002", topic: "arte", letter: "T", question: "Con la T: Textil decorativo tejido.", answer: "Tapiz" },
  { id: "arte_T_003", topic: "arte", letter: "T", question: "Con la T: Escultura en madera o piedra por corte.", answer: "Talla" },
  { id: "arte_T_004", topic: "arte", letter: "T", question: "Con la T: Técnica pictórica con yema de huevo como aglutinante.", answer: "Temple" },
  { id: "arte_T_005", topic: "arte", letter: "T", question: "Con la T: Arte escénico de interpretación.", answer: "Teatro" },
  { id: "arte_T_006", topic: "arte", letter: "T", question: "Con la T: Obra compuesta por tres paneles.", answer: "Tríptico" },
  { id: "arte_T_007", topic: "arte", letter: "T", question: "Con la T: Línea o marca del dibujo.", answer: "Trazo" },
  { id: "arte_T_008", topic: "arte", letter: "T", question: "Con la T: Ilusión óptica de “engaño al ojo”.", answer: "Trompeoeil" },
  { id: "arte_T_009", topic: "arte", letter: "T", question: "Con la T: Pieza pequeña usada en mosaicos.", answer: "Tesela" },
  { id: "arte_T_010", topic: "arte", letter: "T", question: "Con la T: Diseño de letras en comunicación visual.", answer: "Tipografía" },
  { id: "arte_T_011", topic: "arte", letter: "T", question: "Con la T: Cualidad táctil/visual de una superficie en arte.", answer: "Textura" },
  { id: "arte_T_012", topic: "arte", letter: "T", question: "Con la T: Método/material de ejecución de una obra.", answer: "Técnica" },
  { id: "arte_T_013", topic: "arte", letter: "T", question: "Con la T: Pintor veneciano del siglo XVI autor de El paraíso en el Palacio Ducal.", answer: "Tintoretto" },
  { id: "arte_T_014", topic: "arte", letter: "T", question: "Con la T: Técnica de mosaico con cerámica rota, típica de Gaudí.", answer: "Trencadís" },
  { id: "arte_T_015", topic: "arte", letter: "T", question: "Con la T: Escultura parcial del cuerpo humano.", answer: "Torso" },
  { id: "arte_U_001", topic: "arte", letter: "U", question: "Con la U: Grabado japonés de “mundo flotante”.", answer: "Ukiyoe" },
  { id: "arte_U_002", topic: "arte", letter: "U", question: "Con la U: Diseño de ciudades y espacio público.", answer: "Urbanismo" },
  { id: "arte_U_003", topic: "arte", letter: "U", question: "Con la U: Pigmento azul intenso .", answer: "Ultramarino" },
  { id: "arte_U_004", topic: "arte", letter: "U", question: "Con la U: Idea ideal; inspiración en arte y arquitectura.", answer: "Utopía" },
  { id: "arte_U_005", topic: "arte", letter: "U", question: "Con la U: Paso/entrada; símbolo compositivo y arquitectónico.", answer: "Umbral" },
  { id: "arte_U_006", topic: "arte", letter: "U", question: "Con la U: Idea de arte para todos; museos universales .", answer: "Universal" },
  { id: "arte_U_007", topic: "arte", letter: "U", question: "Con la U: Arte y diseño ligados a la ciudad y su espacio público.", answer: "Urbano" },
  { id: "arte_U_008", topic: "arte", letter: "U", question: "Con la U: Costumbre; influye en arte popular.", answer: "Usanza" },
  { id: "arte_U_009", topic: "arte", letter: "U", question: "Con la U: Objeto ceremonial/funerario con valor artístico.", answer: "Urna" },
  { id: "arte_U_010", topic: "arte", letter: "U", question: "Con la U: Conjunto de hilos longitudinales en tejido.", answer: "Urdimbre" },
  { id: "arte_U_011", topic: "arte", letter: "U", question: "Con la U: Motivo típico en bodegones.", answer: "Uva" },
  { id: "arte_U_012", topic: "arte", letter: "U", question: "Con la U: Pintor francés del siglo XX conocido por sus paisajes urbanos de Montmartre.", answer: "Utrillo" },
  { id: "arte_U_013", topic: "arte", letter: "U", question: "Con la U: Galería de Florencia con arte renacentista.", answer: "Uffizi" },
  { id: "arte_U_014", topic: "arte", letter: "U", question: "Con la U: Instrumento; aparece en arte popular/escénico.", answer: "Ukelele" },
  { id: "arte_U_015", topic: "arte", letter: "U", question: "Con la U: Topónimo; paisaje y arte del territorio .", answer: "Urbión" },
  { id: "arte_V_001", topic: "arte", letter: "V", question: "Con la V: Pintor español del siglo XVII autor de Las meninas y La rendición de Breda.", answer: "Velázquez" },
  { id: "arte_V_002", topic: "arte", letter: "V", question: "Con la V: Movimientos que rompen con lo anterior .", answer: "Vanguardia" },
  { id: "arte_V_003", topic: "arte", letter: "V", question: "Con la V: Composición de vidrio coloreado, típica del gótico.", answer: "Vidriera" },
  { id: "arte_V_004", topic: "arte", letter: "V", question: "Con la V: Pintor neerlandés del siglo XVII autor de La joven de la perla.", answer: "Vermeer" },
  { id: "arte_V_005", topic: "arte", letter: "V", question: "Con la V: Sinónimo de vidriera artística.", answer: "Vitral" },
  { id: "arte_V_006", topic: "arte", letter: "V", question: "Con la V: Soporte musical; diseño gráfico y cultura visual.", answer: "Vinilo" },
  { id: "arte_V_007", topic: "arte", letter: "V", question: "Con la V: Autor romano influyente en arquitectura .", answer: "Vitruvio" },
  { id: "arte_V_008", topic: "arte", letter: "V", question: "Con la V: Sensación de tridimensionalidad en una obra.", answer: "Volumen" },
  { id: "arte_V_009", topic: "arte", letter: "V", question: "Con la V: Dibujo breve de cómic o ilustración en una secuencia.", answer: "Viñeta" },
  { id: "arte_V_010", topic: "arte", letter: "V", question: "Con la V: Daño a patrimonio artístico .", answer: "Vandalismo" },
  { id: "arte_V_011", topic: "arte", letter: "V", question: "Con la V: Pergamino fino usado en manuscritos iluminados.", answer: "Vellum" },
  { id: "arte_V_012", topic: "arte", letter: "V", question: "Con la V: Motivo mitológico y escultórico; también pintura.", answer: "Vulcano" },
  { id: "arte_V_013", topic: "arte", letter: "V", question: "Con la V: Mueble de museo para exhibir objetos.", answer: "Vitrina" },
  { id: "arte_V_014", topic: "arte", letter: "V", question: "Con la V: Recurso musical; influencia en ópera y artes escénicas.", answer: "Vibrato" },
  { id: "arte_V_015", topic: "arte", letter: "V", question: "Con la V: Forma espiral; motivo visual en arte y diseño.", answer: "Vórtice" },
  { id: "arte_X_001", topic: "arte", letter: "X", question: "Contiene la X: Evento donde se muestran obras.", answer: "Exposición" },
  { id: "arte_X_002", topic: "arte", letter: "X", question: "Contiene la X: Propiedad visual/táctil.", answer: "Textura" },
  { id: "arte_X_003", topic: "arte", letter: "X", question: "Contiene la X: Marco histórico/cultural de una obra.", answer: "Contexto" },
  { id: "arte_X_004", topic: "arte", letter: "X", question: "Contiene la X: Tema frecuente en arte político.", answer: "Exilio" },
  { id: "arte_X_005", topic: "arte", letter: "X", question: "Contiene la X: Mezcla de medios.", answer: "Mix" },
  { id: "arte_X_006", topic: "arte", letter: "X", question: "Contiene la X: Estética recargada o barroca.", answer: "Exceso" },
  { id: "arte_X_007", topic: "arte", letter: "X", question: "Contiene la X: Unidad de imagen digital.", answer: "Pixel" },
  { id: "arte_X_008", topic: "arte", letter: "X", question: "Contiene la X: Material/efecto en metal.", answer: "Oxido" },
  { id: "arte_X_009", topic: "arte", letter: "X", question: "Contiene la X: Ave mítica en iconografía.", answer: "Fénix" },
  { id: "arte_X_010", topic: "arte", letter: "X", question: "Contiene la X: Grabado en madera.", answer: "Xilografía" },
  { id: "arte_X_011", topic: "arte", letter: "X", question: "Contiene la X: Tema místico en arte.", answer: "Extasis" },
  { id: "arte_X_012", topic: "arte", letter: "X", question: "Contiene la X: Ofrenda artística devocional.", answer: "Exvoto" },
  { id: "arte_X_013", topic: "arte", letter: "X", question: "Contiene la X: Gas usado en flashes fotográficos.", answer: "Xenón" },
  { id: "arte_X_014", topic: "arte", letter: "X", question: "Contiene la X: Sección extra en catálogo.", answer: "Anexo" },
  { id: "arte_X_015", topic: "arte", letter: "X", question: "Contiene la X: Sección adicional en un catálogo o museo.", answer: "Anexo" },
  { id: "arte_Y_001", topic: "arte", letter: "Y", question: "Contiene la Y: Artista pop con presencia en cine y performance.", answer: "Beyoncé" },
  { id: "arte_Y_002", topic: "arte", letter: "Y", question: "Contiene la Y: Artista pop estadounidense conocido por sus serigrafías de Marilyn Monroe.", answer: "Andy" },
  { id: "arte_Y_003", topic: "arte", letter: "Y", question: "Contiene la Y: Obra de varios paneles.", answer: "Políptico" },
  { id: "arte_Y_004", topic: "arte", letter: "Y", question: "Contiene la Y: Artista japonesa contemporánea conocida por sus instalaciones con puntos y espejos.", answer: "Yayoi" },
  { id: "arte_Y_005", topic: "arte", letter: "Y", question: "Contiene la Y: Tapiz medieval famoso.", answer: "Bayeux" },
  { id: "arte_Y_006", topic: "arte", letter: "Y", question: "Contiene la Y: Escultor francés de animales.", answer: "Barye" },
  { id: "arte_Y_007", topic: "arte", letter: "Y", question: "Contiene la Y: Motivo/civilización representada en arte.", answer: "Maya" },
  { id: "arte_Y_008", topic: "arte", letter: "Y", question: "Contiene la Y: Tema narrativo en arte.", answer: "Leyenda" },
  { id: "arte_Y_009", topic: "arte", letter: "Y", question: "Contiene la Y: Artista pop.", answer: "Miley" },
  { id: "arte_Y_010", topic: "arte", letter: "Y", question: "Contiene la Y: Ciudad; escena artística.", answer: "Sydney" },
  { id: "arte_Y_011", topic: "arte", letter: "Y", question: "Contiene la Y: Tapiz medieval famoso.", answer: "Bayeux" },
  { id: "arte_Y_012", topic: "arte", letter: "Y", question: "Contiene la Y: Apellido del pintor español autor de Los caprichos y Las pinturas negras.", answer: "Goya" },
  { id: "arte_Y_013", topic: "arte", letter: "Y", question: "Contiene la Y: Herramienta de forja.", answer: "Yunque" },
  { id: "arte_Y_014", topic: "arte", letter: "Y", question: "Contiene la Y: Motivo botánico en bodegones.", answer: "Yerba" },
  { id: "arte_Y_015", topic: "arte", letter: "Y", question: "Contiene la Y: Nombre antiguo de Tokio; arte japonés.", answer: "Yedo" },
  { id: "arte_Z_001", topic: "arte", letter: "Z", question: "Con la Z: Pintor barroco español de fuerte misticismo.", answer: "Zurbarán" },
  { id: "arte_Z_002", topic: "arte", letter: "Z", question: "Con la Z: Género escénico musical español.", answer: "Zarzuela" },
  { id: "arte_Z_003", topic: "arte", letter: "Z", question: "Con la Z: Arquitectura mesopotámica escalonada .", answer: "Ziggurat" },
  { id: "arte_Z_004", topic: "arte", letter: "Z", question: "Con la Z: Material usado en escultura y grabado.", answer: "Zinc" },
  { id: "arte_Z_005", topic: "arte", letter: "Z", question: "Con la Z: Punto más alto; tema en perspectiva y astronomía artística.", answer: "Zenit" },
  { id: "arte_Z_006", topic: "arte", letter: "Z", question: "Con la Z: Piedra preciosa usada en joyería.", answer: "Zafiro" },
  { id: "arte_Z_007", topic: "arte", letter: "Z", question: "Con la Z: Base arquitectónica o plaza central; geografía urbana del arte.", answer: "Zócalo" },
  { id: "arte_Z_008", topic: "arte", letter: "Z", question: "Con la Z: Motivo animal en arte y diseño.", answer: "Zebra" },
  { id: "arte_Z_009", topic: "arte", letter: "Z", question: "Con la Z: Referencia a escuelas/museos  en arte global.", answer: "Zelanda" },
  { id: "arte_Z_010", topic: "arte", letter: "Z", question: "Con la Z: Recurso audiovisual y de composición digital.", answer: "Zoom" },
  { id: "arte_Z_011", topic: "arte", letter: "Z", question: "Con la Z: Motivo en cine/arte pop contemporáneo.", answer: "Zombi" },
  { id: "arte_Z_012", topic: "arte", letter: "Z", question: "Con la Z: Personaje icónico en cultura visual.", answer: "Zorro" },
  { id: "arte_Z_013", topic: "arte", letter: "Z", question: "Con la Z: Mosaico marroquí; cerámica geométrica.", answer: "Zellige" },
  { id: "arte_Z_014", topic: "arte", letter: "Z", question: "Con la Z: Motivo/objeto en diseño e ilustración retro.", answer: "Zepelín" },
  { id: "arte_Z_015", topic: "arte", letter: "Z", question: "Con la Z: Figura histórica representada en retratos imperiales.", answer: "Zar" },
];
