import type { QA } from "./types";

export const ASTRONOMIA: QA[] = [
  { id: "astro_A_001", topic: "astronomia", letter: "A", question: "Con la A: Cuerpo rocoso pequeño que orbita el Sol, común en el cinturón principal.", answer: "Asteroide" },
  { id: "astro_A_002", topic: "astronomia", letter: "A", question: "Con la A: Punto de una órbita donde un objeto está más lejos de la Tierra.", answer: "Apogeo" },
  { id: "astro_A_003", topic: "astronomia", letter: "A", question: "Con la A: Punto de una órbita donde un planeta está más lejos del Sol.", answer: "Afelio" },
  { id: "astro_A_004", topic: "astronomia", letter: "A", question: "Con la A: Fracción de luz que refleja una superficie, como la de un planeta.", answer: "Albedo" },
  { id: "astro_A_005", topic: "astronomia", letter: "A", question: "Con la A: Luces polares producidas por partículas solares interactuando con la atmósfera.", answer: "Aurora" },
  { id: "astro_A_006", topic: "astronomia", letter: "A", question: "Con la A: Ángulo usado para ubicar objetos en el cielo respecto al norte y el horizonte.", answer: "Azimut" },
  { id: "astro_A_007", topic: "astronomia", letter: "A", question: "Con la A: Ángulo de un objeto celeste sobre el horizonte.", answer: "Altitud" },
  { id: "astro_A_008", topic: "astronomia", letter: "A", question: "Con la A: Patrón reconocible de estrellas dentro o fuera de una constelación oficial.", answer: "Asterismo" },
  { id: "astro_A_009", topic: "astronomia", letter: "A", question: "Con la A: Capa de gases que rodea un planeta.", answer: "Atmósfera" },
  { id: "astro_A_010", topic: "astronomia", letter: "A", question: "Con la A: Estructura de partículas que rodea algunos planetas, como Saturno.", answer: "Anillo" },
  { id: "astro_A_011", topic: "astronomia", letter: "A", question: "Con la A: Proceso por el que un cuerpo crece acumulando materia por gravedad.", answer: "Acreción" },
  { id: "astro_A_012", topic: "astronomia", letter: "A", question: "Con la A: Instrumento antiguo para medir posiciones de estrellas y calcular la hora.", answer: "Astrolabio" },
  { id: "astro_A_013", topic: "astronomia", letter: "A", question: "Con la A: Persona entrenada para viajar y trabajar en el espacio.", answer: "Astronauta" },
  { id: "astro_A_014", topic: "astronomia", letter: "A", question: "Con la A: Disposición casi en línea de varios cuerpos celestes vistos desde un punto.", answer: "Alineación" },
  { id: "astro_A_015", topic: "astronomia", letter: "A", question: "Con la A: Fotografía del cielo tomada con técnicas astronómicas.", answer: "Astrofoto" },
  { id: "astro_B_001", topic: "astronomia", letter: "B", question: "Con la B: Modelo que describe el inicio caliente y denso del universo.", answer: "BigBang" },
  { id: "astro_B_002", topic: "astronomia", letter: "B", question: "Con la B: Meteoro muy brillante que puede fragmentarse en la atmósfera.", answer: "Bólido" },
  { id: "astro_B_003", topic: "astronomia", letter: "B", question: "Con la B: Punto alrededor del cual orbitan dos cuerpos por su masa combinada.", answer: "Baricentro" },
  { id: "astro_B_004", topic: "astronomia", letter: "B", question: "Con la B: Sistema de dos estrellas que orbitan un centro de masa común.", answer: "Binaria" },
  { id: "astro_B_005", topic: "astronomia", letter: "B", question: "Con la B: Cantidad de luz que emite o refleja un objeto celeste, medida en magnitudes.", answer: "Brillo" },
  { id: "astro_B_006", topic: "astronomia", letter: "B", question: "Con la B: Instrumento útil para orientarse al observar el cielo en campo.", answer: "Brújula" },
  { id: "astro_B_007", topic: "astronomia", letter: "B", question: "Con la B: Franja horizontal de nubes paralelas al ecuador, visible en la atmósfera de Júpiter.", answer: "Banda" },
  { id: "astro_B_008", topic: "astronomia", letter: "B", question: "Con la B: Borde o anillo en un ocular que puede limitar el campo visual.", answer: "Bisel" },
  { id: "astro_B_009", topic: "astronomia", letter: "B", question: "Con la B: Estructuras de gas ionizado infladas por estrellas masivas o supernovas.", answer: "Burbujas" },
  { id: "astro_B_010", topic: "astronomia", letter: "B", question: "Con la B: Asteroide cercano a la Tierra estudiado por la misión OSIRIS-REx.", answer: "Bennu" },
  { id: "astro_B_011", topic: "astronomia", letter: "B", question: "Con la B: Astrónomo alemán que creó el sistema de denominación de estrellas con letras griegas.", answer: "Bayer" },
  { id: "astro_B_012", topic: "astronomia", letter: "B", question: "Con la B: Detector sensible a radiación térmica usado en astronomía.", answer: "Bolómetro" },
  { id: "astro_B_013", topic: "astronomia", letter: "B", question: "Con la B: Partícula compuesta  que forma materia ordinaria.", answer: "Baryón" },
  { id: "astro_B_014", topic: "astronomia", letter: "B", question: "Con la B: Adjetivo que describe fenómenos del hemisferio norte, como las auroras del norte.", answer: "Boreal" },
  { id: "astro_B_015", topic: "astronomia", letter: "B", question: "Con la B: Descripción de un borde óptico; en telescopios, afecta viñeteo y campo.", answer: "Biselado" },
  { id: "astro_C_001", topic: "astronomia", letter: "C", question: "Con la C: Cuerpo helado que desarrolla cola al acercarse al Sol.", answer: "Cometa" },
  { id: "astro_C_002", topic: "astronomia", letter: "C", question: "Con la C: Región del cielo con límites oficiales y figuras tradicionales.", answer: "Constelación" },
  { id: "astro_C_003", topic: "astronomia", letter: "C", question: "Con la C: Agrupación de estrellas que nacieron juntas y se mantienen unidas por gravedad.", answer: "Cúmulo" },
  { id: "astro_C_004", topic: "astronomia", letter: "C", question: "Con la C: Depresión circular por impacto visible en la Luna u otros cuerpos.", answer: "Cráter" },
  { id: "astro_C_005", topic: "astronomia", letter: "C", question: "Con la C: Término general para referirse al universo.", answer: "Cosmos" },
  { id: "astro_C_006", topic: "astronomia", letter: "C", question: "Con la C: Capa externa caliente de la atmósfera solar visible en eclipses.", answer: "Corona" },
  { id: "astro_C_007", topic: "astronomia", letter: "C", question: "Con la C: Punto del cielo directamente encima del observador.", answer: "Cenit" },
  { id: "astro_C_008", topic: "astronomia", letter: "C", question: "Con la C: Zona del Sistema Solar entre Marte y Júpiter donde orbitan millones de asteroides.", answer: "Cinturón" },
  { id: "astro_C_009", topic: "astronomia", letter: "C", question: "Con la C: Núcleo galáctico muy brillante alimentado por un agujero negro.", answer: "Cuásar" },
  { id: "astro_C_010", topic: "astronomia", letter: "C", question: "Con la C: Constelación del hemisferio norte asociada a variables cefeidas.", answer: "Cefeo" },
  { id: "astro_C_011", topic: "astronomia", letter: "C", question: "Con la C: Constelación con forma de “W” visible en el cielo norte.", answer: "Cassiopea" },
  { id: "astro_C_012", topic: "astronomia", letter: "C", question: "Con la C: Adjetivo que describe objetos o fenómenos relacionados con el cielo y el espacio.", answer: "Celeste" },
  { id: "astro_C_013", topic: "astronomia", letter: "C", question: "Con la C: Lista sistemática de objetos astronómicos organizados por número o nombre.", answer: "Catálogo" },
  { id: "astro_C_014", topic: "astronomia", letter: "C", question: "Con la C: Ajuste óptico para alinear espejos/lentes en un telescopio.", answer: "Colimación" },
  { id: "astro_C_015", topic: "astronomia", letter: "C", question: "Con la C: Deformación del campo en óptica; afecta enfoque en bordes.", answer: "Curvatura" },
  { id: "astro_D_001", topic: "astronomia", letter: "D", question: "Con la D: Efecto que desplaza frecuencias por movimiento relativo .", answer: "Doppler" },
  { id: "astro_D_002", topic: "astronomia", letter: "D", question: "Con la D: Separación entre objetos; en astronomía se mide con varios métodos.", answer: "Distancia" },
  { id: "astro_D_003", topic: "astronomia", letter: "D", question: "Con la D: Distancia a través del centro de un objeto circular o esférico, medida en kilómetros o grados.", answer: "Diámetro" },
  { id: "astro_D_004", topic: "astronomia", letter: "D", question: "Con la D: Coordenada celeste análoga a la latitud en la esfera celeste.", answer: "Declinación" },
  { id: "astro_D_005", topic: "astronomia", letter: "D", question: "Con la D: Relación entre la masa de un objeto y su volumen, medida en gramos por centímetro cúbico.", answer: "Densidad" },
  { id: "astro_D_006", topic: "astronomia", letter: "D", question: "Con la D: Isótopo del hidrógeno usado como pista en cosmología y formación planetaria.", answer: "Deuterio" },
  { id: "astro_D_007", topic: "astronomia", letter: "D", question: "Con la D: Estructura aplanada de gas y polvo, como estructuras protoplanetarias.", answer: "Disco" },
  { id: "astro_D_008", topic: "astronomia", letter: "D", question: "Con la D: Identificación instrumental de señales de objetos astronómicos.", answer: "Detección" },
  { id: "astro_D_009", topic: "astronomia", letter: "D", question: "Con la D: Efecto óptico que limita la resolución de telescopios.", answer: "Difracción" },
  { id: "astro_D_010", topic: "astronomia", letter: "D", question: "Con la D: Propiedad de sistemas astronómicos que experimentan cambios debido a fuerzas gravitatorias.", answer: "Dinamismo" },
  { id: "astro_D_011", topic: "astronomia", letter: "D", question: "Con la D: Formación superficial de arena; en Marte hay formaciones observadas por sondas.", answer: "Duna" },
  { id: "astro_D_012", topic: "astronomia", letter: "D", question: "Con la D: Estructura alargada; se usa en geología planetaria para relieves.", answer: "Dorsal" },
  { id: "astro_D_013", topic: "astronomia", letter: "D", question: "Con la D: Adjetivo que describe fenómenos que ocurren durante el día, como el movimiento aparente del Sol.", answer: "Diurno" },
  { id: "astro_D_014", topic: "astronomia", letter: "D", question: "Con la D: Gas como CO₂ presente en atmósferas planetarias .", answer: "Dióxido" },
  { id: "astro_D_015", topic: "astronomia", letter: "D", question: "Con la D: Constelación del norte que serpentea cerca de la Osa Mayor.", answer: "Draco" },
  { id: "astro_E_001", topic: "astronomia", letter: "E", question: "Con la E: Cuando un cuerpo bloquea la luz de otro, como el Sol por la Luna.", answer: "Eclipse" },
  { id: "astro_E_002", topic: "astronomia", letter: "E", question: "Con la E: Plano aparente de la órbita terrestre proyectado en el cielo.", answer: "Eclíptica" },
  { id: "astro_E_003", topic: "astronomia", letter: "E", question: "Con la E: Esfera de plasma que produce energía por fusión.", answer: "Estrella" },
  { id: "astro_E_004", topic: "astronomia", letter: "E", question: "Con la E: Distribución de luz por longitudes de onda; revela composición y velocidad.", answer: "Espectro" },
  { id: "astro_E_005", topic: "astronomia", letter: "E", question: "Con la E: Planeta que orbita una estrella fuera del Sistema Solar.", answer: "Exoplaneta" },
  { id: "astro_E_006", topic: "astronomia", letter: "E", question: "Con la E: Momento del año con día y noche de duración similar.", answer: "Equinoccio" },
  { id: "astro_E_007", topic: "astronomia", letter: "E", question: "Con la E: Forma de muchas órbitas según las leyes de Kepler.", answer: "Elipse" },
  { id: "astro_E_008", topic: "astronomia", letter: "E", question: "Con la E: Capacidad de un sistema para realizar trabajo, fundamental en procesos estelares y cósmicos.", answer: "Energía" },
  { id: "astro_E_009", topic: "astronomia", letter: "E", question: "Con la E: Evento explosivo; en el Sol se observan erupciones y fulguraciones.", answer: "Erupción" },
  { id: "astro_E_010", topic: "astronomia", letter: "E", question: "Con la E: Clasificación de estrellas de tamaño pequeño, como las rojas o blancas de tipo pequeño.", answer: "Enana" },
  { id: "astro_E_011", topic: "astronomia", letter: "E", question: "Con la E: Galaxia con estructura de brazos curvados que se extienden desde un núcleo central.", answer: "Espiral" },
  { id: "astro_E_012", topic: "astronomia", letter: "E", question: "Con la E: Adjetivo que describe procesos, objetos o fenómenos relacionados con las estrellas.", answer: "Estelar" },
  { id: "astro_E_013", topic: "astronomia", letter: "E", question: "Con la E: Conjunto denso de meteoros o partículas en una región.", answer: "Enjambre" },
  { id: "astro_E_014", topic: "astronomia", letter: "E", question: "Con la E: Disposición organizada de materia en el universo, como cúmulos de galaxias y filamentos cósmicos.", answer: "Estructura" },
  { id: "astro_E_015", topic: "astronomia", letter: "E", question: "Con la E: Físico alemán autor de la teoría de la relatividad general y especial.", answer: "Einstein" },
  { id: "astro_F_001", topic: "astronomia", letter: "F", question: "Con la F: Proceso nuclear que alimenta al Sol y a otras estrellas.", answer: "Fusión" },
  { id: "astro_F_002", topic: "astronomia", letter: "F", question: "Con la F: Partícula/cuanto de luz que transporta energía.", answer: "Fotón" },
  { id: "astro_F_003", topic: "astronomia", letter: "F", question: "Con la F: Apariencia cambiante de la Luna según su iluminación.", answer: "Fase" },
  { id: "astro_F_004", topic: "astronomia", letter: "F", question: "Con la F: Número de oscilaciones por segundo; clave en radioastronomía.", answer: "Frecuencia" },
  { id: "astro_F_005", topic: "astronomia", letter: "F", question: "Con la F: Aumento rápido de brillo solar por liberación de energía.", answer: "Fulguración" },
  { id: "astro_F_006", topic: "astronomia", letter: "F", question: "Con la F: Cantidad de energía o partículas que pasan a través de una superficie por unidad de tiempo.", answer: "Flujo" },
  { id: "astro_F_007", topic: "astronomia", letter: "F", question: "Con la F: Elemento óptico que selecciona bandas de luz .", answer: "Filtro" },
  { id: "astro_F_008", topic: "astronomia", letter: "F", question: "Con la F: Punto de convergencia de luz en un sistema óptico.", answer: "Foco" },
  { id: "astro_F_009", topic: "astronomia", letter: "F", question: "Con la F: Relacionado con el foco óptico de un telescopio o cámara.", answer: "Focal" },
  { id: "astro_F_010", topic: "astronomia", letter: "F", question: "Con la F: Partícula subatómica con espín semientero, como electrones, protones y neutrones.", answer: "Fermión" },
  { id: "astro_F_011", topic: "astronomia", letter: "F", question: "Con la F: Referencia usada en calibración de mediciones.", answer: "Fiducial" },
  { id: "astro_F_012", topic: "astronomia", letter: "F", question: "Con la F: Ciencia base para entender fenómenos del universo.", answer: "Física" },
  { id: "astro_F_013", topic: "astronomia", letter: "F", question: "Con la F: Telescopio espacial de rayos gamma lanzado en 2008 por la NASA.", answer: "Fermi" },
  { id: "astro_F_014", topic: "astronomia", letter: "F", question: "Con la F: Medida de anchura de una imagen estelar usada para evaluar el “seeing”.", answer: "FWHM" },
  { id: "astro_F_015", topic: "astronomia", letter: "F", question: "Con la F: Molécula discutida en atmósferas planetarias .", answer: "Fosfina" },
  { id: "astro_G_001", topic: "astronomia", letter: "G", question: "Con la G: Sistema de estrellas, gas y materia oscura ligado por gravedad.", answer: "Galaxia" },
  { id: "astro_G_002", topic: "astronomia", letter: "G", question: "Con la G: Fuerza/curvatura que atrae masas y rige órbitas.", answer: "Gravedad" },
  { id: "astro_G_003", topic: "astronomia", letter: "G", question: "Con la G: Clase de estrella grande y luminosa .", answer: "Gigante" },
  { id: "astro_G_004", topic: "astronomia", letter: "G", question: "Con la G: Constelación del zodiaco visible en invierno boreal.", answer: "Géminis" },
  { id: "astro_G_005", topic: "astronomia", letter: "G", question: "Con la G: Elemento que proyecta sombra para medir el tiempo solar.", answer: "Gnomon" },
  { id: "astro_G_006", topic: "astronomia", letter: "G", question: "Con la G: Fase lunar con más de la mitad iluminada pero no llena.", answer: "Gibosa" },
  { id: "astro_G_007", topic: "astronomia", letter: "G", question: "Con la G: Estado de la materia abundante en nebulosas y atmósferas.", answer: "Gas" },
  { id: "astro_G_008", topic: "astronomia", letter: "G", question: "Con la G: Modelo antiguo que ponía a la Tierra en el centro.", answer: "Geocentrismo" },
  { id: "astro_G_009", topic: "astronomia", letter: "G", question: "Con la G: Estudio de superficies; aplicada a planetas y lunas.", answer: "Geología" },
  { id: "astro_G_010", topic: "astronomia", letter: "G", question: "Con la G: Textura en la superficie solar por convección.", answer: "Granulación" },
  { id: "astro_G_011", topic: "astronomia", letter: "G", question: "Con la G: Estructura pequeña; en el Sol se ven estructuras convectivas.", answer: "Gránulo" },
  { id: "astro_G_012", topic: "astronomia", letter: "G", question: "Con la G: Órbita con periodo igual al de rotación terrestre.", answer: "Geosincrona" },
  { id: "astro_G_013", topic: "astronomia", letter: "G", question: "Con la G: Partícula hipotética asociada a la gravedad .", answer: "Gravitón" },
  { id: "astro_G_014", topic: "astronomia", letter: "G", question: "Con la G: Rotación de un cuerpo celeste sobre su eje.", answer: "Giro" },
  { id: "astro_G_015", topic: "astronomia", letter: "G", question: "Con la G: Medición de la forma/rotación de la Tierra; útil en astrometría.", answer: "Geodesia" },
  { id: "astro_H_001", topic: "astronomia", letter: "H", question: "Con la H: Elemento abundante en el universo, producido en estrellas.", answer: "Helio" },
  { id: "astro_H_002", topic: "astronomia", letter: "H", question: "Con la H: Elemento más abundante; combustible principal de estrellas.", answer: "Hidrógeno" },
  { id: "astro_H_003", topic: "astronomia", letter: "H", question: "Con la H: Modelo que sitúa al Sol en el centro del Sistema Solar.", answer: "Heliocentrismo" },
  { id: "astro_H_004", topic: "astronomia", letter: "H", question: "Con la H: Región dominada por el viento solar alrededor del Sol.", answer: "Heliosfera" },
  { id: "astro_H_005", topic: "astronomia", letter: "H", question: "Con la H: Línea aparente donde parece unirse cielo y tierra; referencia de altitud.", answer: "Horizonte" },
  { id: "astro_H_006", topic: "astronomia", letter: "H", question: "Con la H: Telescopio espacial lanzado en 1990 que revolucionó la astronomía observacional.", answer: "Hubble" },
  { id: "astro_H_007", topic: "astronomia", letter: "H", question: "Con la H: Explosión estelar extremadamente energética .", answer: "Hipernova" },
  { id: "astro_H_008", topic: "astronomia", letter: "H", question: "Con la H: Mitad de una esfera; se habla del celeste norte/sur.", answer: "Hemisferio" },
  { id: "astro_H_009", topic: "astronomia", letter: "H", question: "Con la H: Unidad de frecuencia usada en mediciones de ondas.", answer: "Hertz" },
  { id: "astro_H_010", topic: "astronomia", letter: "H", question: "Con la H: Radical/ion presente en química espacial y atmósferas.", answer: "Hidroxilo" },
  { id: "astro_H_011", topic: "astronomia", letter: "H", question: "Con la H: Estudio de oscilaciones del Sol para inferir su interior.", answer: "Heliosismo" },
  { id: "astro_H_012", topic: "astronomia", letter: "H", question: "Con la H: Agua congelada presente en cometas, lunas y regiones frías.", answer: "Hielo" },
  { id: "astro_H_013", topic: "astronomia", letter: "H", question: "Con la H: Región externa de galaxias o brillo alrededor de un objeto.", answer: "Halo" },
  { id: "astro_H_014", topic: "astronomia", letter: "H", question: "Con la H: Equilibrio de presiones y gravedad en estrellas y planetas.", answer: "Hidrostática" },
  { id: "astro_H_015", topic: "astronomia", letter: "H", question: "Con la H: Trayectoria abierta posible en encuentros gravitatorios.", answer: "Hiperbola" },
  { id: "astro_I_001", topic: "astronomia", letter: "I", question: "Con la I: Región del espectro útil para ver polvo y objetos fríos.", answer: "Infrarrojo" },
  { id: "astro_I_002", topic: "astronomia", letter: "I", question: "Con la I: Técnica que combina telescopios para mejorar resolución.", answer: "Interferometría" },
  { id: "astro_I_003", topic: "astronomia", letter: "I", question: "Con la I: Ángulo de un plano orbital respecto a otro plano de referencia.", answer: "Inclinación" },
  { id: "astro_I_004", topic: "astronomia", letter: "I", question: "Con la I: Proceso de quitar o añadir electrones, común en nebulosas.", answer: "Ionización" },
  { id: "astro_I_005", topic: "astronomia", letter: "I", question: "Con la I: Objeto que choca con otro cuerpo, creando cráteres.", answer: "Impactor" },
  { id: "astro_I_006", topic: "astronomia", letter: "I", question: "Con la I: Curva de igual edad usada en diagramas de cúmulos estelares.", answer: "Isocrono" },
  { id: "astro_I_007", topic: "astronomia", letter: "I", question: "Con la I: Plan de observación; p. ej., ruta de una noche de observación.", answer: "Itinerario" },
  { id: "astro_I_008", topic: "astronomia", letter: "I", question: "Con la I: Condición de temperatura constante, usada en modelos atmosféricos.", answer: "Isotermo" },
  { id: "astro_I_009", topic: "astronomia", letter: "I", question: "Con la I: Propiedad de resistir cambios de movimiento; base de dinámica orbital.", answer: "Inercia" },
  { id: "astro_I_010", topic: "astronomia", letter: "I", question: "Con la I: Representación captada por telescopios .", answer: "Imagen" },
  { id: "astro_I_011", topic: "astronomia", letter: "I", question: "Con la I: Tiempo de exposición acumulado en observación astronómica.", answer: "Integración" },
  { id: "astro_I_012", topic: "astronomia", letter: "I", question: "Con la I: Variante de un elemento con distinto número de neutrones; útil en cosmoquímica.", answer: "Isótopo" },
  { id: "astro_I_013", topic: "astronomia", letter: "I", question: "Con la I: Cantidad de radiación solar recibida por un cuerpo.", answer: "Insolación" },
  { id: "astro_I_014", topic: "astronomia", letter: "I", question: "Con la I: Momento preciso; importante en efemérides y eventos .", answer: "Instante" },
  { id: "astro_I_015", topic: "astronomia", letter: "I", question: "Con la I: Forma en que la luz incide en planetas/lunas y produce fases.", answer: "Iluminación" },
  { id: "astro_J_001", topic: "astronomia", letter: "J", question: "Con la J: Planeta gigante gaseoso, el más grande del Sistema Solar.", answer: "Júpiter" },
  { id: "astro_J_002", topic: "astronomia", letter: "J", question: "Con la J: Sonda espacial de la NASA que entró en órbita polar de Júpiter en 2016.", answer: "Juno" },
  { id: "astro_J_003", topic: "astronomia", letter: "J", question: "Con la J: Unidad usada para medir flujo en radioastronomía.", answer: "Jansky" },
  { id: "astro_J_004", topic: "astronomia", letter: "J", question: "Con la J: Luna de Saturno conocida por su contraste de brillo.", answer: "Japeto" },
  { id: "astro_J_005", topic: "astronomia", letter: "J", question: "Con la J: Luna de Saturno que comparte órbita con Epimeteo.", answer: "Jano" },
  { id: "astro_J_006", topic: "astronomia", letter: "J", question: "Con la J: Unidad de energía usada en física.", answer: "Joule" },
  { id: "astro_J_007", topic: "astronomia", letter: "J", question: "Con la J: Tipo de calendario; también se usa el día del calendario astronómico.", answer: "Juliano" },
  { id: "astro_J_008", topic: "astronomia", letter: "J", question: "Con la J: Época de referencia usada para coordenadas astronómicas.", answer: "J2000" },
  { id: "astro_J_009", topic: "astronomia", letter: "J", question: "Con la J: Telescopio espacial infrarrojo lanzado en 2021, sucesor del Hubble.", answer: "JamesWebb" },
  { id: "astro_J_010", topic: "astronomia", letter: "J", question: "Con la J: Chorro colimado de materia visto en estrellas jóvenes o agujeros negros.", answer: "Jet" },
  { id: "astro_J_011", topic: "astronomia", letter: "J", question: "Con la J: Adjetivo relativo a Júpiter o a planetas gigantes gaseosos.", answer: "Joviano" },
  { id: "astro_J_012", topic: "astronomia", letter: "J", question: "Con la J: Astrónomo francés que observó el tránsito de Venus en 1874.", answer: "Janssen" },
  { id: "astro_J_013", topic: "astronomia", letter: "J", question: "Con la J: Relacionado con condiciones parecidas a las de Júpiter .", answer: "Júpiterino" },
  { id: "astro_J_014", topic: "astronomia", letter: "J", question: "Con la J: Variación rápida en una señal; puede afectar mediciones .", answer: "Jitter" },
  { id: "astro_J_015", topic: "astronomia", letter: "J", question: "Con la J: Astrónomo francés que descubrió el helio en el espectro solar durante un eclipse de 1868.", answer: "Janssen" },
  { id: "astro_L_001", topic: "astronomia", letter: "L", question: "Con la L: Satélite natural de la Tierra.", answer: "Luna" },
  { id: "astro_L_002", topic: "astronomia", letter: "L", question: "Con la L: Potencia total emitida por una estrella.", answer: "Luminosidad" },
  { id: "astro_L_003", topic: "astronomia", letter: "L", question: "Con la L: Elemento óptico que refracta luz; base de refractores.", answer: "Lente" },
  { id: "astro_L_004", topic: "astronomia", letter: "L", question: "Con la L: Fuente de luz coherente; usada en instrumentos y medidas.", answer: "Láser" },
  { id: "astro_L_005", topic: "astronomia", letter: "L", question: "Con la L: Coordenada en la Tierra; afecta qué cielo se observa.", answer: "Latitud" },
  { id: "astro_L_006", topic: "astronomia", letter: "L", question: "Con la L: Coordenada geográfica usada para ubicar observatorios.", answer: "Longitud" },
  { id: "astro_L_007", topic: "astronomia", letter: "L", question: "Con la L: Matemático italiano que descubrió cinco puntos estables en sistemas de dos cuerpos.", answer: "Lagrange" },
  { id: "astro_L_008", topic: "astronomia", letter: "L", question: "Con la L: Pequeño “balanceo” aparente de la Luna que deja ver más superficie.", answer: "Libración" },
  { id: "astro_L_009", topic: "astronomia", letter: "L", question: "Con la L: Radiación electromagnética visible.", answer: "Luz" },
  { id: "astro_L_010", topic: "astronomia", letter: "L", question: "Con la L: Capa rígida superficial; en planetología se estudia en cuerpos rocosos.", answer: "Litosfera" },
  { id: "astro_L_011", topic: "astronomia", letter: "L", question: "Con la L: Valor de frontera; p. ej., el de Roche .", answer: "Límite" },
  { id: "astro_L_012", topic: "astronomia", letter: "L", question: "Con la L: Adjetivo histórico ligado a la Luna .", answer: "Lunático" },
  { id: "astro_L_013", topic: "astronomia", letter: "L", question: "Con la L: Brillo por unidad de área aparente; relevante en cielo nocturno.", answer: "Luminancia" },
  { id: "astro_L_014", topic: "astronomia", letter: "L", question: "Con la L: En meteorología planetaria hay precipitación .", answer: "Lluvia" },
  { id: "astro_L_015", topic: "astronomia", letter: "L", question: "Con la L: Periodo entre dos lunas nuevas, ~29,5 días.", answer: "Lunación" },
  { id: "astro_M_001", topic: "astronomia", letter: "M", question: "Con la M: Fragmento que sobrevive y cae al suelo tras entrar en la atmósfera.", answer: "Meteorito" },
  { id: "astro_M_002", topic: "astronomia", letter: "M", question: "Con la M: Fenómeno luminoso al entrar un cuerpo espacial en la atmósfera.", answer: "Meteoro" },
  { id: "astro_M_003", topic: "astronomia", letter: "M", question: "Con la M: Cuerpo pequeño en el espacio, menor que un asteroide.", answer: "Meteoroide" },
  { id: "astro_M_004", topic: "astronomia", letter: "M", question: "Con la M: Escala que describe el brillo aparente de un objeto.", answer: "Magnitud" },
  { id: "astro_M_005", topic: "astronomia", letter: "M", question: "Con la M: Cantidad de materia; determina gravedad y evolución estelar.", answer: "Masa" },
  { id: "astro_M_006", topic: "astronomia", letter: "M", question: "Con la M: Línea de referencia; en astronomía se usa el paso por el círculo vertical.", answer: "Meridiano" },
  { id: "astro_M_007", topic: "astronomia", letter: "M", question: "Con la M: Banda del espectro; clave para el fondo cósmico.", answer: "Microonda" },
  { id: "astro_M_008", topic: "astronomia", letter: "M", question: "Con la M: En cosmología se distingue la sustancia ordinaria y oscura.", answer: "Materia" },
  { id: "astro_M_009", topic: "astronomia", letter: "M", question: "Con la M: Planeta rocoso rojo, objetivo principal de exploración.", answer: "Marte" },
  { id: "astro_M_010", topic: "astronomia", letter: "M", question: "Con la M: Astrónomo francés del siglo XVIII que compiló un catálogo de 110 objetos difusos.", answer: "Messier" },
  { id: "astro_M_011", topic: "astronomia", letter: "M", question: "Con la M: Hipótesis de múltiples universos .", answer: "Multiverso" },
  { id: "astro_M_012", topic: "astronomia", letter: "M", question: "Con la M: Efecto gravitatorio que deforma cuerpos .", answer: "Marea" },
  { id: "astro_M_013", topic: "astronomia", letter: "M", question: "Con la M: Fenómeno asociado a campos magnéticos planetarios y estelares.", answer: "Magnetismo" },
  { id: "astro_M_014", topic: "astronomia", letter: "M", question: "Con la M: Región dominada por el campo magnético de un planeta.", answer: "Magnetosfera" },
  { id: "astro_M_015", topic: "astronomia", letter: "M", question: "Con la M: Roca fundida; en planetología, volcanismo depende de roca fundida.", answer: "Magma" },
  { id: "astro_N_001", topic: "astronomia", letter: "N", question: "Con la N: Nube de gas y polvo donde nacen o mueren estrellas.", answer: "Nebulosa" },
  { id: "astro_N_002", topic: "astronomia", letter: "N", question: "Con la N: Planeta gigante helado del Sistema Solar.", answer: "Neptuno" },
  { id: "astro_N_003", topic: "astronomia", letter: "N", question: "Con la N: Partícula casi sin masa que atraviesa materia; producido en el Sol.", answer: "Neutrino" },
  { id: "astro_N_004", topic: "astronomia", letter: "N", question: "Con la N: Punto opuesto al cenit, bajo los pies del observador.", answer: "Nadir" },
  { id: "astro_N_005", topic: "astronomia", letter: "N", question: "Con la N: Parte central de un planeta o de una estrella.", answer: "Núcleo" },
  { id: "astro_N_006", topic: "astronomia", letter: "N", question: "Con la N: Formación de elementos en el Big Bang y en estrellas.", answer: "Nucleosíntesis" },
  { id: "astro_N_007", topic: "astronomia", letter: "N", question: "Con la N: Periodo sin luz solar; esencial para observación astronómica.", answer: "Noche" },
  { id: "astro_N_008", topic: "astronomia", letter: "N", question: "Con la N: Físico y matemático inglés que formuló la ley de gravitación universal.", answer: "Newton" },
  { id: "astro_N_009", topic: "astronomia", letter: "N", question: "Con la N: Dirección usada para orientarse en el cielo .", answer: "Norte" },
  { id: "astro_N_010", topic: "astronomia", letter: "N", question: "Con la N: En astronomía, estructuras moleculares son regiones frías de formación estelar.", answer: "Nube" },
  { id: "astro_N_011", topic: "astronomia", letter: "N", question: "Con la N: Unidad usada para longitudes de onda de luz.", answer: "Nanómetro" },
  { id: "astro_N_012", topic: "astronomia", letter: "N", question: "Con la N: Elemento presente en atmósferas  y en química espacial.", answer: "Nitrógeno" },
  { id: "astro_N_013", topic: "astronomia", letter: "N", question: "Con la N: Explosión superficial en una enana blanca en un sistema binario.", answer: "Nova" },
  { id: "astro_N_014", topic: "astronomia", letter: "N", question: "Con la N: Oscuridad; el cielo oscuro favorece observar objetos débiles.", answer: "Negrura" },
  { id: "astro_N_015", topic: "astronomia", letter: "N", question: "Con la N: Vehículo espacial, como una sonda o una cápsula tripulada.", answer: "Nave" },
  { id: "astro_Ñ_001", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Unidad de tiempo basada en la órbita de la Tierra alrededor del Sol.", answer: "Año" },
  { id: "astro_Ñ_002", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Plural de año; se usa para escalas de tiempo astronómicas.", answer: "Años" },
  { id: "astro_Ñ_003", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Unidad de distancia basada en lo que recorre la luz en un año.", answer: "AñoLuz" },
  { id: "astro_Ñ_004", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Información detectada por telescopios .", answer: "Señal" },
  { id: "astro_Ñ_005", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Medida física o angular de un objeto en el cielo.", answer: "Tamaño" },
  { id: "astro_Ñ_006", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Adjetivo; se habla de cuerpos reducidos del Sistema Solar.", answer: "Pequeño" },
  { id: "astro_Ñ_007", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: En sistemas binarios, la estrella compañera de otra.", answer: "Compañero" },
  { id: "astro_Ñ_008", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Muchos observatorios se sitúan en elevaciones por cielos más limpios.", answer: "Montaña" },
  { id: "astro_Ñ_009", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Serie organizada de observaciones durante un periodo.", answer: "Campaña" },
  { id: "astro_Ñ_010", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Lugar asociado a lanzamientos espaciales .", answer: "Cañaveral" },
  { id: "astro_Ñ_011", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Fenómeno climático que puede afectar condiciones de observación.", answer: "Niño" },
  { id: "astro_Ñ_012", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Estación en la que cambian constelaciones visibles de noche.", answer: "Otoño" },
  { id: "astro_Ñ_013", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Valle profundo; en planetas como Marte se observan cañones.", answer: "Cañón" },
  { id: "astro_Ñ_014", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Valle o depresión; útil para describir relieves en geología planetaria.", answer: "Cañada" },
  { id: "astro_Ñ_015", topic: "astronomia", letter: "Ñ", question: "Contiene la Ñ: Momento del día; la luz solar impide observar estrellas.", answer: "Mañana" },
  { id: "astro_O_001", topic: "astronomia", letter: "O", question: "Con la O: Trayectoria de un cuerpo alrededor de otro por gravedad.", answer: "Órbita" },
  { id: "astro_O_002", topic: "astronomia", letter: "O", question: "Con la O: Lugar equipado para observar el cielo con instrumentos.", answer: "Observatorio" },
  { id: "astro_O_003", topic: "astronomia", letter: "O", question: "Con la O: Configuración donde un planeta exterior está opuesto al Sol en el cielo.", answer: "Oposición" },
  { id: "astro_O_004", topic: "astronomia", letter: "O", question: "Con la O: Cuando un cuerpo pasa delante de otro y lo tapa desde la Tierra.", answer: "Ocultación" },
  { id: "astro_O_005", topic: "astronomia", letter: "O", question: "Con la O: Lente por donde se mira en un telescopio.", answer: "Ocular" },
  { id: "astro_O_006", topic: "astronomia", letter: "O", question: "Con la O: Astrónomo holandés que propuso la existencia de una nube esférica de cometas en los confines del Sistema Solar.", answer: "Oort" },
  { id: "astro_O_007", topic: "astronomia", letter: "O", question: "Con la O: Instrumento antiguo para medir ángulos, similar al sextante.", answer: "Octante" },
  { id: "astro_O_008", topic: "astronomia", letter: "O", question: "Con la O: Elemento detectado en atmósferas y en espectros de estrellas/planetas.", answer: "Oxígeno" },
  { id: "astro_O_009", topic: "astronomia", letter: "O", question: "Con la O: Variación periódica; se estudian oscilaciones solares y estelares.", answer: "Oscilación" },
  { id: "astro_O_010", topic: "astronomia", letter: "O", question: "Con la O: Condición clave para ver objetos débiles, lejos de contaminación lumínica.", answer: "Oscuridad" },
  { id: "astro_O_011", topic: "astronomia", letter: "O", question: "Con la O: Rama que estudia luz y sistemas de lentes/espejos en telescopios.", answer: "Optica" },
  { id: "astro_O_012", topic: "astronomia", letter: "O", question: "Con la O: Adjetivo relativo a trayectorias, como velocidad de órbita.", answer: "Orbital" },
  { id: "astro_O_013", topic: "astronomia", letter: "O", question: "Con la O: Constelación destacada en el cielo de invierno.", answer: "Orion" },
  { id: "astro_O_014", topic: "astronomia", letter: "O", question: "Con la O: Elemento sintetizado en eventos extremos como fusiones de estrellas de neutrones.", answer: "Oro" },
  { id: "astro_O_015", topic: "astronomia", letter: "O", question: "Con la O: Gas que absorbe ultravioleta; importante en atmósferas planetarias.", answer: "Ozono" },
  { id: "astro_P_001", topic: "astronomia", letter: "P", question: "Con la P: Cuerpo que orbita una estrella y ha “limpiado” su órbita.", answer: "Planeta" },
  { id: "astro_P_002", topic: "astronomia", letter: "P", question: "Con la P: Punto de una órbita donde un objeto está más cerca del Sol.", answer: "Perihelio" },
  { id: "astro_P_003", topic: "astronomia", letter: "P", question: "Con la P: Método de distancia por desplazamiento aparente desde dos posiciones.", answer: "Paralaje" },
  { id: "astro_P_004", topic: "astronomia", letter: "P", question: "Con la P: Estrella de neutrones que emite pulsos regulares de radiación.", answer: "Pulsar" },
  { id: "astro_P_005", topic: "astronomia", letter: "P", question: "Con la P: Estado de la materia dominante en estrellas.", answer: "Plasma" },
  { id: "astro_P_006", topic: "astronomia", letter: "P", question: "Con la P: Estrella en formación antes de iniciar fusión estable.", answer: "Protostar" },
  { id: "astro_P_007", topic: "astronomia", letter: "P", question: "Con la P: Sinónimo común de protostar en español.", answer: "Protoestrella" },
  { id: "astro_P_008", topic: "astronomia", letter: "P", question: "Con la P: Lluvia de meteoros visible en agosto en el hemisferio norte.", answer: "Perseidas" },
  { id: "astro_P_009", topic: "astronomia", letter: "P", question: "Con la P: Cambio lento del eje de rotación, como el de la Tierra.", answer: "Precesión" },
  { id: "astro_P_010", topic: "astronomia", letter: "P", question: "Con la P: Zona parcial de sombra en un eclipse.", answer: "Penumbra" },
  { id: "astro_P_011", topic: "astronomia", letter: "P", question: "Con la P: Punto de una órbita donde un objeto está más cerca de la Tierra.", answer: "Perigeo" },
  { id: "astro_P_012", topic: "astronomia", letter: "P", question: "Con la P: Relativo a extremos geográficos; p. ej., estrella del norte o regiones árticas/antárticas.", answer: "Polar" },
  { id: "astro_P_013", topic: "astronomia", letter: "P", question: "Con la P: Nombre propio de la estrella Polar.", answer: "Polaris" },
  { id: "astro_P_014", topic: "astronomia", letter: "P", question: "Con la P: Mapa del cielo giratorio para localizar constelaciones.", answer: "Planisferio" },
  { id: "astro_P_015", topic: "astronomia", letter: "P", question: "Con la P: Medición del brillo de objetos astronómicos.", answer: "Fotometría" },
  { id: "astro_Q_001", topic: "astronomia", letter: "Q", question: "Contiene la Q: Objeto extremadamente brillante alimentado por un agujero negro.", answer: "Quasar" },
  { id: "astro_Q_002", topic: "astronomia", letter: "Q", question: "Contiene la Q: Partícula fundamental que compone protones y neutrones.", answer: "Quark" },
  { id: "astro_Q_003", topic: "astronomia", letter: "Q", question: "Contiene la Q: Objeto del cinturón de Kuiper .", answer: "Quaoar" },
  { id: "astro_Q_004", topic: "astronomia", letter: "Q", question: "Contiene la Q: Objeto menor  entre Saturno y Urano: 2060 Chiron.", answer: "Quirón" },
  { id: "astro_Q_005", topic: "astronomia", letter: "Q", question: "Contiene la Q: Satélite relé chino usado para comunicaciones en la cara oculta lunar.", answer: "Queqiao" },
  { id: "astro_Q_006", topic: "astronomia", letter: "Q", question: "Contiene la Q: Sigla en astronomía para “quasi-stellar object” .", answer: "QSO" },
  { id: "astro_Q_007", topic: "astronomia", letter: "Q", question: "Contiene la Q: Paquetes discretos de energía; base de la física moderna.", answer: "Quanta" },
  { id: "astro_Q_008", topic: "astronomia", letter: "Q", question: "Contiene la Q: Rama de la física que explica la luz y la materia a escala microscópica.", answer: "Quántica" },
  { id: "astro_Q_009", topic: "astronomia", letter: "Q", question: "Contiene la Q: Estado de baja actividad; se habla de galaxias o estrellas inactivas.", answer: "Quiescente" },
  { id: "astro_Q_010", topic: "astronomia", letter: "Q", question: "Contiene la Q: Estudio de composición; espectros revelan composición del espacio.", answer: "Química" },
  { id: "astro_Q_011", topic: "astronomia", letter: "Q", question: "Contiene la Q: Evento astronómico anual relacionado con la inclinación terrestre.", answer: "Equinoccio" },
  { id: "astro_Q_012", topic: "astronomia", letter: "Q", question: "Contiene la Q: Condición en estrellas donde presión y gravedad se compensan.", answer: "Equilibrio" },
  { id: "astro_Q_013", topic: "astronomia", letter: "Q", question: "Contiene la Q: A igual distancia; usado en descripciones geométricas de observación.", answer: "Equidistante" },
  { id: "astro_Q_014", topic: "astronomia", letter: "Q", question: "Contiene la Q: Condición necesaria; p. ej., condición para ver estrellas débiles: cielo oscuro.", answer: "Requisito" },
  { id: "astro_Q_015", topic: "astronomia", letter: "Q", question: "Contiene la Q: Adjetivo con ‘q’; se usa para cuerpos reducidos del Sistema Solar.", answer: "Pequeño" },
  { id: "astro_R_001", topic: "astronomia", letter: "R", question: "Con la R: Energía emitida como ondas o partículas .", answer: "Radiación" },
  { id: "astro_R_002", topic: "astronomia", letter: "R", question: "Con la R: Giro de un cuerpo sobre su eje.", answer: "Rotación" },
  { id: "astro_R_003", topic: "astronomia", letter: "R", question: "Con la R: Movimiento orbital completo alrededor de otro cuerpo.", answer: "Revolución" },
  { id: "astro_R_004", topic: "astronomia", letter: "R", question: "Con la R: Desviación de la luz al atravesar la atmósfera.", answer: "Refracción" },
  { id: "astro_R_005", topic: "astronomia", letter: "R", question: "Con la R: Telescopio que usa espejos en lugar de lentes.", answer: "Reflector" },
  { id: "astro_R_006", topic: "astronomia", letter: "R", question: "Con la R: Capacidad de distinguir detalles finos en una imagen.", answer: "Resolución" },
  { id: "astro_R_007", topic: "astronomia", letter: "R", question: "Con la R: Límite gravitatorio relacionado con mareas y anillos.", answer: "Roche" },
  { id: "astro_R_008", topic: "astronomia", letter: "R", question: "Con la R: Dirección hacia/desde el observador; se usa en velocidad de dirección.", answer: "Radial" },
  { id: "astro_R_009", topic: "astronomia", letter: "R", question: "Con la R: Teoría que describe gravedad y espacio-tiempo.", answer: "Relatividad" },
  { id: "astro_R_010", topic: "astronomia", letter: "R", question: "Con la R: En “corrimiento al rojo”, indica expansión o alejamiento (color).", answer: "Rojo" },
  { id: "astro_R_011", topic: "astronomia", letter: "R", question: "Con la R: Evento breve e intenso, como estallidos de rayos gamma.", answer: "Ráfaga" },
  { id: "astro_R_012", topic: "astronomia", letter: "R", question: "Con la R: Capa de polvo y fragmentos en superficies sin atmósfera, como la Luna.", answer: "Regolito" },
  { id: "astro_R_013", topic: "astronomia", letter: "R", question: "Con la R: Radiación de alta energía observada en astronomía.", answer: "RayosX" },
  { id: "astro_R_014", topic: "astronomia", letter: "R", question: "Con la R: Instrumento que observa el cielo en ondas de radio.", answer: "Radiotelescopio" },
  { id: "astro_R_015", topic: "astronomia", letter: "R", question: "Con la R: Unidad angular usada en física y astronomía.", answer: "Radian" },
  { id: "astro_S_001", topic: "astronomia", letter: "S", question: "Con la S: Objeto natural o artificial que orbita un planeta.", answer: "Satélite" },
  { id: "astro_S_002", topic: "astronomia", letter: "S", question: "Con la S: Explosión estelar que puede formar una estrella de neutrones o agujero negro.", answer: "Supernova" },
  { id: "astro_S_003", topic: "astronomia", letter: "S", question: "Con la S: Momento del año con máxima inclinación del Sol en el cielo.", answer: "Solsticio" },
  { id: "astro_S_004", topic: "astronomia", letter: "S", question: "Con la S: Conjunto organizado; p. ej., el conjunto de planetas alrededor del Sol.", answer: "Sistema" },
  { id: "astro_S_005", topic: "astronomia", letter: "S", question: "Con la S: Relacionado con estrellas; día estelar vs día solar.", answer: "Sideral" },
  { id: "astro_S_006", topic: "astronomia", letter: "S", question: "Con la S: Relacionado con nuestra estrella, como viento estelar.", answer: "Solar" },
  { id: "astro_S_007", topic: "astronomia", letter: "S", question: "Con la S: Nave no tripulada que explora cuerpos del Sistema Solar.", answer: "Sonda" },
  { id: "astro_S_008", topic: "astronomia", letter: "S", question: "Con la S: Información captada por un detector; p. ej., transmisión de radio.", answer: "Señal" },
  { id: "astro_S_009", topic: "astronomia", letter: "S", question: "Con la S: Relacionado con satélites y observación desde el espacio.", answer: "Satelital" },
  { id: "astro_S_010", topic: "astronomia", letter: "S", question: "Con la S: Región sin luz; clave en eclipses.", answer: "Sombra" },
  { id: "astro_S_011", topic: "astronomia", letter: "S", question: "Con la S: Paso de sólido a gas; explica colas de cometas.", answer: "Sublimación" },
  { id: "astro_S_012", topic: "astronomia", letter: "S", question: "Con la S: En planetas, estudia “terremotos” y estructura interna .", answer: "Sismología" },
  { id: "astro_S_013", topic: "astronomia", letter: "S", question: "Con la S: Condición de rotación/orbita acoplada .", answer: "Sincronía" },
  { id: "astro_S_014", topic: "astronomia", letter: "S", question: "Con la S: Región teórica de densidad extrema en un agujero negro.", answer: "Singularidad" },
  { id: "astro_S_015", topic: "astronomia", letter: "S", question: "Con la S: Planeta con anillos prominentes.", answer: "Saturno" },
  { id: "astro_T_001", topic: "astronomia", letter: "T", question: "Con la T: Instrumento para observar objetos lejanos del cielo.", answer: "Telescopio" },
  { id: "astro_T_002", topic: "astronomia", letter: "T", question: "Con la T: Paso de un cuerpo por delante de otro, como Venus frente al Sol.", answer: "Tránsito" },
  { id: "astro_T_003", topic: "astronomia", letter: "T", question: "Con la T: Magnitud que describe energía térmica; se infiere por color y espectro.", answer: "Temperatura" },
  { id: "astro_T_004", topic: "astronomia", letter: "T", question: "Con la T: Camino seguido por un objeto; se usa para sondas y meteoros.", answer: "Trayectoria" },
  { id: "astro_T_005", topic: "astronomia", letter: "T", question: "Con la T: Procesos que deforman superficies; relevante en planetología.", answer: "Tectónica" },
  { id: "astro_T_006", topic: "astronomia", letter: "T", question: "Con la T: Nuestro planeta, tercero desde el Sol.", answer: "Tierra" },
  { id: "astro_T_007", topic: "astronomia", letter: "T", question: "Con la T: Luna de Saturno con atmósfera densa.", answer: "Titán" },
  { id: "astro_T_008", topic: "astronomia", letter: "T", question: "Con la T: Capa alta de una atmósfera donde la temperatura aumenta con altura.", answer: "Termosfera" },
  { id: "astro_T_009", topic: "astronomia", letter: "T", question: "Con la T: Deformación; en instrumentación puede afectar alineación.", answer: "Torsión" },
  { id: "astro_T_010", topic: "astronomia", letter: "T", question: "Con la T: Movimiento caótico del aire que degrada la “seeing” astronómica.", answer: "Turbulencia" },
  { id: "astro_T_011", topic: "astronomia", letter: "T", question: "Con la T: Relacionado con mareas gravitatorias .", answer: "Tidal" },
  { id: "astro_T_012", topic: "astronomia", letter: "T", question: "Con la T: Elemento químico detectado en algunos espectros; .", answer: "Telurio" },
  { id: "astro_T_013", topic: "astronomia", letter: "T", question: "Con la T: Partícula hipotética más rápida que la luz .", answer: "Taquión" },
  { id: "astro_T_014", topic: "astronomia", letter: "T", question: "Con la T: Palabra clave en efemérides; p. ej., elemento de una serie orbital .", answer: "Término" },
  { id: "astro_T_015", topic: "astronomia", letter: "T", question: "Con la T: Rama que estudia calor y energía; aplicada a atmósferas y estrellas.", answer: "Termodinámica" },
  { id: "astro_U_001", topic: "astronomia", letter: "U", question: "Con la U: Todo lo que existe: espacio, tiempo, materia y energía.", answer: "Universo" },
  { id: "astro_U_002", topic: "astronomia", letter: "U", question: "Con la U: Radiación más energética que la visible, observada con telescopios espaciales.", answer: "Ultravioleta" },
  { id: "astro_U_003", topic: "astronomia", letter: "U", question: "Con la U: Parte más oscura de una sombra, como en un eclipse.", answer: "Umbra" },
  { id: "astro_U_004", topic: "astronomia", letter: "U", question: "Con la U: Valor mínimo detectable en un instrumento o sensor.", answer: "Umbral" },
  { id: "astro_U_005", topic: "astronomia", letter: "U", question: "Con la U: Planeta gigante helado con eje muy inclinado.", answer: "Urano" },
  { id: "astro_U_006", topic: "astronomia", letter: "U", question: "Con la U: Elemento pesado; su abundancia ayuda a datar procesos en astrofísica nuclear.", answer: "Uranio" },
  { id: "astro_U_007", topic: "astronomia", letter: "U", question: "Con la U: Medida estándar; en astronomía hay UA .", answer: "Unidad" },
  { id: "astro_U_008", topic: "astronomia", letter: "U", question: "Con la U: Sincronía; p. ej., rotación sincronizada con la órbita .", answer: "Unisón" },
  { id: "astro_U_009", topic: "astronomia", letter: "U", question: "Con la U: Presencia extendida; p. ej., presencia general del hidrógeno en el universo.", answer: "Ubiquidad" },
  { id: "astro_U_010", topic: "astronomia", letter: "U", question: "Con la U: Banda de radio  usada en comunicaciones y radioastronomía.", answer: "UHF" },
  { id: "astro_U_011", topic: "astronomia", letter: "U", question: "Con la U: Adjetivo de Osa; p. ej., región de la Osa del cielo .", answer: "Ursina" },
  { id: "astro_U_012", topic: "astronomia", letter: "U", question: "Con la U: Zona de sombra; término relacionado con umbra .", answer: "Umbría" },
  { id: "astro_U_013", topic: "astronomia", letter: "U", question: "Con la U: Molécula orgánica detectada en química interestelar .", answer: "Urea" },
  { id: "astro_U_014", topic: "astronomia", letter: "U", question: "Con la U: Letra usada en designaciones estelares y variables en catálogos.", answer: "Upsilon" },
  { id: "astro_U_015", topic: "astronomia", letter: "U", question: "Con la U: Describe pulsos/escala temporal muy breve en instrumentación.", answer: "Ultracorto" },
  { id: "astro_V_001", topic: "astronomia", letter: "V", question: "Con la V: Planeta rocoso con atmósfera densa y efecto invernadero extremo.", answer: "Venus" },
  { id: "astro_V_002", topic: "astronomia", letter: "V", question: "Con la V: Magnitud del movimiento; clave en órbitas y corrimiento Doppler.", answer: "Velocidad" },
  { id: "astro_V_003", topic: "astronomia", letter: "V", question: "Con la V: Región con muy baja densidad de materia, común en el espacio.", answer: "Vacío" },
  { id: "astro_V_004", topic: "astronomia", letter: "V", question: "Con la V: Tipo de estrella cuyo brillo cambia con el tiempo.", answer: "Variable" },
  { id: "astro_V_005", topic: "astronomia", letter: "V", question: "Con la V: Representación de magnitud y dirección; usado en dinámica orbital.", answer: "Vector" },
  { id: "astro_V_006", topic: "astronomia", letter: "V", question: "Con la V: Flujo de partículas; p. ej., corriente solar.", answer: "Viento" },
  { id: "astro_V_007", topic: "astronomia", letter: "V", question: "Con la V: Relativo a primavera; p. ej., equinoccio de primavera.", answer: "Vernal" },
  { id: "astro_V_008", topic: "astronomia", letter: "V", question: "Con la V: Estructura eruptiva; hay volcanismo en Io y en otros cuerpos.", answer: "Volcán" },
  { id: "astro_V_009", topic: "astronomia", letter: "V", question: "Con la V: Qué tan bien se ve un objeto, afectado por atmósfera y luz parásita.", answer: "Visibilidad" },
  { id: "astro_V_010", topic: "astronomia", letter: "V", question: "Con la V: Oscurecimiento hacia bordes del campo en óptica.", answer: "Viñeteo" },
  { id: "astro_V_011", topic: "astronomia", letter: "V", question: "Con la V: Abreviatura de espectro visible en instrumentación .", answer: "Vis" },
  { id: "astro_V_012", topic: "astronomia", letter: "V", question: "Con la V: Punto extremo; en órbitas se habla de puntos de hipérbolas.", answer: "Vértice" },
  { id: "astro_V_013", topic: "astronomia", letter: "V", question: "Con la V: Constelación del zodiaco y cúmulo de galaxias cercano.", answer: "Virgo" },
  { id: "astro_V_014", topic: "astronomia", letter: "V", question: "Con la V: Nombre histórico propuesto para un planeta interior a Mercurio .", answer: "Vulcano" },
  { id: "astro_V_015", topic: "astronomia", letter: "V", question: "Con la V: Depresiones/relieves; en Marte destaca el sistema de depresiones Marineris .", answer: "Valles" },
  { id: "astro_X_001", topic: "astronomia", letter: "X", question: "Contiene la X: Sistema estelar.en español.", answer: "Galaxia" },
  { id: "astro_X_002", topic: "astronomia", letter: "X", question: "Contiene la X: Planeta fuera del Sistema Solar detectado por tránsito o velocidad radial.", answer: "Exoplaneta" },
  { id: "astro_X_003", topic: "astronomia", letter: "X", question: "Contiene la X: Aumento de escala del universo evidenciado por corrimiento al rojo.", answer: "Expansión" },
  { id: "astro_X_004", topic: "astronomia", letter: "X", question: "Contiene la X: Parámetro que mide cuán elíptica es una órbita.", answer: "Excentricidad" },
  { id: "astro_X_005", topic: "astronomia", letter: "X", question: "Contiene la X: Capa más externa y tenue de una atmósfera.", answer: "Exosfera" },
  { id: "astro_X_006", topic: "astronomia", letter: "X", question: "Contiene la X: Relacionado con vida o fenómenos fuera de la Tierra.", answer: "Extraterrestre" },
  { id: "astro_X_007", topic: "astronomia", letter: "X", question: "Contiene la X: Rebote de la luz; importante en espejos de telescopios.", answer: "Reflexión" },
  { id: "astro_X_008", topic: "astronomia", letter: "X", question: "Contiene la X: Relacionado con el eje de rotación .", answer: "Axial" },
  { id: "astro_X_009", topic: "astronomia", letter: "X", question: "Contiene la X: Unidad relacionada con iluminación .", answer: "Lux" },
  { id: "astro_X_010", topic: "astronomia", letter: "X", question: "Contiene la X: Gas noble usado en propulsión iónica en algunas naves.", answer: "Xenón" },
  { id: "astro_X_011", topic: "astronomia", letter: "X", question: "Contiene la X: Evento energético; p. ej., estallido estelar.", answer: "Explosión" },
  { id: "astro_X_012", topic: "astronomia", letter: "X", question: "Contiene la X: Tiempo de captura de luz en astrofotografía.", answer: "Exposición" },
  { id: "astro_X_013", topic: "astronomia", letter: "X", question: "Contiene la X: Enlace o unión entre componentes de un sistema, como en redes de telescopios.", answer: "Conexión" },
  { id: "astro_X_014", topic: "astronomia", letter: "X", question: "Contiene la X: Atenuación de luz por atmósfera o polvo interestelar.", answer: "Extinción" },
  { id: "astro_X_015", topic: "astronomia", letter: "X", question: "Contiene la X: Que está más allá de nuestra galaxia.", answer: "Extragaláctico" },
  { id: "astro_Y_001", topic: "astronomia", letter: "Y", question: "Contiene la Y: Camino seguido por un objeto.", answer: "Trayectoria" },
  { id: "astro_Y_002", topic: "astronomia", letter: "Y", question: "Contiene la Y: Sondas espaciales que exploraron planetas exteriores.", answer: "Voyager" },
  { id: "astro_Y_003", topic: "astronomia", letter: "Y", question: "Contiene la Y: Sonda que descendió en Titán.", answer: "Huygens" },
  { id: "astro_Y_004", topic: "astronomia", letter: "Y", question: "Contiene la Y: Misión japonesa de retorno de muestras.", answer: "Hayabusa" },
  { id: "astro_Y_005", topic: "astronomia", letter: "Y", question: "Contiene la Y: Asteroide del que Hayabusa2 trajo muestras.", answer: "Ryugu" },
  { id: "astro_Y_006", topic: "astronomia", letter: "Y", question: "Contiene la Y: Primera estación espacial de EE. UU.", answer: "Skylab" },
  { id: "astro_Y_007", topic: "astronomia", letter: "Y", question: "Contiene la Y: Serie de estaciones espaciales soviéticas.", answer: "Salyut" },
  { id: "astro_Y_008", topic: "astronomia", letter: "Y", question: "Contiene la Y: Nave rusa tripulada.", answer: "Soyuz" },
  { id: "astro_Y_009", topic: "astronomia", letter: "Y", question: "Contiene la Y: Astrónomo alemán del siglo XVII que introdujo el sistema de letras griegas para nombrar estrellas.", answer: "Bayer" },
  { id: "astro_Y_010", topic: "astronomia", letter: "Y", question: "Contiene la Y: Constelación de la Lira.", answer: "Lyra" },
  { id: "astro_Y_011", topic: "astronomia", letter: "Y", question: "Contiene la Y: Serie de líneas del hidrógeno en ultravioleta.", answer: "Lyman" },
  { id: "astro_Y_012", topic: "astronomia", letter: "Y", question: "Contiene la Y: Como radiación gamma.", answer: "Rayos" },
  { id: "astro_Y_013", topic: "astronomia", letter: "Y", question: "Contiene la Y: Expulsión de material; en astronomía, expulsión de masa coronal.", answer: "Eyección" },
  { id: "astro_Y_014", topic: "astronomia", letter: "Y", question: "Contiene la Y: Cúmulo estelar visible a simple vista.", answer: "Pléyades" },
  { id: "astro_Y_015", topic: "astronomia", letter: "Y", question: "Contiene la Y: Como Osa grande.", answer: "Mayor" },
  { id: "astro_Z_001", topic: "astronomia", letter: "Z", question: "Con la Z: Franja del cielo por donde pasan Sol, Luna y planetas.", answer: "Zodiaco" },
  { id: "astro_Z_002", topic: "astronomia", letter: "Z", question: "Con la Z: Punto del cielo justo sobre el observador .", answer: "Zenit" },
  { id: "astro_Z_003", topic: "astronomia", letter: "Z", question: "Con la Z: Punto del cielo directamente encima del observador.", answer: "Zénit" },
  { id: "astro_Z_004", topic: "astronomia", letter: "Z", question: "Con la Z: Letra usada en designaciones estelares  dentro de constelaciones.", answer: "Zeta" },
  { id: "astro_Z_005", topic: "astronomia", letter: "Z", question: "Con la Z: Relacionado con el zodiaco, como luz zodiacal.", answer: "Zodiacal" },
  { id: "astro_Z_006", topic: "astronomia", letter: "Z", question: "Con la Z: Relacionado con el zodiaco; p. ej., luz zodiacal.", answer: "Zodiacal" },
  { id: "astro_Z_007", topic: "astronomia", letter: "Z", question: "Con la Z: Patrón; en espectros o trayectorias puede describirse así .", answer: "Zigzag" },
  { id: "astro_Z_008", topic: "astronomia", letter: "Z", question: "Con la Z: Color; usado para describir tonos del cielo/planetas .", answer: "Zafiro" },
  { id: "astro_Z_009", topic: "astronomia", letter: "Z", question: "Con la Z: Constelación menor “Vulpecula” en latín; zorro en español .", answer: "Zorro" },
  { id: "astro_Z_010", topic: "astronomia", letter: "Z", question: "Con la Z: Viento regional; afecta seeing en algunos sitios .", answer: "Zonda" },
  { id: "astro_Z_011", topic: "astronomia", letter: "Z", question: "Con la Z: Mineral usado en datación; analogía en geocronología planetaria.", answer: "Zircón" },
  { id: "astro_Z_012", topic: "astronomia", letter: "Z", question: "Con la Z: Relacionado con el cénit; p. ej., distancia al cénit.", answer: "Zenital" },
  { id: "astro_Z_013", topic: "astronomia", letter: "Z", question: "Con la Z: Ruido instrumental; puede contaminar señales .", answer: "Zumbido" },
  { id: "astro_Z_014", topic: "astronomia", letter: "Z", question: "Con la Z: Astrónomo suizo-estadounidense que acuñó el término supernova y predijo la materia oscura.", answer: "Zwicky" },
  { id: "astro_Z_015", topic: "astronomia", letter: "Z", question: "Con la Z: Elemento químico; aparece en química estelar .", answer: "Zirconio" },
];
