import type { QA } from "./types";

export const BIOLOGIA: QA[] = [
  { id: "bio_A_001", topic: "biologia", letter: "A", question: "Con la A: Molécula que contiene la información genética en la mayoría de los seres vivos.", answer: "ADN" },
  { id: "bio_A_002", topic: "biologia", letter: "A", question: "Con la A: Variante de un gen que puede causar diferencias en un rasgo.", answer: "Alelo" },
  { id: "bio_A_003", topic: "biologia", letter: "A", question: "Con la A: Unidad básica que forma las proteínas.", answer: "Aminoácido" },
  { id: "bio_A_004", topic: "biologia", letter: "A", question: "Con la A: Base nitrogenada presente en ADN y ARN.", answer: "Adenina" },
  { id: "bio_A_005", topic: "biologia", letter: "A", question: "Con la A: Prolongación de la neurona que transmite impulsos nerviosos.", answer: "Axón" },
  { id: "bio_A_006", topic: "biologia", letter: "A", question: "Con la A: Saco microscópico en los pulmones donde ocurre el intercambio de gases.", answer: "Alvéolo" },
  { id: "bio_A_007", topic: "biologia", letter: "A", question: "Con la A: Sustancia que puede desencadenar una respuesta inmunitaria.", answer: "Antígeno" },
  { id: "bio_A_008", topic: "biologia", letter: "A", question: "Con la A: Proteína defensiva producida por el sistema inmunitario.", answer: "Anticuerpo" },
  { id: "bio_A_009", topic: "biologia", letter: "A", question: "Con la A: Molécula que actúa como “moneda” energética de la célula.", answer: "ATP" },
  { id: "bio_A_010", topic: "biologia", letter: "A", question: "Con la A: Organismo que produce su propio alimento a partir de sustancias inorgánicas.", answer: "Autótrofo" },
  { id: "bio_A_011", topic: "biologia", letter: "A", question: "Con la A: Vertebrado que suele vivir parte de su vida en agua y parte en tierra.", answer: "Anfibio" },
  { id: "bio_A_012", topic: "biologia", letter: "A", question: "Con la A: Vaso sanguíneo que lleva sangre desde el corazón hacia los tejidos.", answer: "Arteria" },
  { id: "bio_A_013", topic: "biologia", letter: "A", question: "Con la A: Característica heredable que mejora la supervivencia o reproducción.", answer: "Adaptación" },
  { id: "bio_A_014", topic: "biologia", letter: "A", question: "Con la A: Muerte celular programada, esencial para el desarrollo y el equilibrio tisular.", answer: "Apoptosis" },
  { id: "bio_A_015", topic: "biologia", letter: "A", question: "Con la A: La arteria principal que sale del corazón.", answer: "Aorta" },
  { id: "bio_B_001", topic: "biologia", letter: "B", question: "Con la B: Microorganismo unicelular sin núcleo verdadero.", answer: "Bacteria" },
  { id: "bio_B_002", topic: "biologia", letter: "B", question: "Con la B: Gran región ecológica con clima y comunidades características.", answer: "Bioma" },
  { id: "bio_B_003", topic: "biologia", letter: "B", question: "Con la B: Variedad de seres vivos en un área o en el planeta.", answer: "Biodiversidad" },
  { id: "bio_B_004", topic: "biologia", letter: "B", question: "Con la B: Conducto que lleva aire desde la tráquea a los pulmones.", answer: "Bronquio" },
  { id: "bio_B_005", topic: "biologia", letter: "B", question: "Con la B: Líquido producido por el hígado que ayuda a digerir grasas.", answer: "Bilis" },
  { id: "bio_B_006", topic: "biologia", letter: "B", question: "Con la B: Órgano que participa en la filtración de la sangre y la respuesta inmune.", answer: "Bazo" },
  { id: "bio_B_007", topic: "biologia", letter: "B", question: "Con la B: Tipo de bacteria con forma de bastón.", answer: "Bacilo" },
  { id: "bio_B_008", topic: "biologia", letter: "B", question: "Con la B: Lugar físico con condiciones ambientales donde vive una comunidad.", answer: "Biotopo" },
  { id: "bio_B_009", topic: "biologia", letter: "B", question: "Con la B: Inicio del crecimiento de una planta a partir de una yema o semilla.", answer: "Brote" },
  { id: "bio_B_010", topic: "biologia", letter: "B", question: "Con la B: Músculo del brazo que flexiona el codo.", answer: "Bíceps" },
  { id: "bio_B_011", topic: "biologia", letter: "B", question: "Con la B: Molusco con dos valvas, como almejas o mejillones.", answer: "Bivalvo" },
  { id: "bio_B_012", topic: "biologia", letter: "B", question: "Con la B: Etapa temprana del embrión en mamíferos antes de implantarse.", answer: "Blastocisto" },
  { id: "bio_B_013", topic: "biologia", letter: "B", question: "Con la B: Sistema que regula el intercambio entre madre y feto.", answer: "Barreraplacentaria" },
  { id: "bio_B_014", topic: "biologia", letter: "B", question: "Con la B: Tipo de glóbulo blanco implicado en respuestas alérgicas.", answer: "Basófilo" },
  { id: "bio_B_015", topic: "biologia", letter: "B", question: "Con la B: Disciplina que analiza dilemas morales en biología y medicina.", answer: "Bioética" },
  { id: "bio_C_001", topic: "biologia", letter: "C", question: "Con la C: Unidad básica estructural y funcional de los seres vivos.", answer: "Célula" },
  { id: "bio_C_002", topic: "biologia", letter: "C", question: "Con la C: Contenido interno de la célula fuera del núcleo.", answer: "Citoplasma" },
  { id: "bio_C_003", topic: "biologia", letter: "C", question: "Con la C: Estructura que organiza el ADN y contiene genes.", answer: "Cromosoma" },
  { id: "bio_C_004", topic: "biologia", letter: "C", question: "Con la C: Pigmento verde clave para captar luz en la fotosíntesis.", answer: "Clorofila" },
  { id: "bio_C_005", topic: "biologia", letter: "C", question: "Con la C: Conjunto ordenado de cromosomas de un individuo.", answer: "Cariotipo" },
  { id: "bio_C_006", topic: "biologia", letter: "C", question: "Con la C: Vaso sanguíneo muy fino donde se intercambian sustancias con tejidos.", answer: "Capilar" },
  { id: "bio_C_007", topic: "biologia", letter: "C", question: "Con la C: Estructura relacionada con el huso mitótico en células animales.", answer: "Centríolo" },
  { id: "bio_C_008", topic: "biologia", letter: "C", question: "Con la C: Cubierta proteica que rodea el material genético de un virus.", answer: "Cápside" },
  { id: "bio_C_009", topic: "biologia", letter: "C", question: "Con la C: Relación donde una especie se beneficia y la otra no se afecta.", answer: "Comensalismo" },
  { id: "bio_C_010", topic: "biologia", letter: "C", question: "Con la C: Organismo que se alimenta principalmente de otros animales.", answer: "Carnívoro" },
  { id: "bio_C_011", topic: "biologia", letter: "C", question: "Con la C: Bacteria capaz de realizar fotosíntesis y liberar oxígeno.", answer: "Cianobacteria" },
  { id: "bio_C_012", topic: "biologia", letter: "C", question: "Con la C: Etapa del ciclo celular en la que la célula se divide.", answer: "Citosis" },
  { id: "bio_C_013", topic: "biologia", letter: "C", question: "Con la C: Parte del cerebro asociada a coordinación y equilibrio.", answer: "Cerebelo" },
  { id: "bio_C_014", topic: "biologia", letter: "C", question: "Con la C: Proteína estructural abundante en piel, tendones y huesos.", answer: "Colágeno" },
  { id: "bio_C_015", topic: "biologia", letter: "C", question: "Con la C: Capa externa de algunos órganos; p. ej., corteza cerebral o renal.", answer: "Corteza" },
  { id: "bio_D_001", topic: "biologia", letter: "D", question: "Con la D: Movimiento de partículas desde mayor a menor concentración.", answer: "Difusión" },
  { id: "bio_D_002", topic: "biologia", letter: "D", question: "Con la D: Se dice del alelo que se expresa con una sola copia en el genotipo.", answer: "Dominante" },
  { id: "bio_D_003", topic: "biologia", letter: "D", question: "Con la D: Proceso de descomposición de alimentos para absorber nutrientes.", answer: "Digestión" },
  { id: "bio_D_004", topic: "biologia", letter: "D", question: "Con la D: Prolongación neuronal que recibe señales.", answer: "Dendrita" },
  { id: "bio_D_005", topic: "biologia", letter: "D", question: "Con la D: Pérdida de un fragmento de ADN.", answer: "Deleción" },
  { id: "bio_D_006", topic: "biologia", letter: "D", question: "Con la D: Azúcar presente en el ADN.", answer: "Desoxirribosa" },
  { id: "bio_D_007", topic: "biologia", letter: "D", question: "Con la D: Alga microscópica con pared de sílice.", answer: "Diatomea" },
  { id: "bio_D_008", topic: "biologia", letter: "D", question: "Con la D: Con dos juegos de cromosomas (2n).", answer: "Diploide" },
  { id: "bio_D_009", topic: "biologia", letter: "D", question: "Con la D: Azúcar formado por dos monosacáridos.", answer: "Disacárido" },
  { id: "bio_D_010", topic: "biologia", letter: "D", question: "Con la D: Neurotransmisor involucrado en movimiento y recompensa.", answer: "Dopamina" },
  { id: "bio_D_011", topic: "biologia", letter: "D", question: "Con la D: Capa de la piel bajo la epidermis.", answer: "Dermis" },
  { id: "bio_D_012", topic: "biologia", letter: "D", question: "Con la D: Primera porción del intestino delgado.", answer: "Duodeno" },
  { id: "bio_D_013", topic: "biologia", letter: "D", question: "Con la D: Fase en la que el corazón se relaja y se llena de sangre.", answer: "Diástole" },
  { id: "bio_D_014", topic: "biologia", letter: "D", question: "Con la D: Desequilibrio de la microbiota, por ejemplo intestinal.", answer: "Disbiosis" },
  { id: "bio_D_015", topic: "biologia", letter: "D", question: "Con la D: Producción y eliminación de orina.", answer: "Diuresis" },
  { id: "bio_E_001", topic: "biologia", letter: "E", question: "Con la E: Conjunto de organismos y su ambiente físico interactuando.", answer: "Ecosistema" },
  { id: "bio_E_002", topic: "biologia", letter: "E", question: "Con la E: Proteína que acelera reacciones químicas en el cuerpo.", answer: "Enzima" },
  { id: "bio_E_003", topic: "biologia", letter: "E", question: "Con la E: Tejido que recubre superficies y cavidades del organismo.", answer: "Epitelio" },
  { id: "bio_E_004", topic: "biologia", letter: "E", question: "Con la E: Glóbulo rojo, encargado del transporte de oxígeno.", answer: "Eritrocito" },
  { id: "bio_E_005", topic: "biologia", letter: "E", question: "Con la E: Grupo de organismos que pueden reproducirse entre sí y dejar descendencia fértil.", answer: "Especie" },
  { id: "bio_E_006", topic: "biologia", letter: "E", question: "Con la E: Cambio heredable en poblaciones a lo largo de generaciones.", answer: "Evolución" },
  { id: "bio_E_007", topic: "biologia", letter: "E", question: "Con la E: Eliminación de desechos metabólicos del organismo.", answer: "Excreción" },
  { id: "bio_E_008", topic: "biologia", letter: "E", question: "Con la E: Etapa temprana de desarrollo después de la fecundación.", answer: "Embrión" },
  { id: "bio_E_009", topic: "biologia", letter: "E", question: "Con la E: Organismo con células que tienen núcleo verdadero.", answer: "Eucariota" },
  { id: "bio_E_010", topic: "biologia", letter: "E", question: "Con la E: Teoría sobre el origen de mitocondrias y cloroplastos.", answer: "Endosimbiosis" },
  { id: "bio_E_011", topic: "biologia", letter: "E", question: "Con la E: Animal cuya temperatura corporal depende del ambiente.", answer: "Ectotermo" },
  { id: "bio_E_012", topic: "biologia", letter: "E", question: "Con la E: Abertura en hojas por donde entra CO₂ y sale vapor de agua.", answer: "Estoma" },
  { id: "bio_E_013", topic: "biologia", letter: "E", question: "Con la E: Capa más externa de la piel (o de órganos vegetales).", answer: "Epidermis" },
  { id: "bio_E_014", topic: "biologia", letter: "E", question: "Con la E: Hormona sexual que regula múltiples funciones reproductivas.", answer: "Estrógeno" },
  { id: "bio_E_015", topic: "biologia", letter: "E", question: "Con la E: Tubo que lleva el alimento de la boca al estómago.", answer: "Esofago" },
  { id: "bio_F_001", topic: "biologia", letter: "F", question: "Con la F: Proceso por el que plantas producen glucosa usando luz.", answer: "Fotosíntesis" },
  { id: "bio_F_002", topic: "biologia", letter: "F", question: "Con la F: Obtención de energía sin oxígeno, típica de levaduras y bacterias.", answer: "Fermentación" },
  { id: "bio_F_003", topic: "biologia", letter: "F", question: "Con la F: Unión de gametos para formar un cigoto.", answer: "Fecundación" },
  { id: "bio_F_004", topic: "biologia", letter: "F", question: "Con la F: Hueso más largo del cuerpo humano.", answer: "Fémur" },
  { id: "bio_F_005", topic: "biologia", letter: "F", question: "Con la F: Proceso celular que engloba partículas o microbios.", answer: "Fagocitosis" },
  { id: "bio_F_006", topic: "biologia", letter: "F", question: "Con la F: Molécula clave en membranas celulares con cabeza y colas.", answer: "Fosfolípido" },
  { id: "bio_F_007", topic: "biologia", letter: "F", question: "Con la F: Azúcar presente en frutas y miel.", answer: "Fructosa" },
  { id: "bio_F_008", topic: "biologia", letter: "F", question: "Con la F: Proteína que forma redes en la coagulación sanguínea.", answer: "Fibrina" },
  { id: "bio_F_009", topic: "biologia", letter: "F", question: "Con la F: Estructura que puede producir gametos o hormonas (p. ej., ovárico).", answer: "Folículo" },
  { id: "bio_F_010", topic: "biologia", letter: "F", question: "Con la F: Conjunto de plantas de una región.", answer: "Flora" },
  { id: "bio_F_011", topic: "biologia", letter: "F", question: "Con la F: Conducto que comunica boca y cavidad nasal con laringe y esófago.", answer: "Faringe" },
  { id: "bio_F_012", topic: "biologia", letter: "F", question: "Con la F: Proceso por el que restos se preservan como fósiles.", answer: "Fosilización" },
  { id: "bio_F_013", topic: "biologia", letter: "F", question: "Con la F: Rama que estudia cómo funcionan los organismos.", answer: "Fisiología" },
  { id: "bio_F_014", topic: "biologia", letter: "F", question: "Con la F: Proceso renal por el que el plasma pasa a la nefrona.", answer: "Filtración" },
  { id: "bio_F_015", topic: "biologia", letter: "F", question: "Con la F: Conversión de nitrógeno atmosférico en formas utilizables por seres vivos.", answer: "Fijación" },
  { id: "bio_G_001", topic: "biologia", letter: "G", question: "Con la G: Segmento de ADN que contiene información para un rasgo o proteína.", answer: "Gen" },
  { id: "bio_G_002", topic: "biologia", letter: "G", question: "Con la G: Conjunto de alelos de un individuo.", answer: "Genotipo" },
  { id: "bio_G_003", topic: "biologia", letter: "G", question: "Con la G: Azúcar simple usado como principal fuente de energía.", answer: "Glucosa" },
  { id: "bio_G_004", topic: "biologia", letter: "G", question: "Con la G: Célula sexual haploide (óvulo o espermatozoide).", answer: "Gameto" },
  { id: "bio_G_005", topic: "biologia", letter: "G", question: "Con la G: Inicio del crecimiento de una semilla.", answer: "Germinación" },
  { id: "bio_G_006", topic: "biologia", letter: "G", question: "Con la G: Forma de almacenamiento de glucosa en animales.", answer: "Glicógeno" },
  { id: "bio_G_007", topic: "biologia", letter: "G", question: "Con la G: Ruta metabólica que degrada glucosa para obtener energía.", answer: "Glicólisis" },
  { id: "bio_G_008", topic: "biologia", letter: "G", question: "Con la G: Órgano que produce gametos (ovarios o testículos).", answer: "Gónada" },
  { id: "bio_G_009", topic: "biologia", letter: "G", question: "Con la G: Etapa embrionaria donde se forman capas germinales.", answer: "Gastrulación" },
  { id: "bio_G_010", topic: "biologia", letter: "G", question: "Con la G: Neurotransmisor excitador muy común en el sistema nervioso.", answer: "Glutamato" },
  { id: "bio_G_011", topic: "biologia", letter: "G", question: "Con la G: Tipo de glóbulo blanco con gránulos citoplasmáticos.", answer: "Granulocito" },
  { id: "bio_G_012", topic: "biologia", letter: "G", question: "Con la G: Base nitrogenada presente en ADN y ARN.", answer: "Guanina" },
  { id: "bio_G_013", topic: "biologia", letter: "G", question: "Con la G: Órgano que secreta sustancias, como hormonas.", answer: "Glándula" },
  { id: "bio_G_014", topic: "biologia", letter: "G", question: "Con la G: Órgano que produce y libera sustancias como hormonas o enzimas.", answer: "Glándula" },
  { id: "bio_G_015", topic: "biologia", letter: "G", question: "Con la G: Músculo principal de la pantorrilla.", answer: "Gastrocnemio" },
  { id: "bio_H_001", topic: "biologia", letter: "H", question: "Con la H: Mantenimiento de condiciones internas estables del cuerpo.", answer: "Homeostasis" },
  { id: "bio_H_002", topic: "biologia", letter: "H", question: "Con la H: Mensajero químico que regula funciones en el organismo.", answer: "Hormona" },
  { id: "bio_H_003", topic: "biologia", letter: "H", question: "Con la H: Transmisión de rasgos de padres a descendencia.", answer: "Herencia" },
  { id: "bio_H_004", topic: "biologia", letter: "H", question: "Con la H: Órgano clave en metabolismo, detoxificación y producción de bilis.", answer: "Hígado" },
  { id: "bio_H_005", topic: "biologia", letter: "H", question: "Con la H: Hueso del brazo entre hombro y codo.", answer: "Húmero" },
  { id: "bio_H_006", topic: "biologia", letter: "H", question: "Con la H: Con un solo juego de cromosomas (n).", answer: "Haploide" },
  { id: "bio_H_007", topic: "biologia", letter: "H", question: "Con la H: Proteína que transporta oxígeno en los glóbulos rojos.", answer: "Hemoglobina" },
  { id: "bio_H_008", topic: "biologia", letter: "H", question: "Con la H: Cruce entre individuos con genotipos distintos.", answer: "Hibridación" },
  { id: "bio_H_009", topic: "biologia", letter: "H", question: "Con la H: Glándula que regula muchas otras glándulas del cuerpo.", answer: "Hipófisis" },
  { id: "bio_H_010", topic: "biologia", letter: "H", question: "Con la H: Región cerebral que regula hambre, sed y control hormonal.", answer: "Hipotálamo" },
  { id: "bio_H_011", topic: "biologia", letter: "H", question: "Con la H: Sinónimo de eritrocito o glóbulo rojo.", answer: "Hematíe" },
  { id: "bio_H_012", topic: "biologia", letter: "H", question: "Con la H: Molécula implicada en alergias e inflamación.", answer: "Histamina" },
  { id: "bio_H_013", topic: "biologia", letter: "H", question: "Con la H: Acumulación de sangre fuera de un vaso sanguíneo por lesión.", answer: "Hematoma" },
  { id: "bio_H_014", topic: "biologia", letter: "H", question: "Con la H: Enzima que rompe moléculas usando agua.", answer: "Hidrolasa" },
  { id: "bio_H_015", topic: "biologia", letter: "H", question: "Con la H: Prácticas para prevenir enfermedades y contagios.", answer: "Higiene" },
  { id: "bio_I_001", topic: "biologia", letter: "I", question: "Con la I: Capacidad del organismo para defenderse de patógenos.", answer: "Inmunidad" },
  { id: "bio_I_002", topic: "biologia", letter: "I", question: "Con la I: Hormona que regula la glucosa en sangre.", answer: "Insulina" },
  { id: "bio_I_003", topic: "biologia", letter: "I", question: "Con la I: Periodo del ciclo celular donde la célula crece y replica ADN.", answer: "Interfase" },
  { id: "bio_I_004", topic: "biologia", letter: "I", question: "Con la I: Animal sin columna vertebral.", answer: "Invertebrado" },
  { id: "bio_I_005", topic: "biologia", letter: "I", question: "Con la I: Órgano donde se absorben nutrientes y agua.", answer: "Intestino" },
  { id: "bio_I_006", topic: "biologia", letter: "I", question: "Con la I: Sustancia que reduce la actividad de una enzima.", answer: "Inhibidor" },
  { id: "bio_I_007", topic: "biologia", letter: "I", question: "Con la I: Respuesta del cuerpo ante daño o infección.", answer: "Inflamación" },
  { id: "bio_I_008", topic: "biologia", letter: "I", question: "Con la I: Invasión y multiplicación de microorganismos en el cuerpo.", answer: "Infección" },
  { id: "bio_I_009", topic: "biologia", letter: "I", question: "Con la I: Solución con igual concentración de solutos que el interior celular.", answer: "Isotónico" },
  { id: "bio_I_010", topic: "biologia", letter: "I", question: "Con la I: Parte coloreada del ojo que regula la entrada de luz.", answer: "Iris" },
  { id: "bio_I_011", topic: "biologia", letter: "I", question: "Con la I: Última porción del intestino delgado.", answer: "Íleon" },
  { id: "bio_I_012", topic: "biologia", letter: "I", question: "Con la I: Disminución del riego sanguíneo a un tejido por falta de flujo.", answer: "Isquemia" },
  { id: "bio_I_013", topic: "biologia", letter: "I", question: "Con la I: Entrada de alimentos al cuerpo.", answer: "Ingestión" },
  { id: "bio_I_014", topic: "biologia", letter: "I", question: "Con la I: Señal eléctrica transmitida por neuronas.", answer: "Impulso" },
  { id: "bio_I_015", topic: "biologia", letter: "I", question: "Con la I: Introducción de un agente (p. ej., vacuna) para generar respuesta.", answer: "Inoculación" },
  { id: "bio_J_001", topic: "biologia", letter: "J", question: "Con la J: Felino americano, depredador tope en varios ecosistemas.", answer: "Jaguar" },
  { id: "bio_J_002", topic: "biologia", letter: "J", question: "Con la J: Mamífero salvaje emparentado con el cerdo.", answer: "Jabalí" },
  { id: "bio_J_003", topic: "biologia", letter: "J", question: "Con la J: Mamífero africano de cuello largo, herbívoro.", answer: "Jirafa" },
  { id: "bio_J_004", topic: "biologia", letter: "J", question: "Con la J: Instrumento usado para inyectar o extraer fluidos en biología/medicina básica.", answer: "Jeringa" },
  { id: "bio_J_005", topic: "biologia", letter: "J", question: "Con la J: Planta cuyo rizoma se usa como especia y tiene compuestos bioactivos.", answer: "Jengibre" },
  { id: "bio_J_006", topic: "biologia", letter: "J", question: "Con la J: Árbol ornamental con floración vistosa.", answer: "Jacarandá" },
  { id: "bio_J_007", topic: "biologia", letter: "J", question: "Con la J: Planta aromática con flores fragantes.", answer: "Jazmín" },
  { id: "bio_J_008", topic: "biologia", letter: "J", question: "Con la J: Planta de zonas húmedas con tallos largos.", answer: "Junco" },
  { id: "bio_J_009", topic: "biologia", letter: "J", question: "Con la J: Nombre común de varios cangrejos.", answer: "Jaiba" },
  { id: "bio_J_010", topic: "biologia", letter: "J", question: "Con la J: Raíz comestible de una planta (jícama).", answer: "Jicama" },
  { id: "bio_J_011", topic: "biologia", letter: "J", question: "Con la J: Variedad de chile (Capsicum) usada como alimento.", answer: "Jalapeño" },
  { id: "bio_J_012", topic: "biologia", letter: "J", question: "Con la J: Planta cuyas semillas producen una cera/aceite vegetal.", answer: "Jojoba" },
  { id: "bio_J_013", topic: "biologia", letter: "J", question: "Con la J: Ecosistema de selva densa con alta biodiversidad.", answer: "Jungla" },
  { id: "bio_J_014", topic: "biologia", letter: "J", question: "Con la J: Ave pequeña conocida por su canto.", answer: "Jilguero" },
  { id: "bio_J_015", topic: "biologia", letter: "J", question: "Con la J: No utilizable", answer: "Jirón" },
  { id: "bio_L_001", topic: "biologia", letter: "L", question: "Con la L: Molécula orgánica como grasas y aceites, importante en energía y membranas.", answer: "Lípido" },
  { id: "bio_L_002", topic: "biologia", letter: "L", question: "Con la L: Orgánulo que degrada desechos dentro de la célula.", answer: "Lisosoma" },
  { id: "bio_L_003", topic: "biologia", letter: "L", question: "Con la L: Banda de tejido que une huesos en una articulación.", answer: "Ligamento" },
  { id: "bio_L_004", topic: "biologia", letter: "L", question: "Con la L: Azúcar presente en la leche.", answer: "Lactosa" },
  { id: "bio_L_005", topic: "biologia", letter: "L", question: "Con la L: Etapa juvenil de muchos animales antes del adulto.", answer: "Larva" },
  { id: "bio_L_006", topic: "biologia", letter: "L", question: "Con la L: Órgano relacionado con la voz y la vía respiratoria.", answer: "Laringe" },
  { id: "bio_L_007", topic: "biologia", letter: "L", question: "Con la L: Glóbulo blanco del sistema inmunitario.", answer: "Leucocito" },
  { id: "bio_L_008", topic: "biologia", letter: "L", question: "Con la L: Líquido del sistema linfático.", answer: "Linfa" },
  { id: "bio_L_009", topic: "biologia", letter: "L", question: "Con la L: Línea de descendencia de células u organismos.", answer: "Linaje" },
  { id: "bio_L_010", topic: "biologia", letter: "L", question: "Con la L: División o parte de un órgano, como el cerebro o pulmón.", answer: "Lóbulo" },
  { id: "bio_L_011", topic: "biologia", letter: "L", question: "Con la L: Animal invertebrado del suelo que favorece la aireación.", answer: "Lombriz" },
  { id: "bio_L_012", topic: "biologia", letter: "L", question: "Con la L: Espacio interior de un órgano tubular o de un orgánulo.", answer: "Lumen" },
  { id: "bio_L_013", topic: "biologia", letter: "L", question: "Con la L: Bacteria usada en fermentaciones lácticas.", answer: "Lactobacilo" },
  { id: "bio_L_014", topic: "biologia", letter: "L", question: "Con la L: Producción de leche para alimentar a crías.", answer: "Lactancia" },
  { id: "bio_L_015", topic: "biologia", letter: "L", question: "Con la L: Producto de la fermentación láctica en músculos y bacterias.", answer: "Lactato" },
  { id: "bio_M_001", topic: "biologia", letter: "M", question: "Con la M: Orgánulo que produce ATP en respiración celular.", answer: "Mitocondria" },
  { id: "bio_M_002", topic: "biologia", letter: "M", question: "Con la M: División celular que produce dos células hijas idénticas.", answer: "Mitosis" },
  { id: "bio_M_003", topic: "biologia", letter: "M", question: "Con la M: División celular que forma gametos y reduce cromosomas a la mitad.", answer: "Meiosis" },
  { id: "bio_M_004", topic: "biologia", letter: "M", question: "Con la M: Conjunto de microorganismos que viven en un organismo.", answer: "Microbiota" },
  { id: "bio_M_005", topic: "biologia", letter: "M", question: "Con la M: Cambio en el ADN que puede alterar un rasgo.", answer: "Mutación" },
  { id: "bio_M_006", topic: "biologia", letter: "M", question: "Con la M: Barrera selectiva que rodea células u orgánulos.", answer: "Membrana" },
  { id: "bio_M_007", topic: "biologia", letter: "M", question: "Con la M: Conjunto de reacciones químicas del organismo.", answer: "Metabolismo" },
  { id: "bio_M_008", topic: "biologia", letter: "M", question: "Con la M: Proteína muscular que almacena oxígeno.", answer: "Mioglobina" },
  { id: "bio_M_009", topic: "biologia", letter: "M", question: "Con la M: Tejido que permite movimiento mediante contracción.", answer: "Músculo" },
  { id: "bio_M_010", topic: "biologia", letter: "M", question: "Con la M: Tejido que recubre cavidades internas y produce moco.", answer: "Mucosa" },
  { id: "bio_M_011", topic: "biologia", letter: "M", question: "Con la M: Parte interna de ciertos órganos; p. ej., médula espinal.", answer: "Médula" },
  { id: "bio_M_012", topic: "biologia", letter: "M", question: "Con la M: Capa aislante de neuronas que acelera impulsos.", answer: "Mielina" },
  { id: "bio_M_013", topic: "biologia", letter: "M", question: "Con la M: Estructura del citoesqueleto importante en transporte y división.", answer: "Microtúbulo" },
  { id: "bio_M_014", topic: "biologia", letter: "M", question: "Con la M: Célula inmune que libera histamina en alergias.", answer: "Mastocito" },
  { id: "bio_M_015", topic: "biologia", letter: "M", question: "Con la M: Unidad que se repite para formar polímeros.", answer: "Monómero" },
  { id: "bio_N_001", topic: "biologia", letter: "N", question: "Con la N: Célula del sistema nervioso que transmite señales.", answer: "Neurona" },
  { id: "bio_N_002", topic: "biologia", letter: "N", question: "Con la N: Orgánulo que contiene ADN en células eucariotas.", answer: "Núcleo" },
  { id: "bio_N_003", topic: "biologia", letter: "N", question: "Con la N: Unidad funcional del riñón que filtra la sangre.", answer: "Nefrona" },
  { id: "bio_N_004", topic: "biologia", letter: "N", question: "Con la N: Elemento esencial en proteínas y ácidos nucleicos.", answer: "Nitrógeno" },
  { id: "bio_N_005", topic: "biologia", letter: "N", question: "Con la N: Papel ecológico de una especie en su ambiente.", answer: "Nicho" },
  { id: "bio_N_006", topic: "biologia", letter: "N", question: "Con la N: Unidad básica de ADN/ARN (azúcar+base+fosfato).", answer: "Nucleótido" },
  { id: "bio_N_007", topic: "biologia", letter: "N", question: "Con la N: Gusano cilíndrico, muchos son parásitos.", answer: "Nematodo" },
  { id: "bio_N_008", topic: "biologia", letter: "N", question: "Con la N: Sustancia necesaria para crecimiento y energía.", answer: "Nutriente" },
  { id: "bio_N_009", topic: "biologia", letter: "N", question: "Con la N: Recién nacido en sus primeras semanas de vida.", answer: "Neonato" },
  { id: "bio_N_010", topic: "biologia", letter: "N", question: "Con la N: Organismo que se alimenta de materia orgánica en descomposición.", answer: "Necrófago" },
  { id: "bio_N_011", topic: "biologia", letter: "N", question: "Con la N: Sustancia química que comunica neuronas.", answer: "Neurotransmisor" },
  { id: "bio_N_012", topic: "biologia", letter: "N", question: "Con la N: Conjunto de axones que transmiten información.", answer: "Nervio" },
  { id: "bio_N_013", topic: "biologia", letter: "N", question: "Con la N: Pequeña masa o estructura; p. ej., nódulo linfático.", answer: "Nódulo" },
  { id: "bio_N_014", topic: "biologia", letter: "N", question: "Con la N: Prolongación temprana de una neurona en desarrollo (axón/dendrita).", answer: "Neurita" },
  { id: "bio_N_015", topic: "biologia", letter: "N", question: "Con la N: Estructura nuclear donde se forman ribosomas.", answer: "Nucleolo" },
  { id: "bio_Ñ_001", topic: "biologia", letter: "Ñ", question: "Con la Ñ: Ave corredora sudamericana parecida al avestruz.", answer: "Ñandú" },
  { id: "bio_Ñ_002", topic: "biologia", letter: "Ñ", question: "Con la Ñ: Antílope africano conocido por migraciones masivas.", answer: "Ñu" },
  { id: "bio_Ñ_003", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Órgano que filtra la sangre y produce orina.", answer: "Riñón" },
  { id: "bio_Ñ_004", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Artrópodo de ocho patas, generalmente depredador.", answer: "Araña" },
  { id: "bio_Ñ_005", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Infrutescencia comestible de una planta tropical.", answer: "Piña" },
  { id: "bio_Ñ_006", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Planta como la caña de azúcar, fuente de sacarosa.", answer: "Caña" },
  { id: "bio_Ñ_007", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Estructura de queratina que protege las puntas de los dedos.", answer: "Uña" },
  { id: "bio_Ñ_008", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Estado fisiológico esencial para memoria y reparación.", answer: "Sueño" },
  { id: "bio_Ñ_009", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Articulación entre antebrazo y mano.", answer: "Muñeca" },
  { id: "bio_Ñ_010", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Pelo protector del borde del párpado.", answer: "Pestaña" },
  { id: "bio_Ñ_011", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Conjunto de vísceras u órganos internos.", answer: "Entraña" },
  { id: "bio_Ñ_012", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Semilla/fruto comestible de algunos árboles.", answer: "Castaña" },
  { id: "bio_Ñ_013", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Ave zancuda asociada a humedales y migración.", answer: "Cigüeña" },
  { id: "bio_Ñ_014", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Mensaje en comunicación celular, como en rutas de señalización.", answer: "Señal" },
  { id: "bio_Ñ_015", topic: "biologia", letter: "Ñ", question: "Contiene la Ñ: Característica fenotípica que puede depender de genes y ambiente.", answer: "Tamaño" },
  { id: "bio_O_001", topic: "biologia", letter: "O", question: "Con la O: Paso de agua a través de una membrana semipermeable.", answer: "Osmosis" },
  { id: "bio_O_002", topic: "biologia", letter: "O", question: "Con la O: Estructura celular con función específica (orgánulo).", answer: "Organelo" },
  { id: "bio_O_003", topic: "biologia", letter: "O", question: "Con la O: Conjunto de tejidos que realiza una función en el cuerpo.", answer: "Órgano" },
  { id: "bio_O_004", topic: "biologia", letter: "O", question: "Con la O: Gas esencial para respiración celular aeróbica.", answer: "Oxígeno" },
  { id: "bio_O_005", topic: "biologia", letter: "O", question: "Con la O: Liberación de un óvulo desde el ovario.", answer: "Ovulación" },
  { id: "bio_O_006", topic: "biologia", letter: "O", question: "Con la O: Célula sexual femenina en desarrollo.", answer: "Ovocito" },
  { id: "bio_O_007", topic: "biologia", letter: "O", question: "Con la O: Gen que, si se altera, puede favorecer cáncer.", answer: "Oncogén" },
  { id: "bio_O_008", topic: "biologia", letter: "O", question: "Con la O: Animal que pone huevos.", answer: "Ovíparo" },
  { id: "bio_O_009", topic: "biologia", letter: "O", question: "Con la O: Organismo que come tanto plantas como animales.", answer: "Omnívoro" },
  { id: "bio_O_010", topic: "biologia", letter: "O", question: "Con la O: Célula madura del tejido óseo.", answer: "Osteocito" },
  { id: "bio_O_011", topic: "biologia", letter: "O", question: "Con la O: Inflamación ósea (término general).", answer: "Osteíto" },
  { id: "bio_O_012", topic: "biologia", letter: "O", question: "Con la O: Sentido que detecta sustancias químicas en el aire.", answer: "Olfato" },
  { id: "bio_O_013", topic: "biologia", letter: "O", question: "Con la O: Conjunto de genes regulados juntos en bacterias.", answer: "Operón" },
  { id: "bio_O_014", topic: "biologia", letter: "O", question: "Con la O: Gameto femenino; célula sexual femenina.", answer: "Ovulo" },
  { id: "bio_O_015", topic: "biologia", letter: "O", question: "Con la O: Órgano reproductor femenino que produce óvulos y hormonas.", answer: "Ovario" },
  { id: "bio_P_001", topic: "biologia", letter: "P", question: "Con la P: Macromolécula formada por aminoácidos con múltiples funciones.", answer: "Proteína" },
  { id: "bio_P_002", topic: "biologia", letter: "P", question: "Con la P: Cadena corta de aminoácidos.", answer: "Péptido" },
  { id: "bio_P_003", topic: "biologia", letter: "P", question: "Con la P: Molécula circular de ADN frecuente en bacterias.", answer: "Plásmido" },
  { id: "bio_P_004", topic: "biologia", letter: "P", question: "Con la P: Órgano responsable del intercambio gaseoso.", answer: "Pulmón" },
  { id: "bio_P_005", topic: "biologia", letter: "P", question: "Con la P: Órgano que produce enzimas digestivas e insulina.", answer: "Páncreas" },
  { id: "bio_P_006", topic: "biologia", letter: "P", question: "Con la P: Organismo que vive a costa de otro.", answer: "Parásito" },
  { id: "bio_P_007", topic: "biologia", letter: "P", question: "Con la P: Estructura que transporta gametos masculinos en plantas.", answer: "Polen" },
  { id: "bio_P_008", topic: "biologia", letter: "P", question: "Con la P: Conjunto de individuos de la misma especie en un área.", answer: "Población" },
  { id: "bio_P_009", topic: "biologia", letter: "P", question: "Con la P: Organismo sin núcleo verdadero (procariota).", answer: "Procarionte" },
  { id: "bio_P_010", topic: "biologia", letter: "P", question: "Con la P: Organismo eucariota generalmente unicelular (p. ej., ameba).", answer: "Protista" },
  { id: "bio_P_011", topic: "biologia", letter: "P", question: "Con la P: Sustancia que da color y puede absorber luz (p. ej., clorofila).", answer: "Pigmento" },
  { id: "bio_P_012", topic: "biologia", letter: "P", question: "Con la P: Fragmento celular que ayuda a coagular la sangre.", answer: "Plaqueta" },
  { id: "bio_P_013", topic: "biologia", letter: "P", question: "Con la P: Interacción ecológica donde un organismo captura y consume a otro.", answer: "Predación" },
  { id: "bio_P_014", topic: "biologia", letter: "P", question: "Con la P: Órgano temporal que conecta madre y feto en mamíferos.", answer: "Placenta" },
  { id: "bio_P_015", topic: "biologia", letter: "P", question: "Con la P: Aumento del número de células por división.", answer: "Proliferación" },
  { id: "bio_Q_001", topic: "biologia", letter: "Q", question: "Con la Q: Proteína estructural de uñas, pelo y piel.", answer: "Queratina" },
  { id: "bio_Q_002", topic: "biologia", letter: "Q", question: "Con la Q: Producción de materia orgánica usando energía química, no luz.", answer: "Quimiosíntesis" },
  { id: "bio_Q_003", topic: "biologia", letter: "Q", question: "Con la Q: Movimiento de células guiado por señales químicas.", answer: "Quimiotaxis" },
  { id: "bio_Q_004", topic: "biologia", letter: "Q", question: "Con la Q: Partícula que transporta grasas en la sangre tras la digestión.", answer: "Quilomicrón" },
  { id: "bio_Q_005", topic: "biologia", letter: "Q", question: "Con la Q: Saco cerrado con líquido o material semisólido en un tejido.", answer: "Quiste" },
  { id: "bio_Q_006", topic: "biologia", letter: "Q", question: "Con la Q: Enzima que añade grupos fosfato a otras moléculas.", answer: "Quinasa" },
  { id: "bio_Q_007", topic: "biologia", letter: "Q", question: "Con la Q: Organismo con células de dos orígenes genéticos distintos.", answer: "Quimera" },
  { id: "bio_Q_008", topic: "biologia", letter: "Q", question: "Con la Q: Estado de baja actividad celular, reversible.", answer: "Quiescencia" },
  { id: "bio_Q_009", topic: "biologia", letter: "Q", question: "Con la Q: Compuesto vegetal (flavonoide) con propiedades antioxidantes.", answer: "Quercetina" },
  { id: "bio_Q_010", topic: "biologia", letter: "Q", question: "Con la Q: Alcaloide usado contra la malaria, derivado de plantas.", answer: "Quinina" },
  { id: "bio_Q_011", topic: "biologia", letter: "Q", question: "Con la Q: Unión de un ion metálico por una molécula, relevante en toxicología.", answer: "Quelación" },
  { id: "bio_Q_012", topic: "biologia", letter: "Q", question: "Con la Q: Mecanismo de comunicación bacteriana dependiente de densidad (quorum sensing).", answer: "Quorum" },
  { id: "bio_Q_013", topic: "biologia", letter: "Q", question: "Con la Q: Molécula orgánica implicada en transporte de electrones.", answer: "Quinona" },
  { id: "bio_Q_014", topic: "biologia", letter: "Q", question: "Con la Q: Relacionado con quistes; como en enfermedades quísticas (término general).", answer: "Quística" },
  { id: "bio_Q_015", topic: "biologia", letter: "Q", question: "Con la Q: Receptor sensorial que detecta sustancias químicas (gusto/olfato).", answer: "Quimiorreceptor" },
  { id: "bio_R_001", topic: "biologia", letter: "R", question: "Con la R: Complejo celular que fabrica proteínas.", answer: "Ribosoma" },
  { id: "bio_R_002", topic: "biologia", letter: "R", question: "Con la R: Proceso de obtención de energía a partir de nutrientes.", answer: "Respiración" },
  { id: "bio_R_003", topic: "biologia", letter: "R", question: "Con la R: Proteína que recibe señales químicas y activa respuestas celulares.", answer: "Receptor" },
  { id: "bio_R_004", topic: "biologia", letter: "R", question: "Con la R: Ácido ribonucleico, molécula clave en síntesis de proteínas.", answer: "ARN" },
  { id: "bio_R_005", topic: "biologia", letter: "R", question: "Con la R: Azúcar presente en el ARN.", answer: "Ribosa" },
  { id: "bio_R_006", topic: "biologia", letter: "R", question: "Con la R: Respuesta rápida e involuntaria ante un estímulo.", answer: "Reflejo" },
  { id: "bio_R_007", topic: "biologia", letter: "R", question: "Con la R: Proceso por el que los seres vivos generan descendencia.", answer: "Reproducción" },
  { id: "bio_R_008", topic: "biologia", letter: "R", question: "Con la R: Característica observable de un organismo.", answer: "Rasgo" },
  { id: "bio_R_009", topic: "biologia", letter: "R", question: "Con la R: Alelo que se expresa solo si está en doble copia.", answer: "Recesivo" },
  { id: "bio_R_010", topic: "biologia", letter: "R", question: "Con la R: Cámara del estómago de rumiantes donde fermenta la celulosa.", answer: "Rumen" },
  { id: "bio_R_011", topic: "biologia", letter: "R", question: "Con la R: Capa del ojo que detecta luz y la convierte en señales nerviosas.", answer: "Retina" },
  { id: "bio_R_012", topic: "biologia", letter: "R", question: "Con la R: Copia de material genético durante división celular (término general).", answer: "Réplica" },
  { id: "bio_R_013", topic: "biologia", letter: "R", question: "Con la R: Intercambio de material genético durante meiosis, genera variabilidad.", answer: "Recombinación" },
  { id: "bio_R_014", topic: "biologia", letter: "R", question: "Con la R: Primera raíz que emerge al germinar una semilla.", answer: "Radícula" },
  { id: "bio_R_015", topic: "biologia", letter: "R", question: "Con la R: Género de bacterias intracelulares que causan ciertas fiebres.", answer: "Rickettsia" },
  { id: "bio_S_001", topic: "biologia", letter: "S", question: "Con la S: Unión funcional donde se comunican neuronas.", answer: "Sinapsis" },
  { id: "bio_S_002", topic: "biologia", letter: "S", question: "Con la S: Conjunto de órganos que trabajan coordinados.", answer: "Sistema" },
  { id: "bio_S_003", topic: "biologia", letter: "S", question: "Con la S: Tejido líquido que transporta gases y nutrientes.", answer: "Sangre" },
  { id: "bio_S_004", topic: "biologia", letter: "S", question: "Con la S: Relación estrecha entre especies diferentes.", answer: "Simbiosis" },
  { id: "bio_S_005", topic: "biologia", letter: "S", question: "Con la S: Mecanismo evolutivo por el que algunos rasgos se favorecen.", answer: "Selección" },
  { id: "bio_S_006", topic: "biologia", letter: "S", question: "Con la S: Molécula sobre la que actúa una enzima.", answer: "Sustrato" },
  { id: "bio_S_007", topic: "biologia", letter: "S", question: "Con la S: Cambio gradual de comunidades en un ecosistema.", answer: "Sucesión" },
  { id: "bio_S_008", topic: "biologia", letter: "S", question: "Con la S: Organismo que se alimenta de materia orgánica muerta.", answer: "Saprófito" },
  { id: "bio_S_009", topic: "biologia", letter: "S", question: "Con la S: Unidad contráctil del músculo estriado.", answer: "Sarcómero" },
  { id: "bio_S_010", topic: "biologia", letter: "S", question: "Con la S: Relacionado con células del cuerpo no reproductivas.", answer: "Somático" },
  { id: "bio_S_011", topic: "biologia", letter: "S", question: "Con la S: Fase en la que el corazón se contrae y bombea sangre.", answer: "Sístole" },
  { id: "bio_S_012", topic: "biologia", letter: "S", question: "Con la S: Líquido que ayuda a regular la temperatura corporal.", answer: "Sudor" },
  { id: "bio_S_013", topic: "biologia", letter: "S", question: "Con la S: Formación de moléculas complejas a partir de simples.", answer: "Síntesis" },
  { id: "bio_S_014", topic: "biologia", letter: "S", question: "Con la S: Líquido que contiene espermatozoides.", answer: "Semen" },
  { id: "bio_S_015", topic: "biologia", letter: "S", question: "Con la S: Estructura resistente para dispersión y supervivencia en hongos/plantas.", answer: "Espora" },
  { id: "bio_T_001", topic: "biologia", letter: "T", question: "Con la T: Conjunto de células similares con una función común.", answer: "Tejido" },
  { id: "bio_T_002", topic: "biologia", letter: "T", question: "Con la T: Tubo que conduce aire hacia los bronquios.", answer: "Tráquea" },
  { id: "bio_T_003", topic: "biologia", letter: "T", question: "Con la T: Movimiento de sustancias dentro del organismo o a través de membranas.", answer: "Transporte" },
  { id: "bio_T_004", topic: "biologia", letter: "T", question: "Con la T: Órgano donde maduran linfocitos T.", answer: "Timo" },
  { id: "bio_T_005", topic: "biologia", letter: "T", question: "Con la T: Sustancia que puede dañar a un organismo.", answer: "Tóxico" },
  { id: "bio_T_006", topic: "biologia", letter: "T", question: "Con la T: Ciencia que clasifica a los seres vivos.", answer: "Taxonomía" },
  { id: "bio_T_007", topic: "biologia", letter: "T", question: "Con la T: Estado de presión interna en células vegetales por agua.", answer: "Turgencia" },
  { id: "bio_T_008", topic: "biologia", letter: "T", question: "Con la T: Mantenimiento de la temperatura corporal.", answer: "Termorregulación" },
  { id: "bio_T_009", topic: "biologia", letter: "T", question: "Con la T: Enzima clave en la coagulación.", answer: "Trombina" },
  { id: "bio_T_010", topic: "biologia", letter: "T", question: "Con la T: Proceso por el que ribosomas producen proteínas desde ARN.", answer: "Traducción" },
  { id: "bio_T_011", topic: "biologia", letter: "T", question: "Con la T: Síntesis de ARN a partir de ADN.", answer: "Transcripción" },
  { id: "bio_T_012", topic: "biologia", letter: "T", question: "Con la T: Crecimiento dirigido en plantas ante estímulos.", answer: "Tropismo" },
  { id: "bio_T_013", topic: "biologia", letter: "T", question: "Con la T: Organismo con cuatro juegos de cromosomas.", answer: "Tetraploide" },
  { id: "bio_T_014", topic: "biologia", letter: "T", question: "Con la T: Tejido que une músculo con hueso.", answer: "Tendón" },
  { id: "bio_T_015", topic: "biologia", letter: "T", question: "Con la T: Sustancia producida por un organismo que causa daño.", answer: "Toxina" },
  { id: "bio_U_001", topic: "biologia", letter: "U", question: "Con la U: Base nitrogenada del ARN que reemplaza a la timina.", answer: "Uracilo" },
  { id: "bio_U_002", topic: "biologia", letter: "U", question: "Con la U: Desecho nitrogenado excretado en la orina.", answer: "Urea" },
  { id: "bio_U_003", topic: "biologia", letter: "U", question: "Con la U: Órgano donde se desarrolla el embrión/feto en mamíferos.", answer: "Útero" },
  { id: "bio_U_004", topic: "biologia", letter: "U", question: "Con la U: Relacionado con el cordón que conecta al feto con la placenta.", answer: "Umbilical" },
  { id: "bio_U_005", topic: "biologia", letter: "U", question: "Con la U: Formado por una sola célula.", answer: "Unicelular" },
  { id: "bio_U_006", topic: "biologia", letter: "U", question: "Con la U: Proteína que marca otras proteínas para su degradación.", answer: "Ubiquitina" },
  { id: "bio_U_007", topic: "biologia", letter: "U", question: "Con la U: Proceso renal donde el plasma se filtra en el glomérulo.", answer: "Ultrafiltración" },
  { id: "bio_U_008", topic: "biologia", letter: "U", question: "Con la U: Parte del oído interno que detecta aceleraciones lineales.", answer: "Utrículo" },
  { id: "bio_U_009", topic: "biologia", letter: "U", question: "Con la U: Grupo de anfibios como salamandras (urodelos).", answer: "Urodelos" },
  { id: "bio_U_010", topic: "biologia", letter: "U", question: "Con la U: Reacción cutánea con ronchas por liberación de histamina.", answer: "Urticaria" },
  { id: "bio_U_011", topic: "biologia", letter: "U", question: "Con la U: Capa del ojo que incluye iris y coroides.", answer: "Uvea" },
  { id: "bio_U_012", topic: "biologia", letter: "U", question: "Con la U: Planta que provoca irritación por sus pelos urticantes.", answer: "Urtiga" },
  { id: "bio_U_013", topic: "biologia", letter: "U", question: "Con la U: Presencia amplia de un organismo en muchos ambientes.", answer: "Ubiquidad" },
  { id: "bio_U_014", topic: "biologia", letter: "U", question: "Con la U: Conducto que lleva orina del riñón a la vejiga.", answer: "Ureter" },
  { id: "bio_U_015", topic: "biologia", letter: "U", question: "Con la U: Enzima que degrada urea (p. ej., en bacterias).", answer: "Uréasa" },
  { id: "bio_V_001", topic: "biologia", letter: "V", question: "Con la V: Agente infeccioso que necesita células para replicarse.", answer: "Virus" },
  { id: "bio_V_002", topic: "biologia", letter: "V", question: "Con la V: Estructura celular (común en plantas) que almacena sustancias.", answer: "Vacuola" },
  { id: "bio_V_003", topic: "biologia", letter: "V", question: "Con la V: Vaso sanguíneo que devuelve sangre al corazón.", answer: "Vena" },
  { id: "bio_V_004", topic: "biologia", letter: "V", question: "Con la V: Estructura que evita el retroceso de la sangre en el corazón.", answer: "Válvula" },
  { id: "bio_V_005", topic: "biologia", letter: "V", question: "Con la V: Animal con columna vertebral.", answer: "Vertebrado" },
  { id: "bio_V_006", topic: "biologia", letter: "V", question: "Con la V: Compuesto esencial en pequeñas cantidades para funciones del cuerpo.", answer: "Vitamina" },
  { id: "bio_V_007", topic: "biologia", letter: "V", question: "Con la V: Saco pequeño; p. ej., vesícula biliar almacena bilis.", answer: "Vesícula" },
  { id: "bio_V_008", topic: "biologia", letter: "V", question: "Con la V: Proyección del intestino que aumenta la absorción.", answer: "Vellosidad" },
  { id: "bio_V_009", topic: "biologia", letter: "V", question: "Con la V: Organismo que transmite patógenos, como mosquitos.", answer: "Vector" },
  { id: "bio_V_010", topic: "biologia", letter: "V", question: "Con la V: Relacionado con virus o infecciones por virus.", answer: "Viral" },
  { id: "bio_V_011", topic: "biologia", letter: "V", question: "Con la V: Administración de vacuna para generar inmunidad.", answer: "Vacunación" },
  { id: "bio_V_012", topic: "biologia", letter: "V", question: "Con la V: Aparición de rasgos masculinos por cambios hormonales (concepto básico).", answer: "Virilización" },
  { id: "bio_V_013", topic: "biologia", letter: "V", question: "Con la V: Aumento del diámetro de vasos sanguíneos.", answer: "Vasodilatación" },
  { id: "bio_V_014", topic: "biologia", letter: "V", question: "Con la V: Disminución del diámetro de vasos sanguíneos.", answer: "Vasoconstricción" },
  { id: "bio_V_015", topic: "biologia", letter: "V", question: "Con la V: Proteína asociada a adhesión celular (nivel básico).", answer: "Vinculina" },
  { id: "bio_X_001", topic: "biologia", letter: "X", question: "Contiene la X: Tejido vegetal que transporta agua y sales minerales.", answer: "Xilema" },
  { id: "bio_X_002", topic: "biologia", letter: "X", question: "Contiene la X: Organismo que se alimenta de madera.", answer: "Xilófago" },
  { id: "bio_X_003", topic: "biologia", letter: "X", question: "Contiene la X: Planta adaptada a vivir con poca agua.", answer: "Xerófita" },
  { id: "bio_X_004", topic: "biologia", letter: "X", question: "Contiene la X: Pigmento amarillo en plantas, asociado a fotosíntesis.", answer: "Xantofila" },
  { id: "bio_X_005", topic: "biologia", letter: "X", question: "Contiene la X: Sustancia extraña al organismo, como fármacos o contaminantes.", answer: "Xenobiótico" },
  { id: "bio_X_006", topic: "biologia", letter: "X", question: "Contiene la X: Trasplante entre especies diferentes.", answer: "Xenotrasplante" },
  { id: "bio_X_007", topic: "biologia", letter: "X", question: "Contiene la X: Base nitrogenada relacionada con metabolismo de purinas.", answer: "Xantina" },
  { id: "bio_X_008", topic: "biologia", letter: "X", question: "Contiene la X: Depósito de lípidos que puede aparecer en la piel.", answer: "Xantoma" },
  { id: "bio_X_009", topic: "biologia", letter: "X", question: "Contiene la X: Sequedad ocular por déficit de vitamina A.", answer: "Xeroftalmia" },
  { id: "bio_X_010", topic: "biologia", letter: "X", question: "Contiene la X: Azúcar presente en algunos polisacáridos vegetales.", answer: "Xilosa" },
  { id: "bio_X_011", topic: "biologia", letter: "X", question: "Contiene la X: Apéndice del esternón (apófisis xifoides).", answer: "Xifoides" },
  { id: "bio_X_012", topic: "biologia", letter: "X", question: "Contiene la X: Porción inferior del esternón asociada al apéndice xifoides.", answer: "Xifisterno" },
  { id: "bio_X_013", topic: "biologia", letter: "X", question: "Contiene la X: Polinización cruzada entre flores de plantas distintas.", answer: "Xenogamia" },
  { id: "bio_X_014", topic: "biologia", letter: "X", question: "Contiene la X: Origen de material genético procedente de otra especie.", answer: "Xenogénico" },
  { id: "bio_X_015", topic: "biologia", letter: "X", question: "Contiene la X: Gas noble usado en biología/medicina en contextos específicos (p. ej., anestesia).", answer: "Xenón" },
  { id: "bio_Y_001", topic: "biologia", letter: "Y", question: "Contiene la Y: Elemento esencial para hormonas tiroideas.", answer: "Yodo" },
  { id: "bio_Y_002", topic: "biologia", letter: "Y", question: "Contiene la Y: Estructura de reserva en huevos; también yema de brotes en plantas.", answer: "Yema" },
  { id: "bio_Y_003", topic: "biologia", letter: "Y", question: "Contiene la Y: Vena del cuello que drena sangre desde la cabeza.", answer: "Yugular" },
  { id: "bio_Y_004", topic: "biologia", letter: "Y", question: "Contiene la Y: Género bacteriano que incluye especies patógenas.", answer: "Yersinia" },
  { id: "bio_Y_005", topic: "biologia", letter: "Y", question: "Contiene la Y: Forma iónica del yodo, presente en sal yodada.", answer: "Yoduro" },
  { id: "bio_Y_006", topic: "biologia", letter: "Y", question: "Contiene la Y: Proceso de añadir yodo; p. ej., en nutrición o laboratorio.", answer: "Yodación" },
  { id: "bio_Y_007", topic: "biologia", letter: "Y", question: "Contiene la Y: Alimento fermentado por bacterias lácticas.", answer: "Yogur" },
  { id: "bio_Y_008", topic: "biologia", letter: "Y", question: "Contiene la Y: Nombre de caimanes sudamericanos (reptiles).", answer: "Yacaré" },
  { id: "bio_Y_009", topic: "biologia", letter: "Y", question: "Contiene la Y: Planta con raíces comestibles ricas en almidón.", answer: "Yuca" },
  { id: "bio_Y_010", topic: "biologia", letter: "Y", question: "Contiene la Y: Nombre común de hierbas espontáneas o malezas.", answer: "Yuyo" },
  { id: "bio_Y_011", topic: "biologia", letter: "Y", question: "Contiene la Y: Hembra del caballo (mamífero).", answer: "Yegua" },
  { id: "bio_Y_012", topic: "biologia", letter: "Y", question: "Contiene la Y: Planta aromática usada en infusiones (menta).", answer: "Yerbabuena" },
  { id: "bio_Y_013", topic: "biologia", letter: "Y", question: "Contiene la Y: Efecto causado por una intervención médica o tratamiento.", answer: "Yatrogénico" },
  { id: "bio_Y_014", topic: "biologia", letter: "Y", question: "Contiene la Y: Uso terapéutico de yodo radiactivo en medicina.", answer: "Yodoterapia" },
  { id: "bio_Y_015", topic: "biologia", letter: "Y", question: "Contiene la Y: Fibra vegetal obtenida de plantas, usada como material.", answer: "Yute" },
  { id: "bio_Z_001", topic: "biologia", letter: "Z", question: "Con la Z: Raíz comestible rica en carotenoides.", answer: "Zanahoria" },
  { id: "bio_Z_002", topic: "biologia", letter: "Z", question: "Con la Z: Rama de la biología que estudia animales.", answer: "Zoología" },
  { id: "bio_Z_003", topic: "biologia", letter: "Z", question: "Con la Z: Enfermedad que puede transmitirse de animales a humanos.", answer: "Zoonosis" },
  { id: "bio_Z_004", topic: "biologia", letter: "Z", question: "Con la Z: Organismos animales microscópicos que flotan en el agua.", answer: "Zooplancton" },
  { id: "bio_Z_005", topic: "biologia", letter: "Z", question: "Con la Z: Nombre común de mosquitos, vectores de enfermedades.", answer: "Zancudo" },
  { id: "bio_Z_006", topic: "biologia", letter: "Z", question: "Con la Z: Estructura vegetal enrollada que ayuda a trepar.", answer: "Zarcillo" },
  { id: "bio_Z_007", topic: "biologia", letter: "Z", question: "Con la Z: Marsupial americano, conocido también como tlacuache.", answer: "Zarigüeya" },
  { id: "bio_Z_008", topic: "biologia", letter: "Z", question: "Con la Z: Célula resultante de la fecundación.", answer: "Zigoto" },
  { id: "bio_Z_009", topic: "biologia", letter: "Z", question: "Con la Z: Hueso del cráneo asociado al pómulo.", answer: "Zigomático" },
  { id: "bio_Z_010", topic: "biologia", letter: "Z", question: "Con la Z: Pigmento carotenoide presente en plantas y en la retina.", answer: "Zeaxantina" },
  { id: "bio_Z_011", topic: "biologia", letter: "Z", question: "Con la Z: Mineral esencial para enzimas y sistema inmunitario.", answer: "Zinc" },
  { id: "bio_Z_012", topic: "biologia", letter: "Z", question: "Con la Z: Enfermedad causada por reactivación del virus varicela-zóster.", answer: "Zóster" },
  { id: "bio_Z_013", topic: "biologia", letter: "Z", question: "Con la Z: Forma inactiva de una enzima que se activa luego.", answer: "Zimógeno" },
  { id: "bio_Z_014", topic: "biologia", letter: "Z", question: "Con la Z: Planta marina (pastos marinos) que forma praderas submarinas.", answer: "Zostera" },
  { id: "bio_Z_015", topic: "biologia", letter: "Z", question: "Con la Z: Adjetivo relacionado con zoonosis y transmisión animal-humano.", answer: "Zoonótico" },
];
