import type { QA } from "./types";

export const CINE: QA[] = [
  { id: "cine_A_001", topic: "cine", letter: "A", question: "Con la A: Intérprete que representa un personaje en una película.", answer: "Actor" },
  { id: "cine_A_002", topic: "cine", letter: "A", question: "Con la A: Intérprete femenina protagonista o de reparto.", answer: "Actriz" },
  { id: "cine_A_003", topic: "cine", letter: "A", question: "Con la A: Técnica cinematográfica que crea movimiento a partir de imágenes.", answer: "Animación" },
  { id: "cine_A_004", topic: "cine", letter: "A", question: "Con la A: Productora/distribuidora independiente asociada a cine autoral.", answer: "A24" },
  { id: "cine_A_005", topic: "cine", letter: "A", question: "Con la A: Película de ciencia ficción famosa por su uso de 3D.", answer: "Avatar" },
  { id: "cine_A_006", topic: "cine", letter: "A", question: "Con la A: Película francesa conocida por su estilo visual y narración.", answer: "Amélie" },
  { id: "cine_A_007", topic: "cine", letter: "A", question: "Con la A: Director español reconocido internacionalmente.", answer: "Almodóvar" },
  { id: "cine_A_008", topic: "cine", letter: "A", question: "Con la A: En edición, cambio fino de duración o ritmo de un plano.", answer: "Ajuste" },
  { id: "cine_A_009", topic: "cine", letter: "A", question: "Con la A: Prueba de casting para elegir intérpretes.", answer: "Audición" },
  { id: "cine_A_010", topic: "cine", letter: "A", question: "Con la A: Departamento que diseña decorados, utilería y estética de escena.", answer: "Arte" },
  { id: "cine_A_011", topic: "cine", letter: "A", question: "Con la A: En fotografía/cine, control de luz que entra al objetivo.", answer: "Apertura" },
  { id: "cine_A_012", topic: "cine", letter: "A", question: "Con la A: Tipo de personaje recurrente .", answer: "Arquetipo" },
  { id: "cine_A_013", topic: "cine", letter: "A", question: "Con la A: Género centrado en viaje, acción y exploración.", answer: "Aventura" },
  { id: "cine_A_014", topic: "cine", letter: "A", question: "Con la A: Reacción del público al final de una proyección.", answer: "Aplauso" },
  { id: "cine_A_015", topic: "cine", letter: "A", question: "Con la A: Objetos y utilería usados en el set.", answer: "Atrezzo" },
  { id: "cine_B_001", topic: "cine", letter: "B", question: "Con la B: Música de una película; también llamada BSO.", answer: "BandaSonora" },
  { id: "cine_B_002", topic: "cine", letter: "B", question: "Con la B: Director francés asociado al minimalismo y al cine espiritual.", answer: "Bresson" },
  { id: "cine_B_003", topic: "cine", letter: "B", question: "Con la B: Director sueco famoso por dramas existenciales.", answer: "Bergman" },
  { id: "cine_B_004", topic: "cine", letter: "B", question: "Con la B: Industria cinematográfica india conocida por cine musical.", answer: "Bollywood" },
  { id: "cine_B_005", topic: "cine", letter: "B", question: "Con la B: En “blanco y negro”, estética clásica del cine.", answer: "Blanco" },
  { id: "cine_B_006", topic: "cine", letter: "B", question: "Con la B: Película de gran presupuesto y enorme taquilla.", answer: "Blockbuster" },
  { id: "cine_B_007", topic: "cine", letter: "B", question: "Con la B: Asiento típico de una sala de cine.", answer: "Butaca" },
  { id: "cine_B_008", topic: "cine", letter: "B", question: "Con la B: Hechizera con poderes mágicos.", answer: "Bruja" },
  { id: "cine_B_009", topic: "cine", letter: "B", question: "Con la B: Recurso narrativo de repetición temporal en guion.", answer: "Bucle" },
  { id: "cine_B_010", topic: "cine", letter: "B", question: "Con la B: Película biográfica sobre una persona real.", answer: "Biopic" },
  { id: "cine_B_011", topic: "cine", letter: "B", question: "Con la B: Desenfoque estético del fondo en imagen.", answer: "Bokeh" },
  { id: "cine_B_012", topic: "cine", letter: "B", question: "Con la B: Nombre común del Festival de Berlín .", answer: "Berlinale" },
  { id: "cine_B_013", topic: "cine", letter: "B", question: "Con la B: Nombre asociado a Béla Tarr .", answer: "Béla" },
  { id: "cine_B_014", topic: "cine", letter: "B", question: "Con la B: Superhéroe de DC Comics que lucha contra el crimen en Gotham.", answer: "Batman" },
  { id: "cine_B_015", topic: "cine", letter: "B", question: "Con la B: Buster Keaton, figura del cine mudo y comedia física.", answer: "Buster" },
  { id: "cine_C_001", topic: "cine", letter: "C", question: "Con la C: Dispositivo que registra imagen en cine.", answer: "Cámara" },
  { id: "cine_C_002", topic: "cine", letter: "C", question: "Con la C: Película de duración corta, distinta a un largometraje.", answer: "Cortometraje" },
  { id: "cine_C_003", topic: "cine", letter: "C", question: "Con la C: Persona que dirige o crea cine .", answer: "Cineasta" },
  { id: "cine_C_004", topic: "cine", letter: "C", question: "Con la C: Proceso de selección de actores.", answer: "Casting" },
  { id: "cine_C_005", topic: "cine", letter: "C", question: "Con la C: Punto de máxima tensión narrativa en una historia.", answer: "Clímax" },
  { id: "cine_C_006", topic: "cine", letter: "C", question: "Con la C: Lista de nombres y roles al final  de una película.", answer: "Créditos" },
  { id: "cine_C_007", topic: "cine", letter: "C", question: "Con la C: Género que busca provocar risa.", answer: "Comedia" },
  { id: "cine_C_008", topic: "cine", letter: "C", question: "Con la C: Festival de cine famoso por la Palma de Oro.", answer: "Cannes" },
  { id: "cine_C_009", topic: "cine", letter: "C", question: "Con la C: Apellido de los hermanos Coen, directores y guionistas.", answer: "Coen" },
  { id: "cine_C_010", topic: "cine", letter: "C", question: "Con la C: Apellido de Francis Ford Coppola, director.", answer: "Coppola" },
  { id: "cine_C_011", topic: "cine", letter: "C", question: "Con la C: Figura central del cine mudo.", answer: "Chaplin" },
  { id: "cine_C_012", topic: "cine", letter: "C", question: "Con la C: Director mexicano ganador de premios internacionales.", answer: "Cuarón" },
  { id: "cine_C_013", topic: "cine", letter: "C", question: "Con la C: Director canadiense asociado al “body horror”.", answer: "Cronenberg" },
  { id: "cine_C_014", topic: "cine", letter: "C", question: "Con la C: Formato panorámico clásico de pantalla ancha.", answer: "Cinemascope" },
  { id: "cine_C_015", topic: "cine", letter: "C", question: "Con la C: Coherencia visual/narrativa entre planos y escenas.", answer: "Continuidad" },
  { id: "cine_D_001", topic: "cine", letter: "D", question: "Con la D: Responsable creativo principal de una película.", answer: "Director" },
  { id: "cine_D_002", topic: "cine", letter: "D", question: "Con la D: Texto hablado por personajes.", answer: "Diálogo" },
  { id: "cine_D_003", topic: "cine", letter: "D", question: "Con la D: Sustitución de voces originales por otras en otro idioma.", answer: "Doblaje" },
  { id: "cine_D_004", topic: "cine", letter: "D", question: "Con la D: Género que registra o explora hechos reales.", answer: "Documental" },
  { id: "cine_D_005", topic: "cine", letter: "D", question: "Con la D: Género centrado en conflicto emocional y relaciones.", answer: "Drama" },
  { id: "cine_D_006", topic: "cine", letter: "D", question: "Con la D: Película/saga de ciencia ficción basada en una novela.", answer: "Dune" },
  { id: "cine_D_007", topic: "cine", letter: "D", question: "Con la D: Serie de TV sobre un forense que es asesino en serie.", answer: "Dexter" },
  { id: "cine_D_008", topic: "cine", letter: "D", question: "Con la D: Estudio/empresa histórica de animación y cine familiar.", answer: "Disney" },
  { id: "cine_D_009", topic: "cine", letter: "D", question: "Con la D: Carrito para movimientos suaves de cámara.", answer: "Dolly" },
  { id: "cine_D_010", topic: "cine", letter: "D", question: "Con la D: Ficción de sociedades opresivas, común en cine.", answer: "Distopia" },
  { id: "cine_D_011", topic: "cine", letter: "D", question: "Con la D: Apellido de Leonardo DiCaprio, actor de fama mundial.", answer: "Dicaprio" },
  { id: "cine_D_012", topic: "cine", letter: "D", question: "Con la D: Apellido de Robert De Niro, actor icónico.", answer: "DeNiro" },
  { id: "cine_D_013", topic: "cine", letter: "D", question: "Con la D: Movimiento/estética; p. ej., Dogma 95 en cine europeo.", answer: "Dogma" },
  { id: "cine_D_014", topic: "cine", letter: "D", question: "Con la D: Etapa de llevar una película a salas y plataformas.", answer: "Distribución" },
  { id: "cine_D_015", topic: "cine", letter: "D", question: "Con la D: Formato moderno de captura y proyección .", answer: "Digital" },
  { id: "cine_E_001", topic: "cine", letter: "E", question: "Con la E: Proceso de montar y ordenar planos para construir la película.", answer: "Edición" },
  { id: "cine_E_002", topic: "cine", letter: "E", question: "Con la E: Unidad narrativa que ocurre en un lugar y tiempo concretos.", answer: "Escena" },
  { id: "cine_E_003", topic: "cine", letter: "E", question: "Con la E: Trucos visuales o prácticos para crear lo imposible.", answer: "Efectos" },
  { id: "cine_E_004", topic: "cine", letter: "E", question: "Con la E: Primera exhibición pública de una película.", answer: "Estreno" },
  { id: "cine_E_005", topic: "cine", letter: "E", question: "Con la E: Director/teórico soviético asociado al montaje.", answer: "Eisenstein" },
  { id: "cine_E_006", topic: "cine", letter: "E", question: "Con la E: Selección de lo que entra en el cuadro .", answer: "Encadre" },
  { id: "cine_E_007", topic: "cine", letter: "E", question: "Con la E: Relato grande y heroico; cine épico.", answer: "Epopeya" },
  { id: "cine_E_008", topic: "cine", letter: "E", question: "Con la E: Tipo de documental reflexivo o experimental.", answer: "Ensayo" },
  { id: "cine_E_009", topic: "cine", letter: "E", question: "Con la E: Proceso de proyectar cine en salas o festivales.", answer: "Exhibición" },
  { id: "cine_E_010", topic: "cine", letter: "E", question: "Con la E: Ajuste de nitidez de la imagen.", answer: "Enfoque" },
  { id: "cine_E_011", topic: "cine", letter: "E", question: "Con la E: Salto temporal narrativo omitiendo acciones intermedias.", answer: "Elipsis" },
  { id: "cine_E_012", topic: "cine", letter: "E", question: "Con la E: Efecto visual de perspectiva al representar un cuerpo/objeto en ángulo.", answer: "Escorzo" },
  { id: "cine_E_013", topic: "cine", letter: "E", question: "Con la E: Estado emocional; también tono que puede buscar una película.", answer: "Euforia" },
  { id: "cine_E_014", topic: "cine", letter: "E", question: "Con la E: Cadena/plataforma; parte del ecosistema audiovisual.", answer: "Epix" },
  { id: "cine_E_015", topic: "cine", letter: "E", question: "Con la E: Tema frecuente en títulos y tramas .", answer: "Eterno" },
  { id: "cine_F_001", topic: "cine", letter: "F", question: "Con la F: Imagen individual de una película.", answer: "Fotograma" },
  { id: "cine_F_002", topic: "cine", letter: "F", question: "Con la F: Evento donde se exhiben y premian películas.", answer: "Festival" },
  { id: "cine_F_003", topic: "cine", letter: "F", question: "Con la F: Narración inventada, opuesta a documental.", answer: "Ficción" },
  { id: "cine_F_004", topic: "cine", letter: "F", question: "Con la F: Recurso narrativo que vuelve al pasado.", answer: "Flashback" },
  { id: "cine_F_005", topic: "cine", letter: "F", question: "Con la F: Creación de sonidos en postproducción .", answer: "Foley" },
  { id: "cine_F_006", topic: "cine", letter: "F", question: "Con la F: Director italiano reconocido por su estilo barroco.", answer: "Fellini" },
  { id: "cine_F_007", topic: "cine", letter: "F", question: "Con la F: Director alemán clave del Nuevo Cine Alemán.", answer: "Fassbinder" },
  { id: "cine_F_008", topic: "cine", letter: "F", question: "Con la F: Director estadounidense conocido por thrillers estilizados.", answer: "Fincher" },
  { id: "cine_F_009", topic: "cine", letter: "F", question: "Con la F: Cuadro; unidad básica en imagen en movimiento .", answer: "Frame" },
  { id: "cine_F_010", topic: "cine", letter: "F", question: "Con la F: Relación entre ancho y alto de la imagen en pantalla.", answer: "Formato" },
  { id: "cine_F_011", topic: "cine", letter: "F", question: "Con la F: Transición visual: fundido a negro/blanco.", answer: "Fundido" },
  { id: "cine_F_012", topic: "cine", letter: "F", question: "Con la F: Género con magia y mundos imaginarios.", answer: "Fantasía" },
  { id: "cine_F_013", topic: "cine", letter: "F", question: "Con la F: Saga de películas conectadas por marca o universo.", answer: "Franquicia" },
  { id: "cine_F_014", topic: "cine", letter: "F", question: "Con la F: Encuadre; composición del plano .", answer: "Framing" },
  { id: "cine_F_015", topic: "cine", letter: "F", question: "Con la F: Estética/idea de futuro; aparece en diseños de producción.", answer: "Futurismo" },
  { id: "cine_G_001", topic: "cine", letter: "G", question: "Con la G: Texto base con historia, escenas y diálogos.", answer: "Guion" },
  { id: "cine_G_002", topic: "cine", letter: "G", question: "Con la G: Categoría narrativa: terror, comedia, drama, etc.", answer: "Género" },
  { id: "cine_G_003", topic: "cine", letter: "G", question: "Con la G: Estudio japonés famoso por animación .", answer: "Ghibli" },
  { id: "cine_G_004", topic: "cine", letter: "G", question: "Con la G: Premios principales del cine español.", answer: "Goya" },
  { id: "cine_G_005", topic: "cine", letter: "G", question: "Con la G: Director francés clave de la Nouvelle Vague.", answer: "Godard" },
  { id: "cine_G_006", topic: "cine", letter: "G", question: "Con la G: Equipo para mover cámara en altura y travellings amplios.", answer: "Grúa" },
  { id: "cine_G_007", topic: "cine", letter: "G", question: "Con la G: Chistes visuales o situaciones cómicas.", answer: "Gags" },
  { id: "cine_G_008", topic: "cine", letter: "G", question: "Con la G: Género que retrata conflictos bélicos.", answer: "Guerra" },
  { id: "cine_G_009", topic: "cine", letter: "G", question: "Con la G: En rodaje, globo de luz o difusor .", answer: "Globo" },
  { id: "cine_G_010", topic: "cine", letter: "G", question: "Con la G: Estética de violencia explícita en cine de terror.", answer: "Gore" },
  { id: "cine_G_011", topic: "cine", letter: "G", question: "Con la G: Nombre asociado a Greta Gerwig .", answer: "Greta" },
  { id: "cine_G_012", topic: "cine", letter: "G", question: "Con la G: Película basada en novela famosa .", answer: "Gatsby" },
  { id: "cine_G_013", topic: "cine", letter: "G", question: "Con la G: Película épica ambientada en Roma.", answer: "Gladiator" },
  { id: "cine_G_014", topic: "cine", letter: "G", question: "Con la G: Director conocido por creatividad visual .", answer: "Gondry" },
  { id: "cine_G_015", topic: "cine", letter: "G", question: "Con la G: Subgénero italiano de thriller/terror estilizado.", answer: "Giallo" },
  { id: "cine_H_001", topic: "cine", letter: "H", question: "Con la H: Director británico, maestro del suspense.", answer: "Hitchcock" },
  { id: "cine_H_002", topic: "cine", letter: "H", question: "Con la H: Centro industrial del cine comercial estadounidense.", answer: "Hollywood" },
  { id: "cine_H_003", topic: "cine", letter: "H", question: "Con la H: Arquetipo central de muchas narrativas cinematográficas.", answer: "Héroe" },
  { id: "cine_H_004", topic: "cine", letter: "H", question: "Con la H: Género diseñado para provocar miedo.", answer: "Horror" },
  { id: "cine_H_005", topic: "cine", letter: "H", question: "Con la H: Director austríaco conocido por cine incómodo y crítico.", answer: "Haneke" },
  { id: "cine_H_006", topic: "cine", letter: "H", question: "Con la H: Apellido de Tom Hanks, actor popular.", answer: "Hanks" },
  { id: "cine_H_007", topic: "cine", letter: "H", question: "Con la H: Apellido de Ron Howard, director.", answer: "Howard" },
  { id: "cine_H_008", topic: "cine", letter: "H", question: "Con la H: Película  sobre cine y Méliès.", answer: "Hugo" },
  { id: "cine_H_009", topic: "cine", letter: "H", question: "Con la H: Estética que busca verosimilitud extrema en imagen y sonido.", answer: "Hiperrealismo" },
  { id: "cine_H_010", topic: "cine", letter: "H", question: "Con la H: Efecto/tecnología para imágenes 3D en ficción.", answer: "Holograma" },
  { id: "cine_H_011", topic: "cine", letter: "H", question: "Con la H: Estructura breve; en cine puede inspirar montaje poético .", answer: "Haiku" },
  { id: "cine_H_012", topic: "cine", letter: "H", question: "Con la H: Director alemán Werner Herzog.", answer: "Herzog" },
  { id: "cine_H_013", topic: "cine", letter: "H", question: "Con la H: Unidad; usada en audio/cine para frecuencia de sonido.", answer: "Hertz" },
  { id: "cine_H_014", topic: "cine", letter: "H", question: "Con la H: Mezcla de géneros o formatos .", answer: "Hibrido" },
  { id: "cine_H_015", topic: "cine", letter: "H", question: "Con la H: Cámara en mano para sensación de realismo.", answer: "Handheld" },
  { id: "cine_I_001", topic: "cine", letter: "I", question: "Con la I: Película de ciencia ficción sobre sueños y capas de realidad.", answer: "Inception" },
  { id: "cine_I_002", topic: "cine", letter: "I", question: "Con la I: Trabajo actoral para dar vida a un personaje.", answer: "Interpretación" },
  { id: "cine_I_003", topic: "cine", letter: "I", question: "Con la I: Diseño de luz en un set para tono y visibilidad.", answer: "Iluminación" },
  { id: "cine_I_004", topic: "cine", letter: "I", question: "Con la I: Base de datos popular de cine y TV.", answer: "IMDb" },
  { id: "cine_I_005", topic: "cine", letter: "I", question: "Con la I: Figura o símbolo cultural del cine.", answer: "Icono" },
  { id: "cine_I_006", topic: "cine", letter: "I", question: "Con la I: Cine independiente fuera de grandes estudios.", answer: "Indie" },
  { id: "cine_I_007", topic: "cine", letter: "I", question: "Con la I: Sensación de estar dentro de la historia/experiencia.", answer: "Inmersión" },
  { id: "cine_I_008", topic: "cine", letter: "I", question: "Con la I: Tono raro o sorprendente en narrativa y puesta en escena.", answer: "Insolito" },
  { id: "cine_I_009", topic: "cine", letter: "I", question: "Con la I: Textos en pantalla, comunes en cine mudo.", answer: "Intertítulos" },
  { id: "cine_I_010", topic: "cine", letter: "I", question: "Con la I: Origen creativo de una historia o estilo visual.", answer: "Inspiración" },
  { id: "cine_I_011", topic: "cine", letter: "I", question: "Con la I: Sin sonido; describe parte del cine mudo temprano.", answer: "Insonoro" },
  { id: "cine_I_012", topic: "cine", letter: "I", question: "Con la I: Versión no estrenada o corte alternativo.", answer: "Inédita" },
  { id: "cine_I_013", topic: "cine", letter: "I", question: "Con la I: Improvisación en escena por actores .", answer: "Improv" },
  { id: "cine_I_014", topic: "cine", letter: "I", question: "Con la I: Evento que dispara la trama en guion.", answer: "Incidente" },
  { id: "cine_I_015", topic: "cine", letter: "I", question: "Con la I: Tono de cercanía; también coordinadores de intimidad en rodaje.", answer: "Intimidad" },
  { id: "cine_J_001", topic: "cine", letter: "J", question: "Con la J: Película de tiburón que marcó el blockbuster moderno.", answer: "Jaws" },
  { id: "cine_J_002", topic: "cine", letter: "J", question: "Con la J: Película centrada en un villano icónico.", answer: "Joker" },
  { id: "cine_J_003", topic: "cine", letter: "J", question: "Con la J: País clave en historia del cine .", answer: "Japón" },
  { id: "cine_J_004", topic: "cine", letter: "J", question: "Con la J: Cineasta conocido por cine surreal y de culto.", answer: "Jodorowsky" },
  { id: "cine_J_005", topic: "cine", letter: "J", question: "Con la J: Director estadounidense asociado al cine independiente.", answer: "Jarmusch" },
  { id: "cine_J_006", topic: "cine", letter: "J", question: "Con la J: Tema común en cine de tribunales.", answer: "Juicio" },
  { id: "cine_J_007", topic: "cine", letter: "J", question: "Con la J: Película popular de aventura/fantasía.", answer: "Jumanji" },
  { id: "cine_J_008", topic: "cine", letter: "J", question: "Con la J: Escenario frecuente en cine de aventura.", answer: "Jungla" },
  { id: "cine_J_009", topic: "cine", letter: "J", question: "Con la J: Saga cinematográfica sobre dinosaurios.", answer: "Jurassic" },
  { id: "cine_J_010", topic: "cine", letter: "J", question: "Con la J: Película de Almodóvar basada en relatos de Alice Munro.", answer: "Julieta" },
  { id: "cine_J_011", topic: "cine", letter: "J", question: "Con la J: Adjetivo; cine japonés como tradición importante.", answer: "Japonés" },
  { id: "cine_J_012", topic: "cine", letter: "J", question: "Con la J: Etiqueta de “cine joven” o público juvenil .", answer: "Joven" },
  { id: "cine_J_013", topic: "cine", letter: "J", question: "Con la J: Ruido/ambiente de set; jerga informal.", answer: "Jaleo" },
  { id: "cine_J_014", topic: "cine", letter: "J", question: "Con la J: Juego; aparece en escenas .", answer: "Jenga" },
  { id: "cine_J_015", topic: "cine", letter: "J", question: "Con la J: Grupo que decide premios en festivales.", answer: "Jurado" },
  { id: "cine_L_001", topic: "cine", letter: "L", question: "Con la L: Película de duración estándar .", answer: "Largometraje" },
  { id: "cine_L_002", topic: "cine", letter: "L", question: "Con la L: Parte del objetivo que forma la imagen.", answer: "Lente" },
  { id: "cine_L_003", topic: "cine", letter: "L", question: "Con la L: Apellido de pioneros del cine.", answer: "Lumière" },
  { id: "cine_L_004", topic: "cine", letter: "L", question: "Con la L: Director Fritz Lang, clásico del expresionismo.", answer: "Lang" },
  { id: "cine_L_005", topic: "cine", letter: "L", question: "Con la L: Director famoso por la “toque Lubitsch” en comedia.", answer: "Lubitsch" },
  { id: "cine_L_006", topic: "cine", letter: "L", question: "Con la L: Equipo y diseño de iluminación en rodaje.", answer: "Luces" },
  { id: "cine_L_007", topic: "cine", letter: "L", question: "Con la L: Lugar real donde se filma una escena.", answer: "Locación" },
  { id: "cine_L_008", topic: "cine", letter: "L", question: "Con la L: Metáfora; también “pantalla” como lienzo cinematográfico.", answer: "Lienzo" },
  { id: "cine_L_009", topic: "cine", letter: "L", question: "Con la L: Herramienta para ver detalle en montaje/fotografía.", answer: "Lupa" },
  { id: "cine_L_010", topic: "cine", letter: "L", question: "Con la L: Rol en set: dirigir equipo y decisiones.", answer: "Liderazgo" },
  { id: "cine_L_011", topic: "cine", letter: "L", question: "Con la L: Jerga divertida; se usa para hablar del objetivo/cámara.", answer: "Lenteja" },
  { id: "cine_L_012", topic: "cine", letter: "L", question: "Con la L: Línea de diálogo o línea de acción narrativa.", answer: "Línea" },
  { id: "cine_L_013", topic: "cine", letter: "L", question: "Con la L: En set, productos para utilería/FX prácticos .", answer: "Lubricante" },
  { id: "cine_L_014", topic: "cine", letter: "L", question: "Con la L: Efecto óptico de destellos en lente.", answer: "Lensflare" },
  { id: "cine_L_015", topic: "cine", letter: "L", question: "Con la L: Frase que resume una película en una línea.", answer: "Logline" },
  { id: "cine_M_001", topic: "cine", letter: "M", question: "Con la M: Edición y construcción de ritmo/meaning por corte.", answer: "Montaje" },
  { id: "cine_M_002", topic: "cine", letter: "M", question: "Con la M: Pionero del cine de trucos y fantasía.", answer: "Méliès" },
  { id: "cine_M_003", topic: "cine", letter: "M", question: "Con la M: Elemento clave para emoción y ritmo narrativo.", answer: "Música" },
  { id: "cine_M_004", topic: "cine", letter: "M", question: "Con la M: Director japonés de animación.", answer: "Miyazaki" },
  { id: "cine_M_005", topic: "cine", letter: "M", question: "Con la M: Universo de cine de superhéroes muy popular.", answer: "Marvel" },
  { id: "cine_M_006", topic: "cine", letter: "M", question: "Con la M: Película sobre realidad simulada; icono de sci-fi.", answer: "Matrix" },
  { id: "cine_M_007", topic: "cine", letter: "M", question: "Con la M: Thriller narrado de forma no lineal.", answer: "Memento" },
  { id: "cine_M_008", topic: "cine", letter: "M", question: "Con la M: Tono o estética macabra .", answer: "Morbido" },
  { id: "cine_M_009", topic: "cine", letter: "M", question: "Con la M: Cantidad de material filmado.", answer: "Metraje" },
  { id: "cine_M_010", topic: "cine", letter: "M", question: "Con la M: Departamento que transforma apariencia de actores.", answer: "Maquillaje" },
  { id: "cine_M_011", topic: "cine", letter: "M", question: "Con la M: Tema central en muchos géneros y tramas.", answer: "Muerte" },
  { id: "cine_M_012", topic: "cine", letter: "M", question: "Con la M: Género de emociones intensas y conflictos familiares.", answer: "Melodrama" },
  { id: "cine_M_013", topic: "cine", letter: "M", question: "Con la M: Tema/objeto frecuente en thrillers médicos.", answer: "Morfina" },
  { id: "cine_M_014", topic: "cine", letter: "M", question: "Con la M: Género donde canciones avanzan la historia.", answer: "Musical" },
  { id: "cine_M_015", topic: "cine", letter: "M", question: "Con la M: Plataforma conocida por curaduría de cine autoral.", answer: "Mubi" },
  { id: "cine_N_001", topic: "cine", letter: "N", question: "Con la N: Director Christopher Nolan.", answer: "Nolan" },
  { id: "cine_N_002", topic: "cine", letter: "N", question: "Con la N: Plataforma global de streaming con producción de cine/series.", answer: "Netflix" },
  { id: "cine_N_003", topic: "cine", letter: "N", question: "Con la N: Movimiento italiano de posguerra con enfoque realista.", answer: "Neorrealismo" },
  { id: "cine_N_004", topic: "cine", letter: "N", question: "Con la N: Estilo/género con crimen, sombras y moral ambigua.", answer: "Noir" },
  { id: "cine_N_005", topic: "cine", letter: "N", question: "Con la N: Voz o figura que cuenta la historia.", answer: "Narrador" },
  { id: "cine_N_006", topic: "cine", letter: "N", question: "Con la N: Cine nacional; identidad cultural en películas.", answer: "Nación" },
  { id: "cine_N_007", topic: "cine", letter: "N", question: "Con la N: Estética de luces urbanas; común en neo-noir.", answer: "Neón" },
  { id: "cine_N_008", topic: "cine", letter: "N", question: "Con la N: Selección para premio.", answer: "Nominación" },
  { id: "cine_N_009", topic: "cine", letter: "N", question: "Con la N: Escenario/tiempo frecuente en thrillers y terror.", answer: "Noche" },
  { id: "cine_N_010", topic: "cine", letter: "N", question: "Con la N: Cine itinerante o historias de viaje.", answer: "Nómada" },
  { id: "cine_N_011", topic: "cine", letter: "N", question: "Con la N: Conflicto central de una historia.", answer: "Núcleo" },
  { id: "cine_N_012", topic: "cine", letter: "N", question: "Con la N: Tensión; “tener nervio” en una escena.", answer: "Nervio" },
  { id: "cine_N_013", topic: "cine", letter: "N", question: "Con la N: Origen cultural de una película o producción.", answer: "Nacionalidad" },
  { id: "cine_N_014", topic: "cine", letter: "N", question: "Con la N: Capas narrativas o de sonido/imagen en mezcla.", answer: "Niveles" },
  { id: "cine_N_015", topic: "cine", letter: "N", question: "Con la N: Vínculo entre escenas o personajes.", answer: "Nexo" },
  { id: "cine_Ñ_001", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Director hispano-mexicano clave del surrealismo cinematográfico.", answer: "Buñuel" },
  { id: "cine_Ñ_002", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Director mexicano ganador de múltiples premios.", answer: "Iñárritu" },
  { id: "cine_Ñ_003", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Apellido de Michael Peña, actor en cine mundial.", answer: "Peña" },
  { id: "cine_Ñ_004", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Apellido con Ñ; ejemplo de apellidos en créditos.", answer: "Muñiz" },
  { id: "cine_Ñ_005", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: En set, señal para empezar acción o marcar toma.", answer: "Señal" },
  { id: "cine_Ñ_006", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Referencia temporal de estreno; en cine se habla de “año de estreno”.", answer: "Año" },
  { id: "cine_Ñ_007", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Película de Guillermo del Toro sobre un humano y un monstruo.", answer: "Niño" },
  { id: "cine_Ñ_008", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: En lenguaje de cámara, cañón de luz o teleobjetivo “cañón”.", answer: "Cañón" },
  { id: "cine_Ñ_009", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Palabra que significa el día siguiente al de hoy.", answer: "Mañana" },
  { id: "cine_Ñ_010", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Adjetivo en títulos.", answer: "Pequeño" },
  { id: "cine_Ñ_011", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Tema recurrente.", answer: "Sueño" },
  { id: "cine_Ñ_012", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Tema en cine coming-of-age.", answer: "Enseñanza" },
  { id: "cine_Ñ_013", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Topónimo en locaciones.", answer: "Cañada" },
  { id: "cine_Ñ_014", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Escenario de rodaje en cine de aventura.", answer: "Montaña" },
  { id: "cine_Ñ_015", topic: "cine", letter: "Ñ", question: "Contiene la Ñ: Objeto decorativo de papel maché que se rompe en fiestas.", answer: "Piñata" },
  { id: "cine_O_001", topic: "cine", letter: "O", question: "Con la O: Premios de la Academia de Hollywood.", answer: "Oscar" },
  { id: "cine_O_002", topic: "cine", letter: "O", question: "Con la O: Director japonés conocido por cine familiar minimalista.", answer: "Ozu" },
  { id: "cine_O_003", topic: "cine", letter: "O", question: "Con la O: Conflicto central entre protagonista y antagonista.", answer: "Oposición" },
  { id: "cine_O_004", topic: "cine", letter: "O", question: "Con la O: Cine puede adaptar óperas; también género audiovisual grabado.", answer: "Ópera" },
  { id: "cine_O_005", topic: "cine", letter: "O", question: "Con la O: Lente de cámara; determina campo y perspectiva.", answer: "Objetivo" },
  { id: "cine_O_006", topic: "cine", letter: "O", question: "Con la O: Nombre asociado a Orson Welles, figura histórica.", answer: "Orson" },
  { id: "cine_O_007", topic: "cine", letter: "O", question: "Con la O: Toma descartada o extra; material no usado.", answer: "Outtake" },
  { id: "cine_O_008", topic: "cine", letter: "O", question: "Con la O: Regrabación de audio en postproducción.", answer: "Overdub" },
  { id: "cine_O_009", topic: "cine", letter: "O", question: "Con la O: Versión primera frente a remake.", answer: "Original" },
  { id: "cine_O_010", topic: "cine", letter: "O", question: "Con la O: Introducción musical en películas, sobre todo en clásicos.", answer: "Obertura" },
  { id: "cine_O_011", topic: "cine", letter: "O", question: "Con la O: Estética de iluminación baja.", answer: "Oscuro" },
  { id: "cine_O_012", topic: "cine", letter: "O", question: "Con la O: Tema recurrente en dramas y thrillers.", answer: "Olvido" },
  { id: "cine_O_013", topic: "cine", letter: "O", question: "Con la O: Banda británica de rock de los años 90, cantan la cancion Wonderwall.", answer: "Oasis" },
  { id: "cine_O_014", topic: "cine", letter: "O", question: "Con la O: Concepto de “Nueva Ola” en movimientos cinematográficos.", answer: "Ola" },
  { id: "cine_O_015", topic: "cine", letter: "O", question: "Con la O: Título de terror conocido;.", answer: "Omen" },
  { id: "cine_P_001", topic: "cine", letter: "P", question: "Con la P: Unidad básica de imagen entre cortes.", answer: "Plano" },
  { id: "cine_P_002", topic: "cine", letter: "P", question: "Con la P: Obra cinematográfica; también material físico.", answer: "Pelicula" },
  { id: "cine_P_003", topic: "cine", letter: "P", question: "Con la P: Personaje principal de la historia.", answer: "Protagonista" },
  { id: "cine_P_004", topic: "cine", letter: "P", question: "Con la P: Rol que financia, organiza y coordina producción.", answer: "Productor" },
  { id: "cine_P_005", topic: "cine", letter: "P", question: "Con la P: Etapa de edición, color, sonido y VFX tras rodaje.", answer: "Postproducción" },
  { id: "cine_P_006", topic: "cine", letter: "P", question: "Con la P: Reconocimiento .", answer: "Premio" },
  { id: "cine_P_007", topic: "cine", letter: "P", question: "Con la P: Estudio de animación famoso por largometrajes.", answer: "Pixar" },
  { id: "cine_P_008", topic: "cine", letter: "P", question: "Con la P: Película surcoreana premiada internacionalmente.", answer: "Parasite" },
  { id: "cine_P_009", topic: "cine", letter: "P", question: "Con la P: Estética/tono pulp; también referencia a PulpFiction .", answer: "Pulp" },
  { id: "cine_P_010", topic: "cine", letter: "P", question: "Con la P: Película y apellido; cine indie.", answer: "Paterson" },
  { id: "cine_P_011", topic: "cine", letter: "P", question: "Con la P: Toma larga sin cortes visibles.", answer: "Planosecuencia" },
  { id: "cine_P_012", topic: "cine", letter: "P", question: "Con la P: Premio principal de Cannes: Palma de Oro.", answer: "Palma" },
  { id: "cine_P_013", topic: "cine", letter: "P", question: "Con la P: Exhibición de una película en sala o festival.", answer: "Proyección" },
  { id: "cine_P_014", topic: "cine", letter: "P", question: "Con la P: Presentación breve de una idea de película.", answer: "Pitch" },
  { id: "cine_P_015", topic: "cine", letter: "P", question: "Con la P: Sección inicial que introduce contexto de la historia.", answer: "Prólogo" },
  { id: "cine_Q_001", topic: "cine", letter: "Q", question: "Contiene la Q: Nombre del director Quentin Tarantino.", answer: "Quentin" },
  { id: "cine_Q_002", topic: "cine", letter: "Q", question: "Contiene la Q: Referencia a adaptaciones cinematográficas de Don Quijote.", answer: "Quijote" },
  { id: "cine_Q_003", topic: "cine", letter: "Q", question: "Contiene la Q: Recaudación de entradas.", answer: "Taquilla" },
  { id: "cine_Q_004", topic: "cine", letter: "Q", question: "Contiene la Q: Equipo de rodaje: cámara, luz, sonido, etc.", answer: "Equipo" },
  { id: "cine_Q_005", topic: "cine", letter: "Q", question: "Contiene la Q: Película de Darren Aronofsky sobre adicción.", answer: "Requiem" },
  { id: "cine_Q_006", topic: "cine", letter: "Q", question: "Contiene la Q: Balance entre drama/humor o entre niveles de sonido.", answer: "Equilibrio" },
  { id: "cine_Q_007", topic: "cine", letter: "Q", question: "Contiene la Q: Criatura mitológica con partes de muchos diferentes animales.", answer: "Quimera" },
  { id: "cine_Q_008", topic: "cine", letter: "Q", question: "Contiene la Q: Número mínimo; en jurados o votaciones.", answer: "Quorum" },
  { id: "cine_Q_009", topic: "cine", letter: "Q", question: "Contiene la Q: Tema y película.", answer: "Aquelarre" },
  { id: "cine_Q_010", topic: "cine", letter: "Q", question: "Contiene la Q: Compatibilidad entre actores; “química” en pantalla.", answer: "Química" },
  { id: "cine_Q_011", topic: "cine", letter: "Q", question: "Contiene la Q: Superhéroe de Marvel con súper velocidad.", answer: "Quicksilver" },
  { id: "cine_Q_012", topic: "cine", letter: "Q", question: "Contiene la Q: Término usado en títulos sci-fi.", answer: "Quasar" },
  { id: "cine_Q_013", topic: "cine", letter: "Q", question: "Contiene la Q: Objeto andino que aparece en cine histórico.", answer: "Quipu" },
  { id: "cine_Q_014", topic: "cine", letter: "Q", question: "Contiene la Q: Animal en documentales.", answer: "Quokka" },
  { id: "cine_Q_015", topic: "cine", letter: "Q", question: "Contiene la Q: Marca de continuidad al final de toma .", answer: "Queda" },
  { id: "cine_R_001", topic: "cine", letter: "R", question: "Con la R: Proceso de filmación en set o locación.", answer: "Rodaje" },
  { id: "cine_R_002", topic: "cine", letter: "R", question: "Con la R: Conjunto de actores de una película.", answer: "Reparto" },
  { id: "cine_R_003", topic: "cine", letter: "R", question: "Con la R: Nueva versión de una película anterior.", answer: "Remake" },
  { id: "cine_R_004", topic: "cine", letter: "R", question: "Con la R: Crítica escrita sobre una película.", answer: "Reseña" },
  { id: "cine_R_005", topic: "cine", letter: "R", question: "Con la R: Sensación de velocidad narrativa creada por montaje y guion.", answer: "Ritmo" },
  { id: "cine_R_006", topic: "cine", letter: "R", question: "Con la R: Clasificación por edades .", answer: "Rango" },
  { id: "cine_R_007", topic: "cine", letter: "R", question: "Con la R: Técnica de animación trazando sobre imagen real.", answer: "Rotoscopia" },
  { id: "cine_R_008", topic: "cine", letter: "R", question: "Con la R: Director francés clásico; cine humanista.", answer: "Renoir" },
  { id: "cine_R_009", topic: "cine", letter: "R", question: "Con la R: Saga de boxeo icónica.", answer: "Rocky" },
  { id: "cine_R_010", topic: "cine", letter: "R", question: "Con la R: Conflicto entre personajes; base de muchas tramas.", answer: "Rivales" },
  { id: "cine_R_011", topic: "cine", letter: "R", question: "Con la R: Continuidad entre planos .", answer: "Raccord" },
  { id: "cine_R_012", topic: "cine", letter: "R", question: "Con la R: Etapas en festivales/premios .", answer: "Ronda" },
  { id: "cine_R_013", topic: "cine", letter: "R", question: "Con la R: Proceso químico del film en fotografía/cine analógico.", answer: "Revelado" },
  { id: "cine_R_014", topic: "cine", letter: "R", question: "Con la R: Objetivo central en comedia.", answer: "Risa" },
  { id: "cine_R_015", topic: "cine", letter: "R", question: "Con la R: Sonido no deseado; se reduce en mezcla.", answer: "Ruido" },
  { id: "cine_S_001", topic: "cine", letter: "S", question: "Con la S: Elemento clave: diálogos, ambiente, música y efectos.", answer: "Sonido" },
  { id: "cine_S_002", topic: "cine", letter: "S", question: "Con la S: Película que continúa una historia previa.", answer: "Secuela" },
  { id: "cine_S_003", topic: "cine", letter: "S", question: "Con la S: Tensión narrativa sostenida.", answer: "Suspense" },
  { id: "cine_S_004", topic: "cine", letter: "S", question: "Con la S: Director italiano contemporáneo.", answer: "Sorrentino" },
  { id: "cine_S_005", topic: "cine", letter: "S", question: "Con la S: Director estadounidense de enorme influencia.", answer: "Spielberg" },
  { id: "cine_S_006", topic: "cine", letter: "S", question: "Con la S: Director conocido por cine criminal y biografías.", answer: "Scorsese" },
  { id: "cine_S_007", topic: "cine", letter: "S", question: "Con la S: Serie de películas conectadas.", answer: "Saga" },
  { id: "cine_S_008", topic: "cine", letter: "S", question: "Con la S: Estética de “slasher” en terror.", answer: "Slash" },
  { id: "cine_S_009", topic: "cine", letter: "S", question: "Con la S: Texto traducido en pantalla.", answer: "Subtitulo" },
  { id: "cine_S_010", topic: "cine", letter: "S", question: "Con la S: Guion gráfico para planificar planos.", answer: "Storyboard" },
  { id: "cine_S_011", topic: "cine", letter: "S", question: "Con la S: Estabilizador para cámara en movimiento.", answer: "Steadicam" },
  { id: "cine_S_012", topic: "cine", letter: "S", question: "Con la S: Recurso dramático potente en sonido.", answer: "Silencio" },
  { id: "cine_S_013", topic: "cine", letter: "S", question: "Con la S: Lugar de rodaje  o unidad de puntuación.", answer: "Set" },
  { id: "cine_S_014", topic: "cine", letter: "S", question: "Con la S: Género que critica con humor.", answer: "Sátira" },
  { id: "cine_S_015", topic: "cine", letter: "S", question: "Con la S: Animación cuadro a cuadro con objetos reales.", answer: "Stopmotion" },
  { id: "cine_T_001", topic: "cine", letter: "T", question: "Con la T: Cada grabación individual de una acción.", answer: "Toma" },
  { id: "cine_T_002", topic: "cine", letter: "T", question: "Con la T: Avance promocional de una película.", answer: "Trailer" },
  { id: "cine_T_003", topic: "cine", letter: "T", question: "Con la T: Director conocido por diálogos y estilo pop.", answer: "Tarantino" },
  { id: "cine_T_004", topic: "cine", letter: "T", question: "Con la T: Género de suspense y tensión.", answer: "Thriller" },
  { id: "cine_T_005", topic: "cine", letter: "T", question: "Con la T: Lente larga que acerca y comprime perspectiva.", answer: "Teleobjetivo" },
  { id: "cine_T_006", topic: "cine", letter: "T", question: "Con la T: Género diseñado para asustar.", answer: "Terror" },
  { id: "cine_T_007", topic: "cine", letter: "T", question: "Con la T: Éxito enorme en taquilla .", answer: "Taquillazo" },
  { id: "cine_T_008", topic: "cine", letter: "T", question: "Con la T: Número de toma/“toma 2” en rodaje.", answer: "Toma2" },
  { id: "cine_T_009", topic: "cine", letter: "T", question: "Con la T: Cartelas/creditos iniciales o finales.", answer: "Títulos" },
  { id: "cine_T_010", topic: "cine", letter: "T", question: "Con la T: Color emocional/estético de una película.", answer: "Tonalidad" },
  { id: "cine_T_011", topic: "cine", letter: "T", question: "Con la T: Conjunto de tres películas relacionadas.", answer: "Trilogía" },
  { id: "cine_T_012", topic: "cine", letter: "T", question: "Con la T: Movimiento de cámara desplazándose en un eje.", answer: "Travelling" },
  { id: "cine_T_013", topic: "cine", letter: "T", question: "Con la T: Cine de tesis: película con tema/idea central fuerte.", answer: "Tesis" },
  { id: "cine_T_014", topic: "cine", letter: "T", question: "Con la T: Color; en corrección de color se ajusta tint.", answer: "Tinta" },
  { id: "cine_T_015", topic: "cine", letter: "T", question: "Con la T: Estado de suspense dramático en escena.", answer: "Tensión" },
  { id: "cine_U_001", topic: "cine", letter: "U", question: "Con la U: Estudio histórico de Hollywood .", answer: "Universal" },
  { id: "cine_U_002", topic: "cine", letter: "U", question: "Con la U: Formato muy ancho de imagen; describe relaciones de aspecto.", answer: "Ultrapanorámico" },
  { id: "cine_U_003", topic: "cine", letter: "U", question: "Con la U: Tema frecuente en ciencia ficción.", answer: "Utopía" },
  { id: "cine_U_004", topic: "cine", letter: "U", question: "Con la U: Equipo/organización del rodaje en una producción.", answer: "Unidad" },
  { id: "cine_U_005", topic: "cine", letter: "U", question: "Con la U: Resolución 4K/8K; calidad de imagen moderna.", answer: "UHD" },
  { id: "cine_U_006", topic: "cine", letter: "U", question: "Con la U: Lugar concreto de rodaje .", answer: "Ubicación" },
  { id: "cine_U_007", topic: "cine", letter: "U", question: "Con la U: Instrumento que aparece en bandas sonoras o escenas musicales.", answer: "Ukelele" },
  { id: "cine_U_008", topic: "cine", letter: "U", question: "Con la U: Villana del mar en La Sirenita de Disney.", answer: "Ursula" },
  { id: "cine_U_009", topic: "cine", letter: "U", question: "Con la U: Límite de luz/sonido detectable; se usa en técnica.", answer: "Umbral" },
  { id: "cine_U_010", topic: "cine", letter: "U", question: "Con la U: Sonido simultáneo; en musical o coro.", answer: "Unísono" },
  { id: "cine_U_011", topic: "cine", letter: "U", question: "Con la U: Lugar en Argentina; locación posible en cine .", answer: "Ushuaia" },
  { id: "cine_U_012", topic: "cine", letter: "U", question: "Con la U: Musa de la astronomía en la mitología griega.", answer: "Urania" },
  { id: "cine_U_013", topic: "cine", letter: "U", question: "Con la U: Cine ambientado en ciudad; estética urbana.", answer: "Urbano" },
  { id: "cine_U_014", topic: "cine", letter: "U", question: "Con la U: Nombre de letra; V en formatos.", answer: "Uve" },
  { id: "cine_U_015", topic: "cine", letter: "U", question: "Con la U: En plataformas, perfil de usuario que ve cine en streaming.", answer: "Usuario" },
  { id: "cine_V_001", topic: "cine", letter: "V", question: "Con la V: Antagonista o figura opuesta al héroe.", answer: "Villano" },
  { id: "cine_V_002", topic: "cine", letter: "V", question: "Con la V: Departamento que diseña ropa de personajes.", answer: "Vestuario" },
  { id: "cine_V_003", topic: "cine", letter: "V", question: "Con la V: Efectos visuales digitales.", answer: "VFX" },
  { id: "cine_V_004", topic: "cine", letter: "V", question: "Con la V: Película de Hitchcock  muy influyente.", answer: "Vértigo" },
  { id: "cine_V_005", topic: "cine", letter: "V", question: "Con la V: Trabajo de voz en doblaje, animación o narración.", answer: "Voz" },
  { id: "cine_V_006", topic: "cine", letter: "V", question: "Con la V: Término italiano usado como textura/estética .", answer: "Velluto" },
  { id: "cine_V_007", topic: "cine", letter: "V", question: "Con la V: Festival de cine de Venecia .", answer: "Venecia" },
  { id: "cine_V_008", topic: "cine", letter: "V", question: "Con la V: Formato de video doméstico popular en los 80-90.", answer: "VHS" },
  { id: "cine_V_009", topic: "cine", letter: "V", question: "Con la V: Director conocido por sátira y cine provocador.", answer: "Verhoeven" },
  { id: "cine_V_010", topic: "cine", letter: "V", question: "Con la V: Estilo visual; también intención del director.", answer: "Visión" },
  { id: "cine_V_011", topic: "cine", letter: "V", question: "Con la V: Tema frecuente; se trata con géneros y clasificación.", answer: "Violencia" },
  { id: "cine_V_012", topic: "cine", letter: "V", question: "Con la V: Cine experimental y de ruptura estética.", answer: "Vanguardia" },
  { id: "cine_V_013", topic: "cine", letter: "V", question: "Con la V: Formato de video personal; puente con audiovisual moderno.", answer: "Vlog" },
  { id: "cine_V_014", topic: "cine", letter: "V", question: "Con la V: Efecto vocal/musical en cine musical.", answer: "Vibrato" },
  { id: "cine_V_015", topic: "cine", letter: "V", question: "Con la V: Relación emocional entre personajes.", answer: "Vínculo" },
  { id: "cine_X_001", topic: "cine", letter: "X", question: "Contiene la X: Película taquillera o muy popular.", answer: "Exito" },
  { id: "cine_X_002", topic: "cine", letter: "X", question: "Contiene la X: Punto más intenso.", answer: "Clímax" },
  { id: "cine_X_003", topic: "cine", letter: "X", question: "Contiene la X: Proceso de proyectar.", answer: "Exhibición" },
  { id: "cine_X_004", topic: "cine", letter: "X", question: "Contiene la X: Duración total de una película.", answer: "Extensión" },
  { id: "cine_X_005", topic: "cine", letter: "X", question: "Contiene la X: Escena de acción con explosión.", answer: "Explosión" },
  { id: "cine_X_006", topic: "cine", letter: "X", question: "Contiene la X: Detalle visual.", answer: "Textura" },
  { id: "cine_X_007", topic: "cine", letter: "X", question: "Contiene la X: Referencia a “SextoSentido”.", answer: "Sexto" },
  { id: "cine_X_008", topic: "cine", letter: "X", question: "Contiene la X: Estudio de animación.", answer: "Pixar" },
  { id: "cine_X_009", topic: "cine", letter: "X", question: "Contiene la X: Actor de fondo sin diálogo.", answer: "Extra" },
  { id: "cine_X_010", topic: "cine", letter: "X", question: "Contiene la X: Apellido; aparece en créditos o títulos.", answer: "Maxwell" },
  { id: "cine_X_011", topic: "cine", letter: "X", question: "Contiene la X: Apellido artístico de Joaquin Phoenix.", answer: "Phoenix" },
  { id: "cine_X_012", topic: "cine", letter: "X", question: "Contiene la X: Recopilación; en cine, mixtape de música.", answer: "Mixtape" },
  { id: "cine_X_013", topic: "cine", letter: "X", question: "Contiene la X: Relación entre escenas.", answer: "Conexión" },
  { id: "cine_X_014", topic: "cine", letter: "X", question: "Contiene la X: Tema o espejo narrativo.", answer: "Reflexión" },
  { id: "cine_X_015", topic: "cine", letter: "X", question: "Contiene la X: Momento donde se explica información clave.", answer: "Exposición" },
  { id: "cine_Y_001", topic: "cine", letter: "Y", question: "Contiene la Y: Artista pop que aparece en cine, documentales y conciertos.", answer: "Beyoncé" },
  { id: "cine_Y_002", topic: "cine", letter: "Y", question: "Contiene la Y: Cantante pop.", answer: "Miley" },
  { id: "cine_Y_003", topic: "cine", letter: "Y", question: "Contiene la Y: Apellido pop .", answer: "Taylor" },
  { id: "cine_Y_004", topic: "cine", letter: "Y", question: "Contiene la Y: saga de cine deportivo.", answer: "Rocky" },
  { id: "cine_Y_005", topic: "cine", letter: "Y", question: "Contiene la Y: partido local; aparece en cine deportivo.", answer: "Derby" },
  { id: "cine_Y_006", topic: "cine", letter: "Y", question: "Contiene la Y: deporte filmado en cine.", answer: "Hockey" },
  { id: "cine_Y_007", topic: "cine", letter: "Y", question: "Contiene la Y: Película biográfica  sobre Ray Charles.", answer: "Ray" },
  { id: "cine_Y_008", topic: "cine", letter: "Y", question: "Contiene la Y: Franquicia .", answer: "Toy" },
  { id: "cine_Y_009", topic: "cine", letter: "Y", question: "Contiene la Y: referencia científica en cine.", answer: "Huygens" },
  { id: "cine_Y_010", topic: "cine", letter: "Y", question: "Contiene la Y: sondas usadas en documentales de espacio.", answer: "Voyager" },
  { id: "cine_Y_011", topic: "cine", letter: "Y", question: "Contiene la Y: Personaje icónico de StarWars.", answer: "Yoda" },
  { id: "cine_Y_012", topic: "cine", letter: "Y", question: "Contiene la Y: Ciudad; escenario de cine y eventos.", answer: "Sydney" },
  { id: "cine_Y_013", topic: "cine", letter: "Y", question: "Contiene la Y: parte de títulos .", answer: "Story" },
  { id: "cine_Y_014", topic: "cine", letter: "Y", question: "Contiene la Y: Película/título musical.", answer: "Yesterday" },
  { id: "cine_Y_015", topic: "cine", letter: "Y", question: "Contiene la Y: adaptación literaria en cine.", answer: "Gatsby" },
  { id: "cine_Z_001", topic: "cine", letter: "Z", question: "Con la Z: Criatura típica del cine de terror.", answer: "Zombi" },
  { id: "cine_Z_002", topic: "cine", letter: "Z", question: "Con la Z: Película thriller basada en caso real.", answer: "Zodiac" },
  { id: "cine_Z_003", topic: "cine", letter: "Z", question: "Con la Z: Futbolista francés protagonista de un documental de 2006.", answer: "Zidane" },
  { id: "cine_Z_004", topic: "cine", letter: "Z", question: "Con la Z: Princesa de la serie de videojuegos The Legend of.", answer: "Zelda" },
  { id: "cine_Z_005", topic: "cine", letter: "Z", question: "Con la Z: Letra; también nombre en títulos sci-fi.", answer: "Zeta" },
  { id: "cine_Z_006", topic: "cine", letter: "Z", question: "Con la Z: Referencia cultural; aparece en títulos/temas de cine histórico .", answer: "Zulú" },
  { id: "cine_Z_007", topic: "cine", letter: "Z", question: "Con la Z: Apellido común en cine chino; directores/actores .", answer: "Zhang" },
  { id: "cine_Z_008", topic: "cine", letter: "Z", question: "Con la Z: Director de BackToTheFuture y ForrestGump.", answer: "Zemeckis" },
  { id: "cine_Z_009", topic: "cine", letter: "Z", question: "Con la Z: Género escénico; filmaciones/adaptaciones existen.", answer: "Zarzuela" },
  { id: "cine_Z_010", topic: "cine", letter: "Z", question: "Con la Z: Héroe enmascarado que lucha por la justicia en la California española.", answer: "Zorro" },
  { id: "cine_Z_011", topic: "cine", letter: "Z", question: "Con la Z: Rasgo de personaje; también apodo en tramas.", answer: "Zurdo" },
  { id: "cine_Z_012", topic: "cine", letter: "Z", question: "Con la Z: Punto más alto; metáfora en narrativa cinematográfica.", answer: "Zenit" },
  { id: "cine_Z_013", topic: "cine", letter: "Z", question: "Con la Z: Color; se usa en títulos/estética .", answer: "Zafiro" },
  { id: "cine_Z_014", topic: "cine", letter: "Z", question: "Con la Z: Cambiar canales; lenguaje audiovisual moderno.", answer: "Zapping" },
  { id: "cine_Z_015", topic: "cine", letter: "Z", question: "Con la Z: Término usado como apodo en historias .", answer: "Zar" },
];
