import type { QA } from "./types";

export const CULTURAGENERAL: QA[] = [
  { id: "culturageneral_A_001", topic: "culturageneral", letter: "A", question: "Con la A: Instrumento antiguo para contar y hacer cálculos.", answer: "Abaco" },
  { id: "culturageneral_A_002", topic: "culturageneral", letter: "A", question: "Con la A: Ciudadela elevada famosa en Atenas.", answer: "Acropolis" },
  { id: "culturageneral_A_003", topic: "culturageneral", letter: "A", question: "Con la A: Conjunto de letras de un idioma.", answer: "Alfabeto" },
  { id: "culturageneral_A_004", topic: "culturageneral", letter: "A", question: "Con la A: Enfermedad neurodegenerativa descrita en medicina moderna.", answer: "Alzheimer" },
  { id: "culturageneral_A_005", topic: "culturageneral", letter: "A", question: "Con la A: Gran empresa tecnológica y de comercio electrónico.", answer: "Amazon" },
  { id: "culturageneral_A_006", topic: "culturageneral", letter: "A", question: "Con la A: Animal que vive parte en agua y parte en tierra.", answer: "Anfibio" },
  { id: "culturageneral_A_007", topic: "culturageneral", letter: "A", question: "Con la A: Medicamento que combate bacterias.", answer: "Antibiotico" },
  { id: "culturageneral_A_008", topic: "culturageneral", letter: "A", question: "Con la A: Falta de interés o energía.", answer: "Apatia" },
  { id: "culturageneral_A_009", topic: "culturageneral", letter: "A", question: "Con la A: Vaso sanguíneo que lleva sangre desde el corazón.", answer: "Arteria" },
  { id: "culturageneral_A_010", topic: "culturageneral", letter: "A", question: "Con la A: Símbolo tipográfico con forma de estrella.", answer: "Asterisco" },
  { id: "culturageneral_A_011", topic: "culturageneral", letter: "A", question: "Con la A: Unidad básica de la materia en química.", answer: "Atomo" },
  { id: "culturageneral_A_012", topic: "culturageneral", letter: "A", question: "Con la A: Fenómeno luminoso polar en latitudes altas.", answer: "Aurora" },
  { id: "culturageneral_A_013", topic: "culturageneral", letter: "A", question: "Con la A: Condición del neurodesarrollo.", answer: "Autismo" },
  { id: "culturageneral_A_014", topic: "culturageneral", letter: "A", question: "Con la A: Transporte y tecnología de vuelo.", answer: "Aviacion" },
  { id: "culturageneral_A_015", topic: "culturageneral", letter: "A", question: "Con la A: Sustancia dulce común en alimentación.", answer: "Azucar" },
  { id: "culturageneral_B_001", topic: "culturageneral", letter: "B", question: "Con la B: Microorganismo unicelular.", answer: "Bacteria" },
  { id: "culturageneral_B_002", topic: "culturageneral", letter: "B", question: "Con la B: Persona que interpreta danza.", answer: "Bailarin" },
  { id: "culturageneral_B_003", topic: "culturageneral", letter: "B", question: "Con la B: Instrumento para medir masa o peso.", answer: "Balanza" },
  { id: "culturageneral_B_004", topic: "culturageneral", letter: "B", question: "Con la B: Danza escénica de tradición europea.", answer: "Ballet" },
  { id: "culturageneral_B_005", topic: "culturageneral", letter: "B", question: "Con la B: Instrumento que mide presión atmosférica.", answer: "Barometro" },
  { id: "culturageneral_B_006", topic: "culturageneral", letter: "B", question: "Con la B: Vehículo de dos ruedas impulsado a pedales.", answer: "Bicicleta" },
  { id: "culturageneral_B_007", topic: "culturageneral", letter: "B", question: "Con la B: Variedad de seres vivos en un ecosistema.", answer: "Biodiversidad" },
  { id: "culturageneral_B_008", topic: "culturageneral", letter: "B", question: "Con la B: Criptomoneda descentralizada.", answer: "Bitcoin" },
  { id: "culturageneral_B_009", topic: "culturageneral", letter: "B", question: "Con la B: Rama de la biología que estudia plantas.", answer: "Botanica" },
  { id: "culturageneral_B_010", topic: "culturageneral", letter: "B", question: "Con la B: Capital de Bélgica y sede europea.", answer: "Bruselas" },
  { id: "culturageneral_B_011", topic: "culturageneral", letter: "B", question: "Con la B: Objeto que puede volver al lanzador.", answer: "Bumeran" },
  { id: "culturageneral_B_012", topic: "culturageneral", letter: "B", question: "Con la B: Sistema administrativo basado en normas.", answer: "Burocracia" },
  { id: "culturageneral_B_013", topic: "culturageneral", letter: "B", question: "Con la B: Receptáculo para cartas o mensajes.", answer: "Buzon" },
  { id: "culturageneral_B_014", topic: "culturageneral", letter: "B", question: "Con la B: Sal química; también se usa como “frase hecha” en cultura.", answer: "Bromuro" },
  { id: "culturageneral_B_015", topic: "culturageneral", letter: "B", question: "Con la B: Poeta español del Romanticismo autor de Rimas y Leyendas.", answer: "Bécquer" },
  { id: "culturageneral_C_001", topic: "culturageneral", letter: "C", question: "Con la C: Caída de agua en un río.", answer: "Cascada" },
  { id: "culturageneral_C_002", topic: "culturageneral", letter: "C", question: "Con la C: Iglesia principal de una diócesis, de gran valor artístico.", answer: "Catedral" },
  { id: "culturageneral_C_003", topic: "culturageneral", letter: "C", question: "Con la C: Unidad básica de los seres vivos.", answer: "Celula" },
  { id: "culturageneral_C_004", topic: "culturageneral", letter: "C", question: "Con la C: Órgano principal del sistema nervioso.", answer: "Cerebro" },
  { id: "culturageneral_C_005", topic: "culturageneral", letter: "C", question: "Con la C: Escritor español del Siglo de Oro autor de la novela sobre un caballero andante.", answer: "Cervantes" },
  { id: "culturageneral_C_006", topic: "culturageneral", letter: "C", question: "Con la C: Compuesto químico muy tóxico.", answer: "Cianuro" },
  { id: "culturageneral_C_007", topic: "culturageneral", letter: "C", question: "Con la C: Sistema de baja presión con vientos fuertes.", answer: "Ciclon" },
  { id: "culturageneral_C_008", topic: "culturageneral", letter: "C", question: "Con la C: Arte de contar historias con imágenes en movimiento.", answer: "Cine" },
  { id: "culturageneral_C_009", topic: "culturageneral", letter: "C", question: "Con la C: Figura geométrica plana formada por todos los puntos equidistantes de un centro.", answer: "Circulo" },
  { id: "culturageneral_C_010", topic: "culturageneral", letter: "C", question: "Con la C: Pigmento verde de plantas.", answer: "Clorofila" },
  { id: "culturageneral_C_011", topic: "culturageneral", letter: "C", question: "Con la C: Cuerpo del sistema solar con cola al acercarse al Sol.", answer: "Cometa" },
  { id: "culturageneral_C_012", topic: "culturageneral", letter: "C", question: "Con la C: Ley fundamental de un Estado.", answer: "Constitucion" },
  { id: "culturageneral_C_013", topic: "culturageneral", letter: "C", question: "Con la C: Gran masa de tierra emergida.", answer: "Continente" },
  { id: "culturageneral_C_014", topic: "culturageneral", letter: "C", question: "Con la C: Conjunto de costumbres y conocimientos de una sociedad.", answer: "Cultura" },
  { id: "culturageneral_C_015", topic: "culturageneral", letter: "C", question: "Con la C: Mineral muy común en rocas.", answer: "Cuarzo" },
  { id: "culturageneral_D_001", topic: "culturageneral", letter: "D", question: "Con la D: Sistema político basado en participación ciudadana.", answer: "Democracia" },
  { id: "culturageneral_D_002", topic: "culturageneral", letter: "D", question: "Con la D: Relación entre masa y volumen.", answer: "Densidad" },
  { id: "culturageneral_D_003", topic: "culturageneral", letter: "D", question: "Con la D: Región con muy poca precipitación.", answer: "Desierto" },
  { id: "culturageneral_D_004", topic: "culturageneral", letter: "D", question: "Con la D: Enfermedad metabólica relacionada con glucosa.", answer: "Diabetes" },
  { id: "culturageneral_D_005", topic: "culturageneral", letter: "D", question: "Con la D: Reptil prehistórico extinto.", answer: "Dinosaurio" },
  { id: "culturageneral_D_006", topic: "culturageneral", letter: "D", question: "Con la D: Relaciones entre estados mediante negociación.", answer: "Diplomacia" },
  { id: "culturageneral_D_007", topic: "culturageneral", letter: "D", question: "Con la D: Neurotransmisor asociado a recompensa y movimiento.", answer: "Dopamina" },
  { id: "culturageneral_D_008", topic: "culturageneral", letter: "D", question: "Con la D: Autor de obras de teatro.", answer: "Dramaturgo" },
  { id: "culturageneral_D_009", topic: "culturageneral", letter: "D", question: "Con la D: Aeronave sin piloto a bordo.", answer: "Dron" },
  { id: "culturageneral_D_010", topic: "culturageneral", letter: "D", question: "Con la D: Río de la península ibérica.", answer: "Duero" },
  { id: "culturageneral_D_011", topic: "culturageneral", letter: "D", question: "Con la D: Montículo de arena formado por el viento.", answer: "Duna" },
  { id: "culturageneral_D_012", topic: "culturageneral", letter: "D", question: "Con la D: Conducto o tubo para transportar fluidos.", answer: "Ducto" },
  { id: "culturageneral_D_013", topic: "culturageneral", letter: "D", question: "Con la D: Representación gráfica con líneas.", answer: "Dibujo" },
  { id: "culturageneral_D_014", topic: "culturageneral", letter: "D", question: "Con la D: Mamífero marino inteligente.", answer: "Delfin" },
  { id: "culturageneral_D_015", topic: "culturageneral", letter: "D", question: "Con la D: Molécula que contiene información genética.", answer: "ADN" },
  { id: "culturageneral_E_001", topic: "culturageneral", letter: "E", question: "Con la E: Fenómeno cuando un astro oculta a otro.", answer: "Eclipse" },
  { id: "culturageneral_E_002", topic: "culturageneral", letter: "E", question: "Con la E: Ciencia social que estudia producción y consumo.", answer: "Economia" },
  { id: "culturageneral_E_003", topic: "culturageneral", letter: "E", question: "Con la E: Conjunto de seres vivos y su entorno.", answer: "Ecosistema" },
  { id: "culturageneral_E_004", topic: "culturageneral", letter: "E", question: "Con la E: Línea imaginaria que divide hemisferios.", answer: "Ecuador" },
  { id: "culturageneral_E_005", topic: "culturageneral", letter: "E", question: "Con la E: Construcción destinada a usos humanos.", answer: "Edificio" },
  { id: "culturageneral_E_006", topic: "culturageneral", letter: "E", question: "Con la E: Civilización antigua del valle del Nilo.", answer: "Egipto" },
  { id: "culturageneral_E_007", topic: "culturageneral", letter: "E", question: "Con la E: Físico alemán que formuló la teoría de la relatividad y la ecuación E=mc².", answer: "Einstein" },
  { id: "culturageneral_E_008", topic: "culturageneral", letter: "E", question: "Con la E: Fenómenos asociados a carga eléctrica.", answer: "Electricidad" },
  { id: "culturageneral_E_009", topic: "culturageneral", letter: "E", question: "Con la E: Sustancia química de la tabla periódica.", answer: "Elemento" },
  { id: "culturageneral_E_010", topic: "culturageneral", letter: "E", question: "Con la E: Movimiento de población hacia otro lugar.", answer: "Emigracion" },
  { id: "culturageneral_E_011", topic: "culturageneral", letter: "E", question: "Con la E: Obra de referencia con conocimiento organizado.", answer: "Enciclopedia" },
  { id: "culturageneral_E_012", topic: "culturageneral", letter: "E", question: "Con la E: Capacidad de realizar trabajo.", answer: "Energia" },
  { id: "culturageneral_E_013", topic: "culturageneral", letter: "E", question: "Con la E: Problema o misterio difícil.", answer: "Enigma" },
  { id: "culturageneral_E_014", topic: "culturageneral", letter: "E", question: "Con la E: Desgaste del relieve por agentes naturales.", answer: "Erosion" },
  { id: "culturageneral_E_015", topic: "culturageneral", letter: "E", question: "Con la E: Estado de alegría intensa.", answer: "Euforia" },
  { id: "culturageneral_F_001", topic: "culturageneral", letter: "F", question: "Con la F: Escala de temperatura usada en algunos países.", answer: "Fahrenheit" },
  { id: "culturageneral_F_002", topic: "culturageneral", letter: "F", question: "Con la F: Razonamiento incorrecto que parece válido.", answer: "Falacia" },
  { id: "culturageneral_F_003", topic: "culturageneral", letter: "F", question: "Con la F: Lugar donde se dispensan medicamentos.", answer: "Farmacia" },
  { id: "culturageneral_F_004", topic: "culturageneral", letter: "F", question: "Con la F: Categoría de partículas en física.", answer: "Fermion" },
  { id: "culturageneral_F_005", topic: "culturageneral", letter: "F", question: "Con la F: Evento cultural o artístico.", answer: "Festival" },
  { id: "culturageneral_F_006", topic: "culturageneral", letter: "F", question: "Con la F: Sucesión matemática famosa.", answer: "Fibonacci" },
  { id: "culturageneral_F_007", topic: "culturageneral", letter: "F", question: "Con la F: Componente vegetal; también en telecomunicaciones.", answer: "Fibra" },
  { id: "culturageneral_F_008", topic: "culturageneral", letter: "F", question: "Con la F: Disciplina que reflexiona sobre conocimiento y existencia.", answer: "Filosofia" },
  { id: "culturageneral_F_009", topic: "culturageneral", letter: "F", question: "Con la F: Ciencia que estudia materia, energía y leyes naturales.", answer: "Fisica" },
  { id: "culturageneral_F_010", topic: "culturageneral", letter: "F", question: "Con la F: Expresión artística andaluza de cante y baile.", answer: "Flamenco" },
  { id: "culturageneral_F_011", topic: "culturageneral", letter: "F", question: "Con la F: Rastro o resto de un ser vivo antiguo.", answer: "Fosil" },
  { id: "culturageneral_F_012", topic: "culturageneral", letter: "F", question: "Con la F: País europeo vecino de España.", answer: "Francia" },
  { id: "culturageneral_F_013", topic: "culturageneral", letter: "F", question: "Con la F: Número de repeticiones por unidad de tiempo.", answer: "Frecuencia" },
  { id: "culturageneral_F_014", topic: "culturageneral", letter: "F", question: "Con la F: Deporte de balón muy popular.", answer: "Futbol" },
  { id: "culturageneral_F_015", topic: "culturageneral", letter: "F", question: "Con la F: Partícula asociada a la luz.", answer: "Foton" },
  { id: "culturageneral_G_001", topic: "culturageneral", letter: "G", question: "Con la G: Arquitecto catalán que diseñó la Sagrada Familia y el Parque Güell en Barcelona.", answer: "Gaudi" },
  { id: "culturageneral_G_002", topic: "culturageneral", letter: "G", question: "Con la G: Conjunto de estrellas, gas y polvo.", answer: "Galaxia" },
  { id: "culturageneral_G_003", topic: "culturageneral", letter: "G", question: "Con la G: Líder indio que lideró la independencia de la India mediante la resistencia pacífica.", answer: "Gandhi" },
  { id: "culturageneral_G_004", topic: "culturageneral", letter: "G", question: "Con la G: Rama de la biología sobre herencia.", answer: "Genetica" },
  { id: "culturageneral_G_005", topic: "culturageneral", letter: "G", question: "Con la G: Ciencia que estudia la Tierra y sus rocas.", answer: "Geologia" },
  { id: "culturageneral_G_006", topic: "culturageneral", letter: "G", question: "Con la G: Rama matemática de formas y espacios.", answer: "Geometria" },
  { id: "culturageneral_G_007", topic: "culturageneral", letter: "G", question: "Con la G: Lugar para ejercicio físico.", answer: "Gimnasio" },
  { id: "culturageneral_G_008", topic: "culturageneral", letter: "G", question: "Con la G: Masa de hielo que se desplaza lentamente.", answer: "Glaciar" },
  { id: "culturageneral_G_009", topic: "culturageneral", letter: "G", question: "Con la G: Objeto esférico; también globo terráqueo.", answer: "Globo" },
  { id: "culturageneral_G_010", topic: "culturageneral", letter: "G", question: "Con la G: Punto en deportes como fútbol.", answer: "Gol" },
  { id: "culturageneral_G_011", topic: "culturageneral", letter: "G", question: "Con la G: Pintor español del siglo XVIII-XIX autor de Los fusilamientos del 3 de mayo y La maja desnuda.", answer: "Goya" },
  { id: "culturageneral_G_012", topic: "culturageneral", letter: "G", question: "Con la G: Fuerza de atracción entre masas.", answer: "Gravedad" },
  { id: "culturageneral_G_013", topic: "culturageneral", letter: "G", question: "Con la G: Lengua y cultura de la antigua Grecia.", answer: "Griego" },
  { id: "culturageneral_G_014", topic: "culturageneral", letter: "G", question: "Con la G: Río andaluz importante.", answer: "Guadalquivir" },
  { id: "culturageneral_G_015", topic: "culturageneral", letter: "G", question: "Con la G: Instrumento de cuerda muy común en España.", answer: "Guitarra" },
  { id: "culturageneral_H_001", topic: "culturageneral", letter: "H", question: "Con la H: Lugar donde vive una especie.", answer: "Habitat" },
  { id: "culturageneral_H_002", topic: "culturageneral", letter: "H", question: "Con la H: Elemento químico más ligero.", answer: "Hidrogeno" },
  { id: "culturageneral_H_003", topic: "culturageneral", letter: "H", question: "Con la H: Agua en estado sólido.", answer: "Hielo" },
  { id: "culturageneral_H_004", topic: "culturageneral", letter: "H", question: "Con la H: Explicación provisional que puede probarse.", answer: "Hipotesis" },
  { id: "culturageneral_H_005", topic: "culturageneral", letter: "H", question: "Con la H: Disciplina que estudia el pasado humano.", answer: "Historia" },
  { id: "culturageneral_H_006", topic: "culturageneral", letter: "H", question: "Con la H: Prácticas para cuidar la salud.", answer: "Higiene" },
  { id: "culturageneral_H_007", topic: "culturageneral", letter: "H", question: "Con la H: Cordillera asiática de gran altitud.", answer: "Himalaya" },
  { id: "culturageneral_H_008", topic: "culturageneral", letter: "H", question: "Con la H: Genocidio sistemático de millones de personas, principalmente judíos, durante la Segunda Guerra Mundial.", answer: "Holocausto" },
  { id: "culturageneral_H_009", topic: "culturageneral", letter: "H", question: "Con la H: Sustancia química mensajera del cuerpo.", answer: "Hormona" },
  { id: "culturageneral_H_010", topic: "culturageneral", letter: "H", question: "Con la H: Centro de atención médica.", answer: "Hospital" },
  { id: "culturageneral_H_011", topic: "culturageneral", letter: "H", question: "Con la H: Tejido del esqueleto.", answer: "Hueso" },
  { id: "culturageneral_H_012", topic: "culturageneral", letter: "H", question: "Con la H: Capacidad de encontrar lo cómico.", answer: "Humor" },
  { id: "culturageneral_H_013", topic: "culturageneral", letter: "H", question: "Con la H: Animal pequeño; también palabra común en zoología.", answer: "Huron" },
  { id: "culturageneral_H_014", topic: "culturageneral", letter: "H", question: "Con la H: Ciclón tropical intenso.", answer: "Huracan" },
  { id: "culturageneral_H_015", topic: "culturageneral", letter: "H", question: "Con la H: Persona con habilidades técnicas; a veces en ciberseguridad.", answer: "Hacker" },
  { id: "culturageneral_I_001", topic: "culturageneral", letter: "I", question: "Con la I: Símbolo o imagen representativa.", answer: "Icono" },
  { id: "culturageneral_I_002", topic: "culturageneral", letter: "I", question: "Con la I: Institución/edificio religioso.", answer: "Iglesia" },
  { id: "culturageneral_I_003", topic: "culturageneral", letter: "I", question: "Con la I: Vivienda de hielo tradicional.", answer: "Igloo" },
  { id: "culturageneral_I_004", topic: "culturageneral", letter: "I", question: "Con la I: Objeto que atrae ciertos metales.", answer: "Iman" },
  { id: "culturageneral_I_005", topic: "culturageneral", letter: "I", question: "Con la I: Movimiento artístico centrado en luz y pincelada.", answer: "Impresionismo" },
  { id: "culturageneral_I_006", topic: "culturageneral", letter: "I", question: "Con la I: Aumento general de precios.", answer: "Inflacion" },
  { id: "culturageneral_I_007", topic: "culturageneral", letter: "I", question: "Con la I: Red global de comunicaciones.", answer: "Internet" },
  { id: "culturageneral_I_008", topic: "culturageneral", letter: "I", question: "Con la I: Animal de seis patas y cuerpo segmentado.", answer: "Insecto" },
  { id: "culturageneral_I_009", topic: "culturageneral", letter: "I", question: "Con la I: Capacidad de aprender y resolver problemas.", answer: "Inteligencia" },
  { id: "culturageneral_I_010", topic: "culturageneral", letter: "I", question: "Con la I: Estación fría del año.", answer: "Invierno" },
  { id: "culturageneral_I_011", topic: "culturageneral", letter: "I", question: "Con la I: País europeo insular.", answer: "Irlanda" },
  { id: "culturageneral_I_012", topic: "culturageneral", letter: "I", question: "Con la I: Variante de un elemento con distinto número de neutrones.", answer: "Isotopo" },
  { id: "culturageneral_I_013", topic: "culturageneral", letter: "I", question: "Con la I: Ciudad romana cerca de Sevilla.", answer: "Italica" },
  { id: "culturageneral_I_014", topic: "culturageneral", letter: "I", question: "Con la I: Aporte de agua a cultivos.", answer: "Irrigacion" },
  { id: "culturageneral_I_015", topic: "culturageneral", letter: "I", question: "Con la I: Capa alta de la atmósfera con partículas ionizadas.", answer: "Ionosfera" },
  { id: "culturageneral_J_001", topic: "culturageneral", letter: "J", question: "Con la J: Producto para limpiar.", answer: "Jabon" },
  { id: "culturageneral_J_002", topic: "culturageneral", letter: "J", question: "Con la J: Respirar rápido tras esfuerzo.", answer: "Jadear" },
  { id: "culturageneral_J_003", topic: "culturageneral", letter: "J", question: "Con la J: Espacio con plantas organizado.", answer: "Jardin" },
  { id: "culturageneral_J_004", topic: "culturageneral", letter: "J", question: "Con la J: Género musical nacido en EE.UU.", answer: "Jazz" },
  { id: "culturageneral_J_005", topic: "culturageneral", letter: "J", question: "Con la J: Organización en niveles.", answer: "Jerarquia" },
  { id: "culturageneral_J_006", topic: "culturageneral", letter: "J", question: "Con la J: Prenda de vestir; también isla europea.", answer: "Jersey" },
  { id: "culturageneral_J_007", topic: "culturageneral", letter: "J", question: "Con la J: Figura central del cristianismo.", answer: "Jesus" },
  { id: "culturageneral_J_008", topic: "culturageneral", letter: "J", question: "Con la J: Mamífero africano de cuello largo.", answer: "Jirafa" },
  { id: "culturageneral_J_009", topic: "culturageneral", letter: "J", question: "Con la J: Día de trabajo o actividad.", answer: "Jornada" },
  { id: "culturageneral_J_010", topic: "culturageneral", letter: "J", question: "Con la J: Planeta más grande del sistema solar.", answer: "Jupiter" },
  { id: "culturageneral_J_011", topic: "culturageneral", letter: "J", question: "Con la J: Promesa solemne.", answer: "Juramento" },
  { id: "culturageneral_J_012", topic: "culturageneral", letter: "J", question: "Con la J: Principio de dar a cada uno lo suyo.", answer: "Justicia" },
  { id: "culturageneral_J_013", topic: "culturageneral", letter: "J", question: "Con la J: Arte marcial japonés.", answer: "Judo" },
  { id: "culturageneral_J_014", topic: "culturageneral", letter: "J", question: "Con la J: Reunión o asamblea.", answer: "Junta" },
  { id: "culturageneral_J_015", topic: "culturageneral", letter: "J", question: "Con la J: Objeto para jugar.", answer: "Juguete" },
  { id: "culturageneral_L_001", topic: "culturageneral", letter: "L", question: "Con la L: Lugar de caminos enredados.", answer: "Laberinto" },
  { id: "culturageneral_L_002", topic: "culturageneral", letter: "L", question: "Con la L: Espacio de experimentación científica.", answer: "Laboratorio" },
  { id: "culturageneral_L_003", topic: "culturageneral", letter: "L", question: "Con la L: Azúcar presente en la leche.", answer: "Lactosa" },
  { id: "culturageneral_L_004", topic: "culturageneral", letter: "L", question: "Con la L: Coordenada geográfica norte-sur.", answer: "Latitud" },
  { id: "culturageneral_L_005", topic: "culturageneral", letter: "L", question: "Con la L: Sistema de comunicación.", answer: "Lenguaje" },
  { id: "culturageneral_L_006", topic: "culturageneral", letter: "L", question: "Con la L: Animal felino; también provincia española.", answer: "Leon" },
  { id: "culturageneral_L_007", topic: "culturageneral", letter: "L", question: "Con la L: Concepto político y filosófico.", answer: "Libertad" },
  { id: "culturageneral_L_008", topic: "culturageneral", letter: "L", question: "Con la L: País del norte de África.", answer: "Libia" },
  { id: "culturageneral_L_009", topic: "culturageneral", letter: "L", question: "Con la L: Felino; especie emblemática ibérica.", answer: "Lince" },
  { id: "culturageneral_L_010", topic: "culturageneral", letter: "L", question: "Con la L: Arte de escribir obras narrativas o poéticas.", answer: "Literatura" },
  { id: "culturageneral_L_011", topic: "culturageneral", letter: "L", question: "Con la L: Función matemática.", answer: "Logaritmo" },
  { id: "culturageneral_L_012", topic: "culturageneral", letter: "L", question: "Con la L: Ciudad capital de Inglaterra y del Reino Unido, ubicada a orillas del río Támesis.", answer: "Londres" },
  { id: "culturageneral_L_013", topic: "culturageneral", letter: "L", question: "Con la L: Satélite natural de la Tierra.", answer: "Luna" },
  { id: "culturageneral_L_014", topic: "culturageneral", letter: "L", question: "Con la L: Enfermedad autoinmune.", answer: "Lupus" },
  { id: "culturageneral_L_015", topic: "culturageneral", letter: "L", question: "Con la L: País europeo pequeño.", answer: "Luxemburgo" },
  { id: "culturageneral_M_001", topic: "culturageneral", letter: "M", question: "Con la M: Capital de España.", answer: "Madrid" },
  { id: "culturageneral_M_002", topic: "culturageneral", letter: "M", question: "Con la M: Fenómeno físico asociado a campos magnéticos.", answer: "Magnetismo" },
  { id: "culturageneral_M_003", topic: "culturageneral", letter: "M", question: "Con la M: Enfermedad transmitida por mosquitos.", answer: "Malaria" },
  { id: "culturageneral_M_004", topic: "culturageneral", letter: "M", question: "Con la M: Carrera de larga distancia.", answer: "Maraton" },
  { id: "culturageneral_M_005", topic: "culturageneral", letter: "M", question: "Con la M: Planeta rojo.", answer: "Marte" },
  { id: "culturageneral_M_006", topic: "culturageneral", letter: "M", question: "Con la M: Todo lo que tiene masa y ocupa espacio.", answer: "Materia" },
  { id: "culturageneral_M_007", topic: "culturageneral", letter: "M", question: "Con la M: Persona que apoya a artistas.", answer: "Mecenas" },
  { id: "culturageneral_M_008", topic: "culturageneral", letter: "M", question: "Con la M: Ciencia de la salud y tratamiento de enfermedades.", answer: "Medicina" },
  { id: "culturageneral_M_009", topic: "culturageneral", letter: "M", question: "Con la M: Capacidad de almacenar información.", answer: "Memoria" },
  { id: "culturageneral_M_010", topic: "culturageneral", letter: "M", question: "Con la M: Organismo microscópico.", answer: "Microbio" },
  { id: "culturageneral_M_011", topic: "culturageneral", letter: "M", question: "Con la M: Dolor de cabeza intenso recurrente.", answer: "Migraña" },
  { id: "culturageneral_M_012", topic: "culturageneral", letter: "M", question: "Con la M: Proceso de división celular.", answer: "Mitosis" },
  { id: "culturageneral_M_013", topic: "culturageneral", letter: "M", question: "Con la M: Sistema político con rey o reina.", answer: "Monarquia" },
  { id: "culturageneral_M_014", topic: "culturageneral", letter: "M", question: "Con la M: Institución que conserva y exhibe objetos.", answer: "Museo" },
  { id: "culturageneral_M_015", topic: "culturageneral", letter: "M", question: "Con la M: Arte de combinar sonidos.", answer: "Musica" },
  { id: "culturageneral_N_001", topic: "culturageneral", letter: "N", question: "Con la N: Comunidad política/cultural con identidad.", answer: "Nacion" },
  { id: "culturageneral_N_002", topic: "culturageneral", letter: "N", question: "Con la N: Fruta cítrica.", answer: "Naranja" },
  { id: "culturageneral_N_003", topic: "culturageneral", letter: "N", question: "Con la N: Agencia espacial de EE.UU.", answer: "NASA" },
  { id: "culturageneral_N_004", topic: "culturageneral", letter: "N", question: "Con la N: Desplazamiento y orientación por mar/aire.", answer: "Navegacion" },
  { id: "culturageneral_N_005", topic: "culturageneral", letter: "N", question: "Con la N: Célula del sistema nervioso.", answer: "Neurona" },
  { id: "culturageneral_N_006", topic: "culturageneral", letter: "N", question: "Con la N: Partícula subatómica sin carga.", answer: "Neutron" },
  { id: "culturageneral_N_007", topic: "culturageneral", letter: "N", question: "Con la N: Río africano emblemático.", answer: "Nilo" },
  { id: "culturageneral_N_008", topic: "culturageneral", letter: "N", question: "Con la N: Premio internacional en ciencias, literatura y paz.", answer: "Nobel" },
  { id: "culturageneral_N_009", topic: "culturageneral", letter: "N", question: "Con la N: Regla que guía conducta.", answer: "Norma" },
  { id: "culturageneral_N_010", topic: "culturageneral", letter: "N", question: "Con la N: Información sobre un hecho.", answer: "Noticia" },
  { id: "culturageneral_N_011", topic: "culturageneral", letter: "N", question: "Con la N: Conjunto visible de gotas/hielo en la atmósfera.", answer: "Nube" },
  { id: "culturageneral_N_012", topic: "culturageneral", letter: "N", question: "Con la N: Proceso de obtener y usar nutrientes.", answer: "Nutricion" },
  { id: "culturageneral_N_013", topic: "culturageneral", letter: "N", question: "Con la N: Polímero sintético usado en textiles.", answer: "Nylon" },
  { id: "culturageneral_N_014", topic: "culturageneral", letter: "N", question: "Con la N: Figura mitológica; también concepto cultural.", answer: "Narciso" },
  { id: "culturageneral_N_015", topic: "culturageneral", letter: "N", question: "Con la N: Molusco; también símbolo cultural de exploración.", answer: "Nautilus" },
  { id: "culturageneral_Ñ_001", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: País europeo.", answer: "España" },
  { id: "culturageneral_Ñ_002", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Indicador visual o acústico.", answer: "Señal" },
  { id: "culturageneral_Ñ_003", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Grupo o roca.", answer: "Peña" },
  { id: "culturageneral_Ñ_004", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Valle profundo.", answer: "Cañon" },
  { id: "culturageneral_Ñ_005", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Unidad de tiempo.", answer: "Año" },
  { id: "culturageneral_Ñ_006", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Etapa de la vida.", answer: "Niñez" },
  { id: "culturageneral_Ñ_007", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Proceso de descanso.", answer: "Sueño" },
  { id: "culturageneral_Ñ_008", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Articulación o juguete.", answer: "Muñeca" },
  { id: "culturageneral_Ñ_009", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Objeto festivo.", answer: "Piñata" },
  { id: "culturageneral_Ñ_010", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Proceso educativo.", answer: "Enseñanza" },
  { id: "culturageneral_Ñ_011", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Empresa o grupo.", answer: "Compañia" },
  { id: "culturageneral_Ñ_012", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Tratamiento.", answer: "Señora" },
  { id: "culturageneral_Ñ_013", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Relieve elevado.", answer: "Montaña" },
  { id: "culturageneral_Ñ_014", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: Lugar para higiene.", answer: "Baño" },
  { id: "culturageneral_Ñ_015", topic: "culturageneral", letter: "Ñ", question: "Contiene la Ñ: De tamaño reducido.", answer: "Pequeño" },
  { id: "culturageneral_O_001", topic: "culturageneral", letter: "O", question: "Con la O: Gran masa de agua salada.", answer: "Oceano" },
  { id: "culturageneral_O_002", topic: "culturageneral", letter: "O", question: "Con la O: Mes del calendario.", answer: "Octubre" },
  { id: "culturageneral_O_003", topic: "culturageneral", letter: "O", question: "Con la O: Poema épico atribuido a Homero.", answer: "Odisea" },
  { id: "culturageneral_O_004", topic: "culturageneral", letter: "O", question: "Con la O: Sentido de detectar olores.", answer: "Olfato" },
  { id: "culturageneral_O_005", topic: "culturageneral", letter: "O", question: "Con la O: Miembro de una oligarquía.", answer: "Oligarca" },
  { id: "culturageneral_O_006", topic: "culturageneral", letter: "O", question: "Con la O: Grandes competiciones deportivas internacionales.", answer: "Olimpiadas" },
  { id: "culturageneral_O_007", topic: "culturageneral", letter: "O", question: "Con la O: Género musical teatral.", answer: "Opera" },
  { id: "culturageneral_O_008", topic: "culturageneral", letter: "O", question: "Con la O: Rama de física de la luz.", answer: "Optica" },
  { id: "culturageneral_O_009", topic: "culturageneral", letter: "O", question: "Con la O: Trayectoria de un cuerpo celeste.", answer: "Orbita" },
  { id: "culturageneral_O_010", topic: "culturageneral", letter: "O", question: "Con la O: Ser vivo o entidad biológica.", answer: "Organismo" },
  { id: "culturageneral_O_011", topic: "culturageneral", letter: "O", question: "Con la O: Punto de inicio.", answer: "Origen" },
  { id: "culturageneral_O_012", topic: "culturageneral", letter: "O", question: "Con la O: Gas atmosférico que protege de radiación UV.", answer: "Ozono" },
  { id: "culturageneral_O_013", topic: "culturageneral", letter: "O", question: "Con la O: Metal precioso.", answer: "Oro" },
  { id: "culturageneral_O_014", topic: "culturageneral", letter: "O", question: "Con la O: Estación del año.", answer: "Otoño" },
  { id: "culturageneral_O_015", topic: "culturageneral", letter: "O", question: "Con la O: Gas esencial para respiración.", answer: "Oxigeno" },
  { id: "culturageneral_P_001", topic: "culturageneral", letter: "P", question: "Con la P: Unidad lingüística con significado.", answer: "Palabra" },
  { id: "culturageneral_P_002", topic: "culturageneral", letter: "P", question: "Con la P: Institución legislativa.", answer: "Parlamento" },
  { id: "culturageneral_P_003", topic: "culturageneral", letter: "P", question: "Con la P: Unidad pequeña en física o química.", answer: "Particula" },
  { id: "culturageneral_P_004", topic: "culturageneral", letter: "P", question: "Con la P: Bien cultural de una sociedad.", answer: "Patrimonio" },
  { id: "culturageneral_P_005", topic: "culturageneral", letter: "P", question: "Con la P: Obra audiovisual de cine.", answer: "Pelicula" },
  { id: "culturageneral_P_006", topic: "culturageneral", letter: "P", question: "Con la P: Tierra rodeada de agua casi por completo.", answer: "Peninsula" },
  { id: "culturageneral_P_007", topic: "culturageneral", letter: "P", question: "Con la P: Zona alejada del centro.", answer: "Periferia" },
  { id: "culturageneral_P_008", topic: "culturageneral", letter: "P", question: "Con la P: Construcción monumental de base ancha.", answer: "Piramide" },
  { id: "culturageneral_P_009", topic: "culturageneral", letter: "P", question: "Con la P: Cuerpo que orbita una estrella.", answer: "Planeta" },
  { id: "culturageneral_P_010", topic: "culturageneral", letter: "P", question: "Con la P: Material polimérico común.", answer: "Plastico" },
  { id: "culturageneral_P_011", topic: "culturageneral", letter: "P", question: "Con la P: Género literario en verso.", answer: "Poesia" },
  { id: "culturageneral_P_012", topic: "culturageneral", letter: "P", question: "Con la P: Gestión del poder y lo público.", answer: "Politica" },
  { id: "culturageneral_P_013", topic: "culturageneral", letter: "P", question: "Con la P: Forma de expresar una proporción.", answer: "Porcentaje" },
  { id: "culturageneral_P_014", topic: "culturageneral", letter: "P", question: "Con la P: Reconocimiento otorgado.", answer: "Premio" },
  { id: "culturageneral_P_015", topic: "culturageneral", letter: "P", question: "Con la P: Macromolécula esencial en seres vivos.", answer: "Proteina" },
  { id: "culturageneral_Q_001", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Caballero andante protagonista de la novela más famosa de la literatura española.", answer: "Quijote" },
  { id: "culturageneral_Q_002", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Ciencia de sustancias y reacciones.", answer: "Quimica" },
  { id: "culturageneral_Q_003", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Alimento derivado de la leche.", answer: "Queso" },
  { id: "culturageneral_Q_004", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Partícula fundamental.", answer: "Quark" },
  { id: "culturageneral_Q_005", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Número mínimo para votar.", answer: "Quorum" },
  { id: "culturageneral_Q_006", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Propiedad de campo.", answer: "Quinta" },
  { id: "culturageneral_Q_007", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Ave símbolo de Guatemala.", answer: "Quetzal" },
  { id: "culturageneral_Q_008", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Sala de operaciones.", answer: "Quirofano" },
  { id: "culturageneral_Q_009", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Periodo de quince días.", answer: "Quincena" },
  { id: "culturageneral_Q_010", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Sustancia usada contra malaria.", answer: "Quinina" },
  { id: "culturageneral_Q_011", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Pseudocereal.", answer: "Quinoa" },
  { id: "culturageneral_Q_012", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Estado de balance.", answer: "Equilibrio" },
  { id: "culturageneral_Q_013", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Reserva subterránea de agua.", answer: "Aquifero" },
  { id: "culturageneral_Q_014", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Objeto astronómico muy energético.", answer: "Quasar" },
  { id: "culturageneral_Q_015", topic: "culturageneral", letter: "Q", question: "Contiene la Q: Sistema andino de cuerdas para registrar datos.", answer: "Quipu" },
  { id: "culturageneral_R_001", topic: "culturageneral", letter: "R", question: "Con la R: Medio de comunicación por ondas.", answer: "Radio" },
  { id: "culturageneral_R_002", topic: "culturageneral", letter: "R", question: "Con la R: Capacidad de pensar lógicamente.", answer: "Razon" },
  { id: "culturageneral_R_003", topic: "culturageneral", letter: "R", question: "Con la R: Instrucciones para cocinar o prescripción médica.", answer: "Receta" },
  { id: "culturageneral_R_004", topic: "culturageneral", letter: "R", question: "Con la R: Proceso de reutilizar materiales.", answer: "Reciclaje" },
  { id: "culturageneral_R_005", topic: "culturageneral", letter: "R", question: "Con la R: Cambio o mejora estructural.", answer: "Reforma" },
  { id: "culturageneral_R_006", topic: "culturageneral", letter: "R", question: "Con la R: Entidad política gobernada por monarca.", answer: "Reino" },
  { id: "culturageneral_R_007", topic: "culturageneral", letter: "R", question: "Con la R: Instrumento para medir el tiempo.", answer: "Reloj" },
  { id: "culturageneral_R_008", topic: "culturageneral", letter: "R", question: "Con la R: Periodo cultural europeo.", answer: "Renacimiento" },
  { id: "culturageneral_R_009", topic: "culturageneral", letter: "R", question: "Con la R: Sustancia orgánica viscosa de plantas.", answer: "Resina" },
  { id: "culturageneral_R_010", topic: "culturageneral", letter: "R", question: "Con la R: Cambio profundo en sociedad o política.", answer: "Revolucion" },
  { id: "culturageneral_R_011", topic: "culturageneral", letter: "R", question: "Con la R: Orgánulo que fabrica proteínas.", answer: "Ribosoma" },
  { id: "culturageneral_R_012", topic: "culturageneral", letter: "R", question: "Con la R: Probabilidad de daño o pérdida.", answer: "Riesgo" },
  { id: "culturageneral_R_013", topic: "culturageneral", letter: "R", question: "Con la R: Patrón de repetición en música o movimiento.", answer: "Ritmo" },
  { id: "culturageneral_R_014", topic: "culturageneral", letter: "R", question: "Con la R: Máquina programable.", answer: "Robot" },
  { id: "culturageneral_R_015", topic: "culturageneral", letter: "R", question: "Con la R: Símbolo de alfabetos antiguos.", answer: "Runa" },
  { id: "culturageneral_S_001", topic: "culturageneral", letter: "S", question: "Con la S: Estado de bienestar físico y mental.", answer: "Salud" },
  { id: "culturageneral_S_002", topic: "culturageneral", letter: "S", question: "Con la S: Cuerpo que orbita un planeta.", answer: "Satelite" },
  { id: "culturageneral_S_003", topic: "culturageneral", letter: "S", question: "Con la S: Conflicto mundial 1939–1945.", answer: "SegundaGuerra" },
  { id: "culturageneral_S_004", topic: "culturageneral", letter: "S", question: "Con la S: Cámara legislativa en algunos países.", answer: "Senado" },
  { id: "culturageneral_S_005", topic: "culturageneral", letter: "S", question: "Con la S: Neurotransmisor relacionado con estado de ánimo.", answer: "Serotonina" },
  { id: "culturageneral_S_006", topic: "culturageneral", letter: "S", question: "Con la S: Elemento clave en electrónica.", answer: "Silicio" },
  { id: "culturageneral_S_007", topic: "culturageneral", letter: "S", question: "Con la S: Conjunto de elementos que interactúan.", answer: "Sistema" },
  { id: "culturageneral_S_008", topic: "culturageneral", letter: "S", question: "Con la S: Terremoto.", answer: "Sismo" },
  { id: "culturageneral_S_009", topic: "culturageneral", letter: "S", question: "Con la S: Conjunto de personas que conviven.", answer: "Sociedad" },
  { id: "culturageneral_S_010", topic: "culturageneral", letter: "S", question: "Con la S: Estrella del sistema solar.", answer: "Sol" },
  { id: "culturageneral_S_011", topic: "culturageneral", letter: "S", question: "Con la S: Zona sin luz directa.", answer: "Sombra" },
  { id: "culturageneral_S_012", topic: "culturageneral", letter: "S", question: "Con la S: Embarcación que navega bajo el agua.", answer: "Submarino" },
  { id: "culturageneral_S_013", topic: "culturageneral", letter: "S", question: "Con la S: Derecho de voto.", answer: "Sufragio" },
  { id: "culturageneral_S_014", topic: "culturageneral", letter: "S", question: "Con la S: Movimiento artístico del siglo XX.", answer: "Surrealismo" },
  { id: "culturageneral_S_015", topic: "culturageneral", letter: "S", question: "Con la S: Tejido líquido del cuerpo.", answer: "Sangre" },
  { id: "culturageneral_T_001", topic: "culturageneral", letter: "T", question: "Con la T: Clasificación de elementos químicos.", answer: "TablaPeriodica" },
  { id: "culturageneral_T_002", topic: "culturageneral", letter: "T", question: "Con la T: Procesos de placas terrestres.", answer: "Tectonica" },
  { id: "culturageneral_T_003", topic: "culturageneral", letter: "T", question: "Con la T: Proposición demostrable en matemáticas.", answer: "Teorema" },
  { id: "culturageneral_T_004", topic: "culturageneral", letter: "T", question: "Con la T: Instrumento para medir temperatura.", answer: "Termometro" },
  { id: "culturageneral_T_005", topic: "culturageneral", letter: "T", question: "Con la T: Arte escénico de interpretación.", answer: "Teatro" },
  { id: "culturageneral_T_006", topic: "culturageneral", letter: "T", question: "Con la T: Dispositivo de comunicación a distancia.", answer: "Telefono" },
  { id: "culturageneral_T_007", topic: "culturageneral", letter: "T", question: "Con la T: Medio audiovisual.", answer: "Television" },
  { id: "culturageneral_T_008", topic: "culturageneral", letter: "T", question: "Con la T: Instrumento para observar objetos lejanos.", answer: "Telescopio" },
  { id: "culturageneral_T_009", topic: "culturageneral", letter: "T", question: "Con la T: Planeta donde vivimos.", answer: "Tierra" },
  { id: "culturageneral_T_010", topic: "culturageneral", letter: "T", question: "Con la T: Magnitud física; también meteorología.", answer: "Tiempo" },
  { id: "culturageneral_T_011", topic: "culturageneral", letter: "T", question: "Con la T: Aceptación de diferencias.", answer: "Tolerancia" },
  { id: "culturageneral_T_012", topic: "culturageneral", letter: "T", question: "Con la T: Vórtice atmosférico.", answer: "Tornado" },
  { id: "culturageneral_T_013", topic: "culturageneral", letter: "T", question: "Con la T: Costumbre transmitida.", answer: "Tradicion" },
  { id: "culturageneral_T_014", topic: "culturageneral", letter: "T", question: "Con la T: Medios para mover personas o bienes.", answer: "Transporte" },
  { id: "culturageneral_T_015", topic: "culturageneral", letter: "T", question: "Con la T: Figura geométrica de tres lados.", answer: "Triangulo" },
  { id: "culturageneral_U_001", topic: "culturageneral", letter: "U", question: "Con la U: País europeo del este.", answer: "Ucrania" },
  { id: "culturageneral_U_002", topic: "culturageneral", letter: "U", question: "Con la U: Radiación más allá del violeta.", answer: "Ultravioleta" },
  { id: "culturageneral_U_003", topic: "culturageneral", letter: "U", question: "Con la U: Institución de educación superior.", answer: "Universidad" },
  { id: "culturageneral_U_004", topic: "culturageneral", letter: "U", question: "Con la U: Conjunto de todo lo que existe.", answer: "Universo" },
  { id: "culturageneral_U_005", topic: "culturageneral", letter: "U", question: "Con la U: Planeta del sistema solar.", answer: "Urano" },
  { id: "culturageneral_U_006", topic: "culturageneral", letter: "U", question: "Con la U: Recipiente; también en votaciones.", answer: "Urna" },
  { id: "culturageneral_U_007", topic: "culturageneral", letter: "U", question: "Con la U: Persona que usa un sistema o servicio.", answer: "Usuario" },
  { id: "culturageneral_U_008", topic: "culturageneral", letter: "U", question: "Con la U: Idea de sociedad ideal.", answer: "Utopia" },
  { id: "culturageneral_U_009", topic: "culturageneral", letter: "U", question: "Con la U: Planificación de ciudades.", answer: "Urbanismo" },
  { id: "culturageneral_U_010", topic: "culturageneral", letter: "U", question: "Con la U: Situación que requiere atención inmediata.", answer: "Urgencia" },
  { id: "culturageneral_U_011", topic: "culturageneral", letter: "U", question: "Con la U: Estructura en la garganta.", answer: "Uvula" },
  { id: "culturageneral_U_012", topic: "culturageneral", letter: "U", question: "Con la U: Ave común en Europa.", answer: "Urraca" },
  { id: "culturageneral_U_013", topic: "culturageneral", letter: "U", question: "Con la U: Compuesto del metabolismo.", answer: "Urea" },
  { id: "culturageneral_U_014", topic: "culturageneral", letter: "U", question: "Con la U: Cobro abusivo de intereses.", answer: "Usura" },
  { id: "culturageneral_U_015", topic: "culturageneral", letter: "U", question: "Con la U: Valor o provecho de algo.", answer: "Utilidad" },
  { id: "culturageneral_V_001", topic: "culturageneral", letter: "V", question: "Con la V: Preparado que ayuda a prevenir enfermedades.", answer: "Vacuna" },
  { id: "culturageneral_V_002", topic: "culturageneral", letter: "V", question: "Con la V: Ciudad española mediterránea.", answer: "Valencia" },
  { id: "culturageneral_V_003", topic: "culturageneral", letter: "V", question: "Con la V: Entidad matemática con dirección y magnitud.", answer: "Vector" },
  { id: "culturageneral_V_004", topic: "culturageneral", letter: "V", question: "Con la V: Rapidez con dirección; concepto físico.", answer: "Velocidad" },
  { id: "culturageneral_V_005", topic: "culturageneral", letter: "V", question: "Con la V: Planeta vecino de la Tierra.", answer: "Venus" },
  { id: "culturageneral_V_006", topic: "culturageneral", letter: "V", question: "Con la V: Conformidad con los hechos.", answer: "Verdad" },
  { id: "culturageneral_V_007", topic: "culturageneral", letter: "V", question: "Con la V: Hueso de la columna vertebral.", answer: "Vertebra" },
  { id: "culturageneral_V_008", topic: "culturageneral", letter: "V", question: "Con la V: Pueblos nórdicos medievales.", answer: "Vikingos" },
  { id: "culturageneral_V_009", topic: "culturageneral", letter: "V", question: "Con la V: Instrumento de cuerda frotada.", answer: "Violin" },
  { id: "culturageneral_V_010", topic: "culturageneral", letter: "V", question: "Con la V: Agente infeccioso submicroscópico.", answer: "Virus" },
  { id: "culturageneral_V_011", topic: "culturageneral", letter: "V", question: "Con la V: Conjunto de palabras conocidas.", answer: "Vocabulario" },
  { id: "culturageneral_V_012", topic: "culturageneral", letter: "V", question: "Con la V: Abertura que expulsa lava y gases.", answer: "Volcan" },
  { id: "culturageneral_V_013", topic: "culturageneral", letter: "V", question: "Con la V: Medida del espacio que ocupa un cuerpo.", answer: "Volumen" },
  { id: "culturageneral_V_014", topic: "culturageneral", letter: "V", question: "Con la V: Acto de elegir en una elección.", answer: "Voto" },
  { id: "culturageneral_V_015", topic: "culturageneral", letter: "V", question: "Con la V: Cera con mecha; también vela náutica.", answer: "Vela" },
  { id: "culturageneral_X_001", topic: "culturageneral", letter: "X", question: "Contiene la X: Prueba escrita u oral para evaluar conocimientos o competencias de una persona.", answer: "Examen" },
  { id: "culturageneral_X_002", topic: "culturageneral", letter: "X", question: "Contiene la X: Resultado positivo o logro de un objetivo, especialmente en el ámbito profesional o artístico.", answer: "Exito" },
  { id: "culturageneral_X_003", topic: "culturageneral", letter: "X", question: "Contiene la X: Conjunto de palabras escritas que forman un escrito, documento o mensaje.", answer: "Texto" },
  { id: "culturageneral_X_004", topic: "culturageneral", letter: "X", question: "Contiene la X: Salida forzada de un país.", answer: "Exilio" },
  { id: "culturageneral_X_005", topic: "culturageneral", letter: "X", question: "Contiene la X: Deporte de combate.", answer: "Boxeo" },
  { id: "culturageneral_X_006", topic: "culturageneral", letter: "X", question: "Contiene la X: Unidad de imagen digital.", answer: "Pixel" },
  { id: "culturageneral_X_007", topic: "culturageneral", letter: "X", question: "Contiene la X: Marco de una situación.", answer: "Contexto" },
  { id: "culturageneral_X_008", topic: "culturageneral", letter: "X", question: "Contiene la X: Liberación brusca de energía.", answer: "Explosion" },
  { id: "culturageneral_X_009", topic: "culturageneral", letter: "X", question: "Contiene la X: Rito de expulsión de supuestos espíritus.", answer: "Exorcismo" },
  { id: "culturageneral_X_010", topic: "culturageneral", letter: "X", question: "Contiene la X: Estado de intensa emoción.", answer: "Extasis" },
  { id: "culturageneral_X_011", topic: "culturageneral", letter: "X", question: "Contiene la X: Documento o sección adicional que se adjunta a un texto principal para complementar información.", answer: "Anexo" },
  { id: "culturageneral_X_012", topic: "culturageneral", letter: "X", question: "Contiene la X: Gas vital.", answer: "Oxigeno" },
  { id: "culturageneral_X_013", topic: "culturageneral", letter: "X", question: "Contiene la X: Instrumento musical de láminas.", answer: "Xilofono" },
  { id: "culturageneral_X_014", topic: "culturageneral", letter: "X", question: "Contiene la X: Grabado en madera.", answer: "Xilografia" },
  { id: "culturageneral_X_015", topic: "culturageneral", letter: "X", question: "Contiene la X: Gas noble usado en lámparas y flashes.", answer: "Xenon" },
  { id: "culturageneral_Y_001", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Acción de prestar apoyo, auxilio o colaboración a alguien que lo necesita.", answer: "Ayuda" },
  { id: "culturageneral_Y_002", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Título de soberanía masculino que designa al jefe de estado en una monarquía.", answer: "Rey" },
  { id: "culturageneral_Y_003", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Adverbio que se refiere al día presente, al momento actual.", answer: "Hoy" },
  { id: "culturageneral_Y_004", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Quinto mes del año en el calendario gregoriano, entre abril y junio.", answer: "Mayo" },
  { id: "culturageneral_Y_005", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Extensión de arena o grava en la orilla del mar, lago o río donde la gente se baña y toma el sol.", answer: "Playa" },
  { id: "culturageneral_Y_006", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Toro castrado usado tradicionalmente para trabajos agrícolas y transporte.", answer: "Buey" },
  { id: "culturageneral_Y_007", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Bastón largo con la parte superior curvada usado tradicionalmente por pastores para guiar ovejas.", answer: "Cayado" },
  { id: "culturageneral_Y_008", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Prueba o experimento previo para verificar algo, o género literario en prosa.", answer: "Ensayo" },
  { id: "culturageneral_Y_009", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Norma jurídica de carácter obligatorio aprobada por el poder legislativo de un Estado.", answer: "Ley" },
  { id: "culturageneral_Y_010", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Elemento químico halógeno esencial para la función tiroidea, presente en la sal yodada.", answer: "Yodo" },
  { id: "culturageneral_Y_011", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Disciplina física y mental originaria de la India que combina posturas, respiración y meditación.", answer: "Yoga" },
  { id: "culturageneral_Y_012", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Parte más numerosa de un grupo o conjunto, más de la mitad de los elementos.", answer: "Mayoria" },
  { id: "culturageneral_Y_013", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Descarga eléctrica atmosférica visible durante las tormentas, que va de las nubes al suelo.", answer: "Rayos" },
  { id: "culturageneral_Y_014", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Trozo de tela o material absorbente usado para limpiar superficies y quitar el polvo.", answer: "Bayeta" },
  { id: "culturageneral_Y_015", topic: "culturageneral", letter: "Y", question: "Contiene la Y: Bloque de hierro macizo sobre el que los herreros martillean y dan forma al metal caliente.", answer: "Yunque" },
  { id: "culturageneral_Z_001", topic: "culturageneral", letter: "Z", question: "Con la Z: Ciudad española en el valle del Ebro.", answer: "Zaragoza" },
  { id: "culturageneral_Z_002", topic: "culturageneral", letter: "Z", question: "Con la Z: Mamífero africano de la familia de los équidos con rayas blancas y negras características.", answer: "Zebra" },
  { id: "culturageneral_Z_003", topic: "culturageneral", letter: "Z", question: "Con la Z: Provincia holandesa que dio nombre a un país insular del Pacífico Sur.", answer: "Zelanda" },
  { id: "culturageneral_Z_004", topic: "culturageneral", letter: "Z", question: "Con la Z: Escuela de budismo mahayana originaria de China que enfatiza la meditación y la experiencia directa.", answer: "Zen" },
  { id: "culturageneral_Z_005", topic: "culturageneral", letter: "Z", question: "Con la Z: Punto más alto en el cielo sobre el observador.", answer: "Zenit" },
  { id: "culturageneral_Z_006", topic: "culturageneral", letter: "Z", question: "Con la Z: Elemento químico metálico de número atómico 30, usado en galvanización y aleaciones.", answer: "Zinc" },
  { id: "culturageneral_Z_007", topic: "culturageneral", letter: "Z", question: "Con la Z: Franja celeste dividida en signos.", answer: "Zodiaco" },
  { id: "culturageneral_Z_008", topic: "culturageneral", letter: "Z", question: "Con la Z: Mamífero carnívoro de la familia de los cánidos, conocido por su astucia y cola espesa.", answer: "Zorro" },
  { id: "culturageneral_Z_009", topic: "culturageneral", letter: "Z", question: "Con la Z: Líquido obtenido al exprimir o licuar frutas, rico en vitaminas y azúcares naturales.", answer: "Zumo" },
  { id: "culturageneral_Z_010", topic: "culturageneral", letter: "Z", question: "Con la Z: Espacio o territorio delimitado con características específicas, como zona horaria o zona climática.", answer: "Zona" },
  { id: "culturageneral_Z_011", topic: "culturageneral", letter: "Z", question: "Con la Z: Calzado ligero y cómodo con suela flexible, usado para deporte o uso casual.", answer: "Zapatilla" },
  { id: "culturageneral_Z_012", topic: "culturageneral", letter: "Z", question: "Con la Z: Sonido continuo como el de insectos.", answer: "Zumbido" },
  { id: "culturageneral_Z_013", topic: "culturageneral", letter: "Z", question: "Con la Z: Género escénico musical español.", answer: "Zarzuela" },
  { id: "culturageneral_Z_014", topic: "culturageneral", letter: "Z", question: "Con la Z: Surco o foso largo y estrecho excavado en el terreno para drenaje, cables o tuberías.", answer: "Zanja" },
  { id: "culturageneral_Z_015", topic: "culturageneral", letter: "Z", question: "Con la Z: Gema preciosa de color azul intenso, variedad del corindón, usada en joyería.", answer: "Zafiro" },
];
