import type { QA } from "./types";

export const DEPORTE: QA[] = [
  { id: "deporte_A_001", topic: "deporte", letter: "A", question: "Con la A: Deporte de carreras, saltos y lanzamientos en pista y campo.", answer: "Atletismo" },
  { id: "deporte_A_002", topic: "deporte", letter: "A", question: "Con la A: Juego-deporte de estrategia reconocido por federaciones deportivas.", answer: "Ajedrez" },
  { id: "deporte_A_003", topic: "deporte", letter: "A", question: "Con la A: Persona que aplica el reglamento durante un partido o combate.", answer: "Arbitro" },
  { id: "deporte_A_004", topic: "deporte", letter: "A", question: "Con la A: Elemento del baloncesto por el que entra la pelota para anotar.", answer: "Aro" },
  { id: "deporte_A_005", topic: "deporte", letter: "A", question: "Con la A: Acción de sumar puntos o goles en un marcador.", answer: "Anotar" },
  { id: "deporte_A_006", topic: "deporte", letter: "A", question: "Con la A: Deporte de montaña que implica ascender picos y rutas técnicas.", answer: "Alpinismo" },
  { id: "deporte_A_007", topic: "deporte", letter: "A", question: "Con la A: Entrenamiento aeróbico coreografiado con música.", answer: "Aerobics" },
  { id: "deporte_A_008", topic: "deporte", letter: "A", question: "Con la A: Capacidad física de cambiar de dirección rápido y con control.", answer: "Agilidad" },
  { id: "deporte_A_009", topic: "deporte", letter: "A", question: "Con la A: Lista de jugadores que inician un partido.", answer: "Alineacion" },
  { id: "deporte_A_010", topic: "deporte", letter: "A", question: "Con la A: Tarjeta de amonestación en fútbol.", answer: "Amarilla" },
  { id: "deporte_A_011", topic: "deporte", letter: "A", question: "Con la A: Deporte de tiro con arco a un blanco.", answer: "Arqueria" },
  { id: "deporte_A_012", topic: "deporte", letter: "A", question: "Con la A: Disciplina de buceo a pulmón sin equipo de respiración.", answer: "Apnea" },
  { id: "deporte_A_013", topic: "deporte", letter: "A", question: "Con la A: Conjunto de controles para detectar sustancias prohibidas.", answer: "Antidoping" },
  { id: "deporte_A_014", topic: "deporte", letter: "A", question: "Con la A: Pase que facilita un gol o canasta.", answer: "Asistencia" },
  { id: "deporte_A_015", topic: "deporte", letter: "A", question: "Con la A: Aumento rápido de velocidad, clave en sprints.", answer: "Aceleracion" },
  { id: "deporte_B_001", topic: "deporte", letter: "B", question: "Con la B: Deporte de equipo donde se anota encestando en un aro.", answer: "Baloncesto" },
  { id: "deporte_B_002", topic: "deporte", letter: "B", question: "Con la B: Deporte con bate y pelota, muy popular en América y Asia.", answer: "Beisbol" },
  { id: "deporte_B_003", topic: "deporte", letter: "B", question: "Con la B: Objeto esférico usado en muchos deportes, del fútbol al handball.", answer: "Balon" },
  { id: "deporte_B_004", topic: "deporte", letter: "B", question: "Con la B: Deporte de combate con puños y guantes.", answer: "Boxeo" },
  { id: "deporte_B_005", topic: "deporte", letter: "B", question: "Con la B: Deporte de raqueta con volante .", answer: "Badminton" },
  { id: "deporte_B_006", topic: "deporte", letter: "B", question: "Con la B: Vehículo básico del ciclismo.", answer: "Bicicleta" },
  { id: "deporte_B_007", topic: "deporte", letter: "B", question: "Con la B: Estilo de natación con patada y brazada simétricas estilo pecho.", answer: "Braza" },
  { id: "deporte_B_008", topic: "deporte", letter: "B", question: "Con la B: Calzado deportivo, especialmente en fútbol.", answer: "Bota" },
  { id: "deporte_B_009", topic: "deporte", letter: "B", question: "Con la B: En España, muchas canteras nacen en clubes locales.", answer: "Barrio" },
  { id: "deporte_B_010", topic: "deporte", letter: "B", question: "Con la B: Señal final en baloncesto que marca el final del tiempo.", answer: "Buzzer" },
  { id: "deporte_B_011", topic: "deporte", letter: "B", question: "Con la B: Deporte de equipo que se juega con la mano y portería.", answer: "Balonmano" },
  { id: "deporte_B_012", topic: "deporte", letter: "B", question: "Con la B: Acción de golpear la pelota en béisbol.", answer: "Bateo" },
  { id: "deporte_B_013", topic: "deporte", letter: "B", question: "Con la B: Deporte de invierno de trineo rápido en pista de hielo.", answer: "Bobsleigh" },
  { id: "deporte_B_014", topic: "deporte", letter: "B", question: "Con la B: Modalidad de ciclismo BMX en circuito corto con saltos.", answer: "Bicicross" },
  { id: "deporte_B_015", topic: "deporte", letter: "B", question: "Con la B: Apellido del velocista jamaicano que estableció récords mundiales en 100 y 200 metros.", answer: "Bolt" },
  { id: "deporte_C_001", topic: "deporte", letter: "C", question: "Con la C: Deporte de competición en bicicleta .", answer: "Ciclismo" },
  { id: "deporte_C_002", topic: "deporte", letter: "C", question: "Con la C: Prueba de velocidad o resistencia en muchos deportes.", answer: "Carrera" },
  { id: "deporte_C_003", topic: "deporte", letter: "C", question: "Con la C: Anotación de baloncesto; también se usa para el aro y su red.", answer: "Canasta" },
  { id: "deporte_C_004", topic: "deporte", letter: "C", question: "Con la C: Saque de esquina en fútbol.", answer: "Corner" },
  { id: "deporte_C_005", topic: "deporte", letter: "C", question: "Con la C: Jugador que lidera al equipo y representa al grupo ante el árbitro.", answer: "Capitan" },
  { id: "deporte_C_006", topic: "deporte", letter: "C", question: "Con la C: Superficie de juego típica en fútbol y rugby.", answer: "Cesped" },
  { id: "deporte_C_007", topic: "deporte", letter: "C", question: "Con la C: Instrumento para medir tiempos en competición.", answer: "Cronometro" },
  { id: "deporte_C_008", topic: "deporte", letter: "C", question: "Con la C: Recorrido cerrado para carreras .", answer: "Circuito" },
  { id: "deporte_C_009", topic: "deporte", letter: "C", question: "Con la C: Enfrentamiento reglado en deportes como judo o boxeo.", answer: "Combate" },
  { id: "deporte_C_010", topic: "deporte", letter: "C", question: "Con la C: Rutina previa para preparar músculos y reducir lesiones.", answer: "Calentamiento" },
  { id: "deporte_C_011", topic: "deporte", letter: "C", question: "Con la C: Elemento usado en escalada o salto a la comba.", answer: "Cuerda" },
  { id: "deporte_C_012", topic: "deporte", letter: "C", question: "Con la C: Protección esencial en deportes como ciclismo o motor.", answer: "Cascos" },
  { id: "deporte_C_013", topic: "deporte", letter: "C", question: "Con la C: Prenda de juego que identifica equipo y dorsal.", answer: "Camiseta" },
  { id: "deporte_C_014", topic: "deporte", letter: "C", question: "Con la C: Nombre de pila del futbolista portugués que ha ganado múltiples Balones de Oro y Champions League.", answer: "Cristiano" },
  { id: "deporte_C_015", topic: "deporte", letter: "C", question: "Con la C: Momento final de una jugada o esfuerzo .", answer: "Culminacion" },
  { id: "deporte_D_001", topic: "deporte", letter: "D", question: "Con la D: Actividad física competitiva con reglas establecidas que se practica individualmente o en equipo.", answer: "Deporte" },
  { id: "deporte_D_002", topic: "deporte", letter: "D", question: "Con la D: Partido entre rivales de la misma ciudad o región.", answer: "Derbi" },
  { id: "deporte_D_003", topic: "deporte", letter: "D", question: "Con la D: Acción de evitar que el rival anote.", answer: "Defensa" },
  { id: "deporte_D_004", topic: "deporte", letter: "D", question: "Con la D: Número que identifica a un deportista en competición.", answer: "Dorsal" },
  { id: "deporte_D_005", topic: "deporte", letter: "D", question: "Con la D: Uso de sustancias prohibidas para mejorar rendimiento.", answer: "Doping" },
  { id: "deporte_D_006", topic: "deporte", letter: "D", question: "Con la D: Sistema de selección de jugadores en ligas como la NBA o NFL.", answer: "Draft" },
  { id: "deporte_D_007", topic: "deporte", letter: "D", question: "Con la D: Regate o bote para superar a un rival .", answer: "Drible" },
  { id: "deporte_D_008", topic: "deporte", letter: "D", question: "Con la D: Blanco al que se apunta en tiro con arco o dardos.", answer: "Diana" },
  { id: "deporte_D_009", topic: "deporte", letter: "D", question: "Con la D: Proyectil usado en el deporte de tiro con proyectil.", answer: "Dardo" },
  { id: "deporte_D_010", topic: "deporte", letter: "D", question: "Con la D: Prueba combinada de 10 disciplinas en atletismo.", answer: "Decatlon" },
  { id: "deporte_D_011", topic: "deporte", letter: "D", question: "Con la D: Modalidad de velocidad cuesta abajo .", answer: "Descenso" },
  { id: "deporte_D_012", topic: "deporte", letter: "D", question: "Con la D: Rally-raid famoso por rutas exigentes.", answer: "Dakar" },
  { id: "deporte_D_013", topic: "deporte", letter: "D", question: "Con la D: Prueba de atletismo de lanzamiento de objeto circular.", answer: "Disco" },
  { id: "deporte_D_014", topic: "deporte", letter: "D", question: "Con la D: Modalidad de tenis con dos jugadores por lado.", answer: "Doble" },
  { id: "deporte_D_015", topic: "deporte", letter: "D", question: "Con la D: Variación del ritmo o intensidad en un partido o entrenamiento.", answer: "Dinamica" },
  { id: "deporte_E_001", topic: "deporte", letter: "E", question: "Con la E: Proceso de preparación física y técnica para competir.", answer: "Entrenamiento" },
  { id: "deporte_E_002", topic: "deporte", letter: "E", question: "Con la E: Instalación donde se juegan partidos y eventos deportivos.", answer: "Estadio" },
  { id: "deporte_E_003", topic: "deporte", letter: "E", question: "Con la E: Conjunto de jugadores que compiten juntos.", answer: "Equipo" },
  { id: "deporte_E_004", topic: "deporte", letter: "E", question: "Con la E: Resultado en el que ambos equipos terminan con el mismo marcador.", answer: "Empate" },
  { id: "deporte_E_005", topic: "deporte", letter: "E", question: "Con la E: Deporte de nieve con esquís.", answer: "Esqui" },
  { id: "deporte_E_006", topic: "deporte", letter: "E", question: "Con la E: Deporte de combate con espada, florete o sable.", answer: "Esgrima" },
  { id: "deporte_E_007", topic: "deporte", letter: "E", question: "Con la E: Deporte de subir paredes o roca con técnica y seguridad.", answer: "Escalada" },
  { id: "deporte_E_008", topic: "deporte", letter: "E", question: "Con la E: Plan para organizar jugadas y decisiones durante el juego.", answer: "Estrategia" },
  { id: "deporte_E_009", topic: "deporte", letter: "E", question: "Con la E: Capacidad de estirar músculos y articulaciones con amplitud.", answer: "Elasticidad" },
  { id: "deporte_E_010", topic: "deporte", letter: "E", question: "Con la E: Protección usada en fútbol para la tibia.", answer: "Espinillera" },
  { id: "deporte_E_011", topic: "deporte", letter: "E", question: "Con la E: Modalidad de motor o MTB con tramos cronometrados.", answer: "Enduro" },
  { id: "deporte_E_012", topic: "deporte", letter: "E", question: "Con la E: Prueba de esquí con giros entre puertas.", answer: "Eslalon" },
  { id: "deporte_E_013", topic: "deporte", letter: "E", question: "Con la E: Relacionado con deportes a caballo.", answer: "Ecuestre" },
  { id: "deporte_E_014", topic: "deporte", letter: "E", question: "Con la E: Capacidad física para sostener el esfuerzo.", answer: "Energia" },
  { id: "deporte_E_015", topic: "deporte", letter: "E", question: "Con la E: Fase de competición donde el perdedor queda fuera.", answer: "Eliminatoria" },
  { id: "deporte_F_001", topic: "deporte", letter: "F", question: "Con la F: Deporte de equipo más popular en España y gran parte del mundo.", answer: "Futbol" },
  { id: "deporte_F_002", topic: "deporte", letter: "F", question: "Con la F: Infracción del reglamento que suele implicar sanción o tiro libre.", answer: "Falta" },
  { id: "deporte_F_003", topic: "deporte", letter: "F", question: "Con la F: Partido decisivo por un título.", answer: "Final" },
  { id: "deporte_F_004", topic: "deporte", letter: "F", question: "Con la F: Distribución táctica de un equipo en el campo.", answer: "Formacion" },
  { id: "deporte_F_005", topic: "deporte", letter: "F", question: "Con la F: Ejercicio corporal clásico para fuerza de brazos y tronco.", answer: "Flexion" },
  { id: "deporte_F_006", topic: "deporte", letter: "F", question: "Con la F: Victoria por retirada o ausencia del rival.", answer: "Forfait" },
  { id: "deporte_F_007", topic: "deporte", letter: "F", question: "Con la F: Entrenamiento general para mejorar forma física.", answer: "Fitness" },
  { id: "deporte_F_008", topic: "deporte", letter: "F", question: "Con la F: Modalidad de estilo libre .", answer: "Freestyle" },
  { id: "deporte_F_009", topic: "deporte", letter: "F", question: "Con la F: Amago para engañar al rival en deportes de balón.", answer: "Finta" },
  { id: "deporte_F_010", topic: "deporte", letter: "F", question: "Con la F: Proyectil usado en tiro con arco.", answer: "Flecha" },
  { id: "deporte_F_011", topic: "deporte", letter: "F", question: "Con la F: Organismo que regula un deporte en un país.", answer: "Federacion" },
  { id: "deporte_F_012", topic: "deporte", letter: "F", question: "Con la F: Fútbol sala, versión indoor de fútbol con cinco jugadores.", answer: "Futsal" },
  { id: "deporte_F_013", topic: "deporte", letter: "F", question: "Con la F: Pruebas largas de resistencia .", answer: "Fondo" },
  { id: "deporte_F_014", topic: "deporte", letter: "F", question: "Con la F: Instalación donde se juega a esfera vasca.", answer: "Fronton" },
  { id: "deporte_F_015", topic: "deporte", letter: "F", question: "Con la F: Condición física general de un deportista.", answer: "Fisico" },
  { id: "deporte_G_001", topic: "deporte", letter: "G", question: "Con la G: Anotación en fútbol y otros deportes con portería.", answer: "Gol" },
  { id: "deporte_G_002", topic: "deporte", letter: "G", question: "Con la G: Deporte con ejercicios de fuerza, flexibilidad y acrobacia.", answer: "Gimnasia" },
  { id: "deporte_G_003", topic: "deporte", letter: "G", question: "Con la G: Zona de público en un estadio o pabellón.", answer: "Grada" },
  { id: "deporte_G_004", topic: "deporte", letter: "G", question: "Con la G: Protección usada en boxeo y otros deportes.", answer: "Guante" },
  { id: "deporte_G_005", topic: "deporte", letter: "G", question: "Con la G: Portero; jugador que defiende la portería.", answer: "Guardameta" },
  { id: "deporte_G_006", topic: "deporte", letter: "G", question: "Con la G: Jugador destacado por marcar muchos goles.", answer: "Goleador" },
  { id: "deporte_G_007", topic: "deporte", letter: "G", question: "Con la G: Rotación; en saltos y piruetas se usa para describir vueltas.", answer: "Giro" },
  { id: "deporte_G_008", topic: "deporte", letter: "G", question: "Con la G: Aire del caballo usado en hípica.", answer: "Galope" },
  { id: "deporte_G_009", topic: "deporte", letter: "G", question: "Con la G: Lugar de entrenamiento con máquinas y pesas.", answer: "Gimnasio" },
  { id: "deporte_G_010", topic: "deporte", letter: "G", question: "Con la G: Lucha cuerpo a cuerpo basada en agarres .", answer: "Grappling" },
  { id: "deporte_G_011", topic: "deporte", letter: "G", question: "Con la G: Conjunto de los cuatro grandes torneos de tenis.", answer: "GranSlam" },
  { id: "deporte_G_012", topic: "deporte", letter: "G", question: "Con la G: Deportista que compite en gimnasia.", answer: "Gimnasta" },
  { id: "deporte_G_013", topic: "deporte", letter: "G", question: "Con la G: Acción de golpear balón o implemento .", answer: "Golpeo" },
  { id: "deporte_G_014", topic: "deporte", letter: "G", question: "Con la G: Lesión típica de ingle en deportes de sprint .", answer: "Groin" },
  { id: "deporte_G_015", topic: "deporte", letter: "G", question: "Con la G: Lenguaje corporal importante en arbitraje y comunicación en juego.", answer: "Gestual" },
  { id: "deporte_H_001", topic: "deporte", letter: "H", question: "Con la H: Deporte con stick y bola o disco, sobre hielo o césped.", answer: "Hockey" },
  { id: "deporte_H_002", topic: "deporte", letter: "H", question: "Con la H: Deporte de levantar pesas .", answer: "Halterofilia" },
  { id: "deporte_H_003", topic: "deporte", letter: "H", question: "Con la H: Ventaja o corrección usada para igualar niveles .", answer: "Handicap" },
  { id: "deporte_H_004", topic: "deporte", letter: "H", question: "Con la H: Tres goles de un mismo jugador en un partido.", answer: "Hattrick" },
  { id: "deporte_H_005", topic: "deporte", letter: "H", question: "Con la H: Aficionado apasionado de un equipo.", answer: "Hincha" },
  { id: "deporte_H_006", topic: "deporte", letter: "H", question: "Con la H: Deporte ecuestre en distintas modalidades.", answer: "Hipismo" },
  { id: "deporte_H_007", topic: "deporte", letter: "H", question: "Con la H: Aporte de líquidos para rendimiento y recuperación.", answer: "Hidratacion" },
  { id: "deporte_H_008", topic: "deporte", letter: "H", question: "Con la H: Superficie de deportes de invierno como patinaje o hockey.", answer: "Hielo" },
  { id: "deporte_H_009", topic: "deporte", letter: "H", question: "Con la H: Jugada de béisbol en la que se recorre todas las bases.", answer: "HomeRun" },
  { id: "deporte_H_010", topic: "deporte", letter: "H", question: "Con la H: Capacidad técnica: control, precisión y coordinación.", answer: "Habilidad" },
  { id: "deporte_H_011", topic: "deporte", letter: "H", question: "Con la H: Competición combinada de seis pruebas .", answer: "Hexatlon" },
  { id: "deporte_H_012", topic: "deporte", letter: "H", question: "Con la H: Articulación muy exigida en natación y lanzamientos.", answer: "Hombro" },
  { id: "deporte_H_013", topic: "deporte", letter: "H", question: "Con la H: Test físico/entrenamiento popular .", answer: "Harvard" },
  { id: "deporte_H_014", topic: "deporte", letter: "H", question: "Con la H: Apodo de equipos; ejemplo de nombres en deporte .", answer: "Husky" },
  { id: "deporte_H_015", topic: "deporte", letter: "H", question: "Con la H: Golpe curvo en boxeo; también “tiro curvo” en baloncesto.", answer: "Hook" },
  { id: "deporte_I_001", topic: "deporte", letter: "I", question: "Con la I: Punto perfecto que decide un combate en judo.", answer: "Ippon" },
  { id: "deporte_I_002", topic: "deporte", letter: "I", question: "Con la I: Triatlón de larga distancia; también marca icónica.", answer: "Ironman" },
  { id: "deporte_I_003", topic: "deporte", letter: "I", question: "Con la I: Bloque de trabajo alternado con descanso en entrenamiento.", answer: "Intervalo" },
  { id: "deporte_I_004", topic: "deporte", letter: "I", question: "Con la I: Contracción muscular sin movimiento, como plancha.", answer: "Isometria" },
  { id: "deporte_I_005", topic: "deporte", letter: "I", question: "Con la I: Práctica bajo techo , como pista cubierta.", answer: "Indoor" },
  { id: "deporte_I_006", topic: "deporte", letter: "I", question: "Con la I: Registro para participar en una carrera o torneo.", answer: "Inscripcion" },
  { id: "deporte_I_007", topic: "deporte", letter: "I", question: "Con la I: Acción de cortar un pase del rival.", answer: "Intercepcion" },
  { id: "deporte_I_008", topic: "deporte", letter: "I", question: "Con la I: Tendencia a mantener movimiento; relevante en técnica deportiva.", answer: "Inercia" },
  { id: "deporte_I_009", topic: "deporte", letter: "I", question: "Con la I: Contacto fuerte con balón o rival; clave en protección y técnica.", answer: "Impacto" },
  { id: "deporte_I_010", topic: "deporte", letter: "I", question: "Con la I: Nombre de pila del portero español que ganó la Copa del Mundo 2010 y múltiples Champions League con el Real Madrid.", answer: "Iker" },
  { id: "deporte_I_011", topic: "deporte", letter: "I", question: "Con la I: Competición de automovilismo en EE. UU.", answer: "Indycar" },
  { id: "deporte_I_012", topic: "deporte", letter: "I", question: "Con la I: Etapa de aprendizaje deportivo en edades tempranas.", answer: "Iniciacion" },
  { id: "deporte_I_013", topic: "deporte", letter: "I", question: "Con la I: Nivel de esfuerzo; se regula por pulsaciones o percepción.", answer: "Intensidad" },
  { id: "deporte_I_014", topic: "deporte", letter: "I", question: "Con la I: En táctica, capacidad de un jugador para condicionar el juego.", answer: "Influencia" },
  { id: "deporte_I_015", topic: "deporte", letter: "I", question: "Con la I: En gimnasia, movimiento en el que el cuerpo queda invertido.", answer: "Inversion" },
  { id: "deporte_J_001", topic: "deporte", letter: "J", question: "Con la J: Arte marcial y deporte olímpico de agarres y proyecciones.", answer: "Judo" },
  { id: "deporte_J_002", topic: "deporte", letter: "J", question: "Con la J: Danza y música tradicional; también se usa en eventos deportivos regionales.", answer: "Jota" },
  { id: "deporte_J_003", topic: "deporte", letter: "J", question: "Con la J: Correr suave como ejercicio de salud.", answer: "Jogging" },
  { id: "deporte_J_004", topic: "deporte", letter: "J", question: "Con la J: Apellido del jugador de baloncesto estadounidense que ganó seis anillos de la NBA con los Chicago Bulls.", answer: "Jordan" },
  { id: "deporte_J_005", topic: "deporte", letter: "J", question: "Con la J: Prueba de atletismo de lanzamiento de objeto alargado.", answer: "Jabalina" },
  { id: "deporte_J_006", topic: "deporte", letter: "J", question: "Con la J: Jinete que compite en carreras de caballos.", answer: "Jockey" },
  { id: "deporte_J_007", topic: "deporte", letter: "J", question: "Con la J: Fecha o ronda de partidos en una liga.", answer: "Jornada" },
  { id: "deporte_J_008", topic: "deporte", letter: "J", question: "Con la J: Club histórico del fútbol europeo.", answer: "Juventus" },
  { id: "deporte_J_009", topic: "deporte", letter: "J", question: "Con la J: Categoría de edad juvenil en competiciones.", answer: "Junior" },
  { id: "deporte_J_010", topic: "deporte", letter: "J", question: "Con la J: Acción de competir; también se habla de “competencia limpia”.", answer: "Juego" },
  { id: "deporte_J_011", topic: "deporte", letter: "J", question: "Con la J: Ciudad andaluza con tradición deportiva y eventos.", answer: "Jerez" },
  { id: "deporte_J_012", topic: "deporte", letter: "J", question: "Con la J: Arte marcial/deporte de agarres muy popular en MMA.", answer: "JiuJitsu" },
  { id: "deporte_J_013", topic: "deporte", letter: "J", question: "Con la J: Sesión informal; en skate y surf se habla de “jam session” competitiva.", answer: "Jam" },
  { id: "deporte_J_014", topic: "deporte", letter: "J", question: "Con la J: Tipo de salto en baloncesto .", answer: "Jumper" },
  { id: "deporte_J_015", topic: "deporte", letter: "J", question: "Con la J: Deportista que practica judo.", answer: "Judoca" },
  { id: "deporte_L_001", topic: "deporte", letter: "L", question: "Con la L: Competición regular por puntos entre varios equipos.", answer: "Liga" },
  { id: "deporte_L_002", topic: "deporte", letter: "L", question: "Con la L: Deporte de combate basado en agarres y control.", answer: "Lucha" },
  { id: "deporte_L_003", topic: "deporte", letter: "L", question: "Con la L: Acción de arrojar un objeto .", answer: "Lanzamiento" },
  { id: "deporte_L_004", topic: "deporte", letter: "L", question: "Con la L: Posición de fútbol que juega por las bandas defensivas.", answer: "Lateral" },
  { id: "deporte_L_005", topic: "deporte", letter: "L", question: "Con la L: Posición defensiva en voleibol; también en sistemas antiguos de fútbol.", answer: "Libero" },
  { id: "deporte_L_006", topic: "deporte", letter: "L", question: "Con la L: Daño físico que afecta rendimiento y requiere recuperación.", answer: "Lesion" },
  { id: "deporte_L_007", topic: "deporte", letter: "L", question: "Con la L: Superficie del ring en boxeo.", answer: "Lona" },
  { id: "deporte_L_008", topic: "deporte", letter: "L", question: "Con la L: Deporte de equipo con stick y bola, muy popular en Norteamérica.", answer: "Lacrosse" },
  { id: "deporte_L_009", topic: "deporte", letter: "L", question: "Con la L: Salida de una carrera.", answer: "Largada" },
  { id: "deporte_L_010", topic: "deporte", letter: "L", question: "Con la L: Zona baja de la espalda, frecuente en lesiones deportivas.", answer: "Lombar" },
  { id: "deporte_L_011", topic: "deporte", letter: "L", question: "Con la L: Efecto de latigazo en golpes, como en tenis o boxeo.", answer: "Latigo" },
  { id: "deporte_L_012", topic: "deporte", letter: "L", question: "Con la L: Jugador o equipo que va primero en una clasificación.", answer: "Lider" },
  { id: "deporte_L_013", topic: "deporte", letter: "L", question: "Con la L: Resultado conseguido: marca personal o título.", answer: "Logro" },
  { id: "deporte_L_014", topic: "deporte", letter: "L", question: "Con la L: Movimiento recto; útil en técnica de carrera.", answer: "Lineal" },
  { id: "deporte_L_015", topic: "deporte", letter: "L", question: "Con la L: Acción de levantar  o recuperar el balón.", answer: "Levantada" },
  { id: "deporte_M_001", topic: "deporte", letter: "M", question: "Con la M: Carrera de 42,195 km.", answer: "Maraton" },
  { id: "deporte_M_002", topic: "deporte", letter: "M", question: "Con la M: Apellido del futbolista argentino que ha ganado múltiples Balones de Oro y la Copa del Mundo 2022.", answer: "Messi" },
  { id: "deporte_M_003", topic: "deporte", letter: "M", question: "Con la M: Premio en competiciones, especialmente en Juegos Olímpicos.", answer: "Medalla" },
  { id: "deporte_M_004", topic: "deporte", letter: "M", question: "Con la M: Torneo internacional; en fútbol, el torneo de la FIFA.", answer: "Mundial" },
  { id: "deporte_M_005", topic: "deporte", letter: "M", question: "Con la M: Panel o conteo de puntos/goles de un partido.", answer: "Marcador" },
  { id: "deporte_M_006", topic: "deporte", letter: "M", question: "Con la M: Deporte de combate tailandés con golpes de puños, codos, rodillas.", answer: "Muaythai" },
  { id: "deporte_M_007", topic: "deporte", letter: "M", question: "Con la M: Carreras de motos en circuito de tierra con saltos.", answer: "Motocross" },
  { id: "deporte_M_008", topic: "deporte", letter: "M", question: "Con la M: Sigla para “Most Valuable Player”, jugador más valioso.", answer: "MVP" },
  { id: "deporte_M_009", topic: "deporte", letter: "M", question: "Con la M: Acción de hundir el balón en baloncesto.", answer: "Mate" },
  { id: "deporte_M_010", topic: "deporte", letter: "M", question: "Con la M: Defensa compacta; también “muro” en voleibol para bloquear.", answer: "Muro" },
  { id: "deporte_M_011", topic: "deporte", letter: "M", question: "Con la M: Peso de mano usado en entrenamiento de fuerza.", answer: "Mancuerna" },
  { id: "deporte_M_012", topic: "deporte", letter: "M", question: "Con la M: Técnica de recuperación muscular.", answer: "Masaje" },
  { id: "deporte_M_013", topic: "deporte", letter: "M", question: "Con la M: Persona que dirige sesiones en gimnasio o escuela deportiva.", answer: "Monitor" },
  { id: "deporte_M_014", topic: "deporte", letter: "M", question: "Con la M: Prenda ajustada usada en natación o atletismo.", answer: "Malla" },
  { id: "deporte_M_015", topic: "deporte", letter: "M", question: "Con la M: Tejido que genera fuerza y movimiento.", answer: "Musculo" },
  { id: "deporte_N_001", topic: "deporte", letter: "N", question: "Con la N: Deporte acuático de carreras en piscina o aguas abiertas.", answer: "Natacion" },
  { id: "deporte_N_002", topic: "deporte", letter: "N", question: "Con la N: Apellido del tenista español que ha ganado múltiples títulos de Roland Garros y es considerado uno de los mejores de la historia.", answer: "Nadal" },
  { id: "deporte_N_003", topic: "deporte", letter: "N", question: "Con la N: Victoria en boxeo/MMA cuando el rival no puede continuar.", answer: "Nocaut" },
  { id: "deporte_N_004", topic: "deporte", letter: "N", question: "Con la N: Material de trajes para surf y triatlón.", answer: "Neopreno" },
  { id: "deporte_N_005", topic: "deporte", letter: "N", question: "Con la N: Plan de alimentación para rendimiento y recuperación.", answer: "Nutricion" },
  { id: "deporte_N_006", topic: "deporte", letter: "N", question: "Con la N: Grado de habilidad o categoría competitiva.", answer: "Nivel" },
  { id: "deporte_N_007", topic: "deporte", letter: "N", question: "Con la N: Superficie de deportes como esquí y snowboard.", answer: "Nieve" },
  { id: "deporte_N_008", topic: "deporte", letter: "N", question: "Con la N: Técnica esencial en escalada para seguridad con cuerda.", answer: "Nudo" },
  { id: "deporte_N_009", topic: "deporte", letter: "N", question: "Con la N: Deportista en su primer año o con poca experiencia.", answer: "Novato" },
  { id: "deporte_N_010", topic: "deporte", letter: "N", question: "Con la N: Selección que representa a un país en competiciones.", answer: "Nacional" },
  { id: "deporte_N_011", topic: "deporte", letter: "N", question: "Con la N: Estilo regional; en España, norte con tradición ciclista y fútbol.", answer: "Norteño" },
  { id: "deporte_N_012", topic: "deporte", letter: "N", question: "Con la N: En ciclismo, zona neutralizada al inicio o en incidentes.", answer: "Neutro" },
  { id: "deporte_N_013", topic: "deporte", letter: "N", question: "Con la N: Inspirado en carreras de obstáculos tipo “ninja warrior”.", answer: "Ninja" },
  { id: "deporte_N_014", topic: "deporte", letter: "N", question: "Con la N: Nombre vasco de Navarra, muy presente en ciclismo y pelota.", answer: "Nafarroa" },
  { id: "deporte_N_015", topic: "deporte", letter: "N", question: "Con la N: Ansiedad o tensión previa a competir .", answer: "Nervio" },
  { id: "deporte_Ñ_001", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Grupo de aficionados organizado, común en fútbol y otros deportes.", answer: "Peña" },
  { id: "deporte_Ñ_002", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Etapa dura en ciclismo con grandes puertos.", answer: "Montaña" },
  { id: "deporte_Ñ_003", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Disparo muy potente en fútbol o balonmano.", answer: "Cañón" },
  { id: "deporte_Ñ_004", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Regate que pasa el balón entre las piernas del rival.", answer: "Caño" },
  { id: "deporte_Ñ_005", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Temporada competitiva: temporada deportiva.", answer: "Año" },
  { id: "deporte_Ñ_006", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Inmersión en hielo usado en recuperación tras esfuerzos intensos.", answer: "Baño" },
  { id: "deporte_Ñ_007", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Engranaje de la bici; cambia desarrollo y cadencia.", answer: "Piñon" },
  { id: "deporte_Ñ_008", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Gesto del árbitro para indicar una decisión.", answer: "Señal" },
  { id: "deporte_Ñ_009", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Articulación clave en tenis y gimnasia; frecuente en lesiones.", answer: "Muñeca" },
  { id: "deporte_Ñ_010", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Factor de recuperación fundamental para rendimiento.", answer: "Sueño" },
  { id: "deporte_Ñ_011", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Miembro del equipo; cooperación en juego colectivo.", answer: "Compañero" },
  { id: "deporte_Ñ_012", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Categoría infantil en escuelas deportivas y competiciones.", answer: "Niño" },
  { id: "deporte_Ñ_013", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Golpe fuerte  recibido en juego o combate.", answer: "Castaña" },
  { id: "deporte_Ñ_014", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Sesión matinal de entrenamiento en concentraciones.", answer: "Mañana" },
  { id: "deporte_Ñ_015", topic: "deporte", letter: "Ñ", question: "Contiene la Ñ: Parte de temporada en muchos calendarios deportivos.", answer: "Otoño" },
  { id: "deporte_O_001", topic: "deporte", letter: "O", question: "Con la O: Edición de los Juegos Olímpicos, gran evento multideportivo.", answer: "Olimpiada" },
  { id: "deporte_O_002", topic: "deporte", letter: "O", question: "Con la O: Movimiento y valores asociados a los Juegos Olímpicos.", answer: "Olimpismo" },
  { id: "deporte_O_003", topic: "deporte", letter: "O", question: "Con la O: Medalla de primer puesto en competiciones.", answer: "Oro" },
  { id: "deporte_O_004", topic: "deporte", letter: "O", question: "Con la O: Torneo abierto; frecuente en tenis y golf.", answer: "Open" },
  { id: "deporte_O_005", topic: "deporte", letter: "O", question: "Con la O: Espacio de combate típico en MMA.", answer: "Octagono" },
  { id: "deporte_O_006", topic: "deporte", letter: "O", question: "Con la O: Rival al que te enfrentas en un partido o combate.", answer: "Oponente" },
  { id: "deporte_O_007", topic: "deporte", letter: "O", question: "Con la O: Elemento a superar en carreras de vallas o trail.", answer: "Obstaculo" },
  { id: "deporte_O_008", topic: "deporte", letter: "O", question: "Con la O: Deporte de navegación con mapa y brújula.", answer: "Orientacion" },
  { id: "deporte_O_009", topic: "deporte", letter: "O", question: "Con la O: Elemento clave; se habla de VO2max en resistencia.", answer: "Oxigeno" },
  { id: "deporte_O_010", topic: "deporte", letter: "O", question: "Con la O: Elemento central del surf.", answer: "Ola" },
  { id: "deporte_O_011", topic: "deporte", letter: "O", question: "Con la O: Fuera; se usa en tenis y otros deportes para pelota fuera.", answer: "Out" },
  { id: "deporte_O_012", topic: "deporte", letter: "O", question: "Con la O: Prórroga en deportes de marcador .", answer: "Overtime" },
  { id: "deporte_O_013", topic: "deporte", letter: "O", question: "Con la O: Persona que detecta talento deportivo para clubes.", answer: "Ojeador" },
  { id: "deporte_O_014", topic: "deporte", letter: "O", question: "Con la O: Término rioplatense para fuera de juego .", answer: "Orsai" },
  { id: "deporte_O_015", topic: "deporte", letter: "O", question: "Con la O: Nombre simbólico usado en deporte para “cima” o excelencia.", answer: "Olimpo" },
  { id: "deporte_P_001", topic: "deporte", letter: "P", question: "Con la P: Tiro desde los once metros en fútbol.", answer: "Penalti" },
  { id: "deporte_P_002", topic: "deporte", letter: "P", question: "Con la P: Lugar de premiación para los tres primeros.", answer: "Podio" },
  { id: "deporte_P_003", topic: "deporte", letter: "P", question: "Con la P: Superficie de atletismo o lugar de competición.", answer: "Pista" },
  { id: "deporte_P_004", topic: "deporte", letter: "P", question: "Con la P: Jugador que defiende la portería.", answer: "Portero" },
  { id: "deporte_P_005", topic: "deporte", letter: "P", question: "Con la P: Acción de enviar el balón a un compañero.", answer: "Pase" },
  { id: "deporte_P_006", topic: "deporte", letter: "P", question: "Con la P: Elemento central en muchos deportes; también pelota vasca.", answer: "Pelota" },
  { id: "deporte_P_007", topic: "deporte", letter: "P", question: "Con la P: Deporte sobre hielo o ruedas.", answer: "Patinaje" },
  { id: "deporte_P_008", topic: "deporte", letter: "P", question: "Con la P: Entrenamiento de fuerza con cargas.", answer: "Pesas" },
  { id: "deporte_P_009", topic: "deporte", letter: "P", question: "Con la P: Conductor en deportes de motor.", answer: "Piloto" },
  { id: "deporte_P_010", topic: "deporte", letter: "P", question: "Con la P: Posición en baloncesto o balonmano cerca de la zona de anotación.", answer: "Pivot" },
  { id: "deporte_P_011", topic: "deporte", letter: "P", question: "Con la P: Disciplina urbana de desplazamiento superando obstáculos.", answer: "Parkour" },
  { id: "deporte_P_012", topic: "deporte", letter: "P", question: "Con la P: Capacidad de acertar un objetivo .", answer: "Punteria" },
  { id: "deporte_P_013", topic: "deporte", letter: "P", question: "Con la P: Golpe con el pie, clave en fútbol y artes marciales.", answer: "Patada" },
  { id: "deporte_P_014", topic: "deporte", letter: "P", question: "Con la P: Afición en gradas; influye en ambiente del partido.", answer: "Publico" },
  { id: "deporte_P_015", topic: "deporte", letter: "P", question: "Con la P: Parte de un partido  o fase de juego.", answer: "Periodo" },
  { id: "deporte_Q_001", topic: "deporte", letter: "Q", question: "Contiene la Q: Implemento de tenis, pádel o bádminton.", answer: "Raqueta" },
  { id: "deporte_Q_002", topic: "deporte", letter: "Q", question: "Contiene la Q: Golpe inicial o reanudación en tenis/voleibol.", answer: "Saque" },
  { id: "deporte_Q_003", topic: "deporte", letter: "Q", question: "Contiene la Q: Acción ofensiva para anotar.", answer: "Ataque" },
  { id: "deporte_Q_004", topic: "deporte", letter: "Q", question: "Contiene la Q: Acción defensiva en voleibol o baloncesto.", answer: "Bloque" },
  { id: "deporte_Q_005", topic: "deporte", letter: "Q", question: "Contiene la Q: Movimiento para evitar un golpe.", answer: "Esquiva" },
  { id: "deporte_Q_006", topic: "deporte", letter: "Q", question: "Contiene la Q: Cambio brusco de dirección para superar al rival.", answer: "Quiebro" },
  { id: "deporte_Q_007", topic: "deporte", letter: "Q", question: "Contiene la Q: Conjunto de ropa del equipo.", answer: "Equipacion" },
  { id: "deporte_Q_008", topic: "deporte", letter: "Q", question: "Contiene la Q: Apuesta deportiva tradicional en España.", answer: "Quiniela" },
  { id: "deporte_Q_009", topic: "deporte", letter: "Q", question: "Contiene la Q: Tendón muy importante en carrera y salto.", answer: "Aquiles" },
  { id: "deporte_Q_010", topic: "deporte", letter: "Q", question: "Contiene la Q: Lado del campo o pierna/zurda en fútbol.", answer: "Izquierda" },
  { id: "deporte_Q_011", topic: "deporte", letter: "Q", question: "Contiene la Q: Jugador o golpe con el lado zurdo.", answer: "Izquierdo" },
  { id: "deporte_Q_012", topic: "deporte", letter: "Q", question: "Contiene la Q: Golpe fuerte con raqueta.", answer: "Raquetazo" },
  { id: "deporte_Q_013", topic: "deporte", letter: "Q", question: "Contiene la Q: Amago/gesto para desmarcarse.", answer: "Requiebro" },
  { id: "deporte_Q_014", topic: "deporte", letter: "Q", question: "Contiene la Q: Juego limpio e igualdad de reglas.", answer: "Equidad" },
  { id: "deporte_Q_015", topic: "deporte", letter: "Q", question: "Contiene la Q: País que ha organizado grandes eventos deportivos.", answer: "Qatar" },
  { id: "deporte_R_001", topic: "deporte", letter: "R", question: "Con la R: Deporte de contacto con balón ovalado.", answer: "Rugby" },
  { id: "deporte_R_002", topic: "deporte", letter: "R", question: "Con la R: Correr como práctica deportiva popular.", answer: "Running" },
  { id: "deporte_R_003", topic: "deporte", letter: "R", question: "Con la R: Golpe final de una jugada .", answer: "Remate" },
  { id: "deporte_R_004", topic: "deporte", letter: "R", question: "Con la R: Acción de driblar para superar a un rival en fútbol.", answer: "Regate" },
  { id: "deporte_R_005", topic: "deporte", letter: "R", question: "Con la R: Capacidad de sostener esfuerzo prolongado.", answer: "Resistencia" },
  { id: "deporte_R_006", topic: "deporte", letter: "R", question: "Con la R: Carrera por equipos pasando un testigo.", answer: "Relevo" },
  { id: "deporte_R_007", topic: "deporte", letter: "R", question: "Con la R: Competición de motor en tramos cronometrados.", answer: "Rally" },
  { id: "deporte_R_008", topic: "deporte", letter: "R", question: "Con la R: Clasificación ordenada de deportistas o equipos.", answer: "Ranking" },
  { id: "deporte_R_009", topic: "deporte", letter: "R", question: "Con la R: Entrenamiento continuo a ritmo moderado en running/ciclismo.", answer: "Rodaje" },
  { id: "deporte_R_010", topic: "deporte", letter: "R", question: "Con la R: Fase de una competición .", answer: "Ronda" },
  { id: "deporte_R_011", topic: "deporte", letter: "R", question: "Con la R: Tipo de lesión .", answer: "Rotura" },
  { id: "deporte_R_012", topic: "deporte", letter: "R", question: "Con la R: Proceso de descanso y reparación tras entrenar o competir.", answer: "Recuperacion" },
  { id: "deporte_R_013", topic: "deporte", letter: "R", question: "Con la R: Norma del juego; el normas definen sanciones.", answer: "Regla" },
  { id: "deporte_R_014", topic: "deporte", letter: "R", question: "Con la R: Respuesta rápida a un estímulo; clave en salidas y reflejos.", answer: "Reaccion" },
  { id: "deporte_R_015", topic: "deporte", letter: "R", question: "Con la R: Malla en tenis o voleibol que separa campos.", answer: "Red" },
  { id: "deporte_S_001", topic: "deporte", letter: "S", question: "Con la S: Carrera corta de máxima velocidad.", answer: "Sprint" },
  { id: "deporte_S_002", topic: "deporte", letter: "S", question: "Con la S: Método de recuperación usado por algunos deportistas.", answer: "Sauna" },
  { id: "deporte_S_003", topic: "deporte", letter: "S", question: "Con la S: Deporte de deslizarse sobre olas con tabla.", answer: "Surf" },
  { id: "deporte_S_004", topic: "deporte", letter: "S", question: "Con la S: Deporte de nieve con tabla.", answer: "Snowboard" },
  { id: "deporte_S_005", topic: "deporte", letter: "S", question: "Con la S: Unidad de puntuación en tenis y voleibol.", answer: "Set" },
  { id: "deporte_S_006", topic: "deporte", letter: "S", question: "Con la S: En eSports, servidor donde se juega online.", answer: "Server" },
  { id: "deporte_S_007", topic: "deporte", letter: "S", question: "Con la S: Deporte con monopatín y trucos.", answer: "Skate" },
  { id: "deporte_S_008", topic: "deporte", letter: "S", question: "Con la S: Puesta en juego en voleibol o tenis; también servicio de banda en deportes.", answer: "Saque" },
  { id: "deporte_S_009", topic: "deporte", letter: "S", question: "Con la S: Actividad de caminar por rutas; base del trail.", answer: "Senderismo" },
  { id: "deporte_S_010", topic: "deporte", letter: "S", question: "Con la S: Respuesta del cuerpo para regular temperatura en ejercicio.", answer: "Sudor" },
  { id: "deporte_S_011", topic: "deporte", letter: "S", question: "Con la S: Aplicación popular para registrar entrenos de running/ciclismo.", answer: "Strava" },
  { id: "deporte_S_012", topic: "deporte", letter: "S", question: "Con la S: En boxeo, “boxeo de sombra” como ejercicio de técnica.", answer: "Sombra" },
  { id: "deporte_S_013", topic: "deporte", letter: "S", question: "Con la S: Castigo por falta o infracción del reglamento.", answer: "Sancion" },
  { id: "deporte_S_014", topic: "deporte", letter: "S", question: "Con la S: Inicio de una carrera o prueba.", answer: "Salida" },
  { id: "deporte_S_015", topic: "deporte", letter: "S", question: "Con la S: Factor impredecible que puede influir en resultados.", answer: "Suerte" },
  { id: "deporte_T_001", topic: "deporte", letter: "T", question: "Con la T: Deporte de raqueta con puntos, juegos y sets.", answer: "Tenis" },
  { id: "deporte_T_002", topic: "deporte", letter: "T", question: "Con la T: Deporte que combina natación, ciclismo y carrera.", answer: "Triatlon" },
  { id: "deporte_T_003", topic: "deporte", letter: "T", question: "Con la T: Plan de juego para tomar ventajas.", answer: "Tactica" },
  { id: "deporte_T_004", topic: "deporte", letter: "T", question: "Con la T: Variable clave: duración de carrera, posesión, cronómetro.", answer: "Tiempo" },
  { id: "deporte_T_005", topic: "deporte", letter: "T", question: "Con la T: Disparo a portería o lanzamiento al aro.", answer: "Tiro" },
  { id: "deporte_T_006", topic: "deporte", letter: "T", question: "Con la T: Articulación con alta incidencia de esguinces.", answer: "Tobillo" },
  { id: "deporte_T_007", topic: "deporte", letter: "T", question: "Con la T: Carrera por montaña y senderos.", answer: "Trail" },
  { id: "deporte_T_008", topic: "deporte", letter: "T", question: "Con la T: Competición con rondas y eliminatorias.", answer: "Torneo" },
  { id: "deporte_T_009", topic: "deporte", letter: "T", question: "Con la T: Superficie acolchada para judo y artes marciales.", answer: "Tatami" },
  { id: "deporte_T_010", topic: "deporte", letter: "T", question: "Con la T: Placaje en rugby o fútbol americano.", answer: "Tackle" },
  { id: "deporte_T_011", topic: "deporte", letter: "T", question: "Con la T: Aparato de gimnasia para saltos acrobáticos.", answer: "Trampolin" },
  { id: "deporte_T_012", topic: "deporte", letter: "T", question: "Con la T: Apodo de equipos o deportistas; también en surf .", answer: "Tiburon" },
  { id: "deporte_T_013", topic: "deporte", letter: "T", question: "Con la T: Habilidad específica para ejecutar movimientos con eficacia.", answer: "Tecnica" },
  { id: "deporte_T_014", topic: "deporte", letter: "T", question: "Con la T: Premio físico por ganar una competición.", answer: "Trofeo" },
  { id: "deporte_T_015", topic: "deporte", letter: "T", question: "Con la T: Estado físico/mental previo a competir; también tensión muscular.", answer: "Tension" },
  { id: "deporte_U_001", topic: "deporte", letter: "U", question: "Con la U: Nombre de pila del velocista jamaicano que estableció récords mundiales en 100 y 200 metros planos.", answer: "Usain" },
  { id: "deporte_U_002", topic: "deporte", letter: "U", question: "Con la U: Distancias muy largas en carrera .", answer: "Ultra" },
  { id: "deporte_U_003", topic: "deporte", letter: "U", question: "Con la U: Liga/organización famosa de artes marciales mixtas.", answer: "UFC" },
  { id: "deporte_U_004", topic: "deporte", letter: "U", question: "Con la U: Ropa oficial de un equipo o selección.", answer: "Uniforme" },
  { id: "deporte_U_005", topic: "deporte", letter: "U", question: "Con la U: Árbitro en béisbol/tenis .", answer: "Umpire" },
  { id: "deporte_U_006", topic: "deporte", letter: "U", question: "Con la U: Entorno de deportes como skate, parkour o running.", answer: "Urbano" },
  { id: "deporte_U_007", topic: "deporte", letter: "U", question: "Con la U: Valor a partir del cual cambia el esfuerzo .", answer: "Umbral" },
  { id: "deporte_U_008", topic: "deporte", letter: "U", question: "Con la U: Banda usada en microfonía y comunicaciones de eventos.", answer: "UHF" },
  { id: "deporte_U_009", topic: "deporte", letter: "U", question: "Con la U: Equipo táctico o grupo de entrenamiento .", answer: "Unidad" },
  { id: "deporte_U_010", topic: "deporte", letter: "U", question: "Con la U: Movimiento sincronizado de un equipo .", answer: "Unisono" },
  { id: "deporte_U_011", topic: "deporte", letter: "U", question: "Con la U: Ciudad con club de fútbol y eventos; ejemplo de sede deportiva .", answer: "Ulsan" },
  { id: "deporte_U_012", topic: "deporte", letter: "U", question: "Con la U: Ciudad andaluza; aparece en cultura flamenca y eventos .", answer: "Utrera" },
  { id: "deporte_U_013", topic: "deporte", letter: "U", question: "Con la U: Carrera de distancia superior al maratón, a menudo en montaña.", answer: "Ultramaraton" },
  { id: "deporte_U_014", topic: "deporte", letter: "U", question: "Con la U: Motivación ideal; se usa en mensajes deportivos .", answer: "Utopia" },
  { id: "deporte_U_015", topic: "deporte", letter: "U", question: "Con la U: Necesidad inmediata de marcar o remontar .", answer: "Urgencia" },
  { id: "deporte_V_001", topic: "deporte", letter: "V", question: "Con la V: Deporte de red donde se anota con golpes al balón.", answer: "Voleibol" },
  { id: "deporte_V_002", topic: "deporte", letter: "V", question: "Con la V: Gran carrera ciclista por etapas; también “LaVuelta” en España.", answer: "Vuelta" },
  { id: "deporte_V_003", topic: "deporte", letter: "V", question: "Con la V: Resultado de ganar una competición.", answer: "Victoria" },
  { id: "deporte_V_004", topic: "deporte", letter: "V", question: "Con la V: Capacidad de moverse rápido; clave en sprints.", answer: "Velocidad" },
  { id: "deporte_V_005", topic: "deporte", letter: "V", question: "Con la V: Deporte náutico con embarcación impulsada por viento.", answer: "Vela" },
  { id: "deporte_V_006", topic: "deporte", letter: "V", question: "Con la V: Sistema de videoarbitraje en fútbol.", answer: "VAR" },
  { id: "deporte_V_007", topic: "deporte", letter: "V", question: "Con la V: Situación favorable en marcador o táctica.", answer: "Ventaja" },
  { id: "deporte_V_008", topic: "deporte", letter: "V", question: "Con la V: Deportista con mucha experiencia o años de competición.", answer: "Veterano" },
  { id: "deporte_V_009", topic: "deporte", letter: "V", question: "Con la V: Energía física; se trabaja con fuerza y descanso.", answer: "Vigor" },
  { id: "deporte_V_010", topic: "deporte", letter: "V", question: "Con la V: Carreras de vallas en atletismo.", answer: "Vallado" },
  { id: "deporte_V_011", topic: "deporte", letter: "V", question: "Con la V: Posición de fútbol en el medio campo  o pieza en bádminton.", answer: "Volante" },
  { id: "deporte_V_012", topic: "deporte", letter: "V", question: "Con la V: Trompeta popularizada en estadios; cultura de afición.", answer: "Vuvuzela" },
  { id: "deporte_V_013", topic: "deporte", letter: "V", question: "Con la V: Indicador de capacidad aeróbica máxima .", answer: "Vo2max" },
  { id: "deporte_V_014", topic: "deporte", letter: "V", question: "Con la V: Sensación en motor y bici; también vibración muscular en fatiga.", answer: "Vibracion" },
  { id: "deporte_V_015", topic: "deporte", letter: "V", question: "Con la V: Salto vertical o ataque hacia arriba en voleibol/baloncesto.", answer: "Vertical" },
  { id: "deporte_X_001", topic: "deporte", letter: "X", question: "Contiene la X: Deporte de combate.", answer: "Boxeo" },
  { id: "deporte_X_002", topic: "deporte", letter: "X", question: "Contiene la X: Ejercicio de fuerza donde se dobla y estira los brazos manteniendo el cuerpo recto, apoyado en manos y pies.", answer: "Flexion" },
  { id: "deporte_X_003", topic: "deporte", letter: "X", question: "Contiene la X: Posición de banda en fútbol.", answer: "Extremo" },
  { id: "deporte_X_004", topic: "deporte", letter: "X", question: "Contiene la X: Partido o evento no oficial.", answer: "Exhibicion" },
  { id: "deporte_X_005", topic: "deporte", letter: "X", question: "Contiene la X: Tipo de fuerza/acción rápida en salto y sprint.", answer: "Explosivo" },
  { id: "deporte_X_006", topic: "deporte", letter: "X", question: "Contiene la X: Entrenamiento funcional de alta intensidad.", answer: "Crossfit" },
  { id: "deporte_X_007", topic: "deporte", letter: "X", question: "Contiene la X: Nombre de pila del centrocampista español que ganó la Copa del Mundo 2010 y múltiples Champions League con el Barcelona.", answer: "Xavi" },
  { id: "deporte_X_008", topic: "deporte", letter: "X", question: "Contiene la X: Eventos de deportes extremos.", answer: "XGames" },
  { id: "deporte_X_009", topic: "deporte", letter: "X", question: "Contiene la X: Salida deportiva de montaña o club.", answer: "Excursion" },
  { id: "deporte_X_010", topic: "deporte", letter: "X", question: "Contiene la X: Gas esencial para la respiración celular y el rendimiento deportivo, medido en VO2max.", answer: "Oxigeno" },
  { id: "deporte_X_011", topic: "deporte", letter: "X", question: "Contiene la X: Valor más alto alcanzado en una marca personal, récord o rendimiento deportivo.", answer: "Maximo" },
  { id: "deporte_X_012", topic: "deporte", letter: "X", question: "Contiene la X: Término en inglés que significa la siguiente ronda, partido o fase de una competición.", answer: "Next" },
  { id: "deporte_X_013", topic: "deporte", letter: "X", question: "Contiene la X: Sobrecarga de entrenamiento que puede causar fatiga, lesiones o disminución del rendimiento.", answer: "Exceso" },
  { id: "deporte_X_014", topic: "deporte", letter: "X", question: "Contiene la X: Material o tejido usado en la confección de ropa técnica deportiva con propiedades transpirables.", answer: "Textil" },
  { id: "deporte_X_015", topic: "deporte", letter: "X", question: "Contiene la X: Disciplina de bicicleta.", answer: "Bmx" },
  { id: "deporte_Y_001", topic: "deporte", letter: "Y", question: "Contiene la Y: Práctica física y mental muy extendida como disciplina de bienestar.", answer: "Yoga" },
  { id: "deporte_Y_002", topic: "deporte", letter: "Y", question: "Contiene la Y: Deporte de equipo que se juega con un stick o palo para golpear una bola o disco, sobre hielo o césped.", answer: "Hockey" },
  { id: "deporte_Y_003", topic: "deporte", letter: "Y", question: "Contiene la Y: Deporte de equipo de contacto físico donde se juega con un balón ovalado que se puede pasar hacia atrás.", answer: "Rugby" },
  { id: "deporte_Y_004", topic: "deporte", letter: "Y", question: "Contiene la Y: Partido entre dos equipos de la misma ciudad o región, caracterizado por una gran rivalidad.", answer: "Derby" },
  { id: "deporte_Y_005", topic: "deporte", letter: "Y", question: "Contiene la Y: Apellido del futbolista brasileño que jugó en el Barcelona y el PSG, conocido por su regate y velocidad.", answer: "Neymar" },
  { id: "deporte_Y_006", topic: "deporte", letter: "Y", question: "Contiene la Y: Apellido del boxeador estadounidense que fue el campeón más joven de los pesos pesados en la historia.", answer: "Tyson" },
  { id: "deporte_Y_007", topic: "deporte", letter: "Y", question: "Contiene la Y: Apellido del jugador de baloncesto estadounidense que ganó cinco anillos de la NBA con los Lakers y fue conocido como 'Black Mamba'.", answer: "Bryant" },
  { id: "deporte_Y_008", topic: "deporte", letter: "Y", question: "Contiene la Y: Apellido del boxeador estadounidense que se retiró invicto con 50 victorias y múltiples títulos mundiales en diferentes categorías.", answer: "Mayweather" },
  { id: "deporte_Y_009", topic: "deporte", letter: "Y", question: "Contiene la Y: Club alemán de fútbol de Múnich, uno de los más exitosos de Europa con múltiples Champions League.", answer: "Bayern" },
  { id: "deporte_Y_010", topic: "deporte", letter: "Y", question: "Contiene la Y: Apellido del portero soviético conocido como 'La Araña Negra', único guardameta en ganar el Balón de Oro.", answer: "Yashin" },
  { id: "deporte_Y_011", topic: "deporte", letter: "Y", question: "Contiene la Y: Equipo icónico de béisbol.", answer: "Yankees" },
  { id: "deporte_Y_012", topic: "deporte", letter: "Y", question: "Contiene la Y: Ciudad australiana que organizó los Juegos Olímpicos del año 2000.", answer: "Sydney" },
  { id: "deporte_Y_013", topic: "deporte", letter: "Y", question: "Contiene la Y: Nombre de pila de la atleta venezolana que estableció el récord mundial de salto triple y ganó oro olímpico.", answer: "Yulimar" },
  { id: "deporte_Y_014", topic: "deporte", letter: "Y", question: "Contiene la Y: Club francés de fútbol de la ciudad de Lyon, conocido por su cantera y múltiples títulos de liga.", answer: "Lyons" },
  { id: "deporte_Y_015", topic: "deporte", letter: "Y", question: "Contiene la Y: Término en inglés que significa jugar o competir, muy usado en eSports y videojuegos.", answer: "Play" },
  { id: "deporte_Z_001", topic: "deporte", letter: "Z", question: "Con la Z: Apellido del futbolista francés que ganó la Copa del Mundo 1998 y fue entrenador del Real Madrid ganando tres Champions consecutivas.", answer: "Zidane" },
  { id: "deporte_Z_002", topic: "deporte", letter: "Z", question: "Con la Z: Ciudad española en el valle del Ebro, sede del un equipo de Zaragoza y de eventos deportivos importantes.", answer: "Zaragoza" },
  { id: "deporte_Z_003", topic: "deporte", letter: "Z", question: "Con la Z: Calzado ligero y cómodo con suela flexible, usado para correr, entrenar o hacer deporte.", answer: "Zapatilla" },
  { id: "deporte_Z_004", topic: "deporte", letter: "Z", question: "Con la Z: Área delimitada del campo; en defensa por áreas cada jugador cubre un espacio en lugar de marcar a un rival específico.", answer: "Zona" },
  { id: "deporte_Z_005", topic: "deporte", letter: "Z", question: "Con la Z: Longitud del paso al correr; clave en técnica de carrera.", answer: "Zancada" },
  { id: "deporte_Z_006", topic: "deporte", letter: "Z", question: "Con la Z: Línea defensiva en fútbol formada por los defensores que protegen la portería.", answer: "Zaga" },
  { id: "deporte_Z_007", topic: "deporte", letter: "Z", question: "Con la Z: Acción rápida y contundente; se usa como metáfora deportiva.", answer: "Zarpazo" },
  { id: "deporte_Z_008", topic: "deporte", letter: "Z", question: "Con la Z: Actividad fitness que combina movimientos de baile latino con ejercicios aeróbicos, creada en Colombia.", answer: "Zumba" },
  { id: "deporte_Z_009", topic: "deporte", letter: "Z", question: "Con la Z: Plaza pública o espacio abierto donde se celebran eventos deportivos y culturales, especialmente en México.", answer: "Zocalo" },
  { id: "deporte_Z_010", topic: "deporte", letter: "Z", question: "Con la Z: Estado mental de calma y concentración, importante en deportes de precisión como tiro con arco o golf.", answer: "Zen" },
  { id: "deporte_Z_011", topic: "deporte", letter: "Z", question: "Con la Z: Apodo o título que se da a un campeón excepcional, derivado del título imperial ruso.", answer: "Zar" },
  { id: "deporte_Z_012", topic: "deporte", letter: "Z", question: "Con la Z: Movimiento en zigzag (serpenteante) con cambios bruscos de dirección usado en regates y dribles para desorientar al rival.", answer: "Zigzag" },
  { id: "deporte_Z_013", topic: "deporte", letter: "Z", question: "Con la Z: Táctica defensiva que consiste en dividir el campo en zonas donde cada jugador defiende un área específica.", answer: "Zonificacion" },
  { id: "deporte_Z_014", topic: "deporte", letter: "Z", question: "Con la Z: Bolsa o morral de cuero usado en senderismo y montañismo para transportar equipo y provisiones.", answer: "Zurron" },
  { id: "deporte_Z_015", topic: "deporte", letter: "Z", question: "Con la Z: Acción de saltar o lanzarse al agua de cabeza o de pie, usada en natación y saltos.", answer: "Zambullida" },
];
