import type { QA } from "./types";

export const FOLKLORE: QA[] = [
  { id: "folklore_A_001", topic: "folklore", letter: "A", question: "Con la A: Canto o regalo navideño tradicional.", answer: "Aguinaldo" },
  { id: "folklore_A_002", topic: "folklore", letter: "A", question: "Con la A: Canto de amanecer típico en fiestas.", answer: "Alborada" },
  { id: "folklore_A_003", topic: "folklore", letter: "A", question: "Con la A: Danza vasca solemne de honor.", answer: "Aurresku" },
  { id: "folklore_A_004", topic: "folklore", letter: "A", question: "Con la A: Carnaval tradicional en zonas de León y Zamora.", answer: "Antruejo" },
  { id: "folklore_A_005", topic: "folklore", letter: "A", question: "Con la A: Reunión de brujas en la tradición popular.", answer: "Aquelarre" },
  { id: "folklore_A_006", topic: "folklore", letter: "A", question: "Con la A: Desfile festivo-militar tradicional (Irun/Hondarribia).", answer: "Alarde" },
  { id: "folklore_A_007", topic: "folklore", letter: "A", question: "Con la A: Material usado en alfombras festivas y decoraciones.", answer: "Aserrín" },
  { id: "folklore_A_008", topic: "folklore", letter: "A", question: "Con la A: Tambor grande usado en procesiones y fiestas.", answer: "Atabal" },
  { id: "folklore_A_009", topic: "folklore", letter: "A", question: "Con la A: Núcleo rural donde se conservan muchas tradiciones.", answer: "Aldea" },
  { id: "folklore_A_010", topic: "folklore", letter: "A", question: "Con la A: Objeto al que se atribuye protección o suerte.", answer: "Amuleto" },
  { id: "folklore_A_011", topic: "folklore", letter: "A", question: "Con la A: Dulce tradicional de mosto cocido, típico en algunas regiones.", answer: "Arrope" },
  { id: "folklore_A_012", topic: "folklore", letter: "A", question: "Con la A: Decoración de flores/serrín en Corpus y romerías.", answer: "Alfombra" },
  { id: "folklore_A_013", topic: "folklore", letter: "A", question: "Con la A: Trabajo manual tradicional (cestería, cerámica, etc.).", answer: "Artesanía" },
  { id: "folklore_A_014", topic: "folklore", letter: "A", question: "Con la A: Instrumento popular en folclore del norte.", answer: "Acordeón" },
  { id: "folklore_A_015", topic: "folklore", letter: "A", question: "Con la A: Utensilio tradicional asociado a cocina popular y rituales domésticos.", answer: "Almirez" },
  { id: "folklore_B_001", topic: "folklore", letter: "B", question: "Con la B: Recipiente tradicional para enfriar y beber agua.", answer: "Botijo" },
  { id: "folklore_B_002", topic: "folklore", letter: "B", question: "Con la B: Palo flamenco rápido y festivo.", answer: "Bulería" },
  { id: "folklore_B_003", topic: "folklore", letter: "B", question: "Con la B: Instrumento de cuerno usado en avisos y fiestas rurales.", answer: "Bocina" },
  { id: "folklore_B_004", topic: "folklore", letter: "B", question: "Con la B: Objeto ceremonial en danzas y autoridades festivas.", answer: "Bastón" },
  { id: "folklore_B_005", topic: "folklore", letter: "B", question: "Con la B: Persona que baila en fiestas tradicionales.", answer: "Bailarín" },
  { id: "folklore_B_006", topic: "folklore", letter: "B", question: "Con la B: Instrumento de cuerda típico de rondallas.", answer: "Bandurria" },
  { id: "folklore_B_007", topic: "folklore", letter: "B", question: "Con la B: Cuerda grave; también ‘voz’ grave en música popular.", answer: "Bordón" },
  { id: "folklore_B_008", topic: "folklore", letter: "B", question: "Con la B: Acto ritual en fiestas patronales.", answer: "Bendición" },
  { id: "folklore_B_009", topic: "folklore", letter: "B", question: "Con la B: Odre tradicional para vino en celebraciones.", answer: "Bota" },
  { id: "folklore_B_010", topic: "folklore", letter: "B", question: "Con la B: Gesto festivo alzando la copa en reuniones.", answer: "Brindis" },
  { id: "folklore_B_011", topic: "folklore", letter: "B", question: "Con la B: Color rojo usado en trajes y ornamentos.", answer: "Bermellón" },
  { id: "folklore_B_012", topic: "folklore", letter: "B", question: "Con la B: Comida popular muy presente en romerías y ferias.", answer: "Bocadillo" },
  { id: "folklore_B_013", topic: "folklore", letter: "B", question: "Con la B: Estructura de madera para escenarios o hogueras festivas.", answer: "Bastida" },
  { id: "folklore_B_014", topic: "folklore", letter: "B", question: "Con la B: Prenda de comparsas y peñas en fiestas.", answer: "Bufanda" },
  { id: "folklore_B_015", topic: "folklore", letter: "B", question: "Con la B: Acto festivo de ‘bajar’ una imagen o grupo (bajadas populares).", answer: "Bajada" },
  { id: "folklore_C_001", topic: "folklore", letter: "C", question: "Con la C: Instrumento de percusión típico en danzas españolas.", answer: "Castañuelas" },
  { id: "folklore_C_002", topic: "folklore", letter: "C", question: "Con la C: Baile castizo asociado a Madrid.", answer: "Chotis" },
  { id: "folklore_C_003", topic: "folklore", letter: "C", question: "Con la C: Pasacalle con fuego y diablos, típico en Cataluña.", answer: "Correfoc" },
  { id: "folklore_C_004", topic: "folklore", letter: "C", question: "Con la C: Figura festiva de gran cabeza en comparsas.", answer: "Cabezudo" },
  { id: "folklore_C_005", topic: "folklore", letter: "C", question: "Con la C: Banda callejera de viento y percusión en fiestas.", answer: "Charanga" },
  { id: "folklore_C_006", topic: "folklore", letter: "C", question: "Con la C: Hermandad religiosa de SemanaSanta.", answer: "Cofradía" },
  { id: "folklore_C_007", topic: "folklore", letter: "C", question: "Con la C: Grupo festivo con trajes y música en desfiles.", answer: "Comparsa" },
  { id: "folklore_C_008", topic: "folklore", letter: "C", question: "Con la C: Juego popular con premio (palo enjabonado).", answer: "Cucaña" },
  { id: "folklore_C_009", topic: "folklore", letter: "C", question: "Con la C: Vehículo decorado para cabalgatas y desfiles.", answer: "Carroza" },
  { id: "folklore_C_010", topic: "folklore", letter: "C", question: "Con la C: Torre de campanas; toques tradicionales marcan fiestas.", answer: "Campanario" },
  { id: "folklore_C_011", topic: "folklore", letter: "C", question: "Con la C: Ruido ritual con cencerros en celebraciones populares.", answer: "Cencerrada" },
  { id: "folklore_C_012", topic: "folklore", letter: "C", question: "Con la C: Canción tradicional, especialmente en Galicia.", answer: "Cantiga" },
  { id: "folklore_C_013", topic: "folklore", letter: "C", question: "Con la C: Comida festiva catalana en torno a calçots.", answer: "Calçotada" },
  { id: "folklore_C_014", topic: "folklore", letter: "C", question: "Con la C: Interpretación vocal tradicional en celebraciones.", answer: "Canto" },
  { id: "folklore_C_015", topic: "folklore", letter: "C", question: "Con la C: Campana de ganado usada también en ritos sonoros.", answer: "Cencerro" },
  { id: "folklore_D_001", topic: "folklore", letter: "D", question: "Con la D: Instrumento de viento típico en pasacalles.", answer: "Dulzaina" },
  { id: "folklore_D_002", topic: "folklore", letter: "D", question: "Con la D: Danza/representación de diablos en fiestas.", answer: "Diablada" },
  { id: "folklore_D_003", topic: "folklore", letter: "D", question: "Con la D: Baile tradicional con pasos y música propios.", answer: "Danza" },
  { id: "folklore_D_004", topic: "folklore", letter: "D", question: "Con la D: Recorrido festivo con música y trajes.", answer: "Desfile" },
  { id: "folklore_D_005", topic: "folklore", letter: "D", question: "Con la D: Vestimenta para carnaval y fiestas populares.", answer: "Disfraz" },
  { id: "folklore_D_006", topic: "folklore", letter: "D", question: "Con la D: Música de madrugada para despertar en fiestas.", answer: "Diana" },
  { id: "folklore_D_007", topic: "folklore", letter: "D", question: "Con la D: Persona que participa en danzas rituales.", answer: "Danzante" },
  { id: "folklore_D_008", topic: "folklore", letter: "D", question: "Con la D: Vínculo popular con santos y vírgenes patronales.", answer: "Devoción" },
  { id: "folklore_D_009", topic: "folklore", letter: "D", question: "Con la D: Día típico de romerías y celebraciones patronales.", answer: "Domingo" },
  { id: "folklore_D_010", topic: "folklore", letter: "D", question: "Con la D: Postre tradicional en fiestas (torrijas, rosquillas, etc.).", answer: "Dulce" },
  { id: "folklore_D_011", topic: "folklore", letter: "D", question: "Con la D: Vendedor de dulces en ferias y fiestas.", answer: "Dulcero" },
  { id: "folklore_D_012", topic: "folklore", letter: "D", question: "Con la D: Personaje de comparsa o teatro popular.", answer: "Dama" },
  { id: "folklore_D_013", topic: "folklore", letter: "D", question: "Con la D: Embarcación tradicional gallega (cultura costera).", answer: "Dorna" },
  { id: "folklore_D_014", topic: "folklore", letter: "D", question: "Con la D: Vendedor de dulces en ferias y fiestas.", answer: "Dulcero" },
  { id: "folklore_D_015", topic: "folklore", letter: "D", question: "Con la D: Vendedor de dulces en ferias y fiestas.", answer: "Dulcero" },
  { id: "folklore_E_001", topic: "folklore", letter: "E", question: "Con la E: Carrera delante de toros en fiestas populares.", answer: "Encierro" },
  { id: "folklore_E_002", topic: "folklore", letter: "E", question: "Con la E: Bandera o símbolo llevado en procesiones.", answer: "Estandarte" },
  { id: "folklore_E_003", topic: "folklore", letter: "E", question: "Con la E: Pequeño santuario, destino típico de romerías.", answer: "Ermita" },
  { id: "folklore_E_004", topic: "folklore", letter: "E", question: "Con la E: Estudio de costumbres y cultura popular.", answer: "Etnografía" },
  { id: "folklore_E_005", topic: "folklore", letter: "E", question: "Con la E: Decoración tradicional en fachadas (motivos populares).", answer: "Esgrafiado" },
  { id: "folklore_E_006", topic: "folklore", letter: "E", question: "Con la E: Lavanda; planta usada en ritos y sahumerios.", answer: "Espliego" },
  { id: "folklore_E_007", topic: "folklore", letter: "E", question: "Con la E: Alpargata tradicional de esparto.", answer: "Esparteña" },
  { id: "folklore_E_008", topic: "folklore", letter: "E", question: "Con la E: Fibra vegetal usada en cestería y artes populares.", answer: "Esparto" },
  { id: "folklore_E_009", topic: "folklore", letter: "E", question: "Con la E: Imagen devocional repartida en fiestas religiosas.", answer: "Estampa" },
  { id: "folklore_E_010", topic: "folklore", letter: "E", question: "Con la E: Campana/cencerro; sonido tradicional en ganado y rituales.", answer: "Esquila" },
  { id: "folklore_E_011", topic: "folklore", letter: "E", question: "Con la E: Decoración en metal/cerámica en artesanía tradicional.", answer: "Esmalte" },
  { id: "folklore_E_012", topic: "folklore", letter: "E", question: "Con la E: Objeto devocional popular.", answer: "Escapulario" },
  { id: "folklore_E_013", topic: "folklore", letter: "E", question: "Con la E: Alfombra sencilla de fibra usada en usos tradicionales.", answer: "Esterilla" },
  { id: "folklore_E_014", topic: "folklore", letter: "E", question: "Con la E: Accesorio ecuestre en romerías a caballo.", answer: "Estribo" },
  { id: "folklore_E_015", topic: "folklore", letter: "E", question: "Con la E: Estado festivo colectivo en celebraciones.", answer: "Euforia" },
  { id: "folklore_F_001", topic: "folklore", letter: "F", question: "Con la F: Arte andaluz de cante, toque y baile.", answer: "Flamenco" },
  { id: "folklore_F_002", topic: "folklore", letter: "F", question: "Con la F: Baile y canto tradicional presente en varias regiones.", answer: "Fandango" },
  { id: "folklore_F_003", topic: "folklore", letter: "F", question: "Con la F: Monumento efímero quemado en fiestas valencianas.", answer: "Falla" },
  { id: "folklore_F_004", topic: "folklore", letter: "F", question: "Con la F: Fiesta popular con casetas, música y atracciones.", answer: "Feria" },
  { id: "folklore_F_005", topic: "folklore", letter: "F", question: "Con la F: Adorno de papel típico de ferias.", answer: "Farolillo" },
  { id: "folklore_F_006", topic: "folklore", letter: "F", question: "Con la F: Parte del acordeón; sonido típico en música popular.", answer: "Fuelle" },
  { id: "folklore_F_007", topic: "folklore", letter: "F", question: "Con la F: Danza/canto tradicional (Canarias).", answer: "Folía" },
  { id: "folklore_F_008", topic: "folklore", letter: "F", question: "Con la F: Instrumento común en música tradicional.", answer: "Flauta" },
  { id: "folklore_F_009", topic: "folklore", letter: "F", question: "Con la F: Variante local del fandango.", answer: "Fandanguillo" },
  { id: "folklore_F_010", topic: "folklore", letter: "F", question: "Con la F: Celebración popular de un pueblo o barrio.", answer: "Fiesta" },
  { id: "folklore_F_011", topic: "folklore", letter: "F", question: "Con la F: Hoguera festiva (SanJuan, Alicante).", answer: "Foguera" },
  { id: "folklore_F_012", topic: "folklore", letter: "F", question: "Con la F: Faja ancha típica en trajes regionales.", answer: "Fajín" },
  { id: "folklore_F_013", topic: "folklore", letter: "F", question: "Con la F: Adjetivo; asociado a coplas de fandango.", answer: "Fandanguera" },
  { id: "folklore_F_014", topic: "folklore", letter: "F", question: "Con la F: Feria histórica; denominación tradicional en varias ciudades.", answer: "FeriaReal" },
  { id: "folklore_F_015", topic: "folklore", letter: "F", question: "Con la F: Acto festivo con participación comunitaria.", answer: "Festejo" },
  { id: "folklore_G_001", topic: "folklore", letter: "G", question: "Con la G: Instrumento de viento típico del noroeste.", answer: "Gaita" },
  { id: "folklore_G_002", topic: "folklore", letter: "G", question: "Con la G: Figuras enormes que desfilan en fiestas.", answer: "Gigantes" },
  { id: "folklore_G_003", topic: "folklore", letter: "G", question: "Con la G: Músico que toca la gaita en romerías.", answer: "Gaitero" },
  { id: "folklore_G_004", topic: "folklore", letter: "G", question: "Con la G: Estilo festivo inspirado en Goya (trajes, estética).", answer: "Goyesco" },
  { id: "folklore_G_005", topic: "folklore", letter: "G", question: "Con la G: Pequeña gaita o flauta en tradiciones locales.", answer: "Gaitilla" },
  { id: "folklore_G_006", topic: "folklore", letter: "G", question: "Con la G: Desfiladero; en folklore, rutas de romería y leyendas.", answer: "Garganta" },
  { id: "folklore_G_007", topic: "folklore", letter: "G", question: "Con la G: Comida popular colectiva en fiestas.", answer: "Garbanzada" },
  { id: "folklore_G_008", topic: "folklore", letter: "G", question: "Con la G: Adorno festivo de flores o papel.", answer: "Guirnalda" },
  { id: "folklore_G_009", topic: "folklore", letter: "G", question: "Con la G: Instrumento clave en flamenco y música popular.", answer: "Guitarra" },
  { id: "folklore_G_010", topic: "folklore", letter: "G", question: "Con la G: Tipo de gaita del noroeste; tradición musical.", answer: "GaitaGallega" },
  { id: "folklore_G_011", topic: "folklore", letter: "G", question: "Con la G: Actuación colectiva de gaitas.", answer: "Gaitada" },
  { id: "folklore_G_012", topic: "folklore", letter: "G", question: "Con la G: Tipo de gaita tradicional; música de romería.", answer: "GaitaAsturiana" },
  { id: "folklore_G_013", topic: "folklore", letter: "G", question: "Con la G: Tipo de gaita tradicional; música de romería.", answer: "GaitaAsturiana" },
  { id: "folklore_G_014", topic: "folklore", letter: "G", question: "Con la G: Tipo de gaita tradicional; música de romería.", answer: "GaitaAsturiana" },
  { id: "folklore_G_015", topic: "folklore", letter: "G", question: "Con la G: Conjunto de comidas tradicionales de una región.", answer: "Gastronomía" },
  { id: "folklore_H_001", topic: "folklore", letter: "H", question: "Con la H: Fuego ritual y festivo, típico en SanJuan.", answer: "Hoguera" },
  { id: "folklore_H_002", topic: "folklore", letter: "H", question: "Con la H: Grupo religioso que organiza procesiones.", answer: "Hermandad" },
  { id: "folklore_H_003", topic: "folklore", letter: "H", question: "Con la H: Canto marinero popular en la costa mediterránea.", answer: "Habanera" },
  { id: "folklore_H_004", topic: "folklore", letter: "H", question: "Con la H: Bebida tradicional en recreaciones y ferias medievales.", answer: "Hidromiel" },
  { id: "folklore_H_005", topic: "folklore", letter: "H", question: "Con la H: Amuleto popular contra el mal de ojo.", answer: "Higa" },
  { id: "folklore_H_006", topic: "folklore", letter: "H", question: "Con la H: Construcción tradicional del noroeste para guardar grano.", answer: "Hórreo" },
  { id: "folklore_H_007", topic: "folklore", letter: "H", question: "Con la H: Antorcha usada en procesiones nocturnas.", answer: "Hachón" },
  { id: "folklore_H_008", topic: "folklore", letter: "H", question: "Con la H: Saber popular de plantas y remedios tradicionales.", answer: "Herbolario" },
  { id: "folklore_H_009", topic: "folklore", letter: "H", question: "Con la H: Masa usada en dulces tradicionales de fiesta.", answer: "Hojaldre" },
  { id: "folklore_H_010", topic: "folklore", letter: "H", question: "Con la H: Masa usada en dulces tradicionales de fiesta.", answer: "Hojaldre" },
  { id: "folklore_H_011", topic: "folklore", letter: "H", question: "Con la H: Variedad dialectal; parte del patrimonio inmaterial.", answer: "Habla" },
  { id: "folklore_H_012", topic: "folklore", letter: "H", question: "Con la H: Canto colectivo en celebraciones y fiestas.", answer: "Himno" },
  { id: "folklore_H_013", topic: "folklore", letter: "H", question: "Con la H: Ingrediente base de dulces festivos (roscos, buñuelos).", answer: "Harina" },
  { id: "folklore_H_014", topic: "folklore", letter: "H", question: "Con la H: Paisaje agrícola ligado a tradiciones y fiestas locales.", answer: "Huerta" },
  { id: "folklore_H_015", topic: "folklore", letter: "H", question: "Con la H: Masa usada en dulces tradicionales de fiesta.", answer: "Hojaldre" },
  { id: "folklore_I_001", topic: "folklore", letter: "I", question: "Con la I: Broma típica del Día de los SantosInocentes.", answer: "Inocentada" },
  { id: "folklore_I_002", topic: "folklore", letter: "I", question: "Con la I: Emigrante retornado, figura cultural en el norte.", answer: "Indiano" },
  { id: "folklore_I_003", topic: "folklore", letter: "I", question: "Con la I: Espacio central de fiestas patronales y procesiones.", answer: "Iglesia" },
  { id: "folklore_I_004", topic: "folklore", letter: "I", question: "Con la I: Imagen con valor simbólico y devocional.", answer: "Icono" },
  { id: "folklore_I_005", topic: "folklore", letter: "I", question: "Con la I: Canto repentizado en algunas tradiciones.", answer: "Improviso" },
  { id: "folklore_I_006", topic: "folklore", letter: "I", question: "Con la I: Aroma usado en procesiones y ritos.", answer: "Incienso" },
  { id: "folklore_I_007", topic: "folklore", letter: "I", question: "Con la I: Conjunto de ropa típica de un traje regional.", answer: "Indumentaria" },
  { id: "folklore_I_008", topic: "folklore", letter: "I", question: "Con la I: Estación de Navidad, carnavales y matanzas.", answer: "Invierno" },
  { id: "folklore_I_009", topic: "folklore", letter: "I", question: "Con la I: Objeto musical clave en tradiciones (gaita, dulzaina).", answer: "Instrumento" },
  { id: "folklore_I_010", topic: "folklore", letter: "I", question: "Con la I: Conjunto de ropa típica de un traje regional.", answer: "Indumentaria" },
  { id: "folklore_I_011", topic: "folklore", letter: "I", question: "Con la I: Recorrido de procesiones y pasacalles.", answer: "Itinerario" },
  { id: "folklore_I_012", topic: "folklore", letter: "I", question: "Con la I: Conjunto de ropa típica de un traje regional.", answer: "Indumentaria" },
  { id: "folklore_I_013", topic: "folklore", letter: "I", question: "Con la I: Práctica festiva en algunos festejos taurinos.", answer: "Indulto" },
  { id: "folklore_I_014", topic: "folklore", letter: "I", question: "Con la I: Escultor de imágenes religiosas (SemanaSanta).", answer: "Imaginero" },
  { id: "folklore_I_015", topic: "folklore", letter: "I", question: "Con la I: Santo patrón asociado a fiestas agrícolas (SanIsidro).", answer: "Isidro" },
  { id: "folklore_J_001", topic: "folklore", letter: "J", question: "Con la J: Baile y canto tradicional muy extendido en España.", answer: "Jota" },
  { id: "folklore_J_002", topic: "folklore", letter: "J", question: "Con la J: Personaje enmascarado de una fiesta extremeña.", answer: "Jarramplas" },
  { id: "folklore_J_003", topic: "folklore", letter: "J", question: "Con la J: Alegría ruidosa típica de fiestas.", answer: "Jolgorio" },
  { id: "folklore_J_004", topic: "folklore", letter: "J", question: "Con la J: Fiesta animada con música y baile.", answer: "Jarana" },
  { id: "folklore_J_005", topic: "folklore", letter: "J", question: "Con la J: Se usa en juegos populares como la cucaña (palo enjabonado).", answer: "Jabón" },
  { id: "folklore_J_006", topic: "folklore", letter: "J", question: "Con la J: Reunión vecinal para organizar fiestas.", answer: "Junta" },
  { id: "folklore_J_007", topic: "folklore", letter: "J", question: "Con la J: Celebración religiosa especial con tradición popular.", answer: "Jubileo" },
  { id: "folklore_J_008", topic: "folklore", letter: "J", question: "Con la J: Ambiente de ruido y alegría en una fiesta.", answer: "Jaleo" },
  { id: "folklore_J_009", topic: "folklore", letter: "J", question: "Con la J: Copla o canción popular llamada ‘jardinera’ en algunas zonas.", answer: "Jardinera" },
  { id: "folklore_J_010", topic: "folklore", letter: "J", question: "Con la J: Ciudad con tradiciones flamencas y feria.", answer: "Jerez" },
  { id: "folklore_J_011", topic: "folklore", letter: "J", question: "Con la J: Pescador/tradición de jábegas en Málaga.", answer: "Jabeguero" },
  { id: "folklore_J_012", topic: "folklore", letter: "J", question: "Con la J: Tienda; en ferias, recreaciones y mercados temáticos.", answer: "Jaima" },
  { id: "folklore_J_013", topic: "folklore", letter: "J", question: "Con la J: Nombre coloquial de juerga; ambiente festivo.", answer: "Jolgón" },
  { id: "folklore_J_014", topic: "folklore", letter: "J", question: "Con la J: Objeto popular en ferias y fiestas para niños.", answer: "Juguete" },
  { id: "folklore_J_015", topic: "folklore", letter: "J", question: "Con la J: Muñeco que se quema o apalea en ritos populares.", answer: "Judas" },
  { id: "folklore_L_001", topic: "folklore", letter: "L", question: "Con la L: Relato popular transmitido de generación en generación.", answer: "Leyenda" },
  { id: "folklore_L_002", topic: "folklore", letter: "L", question: "Con la L: Símbolo en cuentos y noches de verbena.", answer: "Luciérnaga" },
  { id: "folklore_L_003", topic: "folklore", letter: "L", question: "Con la L: Hoguera o fuego ritual en fiestas de invierno.", answer: "Luminaria" },
  { id: "folklore_L_004", topic: "folklore", letter: "L", question: "Con la L: Adorno en trajes tradicionales.", answer: "Lazo" },
  { id: "folklore_L_005", topic: "folklore", letter: "L", question: "Con la L: Instrumento antiguo; aparece en imaginario popular.", answer: "Lira" },
  { id: "folklore_L_006", topic: "folklore", letter: "L", question: "Con la L: Lugar de sidra; tradición asturiana.", answer: "Llagar" },
  { id: "folklore_L_007", topic: "folklore", letter: "L", question: "Con la L: Figura del campo en romances y canciones populares.", answer: "Labriego" },
  { id: "folklore_L_008", topic: "folklore", letter: "L", question: "Con la L: Canto de números en tradiciones navideñas (lotería).", answer: "Lotería" },
  { id: "folklore_L_009", topic: "folklore", letter: "L", question: "Con la L: Personaje en coplas y cuentos (llorón).", answer: "Llorón" },
  { id: "folklore_L_010", topic: "folklore", letter: "L", question: "Con la L: Bebida típica en fiestas (p. ej., León en SemanaSanta).", answer: "Limonada" },
  { id: "folklore_L_011", topic: "folklore", letter: "L", question: "Con la L: Figura del campo en romances y canciones populares.", answer: "Labriego" },
  { id: "folklore_L_012", topic: "folklore", letter: "L", question: "Con la L: Figura de cantares y tradiciones rurales.", answer: "Labrador" },
  { id: "folklore_L_013", topic: "folklore", letter: "L", question: "Con la L: Copla breve cantada.", answer: "Letrilla" },
  { id: "folklore_L_014", topic: "folklore", letter: "L", question: "Con la L: Lugar de prensado tradicional (vino/aceite).", answer: "Lagar" },
  { id: "folklore_L_015", topic: "folklore", letter: "L", question: "Con la L: Figura del campo en romances y canciones populares.", answer: "Labriego" },
  { id: "folklore_M_001", topic: "folklore", letter: "M", question: "Con la M: Danza tradicional gallega.", answer: "Muiñeira" },
  { id: "folklore_M_002", topic: "folklore", letter: "M", question: "Con la M: Prenda tradicional en celebraciones y SemanaSanta.", answer: "Mantilla" },
  { id: "folklore_M_003", topic: "folklore", letter: "M", question: "Con la M: Fiesta rural de sacrificio del cerdo y comida comunitaria.", answer: "Matanza" },
  { id: "folklore_M_004", topic: "folklore", letter: "M", question: "Con la M: Cantos/fiestas de mayo en varias regiones.", answer: "Mayos" },
  { id: "folklore_M_005", topic: "folklore", letter: "M", question: "Con la M: Figura para quemas y ritos (Judas, fallas).", answer: "Muñeco" },
  { id: "folklore_M_006", topic: "folklore", letter: "M", question: "Con la M: Fiesta con personajes enmascarados (Carnaval rural).", answer: "Mascarada" },
  { id: "folklore_M_007", topic: "folklore", letter: "M", question: "Con la M: Fiestas que recrean batallas y desfiles (Levante).", answer: "MorosyCristianos" },
  { id: "folklore_M_008", topic: "folklore", letter: "M", question: "Con la M: Canto/tonada; en uso popular, melodía cantada.", answer: "Melopea" },
  { id: "folklore_M_009", topic: "folklore", letter: "M", question: "Con la M: Canto religioso tradicional en SemanaSanta.", answer: "Miserere" },
  { id: "folklore_M_010", topic: "folklore", letter: "M", question: "Con la M: Canto/tonada; en uso popular, melodía cantada.", answer: "Melopea" },
  { id: "folklore_M_011", topic: "folklore", letter: "M", question: "Con la M: Material de cestería tradicional.", answer: "Mimbre" },
  { id: "folklore_M_012", topic: "folklore", letter: "M", question: "Con la M: Teatro/cortejo burlesco en fiestas.", answer: "Mojiganga" },
  { id: "folklore_M_013", topic: "folklore", letter: "M", question: "Con la M: Animal en romerías y tradiciones rurales.", answer: "Mula" },
  { id: "folklore_M_014", topic: "folklore", letter: "M", question: "Con la M: Pañuelo tradicional en trajes (Valencia/Cataluña).", answer: "Mocador" },
  { id: "folklore_M_015", topic: "folklore", letter: "M", question: "Con la M: Representación dramática religiosa (p. ej., Elche).", answer: "Misterio" },
  { id: "folklore_N_001", topic: "folklore", letter: "N", question: "Con la N: Penitente con túnica y capirote en procesiones.", answer: "Nazareno" },
  { id: "folklore_N_002", topic: "folklore", letter: "N", question: "Con la N: Noche del 24 de diciembre con cena y villancicos.", answer: "Nochebuena" },
  { id: "folklore_N_003", topic: "folklore", letter: "N", question: "Con la N: Noche del 31 de diciembre con uvas y celebración.", answer: "Nochevieja" },
  { id: "folklore_N_004", topic: "folklore", letter: "N", question: "Con la N: Rezo de nueve días, tradición en fiestas religiosas.", answer: "Novena" },
  { id: "folklore_N_005", topic: "folklore", letter: "N", question: "Con la N: Canción de cuna tradicional.", answer: "Nana" },
  { id: "folklore_N_006", topic: "folklore", letter: "N", question: "Con la N: Elemento en villancicos y ritos de invierno (imaginario).", answer: "Nieve" },
  { id: "folklore_N_007", topic: "folklore", letter: "N", question: "Con la N: Motivo y técnica en artes populares (macramé).", answer: "Nudo" },
  { id: "folklore_N_008", topic: "folklore", letter: "N", question: "Con la N: Ambiente de cuentos y leyendas rurales.", answer: "Niebla" },
  { id: "folklore_N_009", topic: "folklore", letter: "N", question: "Con la N: Elemento tradicional de riego; cultura popular.", answer: "Noria" },
  { id: "folklore_N_010", topic: "folklore", letter: "N", question: "Con la N: Muñeco satírico de las Fallas.", answer: "Ninot" },
  { id: "folklore_N_011", topic: "folklore", letter: "N", question: "Con la N: Árbol presente en fiestas y topónimos tradicionales.", answer: "Noguera" },
  { id: "folklore_N_012", topic: "folklore", letter: "N", question: "Con la N: Elemento en villancicos y ritos de invierno (imaginario).", answer: "Nieve" },
  { id: "folklore_N_013", topic: "folklore", letter: "N", question: "Con la N: Fiestas con belenes, villancicos y tradiciones.", answer: "Navidad" },
  { id: "folklore_N_014", topic: "folklore", letter: "N", question: "Con la N: Relacionado con arte y tradiciones de Granada/Alhambra.", answer: "Nazarí" },
  { id: "folklore_N_015", topic: "folklore", letter: "N", question: "Con la N: Elemento en villancicos y ritos de invierno (imaginario).", answer: "Nieve" },
  { id: "folklore_Ñ_001", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Grupo festivo que organiza y anima las fiestas; contiene Ñ.", answer: "Peña" },
  { id: "folklore_Ñ_002", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Instrumento de percusión en danzas; contiene Ñ.", answer: "Castañuelas" },
  { id: "folklore_Ñ_003", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Baile gallego; contiene Ñ.", answer: "Muiñeira" },
  { id: "folklore_Ñ_004", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Figura central del belén; contiene Ñ.", answer: "NiñoJesús" },
  { id: "folklore_Ñ_005", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Celebración del 1 de enero; contiene Ñ.", answer: "AñoNuevo" },
  { id: "folklore_Ñ_006", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Parque y símbolo cultural del sur; contiene Ñ.", answer: "Doñana" },
  { id: "folklore_Ñ_007", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Localidad con fiestas y tradición; contiene Ñ.", answer: "Peñíscola" },
  { id: "folklore_Ñ_008", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Material vegetal en artesanía; contiene Ñ.", answer: "Cañizo" },
  { id: "folklore_Ñ_009", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Bandera tradicional valenciana; contiene Ñ.", answer: "Señera" },
  { id: "folklore_Ñ_010", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Término histórico presente en tradiciones locales; contiene Ñ.", answer: "Señorío" },
  { id: "folklore_Ñ_011", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Juego festivo popular; contiene Ñ.", answer: "Piñata" },
  { id: "folklore_Ñ_012", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Dulce tradicional; contiene Ñ.", answer: "Buñuelo" },
  { id: "folklore_Ñ_013", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Método popular para ‘predecir’ el tiempo; contiene Ñ.", answer: "Cabañuela" },
  { id: "folklore_Ñ_014", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Vía pecuaria ligada a cultura rural; contiene Ñ.", answer: "Cañada" },
  { id: "folklore_Ñ_015", topic: "folklore", letter: "Ñ", question: "Contiene la Ñ: Pigmento usado en tintes tradicionales; contiene Ñ.", answer: "Añil" },
  { id: "folklore_O_001", topic: "folklore", letter: "O", question: "Con la O: Entrega ritual de flores o presentes (p. ej., patronas).", answer: "Ofrenda" },
  { id: "folklore_O_002", topic: "folklore", letter: "O", question: "Con la O: Rezo comunitario en fiestas religiosas.", answer: "Oración" },
  { id: "folklore_O_003", topic: "folklore", letter: "O", question: "Con la O: Grupo musical típico de verbenas.", answer: "Orquesta" },
  { id: "folklore_O_004", topic: "folklore", letter: "O", question: "Con la O: Artesanía tradicional en plata/oro (joyas populares).", answer: "Orfebrería" },
  { id: "folklore_O_005", topic: "folklore", letter: "O", question: "Con la O: Instrumento de viento usado en música popular.", answer: "Ocarina" },
  { id: "folklore_O_006", topic: "folklore", letter: "O", question: "Con la O: Metal en joyería y ornamentos tradicionales.", answer: "Oro" },
  { id: "folklore_O_007", topic: "folklore", letter: "O", question: "Con la O: Dulce/hostia; tradición en algunas fiestas.", answer: "Oblea" },
  { id: "folklore_O_008", topic: "folklore", letter: "O", question: "Con la O: Animal presente en trashumancia y cultura pastoril.", answer: "Oveja" },
  { id: "folklore_O_009", topic: "folklore", letter: "O", question: "Con la O: Motivo en cantos marineros y fiestas costeras.", answer: "Ola" },
  { id: "folklore_O_010", topic: "folklore", letter: "O", question: "Con la O: Artesanía tradicional en plata/oro (joyas populares).", answer: "Orfebrería" },
  { id: "folklore_O_011", topic: "folklore", letter: "O", question: "Con la O: Estación de vendimias y fiestas rurales.", answer: "Otoño" },
  { id: "folklore_O_012", topic: "folklore", letter: "O", question: "Con la O: Árbol simbólico en cultura mediterránea española.", answer: "Olivo" },
  { id: "folklore_O_013", topic: "folklore", letter: "O", question: "Con la O: Artesanía tradicional en plata/oro (joyas populares).", answer: "Orfebrería" },
  { id: "folklore_O_014", topic: "folklore", letter: "O", question: "Con la O: Detalle en trajes y bordados tradicionales.", answer: "Ojal" },
  { id: "folklore_O_015", topic: "folklore", letter: "O", question: "Con la O: Aguardiente tradicional en el noroeste.", answer: "Orujo" },
  { id: "folklore_P_001", topic: "folklore", letter: "P", question: "Con la P: Desfile religioso con imágenes y cofradías.", answer: "Procesión" },
  { id: "folklore_P_002", topic: "folklore", letter: "P", question: "Con la P: Instrumento de percusión popular.", answer: "Pandereta" },
  { id: "folklore_P_003", topic: "folklore", letter: "P", question: "Con la P: Música y baile asociado a fiestas y plazas.", answer: "Pasodoble" },
  { id: "folklore_P_004", topic: "folklore", letter: "P", question: "Con la P: Danza con palos típica de varias regiones.", answer: "Paloteo" },
  { id: "folklore_P_005", topic: "folklore", letter: "P", question: "Con la P: Persona que hace peregrinación (Camino).", answer: "Peregrino" },
  { id: "folklore_P_006", topic: "folklore", letter: "P", question: "Con la P: Quien anuncia el inicio de fiestas con un pregón.", answer: "Pregonero" },
  { id: "folklore_P_007", topic: "folklore", letter: "P", question: "Con la P: Adorno tradicional del cabello.", answer: "Peineta" },
  { id: "folklore_P_008", topic: "folklore", letter: "P", question: "Con la P: Complemento típico en trajes y peñas.", answer: "Pañuelo" },
  { id: "folklore_P_009", topic: "folklore", letter: "P", question: "Con la P: Guiso tradicional en celebraciones familiares.", answer: "Puchero" },
  { id: "folklore_P_010", topic: "folklore", letter: "P", question: "Con la P: Representación navideña con pastores.", answer: "Pastorela" },
  { id: "folklore_P_011", topic: "folklore", letter: "P", question: "Con la P: Elemento de mascletàs, tracas y fuegos.", answer: "Pólvora" },
  { id: "folklore_P_012", topic: "folklore", letter: "P", question: "Con la P: Arte de fuegos artificiales en fiestas.", answer: "Pirotecnia" },
  { id: "folklore_P_013", topic: "folklore", letter: "P", question: "Con la P: Humor popular y travieso en cuentos y refranes.", answer: "Picaresca" },
  { id: "folklore_P_014", topic: "folklore", letter: "P", question: "Con la P: Devoción a una imagen mariana (SemanaSanta).", answer: "Piedad" },
  { id: "folklore_P_015", topic: "folklore", letter: "P", question: "Con la P: Fiesta del Pilar en Zaragoza, con tradición popular.", answer: "Pilar" },
  { id: "folklore_Q_001", topic: "folklore", letter: "Q", question: "Contiene la Q: Ritual gallego con aguardiente y conjuro; contiene Q.", answer: "Queimada" },
  { id: "folklore_Q_002", topic: "folklore", letter: "Q", question: "Contiene la Q: Fiesta juvenil ligada al reclutamiento tradicional; contiene Q.", answer: "Quintos" },
  { id: "folklore_Q_003", topic: "folklore", letter: "Q", question: "Contiene la Q: Feria popular de barrio o pueblo; contiene Q.", answer: "Quermés" },
  { id: "folklore_Q_004", topic: "folklore", letter: "Q", question: "Contiene la Q: Figura literaria muy presente en cultura popular; contiene Q.", answer: "Quijote" },
  { id: "folklore_Q_005", topic: "folklore", letter: "Q", question: "Contiene la Q: Lugar preferido del toro; término de fiesta taurina; contiene Q.", answer: "Querencia" },
  { id: "folklore_Q_006", topic: "folklore", letter: "Q", question: "Contiene la Q: Periodo de fiestas patronales de quince días; contiene Q.", answer: "Quincena" },
  { id: "folklore_Q_007", topic: "folklore", letter: "Q", question: "Contiene la Q: Vendedor ambulante en ferias; contiene Q.", answer: "Quinquillero" },
  { id: "folklore_Q_008", topic: "folklore", letter: "Q", question: "Contiene la Q: Dulce tradicional (Cantabria); contiene Q.", answer: "Quesada" },
  { id: "folklore_Q_009", topic: "folklore", letter: "Q", question: "Contiene la Q: Marisco típico de costas; gastronomía popular; contiene Q.", answer: "Quisquilla" },
  { id: "folklore_Q_010", topic: "folklore", letter: "Q", question: "Contiene la Q: Objetos pequeños vendidos en ferias; contiene Q.", answer: "Quincalla" },
  { id: "folklore_Q_011", topic: "folklore", letter: "Q", question: "Contiene la Q: Paso/gesto en baile o lidia; contiene Q.", answer: "Quiebro" },
  { id: "folklore_Q_012", topic: "folklore", letter: "Q", question: "Contiene la Q: Sonido de campanas; contiene Q.", answer: "Esquila" },
  { id: "folklore_Q_013", topic: "folklore", letter: "Q", question: "Contiene la Q: Reunión de brujas; contiene Q.", answer: "Aquelarre" },
  { id: "folklore_Q_014", topic: "folklore", letter: "Q", question: "Contiene la Q: Dulce de feria; contiene Q.", answer: "Barquillo" },
  { id: "folklore_Q_015", topic: "folklore", letter: "Q", question: "Contiene la Q: Vendedor ambulante en ferias; contiene Q.", answer: "Quinquillero" },
  { id: "folklore_R_001", topic: "folklore", letter: "R", question: "Con la R: Peregrinación festiva a una ermita.", answer: "Romería" },
  { id: "folklore_R_002", topic: "folklore", letter: "R", question: "Con la R: Grupo de cuerda que toca en fiestas.", answer: "Rondalla" },
  { id: "folklore_R_003", topic: "folklore", letter: "R", question: "Con la R: Instrumento de cuerda frotada tradicional.", answer: "Rabel" },
  { id: "folklore_R_004", topic: "folklore", letter: "R", question: "Con la R: Dicho popular con enseñanza.", answer: "Refrán" },
  { id: "folklore_R_005", topic: "folklore", letter: "R", question: "Con la R: Rezo colectivo en celebraciones religiosas.", answer: "Rosario" },
  { id: "folklore_R_006", topic: "folklore", letter: "R", question: "Con la R: Romería famosa en Andalucía (ElRocío).", answer: "Rocío" },
  { id: "folklore_R_007", topic: "folklore", letter: "R", question: "Con la R: Lidia a caballo en festejos taurinos.", answer: "Rejoneo" },
  { id: "folklore_R_008", topic: "folklore", letter: "R", question: "Con la R: Canto o serenata por las calles.", answer: "Ronda" },
  { id: "folklore_R_009", topic: "folklore", letter: "R", question: "Con la R: Ofrenda vegetal decorada en fiestas (ramo leonés).", answer: "Ramo" },
  { id: "folklore_R_010", topic: "folklore", letter: "R", question: "Con la R: Técnica de rasgueo de guitarra en música popular.", answer: "Rasqueo" },
  { id: "folklore_R_011", topic: "folklore", letter: "R", question: "Con la R: Práctica simbólica repetida en celebraciones.", answer: "Ritual" },
  { id: "folklore_R_012", topic: "folklore", letter: "R", question: "Con la R: Toque rápido de campanas en fiestas.", answer: "Repique" },
  { id: "folklore_R_013", topic: "folklore", letter: "R", question: "Con la R: Hierba; también apodo en coplas (tradición oral).", answer: "Romerito" },
  { id: "folklore_R_014", topic: "folklore", letter: "R", question: "Con la R: Técnica de rasgueo de guitarra en música popular.", answer: "Rasqueo" },
  { id: "folklore_R_015", topic: "folklore", letter: "R", question: "Con la R: Baile en círculo típico de fiestas populares.", answer: "Rueda" },
  { id: "folklore_S_001", topic: "folklore", letter: "S", question: "Con la S: Baile y cante popular andaluz.", answer: "Sevillana" },
  { id: "folklore_S_002", topic: "folklore", letter: "S", question: "Con la S: Danza tradicional catalana en corro.", answer: "Sardana" },
  { id: "folklore_S_003", topic: "folklore", letter: "S", question: "Con la S: Canto religioso a capela en SemanaSanta.", answer: "Saeta" },
  { id: "folklore_S_004", topic: "folklore", letter: "S", question: "Con la S: Teatro breve cómico de tradición popular.", answer: "Sainete" },
  { id: "folklore_S_005", topic: "folklore", letter: "S", question: "Con la S: Zona montañosa ligada a tradiciones rurales.", answer: "Serranía" },
  { id: "folklore_S_006", topic: "folklore", letter: "S", question: "Con la S: Melodías tradicionales; “sones” en música popular.", answer: "Sones" },
  { id: "folklore_S_007", topic: "folklore", letter: "S", question: "Con la S: Fiesta de SanJuan con hogueras y ritos.", answer: "Sanjuanada" },
  { id: "folklore_S_008", topic: "folklore", letter: "S", question: "Con la S: Humo aromático para ‘limpiar’ o bendecir.", answer: "Sahumerio" },
  { id: "folklore_S_009", topic: "folklore", letter: "S", question: "Con la S: Elemento en juegos y danzas (tirar de la soga).", answer: "Soga" },
  { id: "folklore_S_010", topic: "folklore", letter: "S", question: "Con la S: Prenda típica en algunos trajes regionales.", answer: "Sombrero" },
  { id: "folklore_S_011", topic: "folklore", letter: "S", question: "Con la S: Personaje de leyendas (la serrana) en tradición oral.", answer: "Serrana" },
  { id: "folklore_S_012", topic: "folklore", letter: "S", question: "Con la S: Ruta de romería o paso tradicional.", answer: "Senda" },
  { id: "folklore_S_013", topic: "folklore", letter: "S", question: "Con la S: Figura central de fiestas patronales.", answer: "Santo" },
  { id: "folklore_S_014", topic: "folklore", letter: "S", question: "Con la S: Zona montañosa ligada a tradiciones rurales.", answer: "Serranía" },
  { id: "folklore_S_015", topic: "folklore", letter: "S", question: "Con la S: Discurso religioso tradicional en fiestas (misa mayor).", answer: "Sermón" },
  { id: "folklore_T_001", topic: "folklore", letter: "T", question: "Con la T: Fiesta de tambores (SanSebastián).", answer: "Tamborrada" },
  { id: "folklore_T_002", topic: "folklore", letter: "T", question: "Con la T: Instrumento clave en SemanaSanta y fiestas.", answer: "Tambor" },
  { id: "folklore_T_003", topic: "folklore", letter: "T", question: "Con la T: Tira de petardos típica en fiestas valencianas.", answer: "Traca" },
  { id: "folklore_T_004", topic: "folklore", letter: "T", question: "Con la T: Ronda universitaria con música y capas.", answer: "Tuna" },
  { id: "folklore_T_005", topic: "folklore", letter: "T", question: "Con la T: Juego de cartas tradicional en algunas regiones.", answer: "Truco" },
  { id: "folklore_T_006", topic: "folklore", letter: "T", question: "Con la T: Dulce típico de Navidad.", answer: "Turrón" },
  { id: "folklore_T_007", topic: "folklore", letter: "T", question: "Con la T: Tradición taurina en fiestas populares.", answer: "Toreo" },
  { id: "folklore_T_008", topic: "folklore", letter: "T", question: "Con la T: Vestimenta regional usada en celebraciones.", answer: "Traje" },
  { id: "folklore_T_009", topic: "folklore", letter: "T", question: "Con la T: Estructura para llevar imágenes en procesiones.", answer: "Trono" },
  { id: "folklore_T_010", topic: "folklore", letter: "T", question: "Con la T: Lugar de reunión con música y tradición oral.", answer: "Taberna" },
  { id: "folklore_T_011", topic: "folklore", letter: "T", question: "Con la T: Melodía o canción tradicional (Asturias, etc.).", answer: "Tonada" },
  { id: "folklore_T_012", topic: "folklore", letter: "T", question: "Con la T: Palo flamenco más pausado.", answer: "Tiento" },
  { id: "folklore_T_013", topic: "folklore", letter: "T", question: "Con la T: Labor agrícola tradicional con fiesta asociada.", answer: "Trilla" },
  { id: "folklore_T_014", topic: "folklore", letter: "T", question: "Con la T: Leño encendido usado en hogueras rituales.", answer: "Tizón" },
  { id: "folklore_T_015", topic: "folklore", letter: "T", question: "Con la T: Tambor pequeño usado con flauta en folclore.", answer: "Tamboril" },
  { id: "folklore_U_001", topic: "folklore", letter: "U", question: "Con la U: Tradición de las doce uvas en Nochevieja.", answer: "Uvas" },
  { id: "folklore_U_002", topic: "folklore", letter: "U", question: "Con la U: Hilos base del tejido en artes populares.", answer: "Urdimbre" },
  { id: "folklore_U_003", topic: "folklore", letter: "U", question: "Con la U: Conjunto de herramientas para artesanía y oficios.", answer: "Utillaje" },
  { id: "folklore_U_004", topic: "folklore", letter: "U", question: "Con la U: Lugar simbólico en ritos domésticos (entrada de casa).", answer: "Umbral" },
  { id: "folklore_U_005", topic: "folklore", letter: "U", question: "Con la U: Preparado tradicional de herbolario popular.", answer: "Ungüento" },
  { id: "folklore_U_006", topic: "folklore", letter: "U", question: "Con la U: Ave asociada a supersticiones y cuentos.", answer: "Urraca" },
  { id: "folklore_U_007", topic: "folklore", letter: "U", question: "Con la U: Folclore de barrio: verbenas, pregones y peñas.", answer: "Urbano" },
  { id: "folklore_U_008", topic: "folklore", letter: "U", question: "Con la U: Rito religioso; tradición en celebraciones.", answer: "Unción" },
  { id: "folklore_U_009", topic: "folklore", letter: "U", question: "Con la U: Ave del norte presente en cultura rural y cuentos.", answer: "Urogallo" },
  { id: "folklore_U_010", topic: "folklore", letter: "U", question: "Con la U: Comarca gallega con tradición y feria de quesos.", answer: "Ulloa" },
  { id: "folklore_U_011", topic: "folklore", letter: "U", question: "Con la U: Ave del norte presente en cultura rural y cuentos.", answer: "Urogallo" },
  { id: "folklore_U_012", topic: "folklore", letter: "U", question: "Con la U: Sonido ritual en algunos festejos (metáfora popular).", answer: "Ulular" },
  { id: "folklore_U_013", topic: "folklore", letter: "U", question: "Con la U: Costumbre transmitida en una comunidad.", answer: "Usanza" },
  { id: "folklore_U_014", topic: "folklore", letter: "U", question: "Con la U: Objeto ceremonial/funerario en cultura material.", answer: "Urna" },
  { id: "folklore_U_015", topic: "folklore", letter: "U", question: "Con la U: Ciudad andaluza con tradición flamenca y devociones.", answer: "Utrera" },
  { id: "folklore_V_001", topic: "folklore", letter: "V", question: "Con la V: Fiesta nocturna con música en plazas.", answer: "Verbena" },
  { id: "folklore_V_002", topic: "folklore", letter: "V", question: "Con la V: Canto tradicional de Navidad.", answer: "Villancico" },
  { id: "folklore_V_003", topic: "folklore", letter: "V", question: "Con la V: Figura mariana patrona de pueblos y barrios.", answer: "Virgen" },
  { id: "folklore_V_004", topic: "folklore", letter: "V", question: "Con la V: Instrumento histórico presente en tradición musical.", answer: "Vihuela" },
  { id: "folklore_V_005", topic: "folklore", letter: "V", question: "Con la V: Promesa popular a un santo (voto perpetuo).", answer: "Voto" },
  { id: "folklore_V_006", topic: "folklore", letter: "V", question: "Con la V: Luz ritual en procesiones y vigilias.", answer: "Velas" },
  { id: "folklore_V_007", topic: "folklore", letter: "V", question: "Con la V: Respeto devocional a imágenes.", answer: "Veneración" },
  { id: "folklore_V_008", topic: "folklore", letter: "V", question: "Con la V: Posada rural; escenario de cuentos y tradiciones.", answer: "Venta" },
  { id: "folklore_V_009", topic: "folklore", letter: "V", question: "Con la V: Bastón de mando en autoridades festivas.", answer: "Vara" },
  { id: "folklore_V_010", topic: "folklore", letter: "V", question: "Con la V: Prenda típica en trajes regionales.", answer: "Vestido" },
  { id: "folklore_V_011", topic: "folklore", letter: "V", question: "Con la V: Cosecha de uva con fiestas del vino.", answer: "Vendimia" },
  { id: "folklore_V_012", topic: "folklore", letter: "V", question: "Con la V: Elemento en ritos meteorológicos y refranes.", answer: "Viento" },
  { id: "folklore_V_013", topic: "folklore", letter: "V", question: "Con la V: Día previo de fiesta grande (víspera patronal).", answer: "Víspera" },
  { id: "folklore_V_014", topic: "folklore", letter: "V", question: "Con la V: Sonido en tambores y palmas (compás).", answer: "Vibración" },
  { id: "folklore_V_015", topic: "folklore", letter: "V", question: "Con la V: Lana de oveja; economía y cultura pastoril.", answer: "Vellón" },
  { id: "folklore_X_001", topic: "folklore", letter: "X", question: "Contiene la X: Año/celebración del CaminoDeSantiago; contiene X.", answer: "Xacobeo" },
  { id: "folklore_X_002", topic: "folklore", letter: "X", question: "Contiene la X: Flauta vasca de tres agujeros; contiene X.", answer: "Txistu" },
  { id: "folklore_X_003", topic: "folklore", letter: "X", question: "Contiene la X: Instrumento vasco de percusión; contiene X.", answer: "Txalaparta" },
  { id: "folklore_X_004", topic: "folklore", letter: "X", question: "Contiene la X: Ofrenda artística/devocional; contiene X.", answer: "Exvoto" },
  { id: "folklore_X_005", topic: "folklore", letter: "X", question: "Contiene la X: Tema místico en imaginería; contiene X.", answer: "Extasis" },
  { id: "folklore_X_006", topic: "folklore", letter: "X", question: "Contiene la X: Marco cultural de una tradición; contiene X.", answer: "Contexto" },
  { id: "folklore_X_007", topic: "folklore", letter: "X", question: "Contiene la X: Coplas y romances escritos; contiene X.", answer: "Texto" },
  { id: "folklore_X_008", topic: "folklore", letter: "X", question: "Contiene la X: Rito popular-religioso; contiene X.", answer: "Exorcismo" },
  { id: "folklore_X_009", topic: "folklore", letter: "X", question: "Contiene la X: Tema de cantos y memoria popular; contiene X.", answer: "Exilio" },
  { id: "folklore_X_010", topic: "folklore", letter: "X", question: "Contiene la X: Fiesta muy intensa; ‘exceso’ festivo; contiene X.", answer: "Exceso" },
  { id: "folklore_X_011", topic: "folklore", letter: "X", question: "Contiene la X: Mezcla de tradiciones locales; contiene X.", answer: "Mixtura" },
  { id: "folklore_X_012", topic: "folklore", letter: "X", question: "Contiene la X: Ritos funerarios tradicionales; contiene X.", answer: "Exequias" },
  { id: "folklore_X_013", topic: "folklore", letter: "X", question: "Contiene la X: Pátina en campanas/metal de tradición; contiene X.", answer: "Oxido" },
  { id: "folklore_X_014", topic: "folklore", letter: "X", question: "Contiene la X: Sección extra en programa de fiestas; contiene X.", answer: "Anexo" },
  { id: "folklore_X_015", topic: "folklore", letter: "X", question: "Contiene la X: Encina pequeña; paisaje rural; contiene X.", answer: "Coxcoja" },
  { id: "folklore_Y_001", topic: "folklore", letter: "Y", question: "Contiene la Y: Persona que organiza una fiesta patronal; contiene Y.", answer: "Mayordomo" },
  { id: "folklore_Y_002", topic: "folklore", letter: "Y", question: "Contiene la Y: Juego infantil tradicional; contiene Y.", answer: "Rayuela" },
  { id: "folklore_Y_003", topic: "folklore", letter: "Y", question: "Contiene la Y: Figura de animación en ferias; contiene Y.", answer: "Payaso" },
  { id: "folklore_Y_004", topic: "folklore", letter: "Y", question: "Contiene la Y: Animal en escenas navideñas y fiestas rurales; contiene Y.", answer: "Buey" },
  { id: "folklore_Y_005", topic: "folklore", letter: "Y", question: "Contiene la Y: Estética festiva inspirada en Goya; contiene Y.", answer: "Goyesco" },
  { id: "folklore_Y_006", topic: "folklore", letter: "Y", question: "Contiene la Y: Bastón de pastor; contiene Y.", answer: "Cayado" },
  { id: "folklore_Y_007", topic: "folklore", letter: "Y", question: "Contiene la Y: Bastón de pastor; contiene Y.", answer: "Cayado" },
  { id: "folklore_Y_008", topic: "folklore", letter: "Y", question: "Contiene la Y: Relato popular; contiene Y.", answer: "Leyenda" },
  { id: "folklore_Y_009", topic: "folklore", letter: "Y", question: "Contiene la Y: Bastón de pastor; contiene Y.", answer: "Cayado" },
  { id: "folklore_Y_010", topic: "folklore", letter: "Y", question: "Contiene la Y: Referencia temporal común en romances; contiene Y.", answer: "Ayer" },
  { id: "folklore_Y_011", topic: "folklore", letter: "Y", question: "Contiene la Y: Bastón de pastor; contiene Y.", answer: "Cayado" },
  { id: "folklore_Y_012", topic: "folklore", letter: "Y", question: "Contiene la Y: Bastón de pastor; contiene Y.", answer: "Cayado" },
  { id: "folklore_Y_013", topic: "folklore", letter: "Y", question: "Contiene la Y: Práctica previa de una comparsa; contiene Y.", answer: "Ensayo" },
  { id: "folklore_Y_014", topic: "folklore", letter: "Y", question: "Contiene la Y: Relacionado con dehesas y cultura ganadera; contiene Y.", answer: "Boyal" },
  { id: "folklore_Y_015", topic: "folklore", letter: "Y", question: "Contiene la Y: Institución que suele organizar fiestas locales; contiene Y.", answer: "Ayuntamiento" },
  { id: "folklore_Z_001", topic: "folklore", letter: "Z", question: "Con la Z: Instrumento de fricción típico en Navidad.", answer: "Zambomba" },
  { id: "folklore_Z_002", topic: "folklore", letter: "Z", question: "Con la Z: Género escénico musical español.", answer: "Zarzuela" },
  { id: "folklore_Z_003", topic: "folklore", letter: "Z", question: "Con la Z: Joven pastor en romances y cuentos rurales.", answer: "Zagal" },
  { id: "folklore_Z_004", topic: "folklore", letter: "Z", question: "Con la Z: Persona a la que se atribuye encontrar agua; creencia popular.", answer: "Zahorí" },
  { id: "folklore_Z_005", topic: "folklore", letter: "Z", question: "Con la Z: Calzado en danzas y comparsas.", answer: "Zapatilla" },
  { id: "folklore_Z_006", topic: "folklore", letter: "Z", question: "Con la Z: Bebida popular de fiestas (vino, fruta, azúcar).", answer: "Zurracapote" },
  { id: "folklore_Z_007", topic: "folklore", letter: "Z", question: "Con la Z: Tamiz tradicional en labores rurales.", answer: "Zaranda" },
  { id: "folklore_Z_008", topic: "folklore", letter: "Z", question: "Con la Z: Plaza/centro urbano donde se celebran fiestas (uso común).", answer: "Zócalo" },
  { id: "folklore_Z_009", topic: "folklore", letter: "Z", question: "Con la Z: Bolsa de pastor tradicional.", answer: "Zurrón" },
  { id: "folklore_Z_010", topic: "folklore", letter: "Z", question: "Con la Z: Planta presente en cuentos y simbolismo rural.", answer: "Zarza" },
  { id: "folklore_Z_011", topic: "folklore", letter: "Z", question: "Con la Z: Sonido; en folklore, insectos y ambiente de noche.", answer: "Zumbido" },
  { id: "folklore_Z_012", topic: "folklore", letter: "Z", question: "Con la Z: Motivo en artes populares (calendarios, símbolos).", answer: "Zodiaco" },
  { id: "folklore_Z_013", topic: "folklore", letter: "Z", question: "Con la Z: Bebida popular de fiestas (vino, fruta, azúcar).", answer: "Zurracapote" },
  { id: "folklore_Z_014", topic: "folklore", letter: "Z", question: "Con la Z: Interjección popular en humor oral.", answer: "Zasca" },
  { id: "folklore_Z_015", topic: "folklore", letter: "Z", question: "Con la Z: Bebida; en ferias, zumos y refrescos populares.", answer: "Zumo" },
];
