import type { QA } from "./types";

export const GEOGRAFIA: QA[] = [
  { id: "geografia_A_001", topic: "geografia", letter: "A", question: "Con la A: Comunidad autónoma del sur de España con capital en Sevilla.", answer: "Andalucía" },
  { id: "geografia_A_002", topic: "geografia", letter: "A", question: "Con la A: Comunidad autónoma donde se encuentran Zaragoza y parte de los Pirineos.", answer: "Aragón" },
  { id: "geografia_A_003", topic: "geografia", letter: "A", question: "Con la A: Comunidad autónoma del norte conocida por la Cordillera Cantábrica.", answer: "Asturias" },
  { id: "geografia_A_004", topic: "geografia", letter: "A", question: "Con la A: Provincia de Castilla-La Mancha en la Meseta Sur.", answer: "Albacete" },
  { id: "geografia_A_005", topic: "geografia", letter: "A", question: "Con la A: Provincia andaluza con el desierto de Tabernas.", answer: "Almería" },
  { id: "geografia_A_006", topic: "geografia", letter: "A", question: "Con la A: Pico más alto de los Pirineos.", answer: "Aneto" },
  { id: "geografia_A_007", topic: "geografia", letter: "A", question: "Con la A: Río de Sudamérica con una de las cuencas más grandes del planeta.", answer: "Amazonas" },
  { id: "geografia_A_008", topic: "geografia", letter: "A", question: "Con la A: Cordillera del noroeste de África.", answer: "Atlas" },
  { id: "geografia_A_009", topic: "geografia", letter: "A", question: "Con la A: Montaña más alta de América, en los Andes.", answer: "Aconcagua" },
  { id: "geografia_A_010", topic: "geografia", letter: "A", question: "Con la A: Laguna costera famosa junto a Valencia.", answer: "Albufera" },
  { id: "geografia_A_011", topic: "geografia", letter: "A", question: "Con la A: Medida de la altura sobre el nivel del mar.", answer: "Altitud" },
  { id: "geografia_A_012", topic: "geografia", letter: "A", question: "Con la A: Conjunto de islas próximas entre sí.", answer: "Archipiélago" },
  { id: "geografia_A_013", topic: "geografia", letter: "A", question: "Con la A: Depósito subterráneo de agua.", answer: "Acuífero" },
  { id: "geografia_A_014", topic: "geografia", letter: "A", question: "Con la A: Zona de arena, típica de costas y dunas.", answer: "Arenal" },
  { id: "geografia_A_015", topic: "geografia", letter: "A", question: "Con la A: Continente del polo sur cubierto en gran parte por hielo.", answer: "Antártida" },
  { id: "geografia_B_001", topic: "geografia", letter: "B", question: "Con la B: Ciudad española junto al Mediterráneo, capital de Cataluña.", answer: "Barcelona" },
  { id: "geografia_B_002", topic: "geografia", letter: "B", question: "Con la B: Archipiélago español en el Mediterráneo .", answer: "Baleares" },
  { id: "geografia_B_003", topic: "geografia", letter: "B", question: "Con la B: Ciudad del País Vasco junto a la ría del Nervión.", answer: "Bilbao" },
  { id: "geografia_B_004", topic: "geografia", letter: "B", question: "Con la B: Ciudad castellana en el norte de España, en el valle del Arlanzón.", answer: "Burgos" },
  { id: "geografia_B_005", topic: "geografia", letter: "B", question: "Con la B: Nombre histórico del valle y depresión del Guadalquivir .", answer: "Bética" },
  { id: "geografia_B_006", topic: "geografia", letter: "B", question: "Con la B: Mar del norte de Europa entre Escandinavia y el continente.", answer: "Báltico" },
  { id: "geografia_B_007", topic: "geografia", letter: "B", question: "Con la B: Estrecho que separa Europa y Asia en Estambul.", answer: "Bósforo" },
  { id: "geografia_B_008", topic: "geografia", letter: "B", question: "Con la B: Capital de Colombia, situada en una altiplanicie andina.", answer: "Bogotá" },
  { id: "geografia_B_009", topic: "geografia", letter: "B", question: "Con la B: Capital de Bélgica y sede de instituciones europeas.", answer: "Bruselas" },
  { id: "geografia_B_010", topic: "geografia", letter: "B", question: "Con la B: Gran isla del sudeste asiático compartida por varios países.", answer: "Borneo" },
  { id: "geografia_B_011", topic: "geografia", letter: "B", question: "Con la B: Gran río de Asia que atraviesa India y Bangladés.", answer: "Brahmaputra" },
  { id: "geografia_B_012", topic: "geografia", letter: "B", question: "Con la B: Estrecho entre Siberia y Alaska.", answer: "Bering" },
  { id: "geografia_B_013", topic: "geografia", letter: "B", question: "Con la B: Región del sureste de Europa con gran diversidad geográfica.", answer: "Balcánes" },
  { id: "geografia_B_014", topic: "geografia", letter: "B", question: "Con la B: Entrada del mar en la costa, generalmente amplia.", answer: "Bahía" },
  { id: "geografia_B_015", topic: "geografia", letter: "B", question: "Con la B: Dirección o zona de donde viene el viento .", answer: "Barlovento" },
  { id: "geografia_C_001", topic: "geografia", letter: "C", question: "Con la C: Comunidad autónoma del norte de España junto al mar Cantábrico.", answer: "Cantabria" },
  { id: "geografia_C_002", topic: "geografia", letter: "C", question: "Con la C: Nombre histórico de una gran región de la meseta española.", answer: "Castilla" },
  { id: "geografia_C_003", topic: "geografia", letter: "C", question: "Con la C: Comunidad autónoma del noreste de España con costa mediterránea.", answer: "Cataluña" },
  { id: "geografia_C_004", topic: "geografia", letter: "C", question: "Con la C: Archipiélago español en el Atlántico frente a África.", answer: "Canarias" },
  { id: "geografia_C_005", topic: "geografia", letter: "C", question: "Con la C: Ciudad y provincia andaluza en el Atlántico, cerca del Estrecho.", answer: "Cádiz" },
  { id: "geografia_C_006", topic: "geografia", letter: "C", question: "Con la C: Ciudad andaluza a orillas del Guadalquivir.", answer: "Córdoba" },
  { id: "geografia_C_007", topic: "geografia", letter: "C", question: "Con la C: Ciudad autónoma española en el norte de África.", answer: "Ceuta" },
  { id: "geografia_C_008", topic: "geografia", letter: "C", question: "Con la C: Mar que baña la costa norte de España.", answer: "Cantábrico" },
  { id: "geografia_C_009", topic: "geografia", letter: "C", question: "Con la C: Cabo gallego asociado al “fin de la tierra” en el Atlántico.", answer: "CaboFinisterre" },
  { id: "geografia_C_010", topic: "geografia", letter: "C", question: "Con la C: Cabo y parque natural en Almería, de costa volcánica.", answer: "CaboGata" },
  { id: "geografia_C_011", topic: "geografia", letter: "C", question: "Con la C: Cordillera entre el mar Negro y el mar Caspio.", answer: "Cáucaso" },
  { id: "geografia_C_012", topic: "geografia", letter: "C", question: "Con la C: Isla italiana del Mediterráneo.", answer: "Cerdeña" },
  { id: "geografia_C_013", topic: "geografia", letter: "C", question: "Con la C: Río de Norteamérica famoso por el Gran Cañón.", answer: "Colorado" },
  { id: "geografia_C_014", topic: "geografia", letter: "C", question: "Con la C: Línea de latitud cercana al polo con fenómenos de día/noche polar.", answer: "CírculoPolar" },
  { id: "geografia_C_015", topic: "geografia", letter: "C", question: "Con la C: Ciencia y técnica de elaborar mapas.", answer: "Cartografía" },
  { id: "geografia_D_001", topic: "geografia", letter: "D", question: "Con la D: Río que atraviesa el norte de España y desemboca en Portugal.", answer: "Duero" },
  { id: "geografia_D_002", topic: "geografia", letter: "D", question: "Con la D: Nombre portugués del río Duero; clave en la región vinícola.", answer: "Douro" },
  { id: "geografia_D_003", topic: "geografia", letter: "D", question: "Con la D: Capital de Irlanda, conocida por su río Liffey y su historia literaria.", answer: "Dublín" },
  { id: "geografia_D_004", topic: "geografia", letter: "D", question: "Con la D: Forma de desembocadura fluvial con varios brazos y sedimentos.", answer: "Delta" },
  { id: "geografia_D_005", topic: "geografia", letter: "D", question: "Con la D: Montículo de arena modelado por el viento.", answer: "Duna" },
  { id: "geografia_D_006", topic: "geografia", letter: "D", question: "Con la D: Región muy seca con escasas precipitaciones.", answer: "Desierto" },
  { id: "geografia_D_007", topic: "geografia", letter: "D", question: "Con la D: Zona de terreno más baja que su entorno .", answer: "Depresión" },
  { id: "geografia_D_008", topic: "geografia", letter: "D", question: "Con la D: Cordillera a lo largo de la costa adriática .", answer: "Dinarides" },
  { id: "geografia_D_009", topic: "geografia", letter: "D", question: "Con la D: Río europeo que cruza varias capitales y desemboca en el mar Negro.", answer: "Danubio" },
  { id: "geografia_D_010", topic: "geografia", letter: "D", question: "Con la D: Capital de Irlanda, en la desembocadura del río Liffey.", answer: "Dublín" },
  { id: "geografia_D_011", topic: "geografia", letter: "D", question: "Con la D: Capital de Senegal, en la península de Cabo Verde.", answer: "Dakar" },
  { id: "geografia_D_012", topic: "geografia", letter: "D", question: "Con la D: Parque nacional andaluz de marismas y biodiversidad.", answer: "Doñana" },
  { id: "geografia_D_013", topic: "geografia", letter: "D", question: "Con la D: Elevación submarina alargada, como las dorsales oceánicas.", answer: "Dorsal" },
  { id: "geografia_D_014", topic: "geografia", letter: "D", question: "Con la D: Tipo de límite de placas tectónicas donde se separan.", answer: "Divergente" },
  { id: "geografia_D_015", topic: "geografia", letter: "D", question: "Con la D: Gran cordillera submarina en el Atlántico.", answer: "DorsalAtlántica" },
  { id: "geografia_E_001", topic: "geografia", letter: "E", question: "Con la E: Río más caudaloso de España que desemboca en el Mediterráneo.", answer: "Ebro" },
  { id: "geografia_E_002", topic: "geografia", letter: "E", question: "Con la E: Comunidad autónoma del oeste de España, fronteriza con Portugal.", answer: "Extremadura" },
  { id: "geografia_E_003", topic: "geografia", letter: "E", question: "Con la E: Paso de mar angosto entre dos masas de tierra.", answer: "Estrecho" },
  { id: "geografia_E_004", topic: "geografia", letter: "E", question: "Con la E: Desembocadura donde se mezclan agua dulce y salada.", answer: "Estuario" },
  { id: "geografia_E_005", topic: "geografia", letter: "E", question: "Con la E: Momento del año con día y noche de duración similar.", answer: "Equinoccio" },
  { id: "geografia_E_006", topic: "geografia", letter: "E", question: "Con la E: Línea imaginaria que divide la Tierra en hemisferio norte y sur.", answer: "Ecuador" },
  { id: "geografia_E_007", topic: "geografia", letter: "E", question: "Con la E: País sudamericano atravesado por la línea del ecuador.", answer: "EcuadorPaís" },
  { id: "geografia_E_008", topic: "geografia", letter: "E", question: "Con la E: País europeo con costa adriática y zonas alpinas.", answer: "Eslovenia" },
  { id: "geografia_E_009", topic: "geografia", letter: "E", question: "Con la E: País africano con altiplanos y el valle del Rift.", answer: "Etiopía" },
  { id: "geografia_E_010", topic: "geografia", letter: "E", question: "Con la E: País báltico con numerosas islas en el mar Báltico.", answer: "Estonia" },
  { id: "geografia_E_011", topic: "geografia", letter: "E", question: "Con la E: Montaña más alta del mundo sobre el nivel del mar.", answer: "Everest" },
  { id: "geografia_E_012", topic: "geografia", letter: "E", question: "Con la E: Pico del Cáucaso, a menudo citado como el más alto de Europa.", answer: "Elbrus" },
  { id: "geografia_E_013", topic: "geografia", letter: "E", question: "Con la E: Desgaste del relieve por agua, viento o hielo.", answer: "Erosión" },
  { id: "geografia_E_014", topic: "geografia", letter: "E", question: "Con la E: Agua que fluye por la superficie tras lluvia o deshielo.", answer: "Escorrentía" },
  { id: "geografia_E_015", topic: "geografia", letter: "E", question: "Con la E: Entrada del mar menor que una bahía.", answer: "Ensenada" },
  { id: "geografia_F_001", topic: "geografia", letter: "F", question: "Con la F: Torre con luz para guiar navegación costera.", answer: "Faro" },
  { id: "geografia_F_002", topic: "geografia", letter: "F", question: "Con la F: Depresión profunda; en océanos, fosas de subducción.", answer: "Fosa" },
  { id: "geografia_F_003", topic: "geografia", letter: "F", question: "Con la F: Entrada estrecha del mar entre montañas, típica de Noruega.", answer: "Fiordo" },
  { id: "geografia_F_004", topic: "geografia", letter: "F", question: "Con la F: Isla canaria conocida por playas y paisajes áridos.", answer: "Fuerteventura" },
  { id: "geografia_F_005", topic: "geografia", letter: "F", question: "Con la F: Isla balear de aguas claras al sur de Ibiza.", answer: "Formentera" },
  { id: "geografia_F_006", topic: "geografia", letter: "F", question: "Con la F: Ciudad gallega con ría y tradición naval.", answer: "Ferrol" },
  { id: "geografia_F_007", topic: "geografia", letter: "F", question: "Con la F: Región europea histórica con llanuras y canales .", answer: "Flandes" },
  { id: "geografia_F_008", topic: "geografia", letter: "F", question: "Con la F: Monte Fuji en Japón, volcán emblemático.", answer: "Fujiyama" },
  { id: "geografia_F_009", topic: "geografia", letter: "F", question: "Con la F: Región costera del norte de Europa con islas y marismas.", answer: "Frisia" },
  { id: "geografia_F_010", topic: "geografia", letter: "F", question: "Con la F: País europeo que limita con España por los Pirineos.", answer: "Francia" },
  { id: "geografia_F_011", topic: "geografia", letter: "F", question: "Con la F: Límite político entre territorios o estados.", answer: "Frontera" },
  { id: "geografia_F_012", topic: "geografia", letter: "F", question: "Con la F: Relacionado con bosques y su gestión.", answer: "Forestal" },
  { id: "geografia_F_013", topic: "geografia", letter: "F", question: "Con la F: Hecho observable; en geografía, fenómenos climáticos o del relieve.", answer: "Fenómeno" },
  { id: "geografia_F_014", topic: "geografia", letter: "F", question: "Con la F: Relacionado con ríos y su dinámica.", answer: "Fluvial" },
  { id: "geografia_F_015", topic: "geografia", letter: "F", question: "Con la F: Relativo al nivel freático del agua subterránea.", answer: "Freatico" },
  { id: "geografia_G_001", topic: "geografia", letter: "G", question: "Con la G: Comunidad autónoma del noroeste de España con rías atlánticas.", answer: "Galicia" },
  { id: "geografia_G_002", topic: "geografia", letter: "G", question: "Con la G: Ciudad andaluza al pie de SierraNevada.", answer: "Granada" },
  { id: "geografia_G_003", topic: "geografia", letter: "G", question: "Con la G: Río andaluz que pasa por Córdoba y Sevilla.", answer: "Guadalquivir" },
  { id: "geografia_G_004", topic: "geografia", letter: "G", question: "Con la G: Río del oeste peninsular que marca tramos de frontera con Portugal.", answer: "Guadiana" },
  { id: "geografia_G_005", topic: "geografia", letter: "G", question: "Con la G: Sierra del SistemaCentral, conocida por el pico Almanzor.", answer: "Gredos" },
  { id: "geografia_G_006", topic: "geografia", letter: "G", question: "Con la G: Isla canaria con el Parque Nacional de Garajonay.", answer: "Gomera" },
  { id: "geografia_G_007", topic: "geografia", letter: "G", question: "Con la G: Estrecho y peñón clave entre Atlántico y Mediterráneo.", answer: "Gibraltar" },
  { id: "geografia_G_008", topic: "geografia", letter: "G", question: "Con la G: Provincia catalana con Pirineos y CostaBrava.", answer: "Girona" },
  { id: "geografia_G_009", topic: "geografia", letter: "G", question: "Con la G: Masa de hielo en movimiento que modela el relieve.", answer: "Glaciar" },
  { id: "geografia_G_010", topic: "geografia", letter: "G", question: "Con la G: Gran entrada del mar, como el golfo de Cádiz.", answer: "Golfo" },
  { id: "geografia_G_011", topic: "geografia", letter: "G", question: "Con la G: Ciencia que estudia la Tierra, rocas y procesos.", answer: "Geología" },
  { id: "geografia_G_012", topic: "geografia", letter: "G", question: "Con la G: Ciencia que estudia el espacio terrestre y sus paisajes.", answer: "Geografía" },
  { id: "geografia_G_013", topic: "geografia", letter: "G", question: "Con la G: Cambio progresivo en una magnitud .", answer: "Gradiente" },
  { id: "geografia_G_014", topic: "geografia", letter: "G", question: "Con la G: Energía procedente del calor interno de la Tierra.", answer: "Geotermia" },
  { id: "geografia_G_015", topic: "geografia", letter: "G", question: "Con la G: Gran isla ártica cubierta por hielo en gran parte.", answer: "Greenland" },
  { id: "geografia_H_001", topic: "geografia", letter: "H", question: "Con la H: Provincia andaluza con marismas y costa atlántica.", answer: "Huelva" },
  { id: "geografia_H_002", topic: "geografia", letter: "H", question: "Con la H: Provincia aragonesa con alta montaña pirenaica.", answer: "Huesca" },
  { id: "geografia_H_003", topic: "geografia", letter: "H", question: "Con la H: Cordillera asiática donde se encuentran ochomiles.", answer: "Himalaya" },
  { id: "geografia_H_004", topic: "geografia", letter: "H", question: "Con la H: Capital de Finlandia, junto al golfo de Finlandia.", answer: "Helsinki" },
  { id: "geografia_H_005", topic: "geografia", letter: "H", question: "Con la H: Parte de la geografía que estudia aguas .", answer: "Hidrografía" },
  { id: "geografia_H_006", topic: "geografia", letter: "H", question: "Con la H: Cada mitad de la Tierra dividida por el ecuador.", answer: "Hemisferio" },
  { id: "geografia_H_007", topic: "geografia", letter: "H", question: "Con la H: Cantidad de vapor de agua en el aire.", answer: "Humedad" },
  { id: "geografia_H_008", topic: "geografia", letter: "H", question: "Con la H: Ciclón tropical intenso en océanos cálidos.", answer: "Huracán" },
  { id: "geografia_H_009", topic: "geografia", letter: "H", question: "Con la H: Ciudad neerlandesa; también topónimo europeo.", answer: "Haya" },
  { id: "geografia_H_010", topic: "geografia", letter: "H", question: "Con la H: Conjunto de aguas del planeta.", answer: "Hidrosfera" },
  { id: "geografia_H_011", topic: "geografia", letter: "H", question: "Con la H: Depresión pequeña del terreno.", answer: "Hondonada" },
  { id: "geografia_H_012", topic: "geografia", letter: "H", question: "Con la H: Línea aparente donde cielo y tierra/agua parecen unirse.", answer: "Horizonte" },
  { id: "geografia_H_013", topic: "geografia", letter: "H", question: "Con la H: Bosque de hayas, típico de zonas húmedas y frescas.", answer: "Hayedo" },
  { id: "geografia_H_014", topic: "geografia", letter: "H", question: "Con la H: Descenso de temperatura bajo cero con efectos en paisaje y agricultura.", answer: "Helada" },
  { id: "geografia_H_015", topic: "geografia", letter: "H", question: "Con la H: Depresión/valle pequeño; forma de relieve local.", answer: "Hondon" },
  { id: "geografia_I_001", topic: "geografia", letter: "I", question: "Con la I: Porción de tierra rodeada de agua.", answer: "Isla" },
  { id: "geografia_I_002", topic: "geografia", letter: "I", question: "Con la I: Isla muy pequeña.", answer: "Islote" },
  { id: "geografia_I_003", topic: "geografia", letter: "I", question: "Con la I: Isla balear famosa por calas y vida nocturna.", answer: "Ibiza" },
  { id: "geografia_I_004", topic: "geografia", letter: "I", question: "Con la I: País-isla del Atlántico Norte con volcanes y géiseres.", answer: "Islandia" },
  { id: "geografia_I_005", topic: "geografia", letter: "I", question: "Con la I: País archipelágico con miles de islas.", answer: "Indonesia" },
  { id: "geografia_I_006", topic: "geografia", letter: "I", question: "Con la I: Nombre geográfico para la península ibérica.", answer: "Iberia" },
  { id: "geografia_I_007", topic: "geografia", letter: "I", question: "Con la I: Líneas de igual presión en mapas meteorológicos.", answer: "Isobaras" },
  { id: "geografia_I_008", topic: "geografia", letter: "I", question: "Con la I: Franja estrecha de tierra que une dos masas continentales.", answer: "Istmo" },
  { id: "geografia_I_009", topic: "geografia", letter: "I", question: "Con la I: Desbordamiento de agua sobre zonas habitualmente secas.", answer: "Inundación" },
  { id: "geografia_I_010", topic: "geografia", letter: "I", question: "Con la I: Cantidad de radiación solar recibida en un lugar.", answer: "Insolación" },
  { id: "geografia_I_011", topic: "geografia", letter: "I", question: "Con la I: Zona entre dos ríos o cauces.", answer: "Interfluvio" },
  { id: "geografia_I_012", topic: "geografia", letter: "I", question: "Con la I: Línea de igual temperatura en mapas.", answer: "Isoterma" },
  { id: "geografia_I_013", topic: "geografia", letter: "I", question: "Con la I: Masa de hielo flotante desprendida de un glaciar.", answer: "Iceberg" },
  { id: "geografia_I_014", topic: "geografia", letter: "I", question: "Con la I: Zona alejada de la costa; en España, la meseta es interior.", answer: "Interior" },
  { id: "geografia_I_015", topic: "geografia", letter: "I", question: "Con la I: Terreno difícil de cruzar por relieve o vegetación.", answer: "Infranqueable" },
  { id: "geografia_J_001", topic: "geografia", letter: "J", question: "Con la J: Provincia andaluza famosa por olivares y la Sierra de Cazorla.", answer: "Jaén" },
  { id: "geografia_J_002", topic: "geografia", letter: "J", question: "Con la J: Río del este de España que desemboca en el Mediterráneo.", answer: "Júcar" },
  { id: "geografia_J_003", topic: "geografia", letter: "J", question: "Con la J: Ciudad gaditana cercana a la campiña y al Atlántico.", answer: "Jerez" },
  { id: "geografia_J_004", topic: "geografia", letter: "J", question: "Con la J: Río de Oriente Próximo que desemboca en el mar Muerto.", answer: "Jordán" },
  { id: "geografia_J_005", topic: "geografia", letter: "J", question: "Con la J: Ciudad oscense en el Pirineo aragonés, cerca de pasos de montaña.", answer: "Jaca" },
  { id: "geografia_J_006", topic: "geografia", letter: "J", question: "Con la J: Archipiélago de Filipinas ; en español como Joló.", answer: "Joló" },
  { id: "geografia_J_007", topic: "geografia", letter: "J", question: "Con la J: Macizo y península al sur de Fuerteventura.", answer: "Jandía" },
  { id: "geografia_J_008", topic: "geografia", letter: "J", question: "Con la J: Bioma de selva húmeda tropical.", answer: "Jungla" },
  { id: "geografia_J_009", topic: "geografia", letter: "J", question: "Con la J: Península danesa entre el mar del Norte y el Báltico.", answer: "Jutlandia" },
  { id: "geografia_J_010", topic: "geografia", letter: "J", question: "Con la J: Ciudad del desierto del Thar  asociada a dunas.", answer: "Jaisalmer" },
  { id: "geografia_J_011", topic: "geografia", letter: "J", question: "Con la J: País insular del Pacífico con cadenas montañosas y volcanes.", answer: "Japon" },
  { id: "geografia_J_012", topic: "geografia", letter: "J", question: "Con la J: Isla del canal de la Mancha .", answer: "Jersey" },
  { id: "geografia_J_013", topic: "geografia", letter: "J", question: "Con la J: Mineral verde usado en joyería, especialmente valorado en culturas asiáticas como la china.", answer: "Jade" },
  { id: "geografia_J_014", topic: "geografia", letter: "J", question: "Con la J: Embarcación tradicional; vinculada a geografía costera mediterránea.", answer: "Jábega" },
  { id: "geografia_J_015", topic: "geografia", letter: "J", question: "Con la J: Valle extremeño famoso por sus cerezos.", answer: "Jerte" },
  { id: "geografia_L_001", topic: "geografia", letter: "L", question: "Con la L: Provincia gallega con costa y la ría de Viveiro.", answer: "Lugo" },
  { id: "geografia_L_002", topic: "geografia", letter: "L", question: "Con la L: Provincia castellana con montañas y meseta.", answer: "León" },
  { id: "geografia_L_003", topic: "geografia", letter: "L", question: "Con la L: Provincia catalana con Pirineos y valle del Segre.", answer: "Lleida" },
  { id: "geografia_L_004", topic: "geografia", letter: "L", question: "Con la L: Capital de Portugal en la desembocadura del Tajo.", answer: "Lisboa" },
  { id: "geografia_L_005", topic: "geografia", letter: "L", question: "Con la L: Isla canaria de paisaje volcánico.", answer: "Lanzarote" },
  { id: "geografia_L_006", topic: "geografia", letter: "L", question: "Con la L: Isla canaria conocida por volcanes y cielos oscuros.", answer: "LaPalma" },
  { id: "geografia_L_007", topic: "geografia", letter: "L", question: "Con la L: Zona costera donde tierra y mar se encuentran.", answer: "Litoral" },
  { id: "geografia_L_008", topic: "geografia", letter: "L", question: "Con la L: Terreno extenso y relativamente plano.", answer: "Llanura" },
  { id: "geografia_L_009", topic: "geografia", letter: "L", question: "Con la L: Coordenada que mide distancia al ecuador.", answer: "Latitud" },
  { id: "geografia_L_010", topic: "geografia", letter: "L", question: "Con la L: Coordenada que mide posición este-oeste respecto a un meridiano.", answer: "Longitud" },
  { id: "geografia_L_011", topic: "geografia", letter: "L", question: "Con la L: Cuerpo de agua poco profundo, a menudo cercano a la costa.", answer: "Laguna" },
  { id: "geografia_L_012", topic: "geografia", letter: "L", question: "Con la L: Cuerpo de agua interior rodeado de tierra.", answer: "Lago" },
  { id: "geografia_L_013", topic: "geografia", letter: "L", question: "Con la L: Región ártica en el norte de Europa.", answer: "Laponia" },
  { id: "geografia_L_014", topic: "geografia", letter: "L", question: "Con la L: Río más largo de Francia.", answer: "Loira" },
  { id: "geografia_L_015", topic: "geografia", letter: "L", question: "Con la L: Frontera; también se usa para límites históricos .", answer: "Limes" },
  { id: "geografia_M_001", topic: "geografia", letter: "M", question: "Con la M: Capital de España, en el centro de la península.", answer: "Madrid" },
  { id: "geografia_M_002", topic: "geografia", letter: "M", question: "Con la M: Región del sureste de España con huerta y costa.", answer: "Murcia" },
  { id: "geografia_M_003", topic: "geografia", letter: "M", question: "Con la M: Provincia andaluza en la Costa del Sol.", answer: "Málaga" },
  { id: "geografia_M_004", topic: "geografia", letter: "M", question: "Con la M: Isla mayor de Baleares.", answer: "Mallorca" },
  { id: "geografia_M_005", topic: "geografia", letter: "M", question: "Con la M: Isla balear al noreste de Mallorca.", answer: "Menorca" },
  { id: "geografia_M_006", topic: "geografia", letter: "M", question: "Con la M: Río gallego que desemboca en el Atlántico y hace frontera con Portugal.", answer: "Miño" },
  { id: "geografia_M_007", topic: "geografia", letter: "M", question: "Con la M: Gran altiplano central de España.", answer: "Meseta" },
  { id: "geografia_M_008", topic: "geografia", letter: "M", question: "Con la M: Mar que baña la costa oriental y sur de España.", answer: "Mediterráneo" },
  { id: "geografia_M_009", topic: "geografia", letter: "M", question: "Con la M: Gran elevación del terreno.", answer: "Montaña" },
  { id: "geografia_M_010", topic: "geografia", letter: "M", question: "Con la M: Gran ciudad con influencia regional o global.", answer: "Metrópolis" },
  { id: "geografia_M_011", topic: "geografia", letter: "M", question: "Con la M: Línea de longitud; referencia en coordenadas.", answer: "Meridiano" },
  { id: "geografia_M_012", topic: "geografia", letter: "M", question: "Con la M: Viento estacional con lluvias intensas en Asia.", answer: "Monzón" },
  { id: "geografia_M_013", topic: "geografia", letter: "M", question: "Con la M: Pico más alto de la península ibérica .", answer: "Mulhacén" },
  { id: "geografia_M_014", topic: "geografia", letter: "M", question: "Con la M: Mar interior turco conectado al Bósforo y Dardanelos.", answer: "Marmara" },
  { id: "geografia_M_015", topic: "geografia", letter: "M", question: "Con la M: Comarca costera catalana al norte de Barcelona.", answer: "Maresme" },
  { id: "geografia_N_001", topic: "geografia", letter: "N", question: "Con la N: Comunidad autónoma del norte con Pirineos y valles.", answer: "Navarra" },
  { id: "geografia_N_002", topic: "geografia", letter: "N", question: "Con la N: Localidad costera malagueña famosa por sus acantilados y cuevas.", answer: "Nerja" },
  { id: "geografia_N_003", topic: "geografia", letter: "N", question: "Con la N: Río africano clave, asociado a Egipto y Sudán.", answer: "Nilo" },
  { id: "geografia_N_004", topic: "geografia", letter: "N", question: "Con la N: País con fiordos y costa muy recortada.", answer: "Noruega" },
  { id: "geografia_N_005", topic: "geografia", letter: "N", question: "Con la N: Centro; en geografía urbana, núcleo histórico de una ciudad.", answer: "Núcleo" },
  { id: "geografia_N_006", topic: "geografia", letter: "N", question: "Con la N: Referencia para medir altitud, tomada como cero.", answer: "NivelMar" },
  { id: "geografia_N_007", topic: "geografia", letter: "N", question: "Con la N: Relacionado con presencia de nubes .", answer: "Nuboso" },
  { id: "geografia_N_008", topic: "geografia", letter: "N", question: "Con la N: Punto cardinal opuesto al sur.", answer: "Norte" },
  { id: "geografia_N_009", topic: "geografia", letter: "N", question: "Con la N: Lugar donde nace un río o manantial.", answer: "Naciente" },
  { id: "geografia_N_010", topic: "geografia", letter: "N", question: "Con la N: En meteorología, precipitación sólida en forma de nieve.", answer: "Nevada" },
  { id: "geografia_N_011", topic: "geografia", letter: "N", question: "Con la N: Desplazamiento por mar/aire; esencial en geografía humana.", answer: "Navegación" },
  { id: "geografia_N_012", topic: "geografia", letter: "N", question: "Con la N: Subcontinente que incluye Canadá, EE.UU. y México.", answer: "Norteamérica" },
  { id: "geografia_N_013", topic: "geografia", letter: "N", question: "Con la N: Región histórica del valle del Nilo .", answer: "Nubia" },
  { id: "geografia_N_014", topic: "geografia", letter: "N", question: "Con la N: Ciudad italiana en bahía volcánica bajo el Vesubio.", answer: "Nápoles" },
  { id: "geografia_N_015", topic: "geografia", letter: "N", question: "Con la N: Capital de Kenia, en una meseta del África oriental.", answer: "Nairobi" },
  { id: "geografia_Ñ_001", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: País europeo de la península ibérica.", answer: "España" },
  { id: "geografia_Ñ_002", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Unidad temporal usada en climatología y registros geográficos.", answer: "Año" },
  { id: "geografia_Ñ_003", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Marca en mapas o rutas.", answer: "Señal" },
  { id: "geografia_Ñ_004", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Roca prominente; ejemplo: Gibraltar.", answer: "Peñón" },
  { id: "geografia_Ñ_005", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Relieve elevado.", answer: "Montaña" },
  { id: "geografia_Ñ_006", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Valle profundo excavado por un río.", answer: "Cañón" },
  { id: "geografia_Ñ_007", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Vivienda rural; geografía humana.", answer: "Cabaña" },
  { id: "geografia_Ñ_008", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Fenómeno climático del Pacífico .", answer: "Niño" },
  { id: "geografia_Ñ_009", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Franja del día; en clima, variación diaria.", answer: "Mañana" },
  { id: "geografia_Ñ_010", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Adjetivo común en topónimos .", answer: "Pequeño" },
  { id: "geografia_Ñ_011", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Camino o valle estrecho.", answer: "Cañada" },
  { id: "geografia_Ñ_012", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Red histórica de vías pecuarias en España.", answer: "CañadaReal" },
  { id: "geografia_Ñ_013", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Geografía enseñada en escuelas.", answer: "Enseñanza" },
  { id: "geografia_Ñ_014", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Formación rocosa; topónimo frecuente.", answer: "Peña" },
  { id: "geografia_Ñ_015", topic: "geografia", letter: "Ñ", question: "Contiene la Ñ: Conjunto de señales de rutas y carreteras.", answer: "Señalización" },
  { id: "geografia_O_001", topic: "geografia", letter: "O", question: "Con la O: Gran masa de agua salada que cubre gran parte del planeta.", answer: "Océano" },
  { id: "geografia_O_002", topic: "geografia", letter: "O", question: "Con la O: Nombre español de Ourense, provincia gallega interior.", answer: "Orense" },
  { id: "geografia_O_003", topic: "geografia", letter: "O", question: "Con la O: Capital de Asturias, cerca de la Cordillera Cantábrica.", answer: "Oviedo" },
  { id: "geografia_O_004", topic: "geografia", letter: "O", question: "Con la O: Ciudad portuguesa en el estuario del Douro.", answer: "Oporto" },
  { id: "geografia_O_005", topic: "geografia", letter: "O", question: "Con la O: Dirección o región del este en mapas y relatos.", answer: "Oriente" },
  { id: "geografia_O_006", topic: "geografia", letter: "O", question: "Con la O: Dirección o región del oeste.", answer: "Occidente" },
  { id: "geografia_O_007", topic: "geografia", letter: "O", question: "Con la O: Zona fértil en un desierto con agua disponible.", answer: "Oasis" },
  { id: "geografia_O_008", topic: "geografia", letter: "O", question: "Con la O: Proceso de formación de montañas por tectónica.", answer: "Orogénesis" },
  { id: "geografia_O_009", topic: "geografia", letter: "O", question: "Con la O: Río de Venezuela y Colombia que desemboca en el Atlántico.", answer: "Orinoco" },
  { id: "geografia_O_010", topic: "geografia", letter: "O", question: "Con la O: Provincia canadiense con el lago Ontario.", answer: "Ontario" },
  { id: "geografia_O_011", topic: "geografia", letter: "O", question: "Con la O: Delta interior famoso en Botsuana.", answer: "Okavango" },
  { id: "geografia_O_012", topic: "geografia", letter: "O", question: "Con la O: Estado mexicano con sierras y costa del Pacífico.", answer: "Oaxaca" },
  { id: "geografia_O_013", topic: "geografia", letter: "O", question: "Con la O: Ciudad argentina en Misiones .", answer: "Oberá" },
  { id: "geografia_O_014", topic: "geografia", letter: "O", question: "Con la O: Gas atmosférico importante en la estratosfera.", answer: "Ozono" },
  { id: "geografia_O_015", topic: "geografia", letter: "O", question: "Con la O: En toponimia, “ojo” puede referir a un manantial .", answer: "Ojo" },
  { id: "geografia_P_001", topic: "geografia", letter: "P", question: "Con la P: Cordillera que separa España y Francia.", answer: "Pirineos" },
  { id: "geografia_P_002", topic: "geografia", letter: "P", question: "Con la P: Macizo montañoso del norte de España.", answer: "PicosdeEuropa" },
  { id: "geografia_P_003", topic: "geografia", letter: "P", question: "Con la P: Comunidad autónoma del norte de España.", answer: "PaísVasco" },
  { id: "geografia_P_004", topic: "geografia", letter: "P", question: "Con la P: País vecino de España en la península ibérica.", answer: "Portugal" },
  { id: "geografia_P_005", topic: "geografia", letter: "P", question: "Con la P: Tierra rodeada de agua por casi todos lados, unida por un istmo.", answer: "Península" },
  { id: "geografia_P_006", topic: "geografia", letter: "P", question: "Con la P: Franja de arena o grava junto al mar.", answer: "Playa" },
  { id: "geografia_P_007", topic: "geografia", letter: "P", question: "Con la P: Lugar costero para barcos; también paso de montaña.", answer: "Puerto" },
  { id: "geografia_P_008", topic: "geografia", letter: "P", question: "Con la P: Altiplanicie fría o meseta elevada con vegetación escasa.", answer: "Páramo" },
  { id: "geografia_P_009", topic: "geografia", letter: "P", question: "Con la P: Agua que cae de la atmósfera: lluvia, nieve, granizo.", answer: "Precipitación" },
  { id: "geografia_P_010", topic: "geografia", letter: "P", question: "Con la P: Conjunto de habitantes de un lugar .", answer: "Población" },
  { id: "geografia_P_011", topic: "geografia", letter: "P", question: "Con la P: Medición de la lluvia en un lugar.", answer: "Pluviometría" },
  { id: "geografia_P_012", topic: "geografia", letter: "P", question: "Con la P: Zona elevada; también plataforma continental bajo el mar.", answer: "Plataforma" },
  { id: "geografia_P_013", topic: "geografia", letter: "P", question: "Con la P: Relacionado con los Pirineos .", answer: "Pirinéico" },
  { id: "geografia_P_014", topic: "geografia", letter: "P", question: "Con la P: Ciudad navarra conocida por su localización en valles y ríos.", answer: "Pamplona" },
  { id: "geografia_P_015", topic: "geografia", letter: "P", question: "Con la P: Cordillera/meseta alta en Asia Central.", answer: "Pamir" },
  { id: "geografia_Q_001", topic: "geografia", letter: "Q", question: "Contiene la Q: Capital de Ecuador situada en la cordillera de los Andes.", answer: "Quito" },
  { id: "geografia_Q_002", topic: "geografia", letter: "Q", question: "Contiene la Q: Estado mexicano con costa caribeña.", answer: "QuintanaRoo" },
  { id: "geografia_Q_003", topic: "geografia", letter: "Q", question: "Contiene la Q: Departamento de Colombia en zona andina.", answer: "Quindío" },
  { id: "geografia_Q_004", topic: "geografia", letter: "Q", question: "Contiene la Q: Nombre del género de robles; en geografía, bosques de quercíneas.", answer: "Quercus" },
  { id: "geografia_Q_005", topic: "geografia", letter: "Q", question: "Contiene la Q: Momento del año con día y noche similares.", answer: "Equinoccio" },
  { id: "geografia_Q_006", topic: "geografia", letter: "Q", question: "Contiene la Q: Forma histórica/alternativa; línea del ecuador.", answer: "Equador" },
  { id: "geografia_Q_007", topic: "geografia", letter: "Q", question: "Contiene la Q: Pueblo ártico; geografía humana.", answer: "Esquimal" },
  { id: "geografia_Q_008", topic: "geografia", letter: "Q", question: "Contiene la Q: Reserva subterránea de agua.", answer: "Acuífero" },
  { id: "geografia_Q_009", topic: "geografia", letter: "Q", question: "Contiene la Q: Roca metamórfica común en cordilleras.", answer: "Esquisto" },
  { id: "geografia_Q_010", topic: "geografia", letter: "Q", question: "Contiene la Q: Región del suroeste de Francia.", answer: "Aquitania" },
  { id: "geografia_Q_011", topic: "geografia", letter: "Q", question: "Contiene la Q: Punto de cruce/giro en ciudad; geografía urbana.", answer: "Esquina" },
  { id: "geografia_Q_012", topic: "geografia", letter: "Q", question: "Contiene la Q: Fractura o ruptura en el terreno causada por fallas geológicas o erosión.", answer: "Quiebra" },
  { id: "geografia_Q_013", topic: "geografia", letter: "Q", question: "Contiene la Q: Municipio de Brasil.", answer: "Aquiraz" },
  { id: "geografia_Q_014", topic: "geografia", letter: "Q", question: "Contiene la Q: Nombre histórico de La Española.", answer: "Quisqueya" },
  { id: "geografia_Q_015", topic: "geografia", letter: "Q", question: "Contiene la Q: Ave símbolo de Guatemala; también topónimo/cultura.", answer: "Quetzal" },
  { id: "geografia_R_001", topic: "geografia", letter: "R", question: "Con la R: Curso natural de agua que fluye hacia un mar, lago u otro río.", answer: "Río" },
  { id: "geografia_R_002", topic: "geografia", letter: "R", question: "Con la R: Conjunto de formas de la superficie terrestre.", answer: "Relieve" },
  { id: "geografia_R_003", topic: "geografia", letter: "R", question: "Con la R: Entradas de mar en valles fluviales, típicas de Galicia.", answer: "Rías" },
  { id: "geografia_R_004", topic: "geografia", letter: "R", question: "Con la R: Ciudad andaluza con famoso tajo y relieve escarpado.", answer: "Ronda" },
  { id: "geografia_R_005", topic: "geografia", letter: "R", question: "Con la R: Municipio almeriense costero; ejemplo de litoral mediterráneo.", answer: "Roquetas" },
  { id: "geografia_R_006", topic: "geografia", letter: "R", question: "Con la R: Ciudad italiana junto al río Tíber.", answer: "Roma" },
  { id: "geografia_R_007", topic: "geografia", letter: "R", question: "Con la R: Capital de Marruecos en la costa atlántica.", answer: "Rabat" },
  { id: "geografia_R_008", topic: "geografia", letter: "R", question: "Con la R: Valle de hundimiento tectónico, como el ValleDelRift africano.", answer: "Rift" },
  { id: "geografia_R_009", topic: "geografia", letter: "R", question: "Con la R: Material sólido que compone la corteza terrestre.", answer: "Roca" },
  { id: "geografia_R_010", topic: "geografia", letter: "R", question: "Con la R: Río más largo de la península ibérica en longitud total.", answer: "RíoTajo" },
  { id: "geografia_R_011", topic: "geografia", letter: "R", question: "Con la R: Río del sureste de España con huerta y embalses.", answer: "RíoSegura" },
  { id: "geografia_R_012", topic: "geografia", letter: "R", question: "Con la R: Río francés que desemboca en el Mediterráneo.", answer: "Ródano" },
  { id: "geografia_R_013", topic: "geografia", letter: "R", question: "Con la R: Nombre del río Nilo; eje del valle egipcio.", answer: "RíoNilo" },
  { id: "geografia_R_014", topic: "geografia", letter: "R", question: "Con la R: Humedad condensada al amanecer; clima local.", answer: "Rocío" },
  { id: "geografia_R_015", topic: "geografia", letter: "R", question: "Con la R: Relacionado con rocas; relieve y geología; geografía física.", answer: "Rupestre" },
  { id: "geografia_S_001", topic: "geografia", letter: "S", question: "Con la S: Capital andaluza a orillas del Guadalquivir.", answer: "Sevilla" },
  { id: "geografia_S_002", topic: "geografia", letter: "S", question: "Con la S: Ciudad castellana cercana a la Sierra de Guadarrama.", answer: "Segovia" },
  { id: "geografia_S_003", topic: "geografia", letter: "S", question: "Con la S: Provincia castellana con sistemas ibéricos y mesetas.", answer: "Soria" },
  { id: "geografia_S_004", topic: "geografia", letter: "S", question: "Con la S: Ciudad en el río Tormes, interior peninsular.", answer: "Salamanca" },
  { id: "geografia_S_005", topic: "geografia", letter: "S", question: "Con la S: Capital de Galicia, cerca de rías y relieve atlántico.", answer: "Santiago" },
  { id: "geografia_S_006", topic: "geografia", letter: "S", question: "Con la S: Cordillera andaluza con picos altos como el Mulhacén.", answer: "SierraNevada" },
  { id: "geografia_S_007", topic: "geografia", letter: "S", question: "Con la S: Cordillera que atraviesa el centro de España.", answer: "SistemaCentral" },
  { id: "geografia_S_008", topic: "geografia", letter: "S", question: "Con la S: Desierto más grande  del mundo en el norte de África.", answer: "Sahara" },
  { id: "geografia_S_009", topic: "geografia", letter: "S", question: "Con la S: Región extensa del norte de Asia con climas fríos.", answer: "Siberia" },
  { id: "geografia_S_010", topic: "geografia", letter: "S", question: "Con la S: Proceso tectónico donde una placa se hunde bajo otra.", answer: "Subducción" },
  { id: "geografia_S_011", topic: "geografia", letter: "S", question: "Con la S: Material depositado por agua, viento o hielo.", answer: "Sedimento" },
  { id: "geografia_S_012", topic: "geografia", letter: "S", question: "Con la S: Momento del año con día más largo o más corto.", answer: "Solsticio" },
  { id: "geografia_S_013", topic: "geografia", letter: "S", question: "Con la S: Movimiento de la Tierra; terremoto.", answer: "Seísmo" },
  { id: "geografia_S_014", topic: "geografia", letter: "S", question: "Con la S: Cantidad de sal disuelta en el agua.", answer: "Salinidad" },
  { id: "geografia_S_015", topic: "geografia", letter: "S", question: "Con la S: Zona resguardada del viento .", answer: "Sotavento" },
  { id: "geografia_T_001", topic: "geografia", letter: "T", question: "Con la T: Río que nace en España y desemboca en Lisboa.", answer: "Tajo" },
  { id: "geografia_T_002", topic: "geografia", letter: "T", question: "Con la T: Volcán y pico más alto de España, en Tenerife.", answer: "Teide" },
  { id: "geografia_T_003", topic: "geografia", letter: "T", question: "Con la T: Isla canaria con el Teide.", answer: "Tenerife" },
  { id: "geografia_T_004", topic: "geografia", letter: "T", question: "Con la T: Ciudad histórica en un meandro del río Tajo.", answer: "Toledo" },
  { id: "geografia_T_005", topic: "geografia", letter: "T", question: "Con la T: Provincia catalana con costa y delta del Ebro cercano.", answer: "Tarragona" },
  { id: "geografia_T_006", topic: "geografia", letter: "T", question: "Con la T: Provincia aragonesa del interior, con sierras y altiplanos.", answer: "Teruel" },
  { id: "geografia_T_007", topic: "geografia", letter: "T", question: "Con la T: Río que atraviesa Roma.", answer: "Tíber" },
  { id: "geografia_T_008", topic: "geografia", letter: "T", question: "Con la T: Vórtice atmosférico intenso.", answer: "Tornado" },
  { id: "geografia_T_009", topic: "geografia", letter: "T", question: "Con la T: Ola gigante causada por sismos o deslizamientos submarinos.", answer: "Tsunami" },
  { id: "geografia_T_010", topic: "geografia", letter: "T", question: "Con la T: Procesos de placas que modelan el relieve.", answer: "Tectónica" },
  { id: "geografia_T_011", topic: "geografia", letter: "T", question: "Con la T: Magnitud climática que mide el calor del aire.", answer: "Temperatura" },
  { id: "geografia_T_012", topic: "geografia", letter: "T", question: "Con la T: Descripción y medición detallada del terreno.", answer: "Topografía" },
  { id: "geografia_T_013", topic: "geografia", letter: "T", question: "Con la T: Líneas de latitud: Cáncer y Capricornio.", answer: "Trópico" },
  { id: "geografia_T_014", topic: "geografia", letter: "T", question: "Con la T: Bioma de coníferas en latitudes frías.", answer: "Taiga" },
  { id: "geografia_T_015", topic: "geografia", letter: "T", question: "Con la T: Bioma frío con suelos helados y vegetación baja.", answer: "Tundra" },
  { id: "geografia_U_001", topic: "geografia", letter: "U", question: "Con la U: País sudamericano entre Argentina y Brasil.", answer: "Uruguay" },
  { id: "geografia_U_002", topic: "geografia", letter: "U", question: "Con la U: Municipio sevillano; ejemplo de campiña andaluza.", answer: "Utrera" },
  { id: "geografia_U_003", topic: "geografia", letter: "U", question: "Con la U: Posición de un lugar en el espacio.", answer: "Ubicación" },
  { id: "geografia_U_004", topic: "geografia", letter: "U", question: "Con la U: Planificación y organización del espacio urbano.", answer: "Urbanismo" },
  { id: "geografia_U_005", topic: "geografia", letter: "U", question: "Con la U: Relacionado con ciudades y vida en urbes.", answer: "Urbano" },
  { id: "geografia_U_006", topic: "geografia", letter: "U", question: "Con la U: Cordillera que separa Europa y Asia en Rusia.", answer: "Ural" },
  { id: "geografia_U_007", topic: "geografia", letter: "U", question: "Con la U: Territorios de ultramar; geografía política e histórica.", answer: "Ultramar" },
  { id: "geografia_U_008", topic: "geografia", letter: "U", question: "Con la U: Región italiana interior con relieve montañoso.", answer: "Umbría" },
  { id: "geografia_U_009", topic: "geografia", letter: "U", question: "Con la U: Ciudad argentina austral, cercana al canal Beagle.", answer: "Ushuaia" },
  { id: "geografia_U_010", topic: "geografia", letter: "U", question: "Con la U: Capital de Mongolia en un valle continental.", answer: "Ulaanbaatar" },
  { id: "geografia_U_011", topic: "geografia", letter: "U", question: "Con la U: Ciudad india junto a lagos; topónimo.", answer: "Udaipur" },
  { id: "geografia_U_012", topic: "geografia", letter: "U", question: "Con la U: Ciudad sueca; geografía humana del norte europeo.", answer: "Uppsala" },
  { id: "geografia_U_013", topic: "geografia", letter: "U", question: "Con la U: Organismo que declara patrimonio; geografía cultural.", answer: "Unesco" },
  { id: "geografia_U_014", topic: "geografia", letter: "U", question: "Con la U: Presencia extendida; en geografía, distribución amplia de especies.", answer: "Ubiquidad" },
  { id: "geografia_U_015", topic: "geografia", letter: "U", question: "Con la U: Sierra en el SistemaIbérico; nacen ríos como el Duero .", answer: "Urbión" },
  { id: "geografia_V_001", topic: "geografia", letter: "V", question: "Con la V: Ciudad y comunidad con costa mediterránea.", answer: "Valencia" },
  { id: "geografia_V_002", topic: "geografia", letter: "V", question: "Con la V: Ciudad castellana en la meseta, junto al Pisuerga.", answer: "Valladolid" },
  { id: "geografia_V_003", topic: "geografia", letter: "V", question: "Con la V: Ciudad gallega junto a una ría atlántica.", answer: "Vigo" },
  { id: "geografia_V_004", topic: "geografia", letter: "V", question: "Con la V: Abertura que expulsa magma y gases.", answer: "Volcán" },
  { id: "geografia_V_005", topic: "geografia", letter: "V", question: "Con la V: Depresión alargada entre montañas por erosión o tectónica.", answer: "Valle" },
  { id: "geografia_V_006", topic: "geografia", letter: "V", question: "Con la V: Volcán italiano junto a Nápoles.", answer: "Vesubio" },
  { id: "geografia_V_007", topic: "geografia", letter: "V", question: "Con la V: Capital de Austria junto al Danubio.", answer: "Viena" },
  { id: "geografia_V_008", topic: "geografia", letter: "V", question: "Con la V: Ciudad canadiense en la costa del Pacífico.", answer: "Vancouver" },
  { id: "geografia_V_009", topic: "geografia", letter: "V", question: "Con la V: Conjunto de plantas de una región.", answer: "Vegetación" },
  { id: "geografia_V_010", topic: "geografia", letter: "V", question: "Con la V: Movimiento del aire, clave en clima y erosión.", answer: "Viento" },
  { id: "geografia_V_011", topic: "geografia", letter: "V", question: "Con la V: Ladera; también cuenca que vierte aguas a un mar.", answer: "Vertiente" },
  { id: "geografia_V_012", topic: "geografia", letter: "V", question: "Con la V: Movimiento giratorio en fluidos .", answer: "Vórtice" },
  { id: "geografia_V_013", topic: "geografia", letter: "V", question: "Con la V: Conjunto de fenómenos relacionados con volcanes.", answer: "Vulcanismo" },
  { id: "geografia_V_014", topic: "geografia", letter: "V", question: "Con la V: Isla italiana volcánica; también tipo de relieve.", answer: "Vulcano" },
  { id: "geografia_V_015", topic: "geografia", letter: "V", question: "Con la V: Río/valle de Alicante; contiene V y es topónimo español.", answer: "Vinalopó" },
  { id: "geografia_X_001", topic: "geografia", letter: "X", question: "Contiene la X: Comunidad española del oeste.", answer: "Extremadura" },
  { id: "geografia_X_002", topic: "geografia", letter: "X", question: "Contiene la X: Comarca de Málaga al este de la provincia.", answer: "Axarquía" },
  { id: "geografia_X_003", topic: "geografia", letter: "X", question: "Contiene la X: Ciudad valenciana histórica .", answer: "Xàtiva" },
  { id: "geografia_X_004", topic: "geografia", letter: "X", question: "Contiene la X: Estado mexicano del sur con sierras, costa del Pacífico y rica herencia cultural indígena.", answer: "Oaxaca" },
  { id: "geografia_X_005", topic: "geografia", letter: "X", question: "Contiene la X: País de América del Norte que limita con Estados Unidos al norte y Guatemala al sur, con costas en el Pacífico y el Atlántico.", answer: "México" },
  { id: "geografia_X_006", topic: "geografia", letter: "X", question: "Contiene la X: Estado del sur de Estados Unidos, el segundo más grande del país, con costa en el golfo de México y frontera con México.", answer: "Texas" },
  { id: "geografia_X_007", topic: "geografia", letter: "X", question: "Contiene la X: Pequeño país europeo sin salida al mar, rodeado por Bélgica, Francia y Alemania, sede de instituciones de la Unión Europea.", answer: "Luxemburgo" },
  { id: "geografia_X_008", topic: "geografia", letter: "X", question: "Contiene la X: Zona lacustre de Ciudad de México.", answer: "Xochimilco" },
  { id: "geografia_X_009", topic: "geografia", letter: "X", question: "Contiene la X: Región de China.", answer: "Xinjiang" },
  { id: "geografia_X_010", topic: "geografia", letter: "X", question: "Contiene la X: Río/área amazónica en Brasil.", answer: "Xingu" },
  { id: "geografia_X_011", topic: "geografia", letter: "X", question: "Contiene la X: Ciudad de EE.UU.", answer: "Phoenix" },
  { id: "geografia_X_012", topic: "geografia", letter: "X", question: "Contiene la X: Ciudad inglesa.", answer: "Exeter" },
  { id: "geografia_X_013", topic: "geografia", letter: "X", question: "Contiene la X: Localidad costera mexicana.", answer: "Ixtapa" },
  { id: "geografia_X_014", topic: "geografia", letter: "X", question: "Contiene la X: Parque/zona de RivieraMaya.", answer: "Xcaret" },
  { id: "geografia_X_015", topic: "geografia", letter: "X", question: "Contiene la X: Municipio almeriense.", answer: "Albox" },
  { id: "geografia_Y_001", topic: "geografia", letter: "Y", question: "Contiene la Y: País de la península arábiga.", answer: "Yemen" },
  { id: "geografia_Y_002", topic: "geografia", letter: "Y", question: "Contiene la Y: Península mexicana entre golfo de México y Caribe.", answer: "Yucatán" },
  { id: "geografia_Y_003", topic: "geografia", letter: "Y", question: "Contiene la Y: País sudamericano pequeño ubicado entre Argentina y Brasil, con costa atlántica y capital en Montevideo.", answer: "Uruguay" },
  { id: "geografia_Y_004", topic: "geografia", letter: "Y", question: "Contiene la Y: Ciudad ecuatoriana en un estuario.", answer: "Guayaquil" },
  { id: "geografia_Y_005", topic: "geografia", letter: "Y", question: "Contiene la Y: Ciudad australiana en una bahía.", answer: "Sydney" },
  { id: "geografia_Y_006", topic: "geografia", letter: "Y", question: "Contiene la Y: Cordillera más alta del mundo en Asia, que incluye el monte Everest y separa el subcontinente indio del Tíbet.", answer: "Himalaya" },
  { id: "geografia_Y_007", topic: "geografia", letter: "Y", question: "Contiene la Y: Estado federado alemán más grande, conocido como Baviera, con capital en Múnich y los Alpes bávaros.", answer: "Bayern" },
  { id: "geografia_Y_008", topic: "geografia", letter: "Y", question: "Contiene la Y: Isla francesa de ultramar en el océano Índico, parte del archipiélago de las Comoras, entre Madagascar y África.", answer: "Mayotte" },
  { id: "geografia_Y_009", topic: "geografia", letter: "Y", question: "Contiene la Y: Ciudad/GuayanaFrancesa.", answer: "Cayena" },
  { id: "geografia_Y_010", topic: "geografia", letter: "Y", question: "Contiene la Y: Lago natural de origen cárstico en la comarca del Pla de l'Estany, en la provincia de Girona, Cataluña.", answer: "Banyoles" },
  { id: "geografia_Y_011", topic: "geografia", letter: "Y", question: "Contiene la Y: Valle/carretera; topónimo cántabro.", answer: "Cayón" },
  { id: "geografia_Y_012", topic: "geografia", letter: "Y", question: "Contiene la Y: Villa costera gallega en la provincia de Pontevedra, conocida por su casco histórico y su ubicación en la ría de Vigo.", answer: "Bayona" },
  { id: "geografia_Y_013", topic: "geografia", letter: "Y", question: "Contiene la Y: Fuente termal que expulsa periódicamente columnas de agua caliente y vapor, típica de zonas geotérmicas como Islandia o Yellowstone.", answer: "Geyser" },
  { id: "geografia_Y_014", topic: "geografia", letter: "Y", question: "Contiene la Y: Capital y ciudad más grande de Indonesia, ubicada en la isla de Java, con más de 10 millones de habitantes.", answer: "Yakarta" },
  { id: "geografia_Y_015", topic: "geografia", letter: "Y", question: "Contiene la Y: Parque nacional de Estados Unidos en California, famoso por sus valles glaciares, secuoyas gigantes y cascadas como Yosemite Falls.", answer: "Yosemite" },
  { id: "geografia_Z_001", topic: "geografia", letter: "Z", question: "Con la Z: Ciudad aragonesa junto al río Ebro.", answer: "Zaragoza" },
  { id: "geografia_Z_002", topic: "geografia", letter: "Z", question: "Con la Z: Provincia/capital castellana junto al Duero.", answer: "Zamora" },
  { id: "geografia_Z_003", topic: "geografia", letter: "Z", question: "Con la Z: Localidad costera vasca; ejemplo de litoral cantábrico.", answer: "Zarautz" },
  { id: "geografia_Z_004", topic: "geografia", letter: "Z", question: "Con la Z: Ciudad suiza junto al lago Zúrich.", answer: "Zúrich" },
  { id: "geografia_Z_005", topic: "geografia", letter: "Z", question: "Con la Z: Capital de Croacia, en región balcánica.", answer: "Zagreb" },
  { id: "geografia_Z_006", topic: "geografia", letter: "Z", question: "Con la Z: Río africano con cataratas Victoria.", answer: "Zambeze" },
  { id: "geografia_Z_007", topic: "geografia", letter: "Z", question: "Con la Z: Isla del Índico frente a Tanzania.", answer: "Zanzibar" },
  { id: "geografia_Z_008", topic: "geografia", letter: "Z", question: "Con la Z: Letra usada en mapas/leyendas; referencia cartográfica.", answer: "Zeta" },
  { id: "geografia_Z_009", topic: "geografia", letter: "Z", question: "Con la Z: Punto del cielo sobre el observador; útil en navegación astronómica.", answer: "Zenit" },
  { id: "geografia_Z_010", topic: "geografia", letter: "Z", question: "Con la Z: Plaza central; en geografía urbana, zócalo como núcleo .", answer: "Zócalo" },
  { id: "geografia_Z_011", topic: "geografia", letter: "Z", question: "Con la Z: Área delimitada; zona climática, zona urbana, etc.", answer: "Zona" },
  { id: "geografia_Z_012", topic: "geografia", letter: "Z", question: "Con la Z: Espacio urbano de exhibición; geografía del ocio.", answer: "Zoológico" },
  { id: "geografia_Z_013", topic: "geografia", letter: "Z", question: "Con la Z: Construcción mesopotámica; geografía cultural del CrecienteFértil.", answer: "Zigurat" },
  { id: "geografia_Z_014", topic: "geografia", letter: "Z", question: "Con la Z: Recurso mineral; geografía económica de minas.", answer: "Zinc" },
  { id: "geografia_Z_015", topic: "geografia", letter: "Z", question: "Con la Z: Divisiones o áreas delimitadas del territorio clasificadas según criterios como clima, relieve, uso del suelo o características geográficas específicas.", answer: "Zonas" },
];
