import type { QA } from "./types";

export const HISTORIA: QA[] = [
  { id: "historia_A_001", topic: "historia", letter: "A", question: "Con la A: Periodo histórico previo a la Edad Media, con civilizaciones clásicas.", answer: "Antigüedad" },
  { id: "historia_A_002", topic: "historia", letter: "A", question: "Con la A: Sistema político donde el monarca concentra el poder.", answer: "Absolutismo" },
  { id: "historia_A_003", topic: "historia", letter: "A", question: "Con la A: Conquistador macedonio conocido como “Magno”.", answer: "Alejandro" },
  { id: "historia_A_004", topic: "historia", letter: "A", question: "Con la A: Polis griega asociada a democracia y filosofía.", answer: "Atenas" },
  { id: "historia_A_005", topic: "historia", letter: "A", question: "Con la A: Ideología política que rechaza el Estado como autoridad central.", answer: "Anarquismo" },
  { id: "historia_A_006", topic: "historia", letter: "A", question: "Con la A: Flota militar; famosa la “Armada Invencible” del siglo XVI.", answer: "Armada" },
  { id: "historia_A_007", topic: "historia", letter: "A", question: "Con la A: Complejo palaciego nazarí en Granada.", answer: "Alhambra" },
  { id: "historia_A_008", topic: "historia", letter: "A", question: "Con la A: Nombre histórico de territorios musulmanes en la península ibérica.", answer: "AlAndalus" },
  { id: "historia_A_009", topic: "historia", letter: "A", question: "Con la A: Estructura social y política previa a revoluciones liberales.", answer: "AntiguoRegimen" },
  { id: "historia_A_010", topic: "historia", letter: "A", question: "Con la A: Disciplina que estudia el pasado mediante restos materiales.", answer: "Arqueología" },
  { id: "historia_A_011", topic: "historia", letter: "A", question: "Con la A: Movimiento para eliminar la esclavitud.", answer: "Abolicionismo" },
  { id: "historia_A_012", topic: "historia", letter: "A", question: "Con la A: Batalla clave de Napoleón .", answer: "Austerlitz" },
  { id: "historia_A_013", topic: "historia", letter: "A", question: "Con la A: Sistema de segregación racial en Sudáfrica.", answer: "Apartheid" },
  { id: "historia_A_014", topic: "historia", letter: "A", question: "Con la A: Política económica de autosuficiencia, típica en posguerras.", answer: "Autarquía" },
  { id: "historia_A_015", topic: "historia", letter: "A", question: "Con la A: Región histórica clave en imperios como hititas y otomanos.", answer: "Anatolia" },
  { id: "historia_B_001", topic: "historia", letter: "B", question: "Con la B: Dinastía reinante en España desde el siglo XVIII.", answer: "Borbón" },
  { id: "historia_B_002", topic: "historia", letter: "B", question: "Con la B: Ciudad-estado mesopotámica famosa por su poder y leyes.", answer: "Babilonia" },
  { id: "historia_B_003", topic: "historia", letter: "B", question: "Con la B: Nombre común del Imperio Romano de Oriente.", answer: "Bizancio" },
  { id: "historia_B_004", topic: "historia", letter: "B", question: "Con la B: Fortaleza cuya toma simboliza la Revolución Francesa.", answer: "Bastilla" },
  { id: "historia_B_005", topic: "historia", letter: "B", question: "Con la B: Político prusiano clave en la unificación alemana.", answer: "Bismarck" },
  { id: "historia_B_006", topic: "historia", letter: "B", question: "Con la B: Facción revolucionaria rusa que tomó el poder en 1917.", answer: "Bolchevique" },
  { id: "historia_B_007", topic: "historia", letter: "B", question: "Con la B: Invento de navegación que impulsó exploraciones oceánicas.", answer: "Brújula" },
  { id: "historia_B_008", topic: "historia", letter: "B", question: "Con la B: Ciudad símbolo de la Guerra Fría y su muro.", answer: "Berlín" },
  { id: "historia_B_009", topic: "historia", letter: "B", question: "Con la B: Elemento de fortificación defensiva en guerras modernas.", answer: "Bastión" },
  { id: "historia_B_010", topic: "historia", letter: "B", question: "Con la B: Ciudad española importante en historia medieval y contemporánea.", answer: "Burgos" },
  { id: "historia_B_011", topic: "historia", letter: "B", question: "Con la B: Periodo cultural europeo del siglo XVII con gran impacto histórico.", answer: "Barroco" },
  { id: "historia_B_012", topic: "historia", letter: "B", question: "Con la B: Región histórica de Asia Central ligada a rutas y reinos helenísticos.", answer: "Bactria" },
  { id: "historia_B_013", topic: "historia", letter: "B", question: "Con la B: Relacionado con reformas del siglo XVIII en España.", answer: "Borbónico" },
  { id: "historia_B_014", topic: "historia", letter: "B", question: "Con la B: Táctica de “guerra relámpago” asociada a la II Guerra Mundial.", answer: "Blitzkrieg" },
  { id: "historia_B_015", topic: "historia", letter: "B", question: "Con la B: Símbolo de identidad política, militar o nacional.", answer: "Bandera" },
  { id: "historia_C_001", topic: "historia", letter: "C", question: "Con la C: Ley fundamental que organiza un Estado.", answer: "Constitución" },
  { id: "historia_C_002", topic: "historia", letter: "C", question: "Con la C: Dominación de territorios por potencias extranjeras.", answer: "Colonialismo" },
  { id: "historia_C_003", topic: "historia", letter: "C", question: "Con la C: Guerras medievales hacia Tierra Santa.", answer: "Cruzadas" },
  { id: "historia_C_004", topic: "historia", letter: "C", question: "Con la C: Ciudad-estado rival de Roma en las Guerras Púnicas.", answer: "Cartago" },
  { id: "historia_C_005", topic: "historia", letter: "C", question: "Con la C: Navegante asociado al viaje de 1492.", answer: "Colón" },
  { id: "historia_C_006", topic: "historia", letter: "C", question: "Con la C: Forma de gobierno islámico encabezado por un califa.", answer: "Califato" },
  { id: "historia_C_007", topic: "historia", letter: "C", question: "Con la C: Asamblea representativa histórica .", answer: "Cortes" },
  { id: "historia_C_008", topic: "historia", letter: "C", question: "Con la C: Sometimiento de territorios por fuerza militar.", answer: "Conquista" },
  { id: "historia_C_009", topic: "historia", letter: "C", question: "Con la C: Territorio con historia política propia en la Corona de Aragón.", answer: "Cataluña" },
  { id: "historia_C_010", topic: "historia", letter: "C", question: "Con la C: Ruptura dentro de una institución religiosa .", answer: "Cisma" },
  { id: "historia_C_011", topic: "historia", letter: "C", question: "Con la C: Control de información por un poder político o religioso.", answer: "Censura" },
  { id: "historia_C_012", topic: "historia", letter: "C", question: "Con la C: Condición de pertenencia política con derechos y deberes.", answer: "Ciudadanía" },
  { id: "historia_C_013", topic: "historia", letter: "C", question: "Con la C: Revuelta castellana del siglo XVI contra Carlos I.", answer: "Comuneros" },
  { id: "historia_C_014", topic: "historia", letter: "C", question: "Con la C: Acuerdo entre un Estado y la Iglesia.", answer: "Concordato" },
  { id: "historia_C_015", topic: "historia", letter: "C", question: "Con la C: Magistrado de máxima autoridad en la Roma republicana.", answer: "Cónsul" },
  { id: "historia_D_001", topic: "historia", letter: "D", question: "Con la D: Sistema político basado en participación ciudadana.", answer: "Democracia" },
  { id: "historia_D_002", topic: "historia", letter: "D", question: "Con la D: Régimen con poder concentrado y libertades limitadas.", answer: "Dictadura" },
  { id: "historia_D_003", topic: "historia", letter: "D", question: "Con la D: Serie de gobernantes de una misma familia.", answer: "Dinastía" },
  { id: "historia_D_004", topic: "historia", letter: "D", question: "Con la D: Término tradicional para el contacto europeo con América en 1492.", answer: "Descubrimiento" },
  { id: "historia_D_005", topic: "historia", letter: "D", question: "Con la D: Venta de bienes eclesiásticos/municipales en España .", answer: "Desamortización" },
  { id: "historia_D_006", topic: "historia", letter: "D", question: "Con la D: Libertades y garantías reconocidas por leyes.", answer: "Derechos" },
  { id: "historia_D_007", topic: "historia", letter: "D", question: "Con la D: Caso francés que marcó debates sobre justicia y antisemitismo.", answer: "Dreyfus" },
  { id: "historia_D_008", topic: "historia", letter: "D", question: "Con la D: Gestión de relaciones entre estados.", answer: "Diplomacia" },
  { id: "historia_D_009", topic: "historia", letter: "D", question: "Con la D: Territorio gobernado por un duque en sistemas feudales.", answer: "Ducado" },
  { id: "historia_D_010", topic: "historia", letter: "D", question: "Con la D: Estrecho estratégico en conflictos como la I Guerra Mundial.", answer: "Dardanellos" },
  { id: "historia_D_011", topic: "historia", letter: "D", question: "Con la D: Norma legal emitida por autoridad ejecutiva.", answer: "Decreto" },
  { id: "historia_D_012", topic: "historia", letter: "D", question: "Con la D: Forma de gobierno autoritaria; se habla de despotismo ilustrado.", answer: "Despotismo" },
  { id: "historia_D_013", topic: "historia", letter: "D", question: "Con la D: Proceso de independencia de colonias en el siglo XX.", answer: "Decolonización" },
  { id: "historia_D_014", topic: "historia", letter: "D", question: "Con la D: Emperador romano asociado a reformas del Imperio.", answer: "Diocleciano" },
  { id: "historia_D_015", topic: "historia", letter: "D", question: "Con la D: Figura religiosa/cultural en pueblos celtas .", answer: "Druida" },
  { id: "historia_E_001", topic: "historia", letter: "E", question: "Con la E: Periodo histórico europeo entre Antigüedad y Edad Moderna.", answer: "EdadMedia" },
  { id: "historia_E_002", topic: "historia", letter: "E", question: "Con la E: Periodo entre Edad Media y Contemporánea .", answer: "EdadModerna" },
  { id: "historia_E_003", topic: "historia", letter: "E", question: "Con la E: Periodo desde finales del s. XVIII hasta hoy.", answer: "EdadContemporánea" },
  { id: "historia_E_004", topic: "historia", letter: "E", question: "Con la E: Corriente filosófica moderna basada en experiencia.", answer: "Empirismo" },
  { id: "historia_E_005", topic: "historia", letter: "E", question: "Con la E: Sistema colonial español de trabajo/tributo en América.", answer: "Encomienda" },
  { id: "historia_E_006", topic: "historia", letter: "E", question: "Con la E: Sistema de explotación de personas como propiedad.", answer: "Esclavitud" },
  { id: "historia_E_007", topic: "historia", letter: "E", question: "Con la E: Política de ampliar territorio o influencia.", answer: "Expansionismo" },
  { id: "historia_E_008", topic: "historia", letter: "E", question: "Con la E: Enfermedad extendida con impacto histórico .", answer: "Epidemia" },
  { id: "historia_E_009", topic: "historia", letter: "E", question: "Con la E: Salida de población; clave en historia social.", answer: "Emigración" },
  { id: "historia_E_010", topic: "historia", letter: "E", question: "Con la E: Término para el contacto entre Europa y América.", answer: "Encuentro" },
  { id: "historia_E_011", topic: "historia", letter: "E", question: "Con la E: Etapa política soviética asociada a Stalin.", answer: "Estalinismo" },
  { id: "historia_E_012", topic: "historia", letter: "E", question: "Con la E: Proyecto ilustrado de compilar conocimiento .", answer: "Enciclopedismo" },
  { id: "historia_E_013", topic: "historia", letter: "E", question: "Con la E: Institución militar de un Estado.", answer: "Ejército" },
  { id: "historia_E_014", topic: "historia", letter: "E", question: "Con la E: Plan para alcanzar objetivos en conflictos y política.", answer: "Estrategia" },
  { id: "historia_E_015", topic: "historia", letter: "E", question: "Con la E: Medida económica que restringe comercio entre estados.", answer: "Embargo" },
  { id: "historia_F_001", topic: "historia", letter: "F", question: "Con la F: Sistema social medieval basado en vasallaje y tierras.", answer: "Feudalismo" },
  { id: "historia_F_002", topic: "historia", letter: "F", question: "Con la F: Ideología autoritaria del siglo XX.", answer: "Fascismo" },
  { id: "historia_F_003", topic: "historia", letter: "F", question: "Con la F: Régimen de Franco en España .", answer: "Franquismo" },
  { id: "historia_F_004", topic: "historia", letter: "F", question: "Con la F: Límite entre territorios; cambia con guerras y tratados.", answer: "Frontera" },
  { id: "historia_F_005", topic: "historia", letter: "F", question: "Con la F: Red asociativa con influencia cultural y política en época moderna.", answer: "Francmasonería" },
  { id: "historia_F_006", topic: "historia", letter: "F", question: "Con la F: Construcción defensiva .", answer: "Fortaleza" },
  { id: "historia_F_007", topic: "historia", letter: "F", question: "Con la F: Conjunto de leyes y privilegios locales en historia hispánica.", answer: "Fuero" },
  { id: "historia_F_008", topic: "historia", letter: "F", question: "Con la F: Ciudad-estado clave del Renacimiento.", answer: "Florencia" },
  { id: "historia_F_009", topic: "historia", letter: "F", question: "Con la F: Título del monarca del Antiguo Egipto.", answer: "Faraón" },
  { id: "historia_F_010", topic: "historia", letter: "F", question: "Con la F: Archipiélago con pasado colonial español y cambio en 1898.", answer: "Filipinas" },
  { id: "historia_F_011", topic: "historia", letter: "F", question: "Con la F: Modelo que distribuye poder entre regiones y centro.", answer: "Federalismo" },
  { id: "historia_F_012", topic: "historia", letter: "F", question: "Con la F: Región estratégica en guerras europeas .", answer: "Flandes" },
  { id: "historia_F_013", topic: "historia", letter: "F", question: "Con la F: Arma de fuego que marcó guerras modernas.", answer: "Fusil" },
  { id: "historia_F_014", topic: "historia", letter: "F", question: "Con la F: Guerras civiles francesas del siglo XVII .", answer: "Fronde" },
  { id: "historia_F_015", topic: "historia", letter: "F", question: "Con la F: Tecnología clave de la Revolución Industrial.", answer: "Ferrocarril" },
  { id: "historia_G_001", topic: "historia", letter: "G", question: "Con la G: Conflicto armado entre estados o grupos.", answer: "Guerra" },
  { id: "historia_G_002", topic: "historia", letter: "G", question: "Con la G: Conflicto interno; en España, 1936–1939 es referencia central.", answer: "GuerraCivil" },
  { id: "historia_G_003", topic: "historia", letter: "G", question: "Con la G: Combatiente de espectáculos en la Roma antigua.", answer: "Gladiador" },
  { id: "historia_G_004", topic: "historia", letter: "G", question: "Con la G: Figura asociada a la imprenta de tipos móviles en Europa.", answer: "Gutenberg" },
  { id: "historia_G_005", topic: "historia", letter: "G", question: "Con la G: Exterminio sistemático de un grupo.", answer: "Genocidio" },
  { id: "historia_G_006", topic: "historia", letter: "G", question: "Con la G: Reino nazarí y ciudad clave en 1492.", answer: "Granada" },
  { id: "historia_G_007", topic: "historia", letter: "G", question: "Con la G: Civilización clásica influyente en política y cultura.", answer: "Grecia" },
  { id: "historia_G_008", topic: "historia", letter: "G", question: "Con la G: Instrumento asociado a ejecuciones en la Revolución Francesa.", answer: "Guillotina" },
  { id: "historia_G_009", topic: "historia", letter: "G", question: "Con la G: Barco usado en rutas coloniales españolas.", answer: "Galeón" },
  { id: "historia_G_010", topic: "historia", letter: "G", question: "Con la G: Asociación de artesanos/comerciantes en ciudades medievales.", answer: "Gremio" },
  { id: "historia_G_011", topic: "historia", letter: "G", question: "Con la G: Nombre romano para regiones de la actual Francia.", answer: "Galia" },
  { id: "historia_G_012", topic: "historia", letter: "G", question: "Con la G: Líder de la independencia india con resistencia no violenta.", answer: "Gandhi" },
  { id: "historia_G_013", topic: "historia", letter: "G", question: "Con la G: Toma del poder por la fuerza .", answer: "Golpe" },
  { id: "historia_G_014", topic: "historia", letter: "G", question: "Con la G: Ciudad símbolo por el bombardeo de 1937.", answer: "Guernica" },
  { id: "historia_G_015", topic: "historia", letter: "G", question: "Con la G: Policía secreta nazi.", answer: "Gestapo" },
  { id: "historia_H_001", topic: "historia", letter: "H", question: "Con la H: Asesinato masivo planificado por el régimen nazi.", answer: "Holocausto" },
  { id: "historia_H_002", topic: "historia", letter: "H", question: "Con la H: Dinastía europea que gobernó la monarquía hispánica .", answer: "Habsburgo" },
  { id: "historia_H_003", topic: "historia", letter: "H", question: "Con la H: Ciudad bombardeada con arma nuclear en 1945.", answer: "Hiroshima" },
  { id: "historia_H_004", topic: "historia", letter: "H", question: "Con la H: Nombre romano para la península ibérica.", answer: "Hispania" },
  { id: "historia_H_005", topic: "historia", letter: "H", question: "Con la H: Corriente renacentista centrada en el ser humano.", answer: "Humanismo" },
  { id: "historia_H_006", topic: "historia", letter: "H", question: "Con la H: Creencia considerada contraria a doctrina oficial.", answer: "Herejía" },
  { id: "historia_H_007", topic: "historia", letter: "H", question: "Con la H: Dominio o liderazgo de un estado sobre otros.", answer: "Hegemonía" },
  { id: "historia_H_008", topic: "historia", letter: "H", question: "Con la H: Nobleza menor en la España medieval y moderna.", answer: "Hidalgo" },
  { id: "historia_H_009", topic: "historia", letter: "H", question: "Con la H: Rey babilonio asociado a un famoso código legal.", answer: "Hammurabi" },
  { id: "historia_H_010", topic: "historia", letter: "H", question: "Con la H: Término para grupos nómadas; p. ej., Horda de Oro.", answer: "Horda" },
  { id: "historia_H_011", topic: "historia", letter: "H", question: "Con la H: Liga comercial medieval del norte de Europa.", answer: "Hanseática" },
  { id: "historia_H_012", topic: "historia", letter: "H", question: "Con la H: Protestante francés en guerras de religión.", answer: "Huguenote" },
  { id: "historia_H_013", topic: "historia", letter: "H", question: "Con la H: Administración fiscal; clave en Estados modernos.", answer: "Hacienda" },
  { id: "historia_H_014", topic: "historia", letter: "H", question: "Con la H: Emperador japonés durante gran parte de la II Guerra Mundial.", answer: "Hirohito" },
  { id: "historia_H_015", topic: "historia", letter: "H", question: "Con la H: Modelo astronómico-histórico que desplazó el geocentrismo.", answer: "Heliocentrismo" },
  { id: "historia_I_001", topic: "historia", letter: "I", question: "Con la I: Estado que domina grandes territorios y pueblos.", answer: "Imperio" },
  { id: "historia_I_002", topic: "historia", letter: "I", question: "Con la I: Movimiento intelectual del siglo XVIII.", answer: "Ilustración" },
  { id: "historia_I_003", topic: "historia", letter: "I", question: "Con la I: Transformación por fábricas, máquinas y urbanización.", answer: "Industrialización" },
  { id: "historia_I_004", topic: "historia", letter: "I", question: "Con la I: Institución para perseguir herejías en Europa y España.", answer: "Inquisición" },
  { id: "historia_I_005", topic: "historia", letter: "I", question: "Con la I: Emancipación política de colonias o regiones.", answer: "Independencia" },
  { id: "historia_I_006", topic: "historia", letter: "I", question: "Con la I: Expansión de potencias en s. XIX–XX.", answer: "Imperialismo" },
  { id: "historia_I_007", topic: "historia", letter: "I", question: "Con la I: Periodo vinculado a Isabel II en España .", answer: "Isabelina" },
  { id: "historia_I_008", topic: "historia", letter: "I", question: "Con la I: Levantamiento armado o rebelión.", answer: "Insurrección" },
  { id: "historia_I_009", topic: "historia", letter: "I", question: "Con la I: Zona estratégica; p. ej., Panamá en rutas y geopolítica.", answer: "Istmo" },
  { id: "historia_I_010", topic: "historia", letter: "I", question: "Con la I: Destrucción de imágenes religiosas; episodios en Bizancio.", answer: "Iconoclasia" },
  { id: "historia_I_011", topic: "historia", letter: "I", question: "Con la I: Nombre histórico-geográfico de la península ibérica.", answer: "Iberia" },
  { id: "historia_I_012", topic: "historia", letter: "I", question: "Con la I: Fenómeno económico relevante en crisis históricas.", answer: "Inflación" },
  { id: "historia_I_013", topic: "historia", letter: "I", question: "Con la I: Región colonial francesa y foco de guerras del s. XX.", answer: "Indochina" },
  { id: "historia_I_014", topic: "historia", letter: "I", question: "Con la I: País con historia de independencia y conflicto .", answer: "Irlanda" },
  { id: "historia_I_015", topic: "historia", letter: "I", question: "Con la I: Ciudad romana en Hispania, cerca de Sevilla.", answer: "Itálica" },
  { id: "historia_J_001", topic: "historia", letter: "J", question: "Con la J: Ciudad clave en religiones y cruzadas.", answer: "Jerusalén" },
  { id: "historia_J_002", topic: "historia", letter: "J", question: "Con la J: Orden religiosa con impacto educativo y político global.", answer: "Jesuitas" },
  { id: "historia_J_003", topic: "historia", letter: "J", question: "Con la J: Estado clave en modernización e historia del siglo XX.", answer: "Japón" },
  { id: "historia_J_004", topic: "historia", letter: "J", question: "Con la J: Grupo radical en la Revolución Francesa.", answer: "Jacobinos" },
  { id: "historia_J_005", topic: "historia", letter: "J", question: "Con la J: Órgano de gobierno; juntas en crisis políticas y guerras.", answer: "Junta" },
  { id: "historia_J_006", topic: "historia", letter: "J", question: "Con la J: Soldado de élite del Imperio Otomano.", answer: "Jenízaro" },
  { id: "historia_J_007", topic: "historia", letter: "J", question: "Con la J: Batalla naval importante de la I Guerra Mundial.", answer: "Jutlandia" },
  { id: "historia_J_008", topic: "historia", letter: "J", question: "Con la J: Celebración religiosa con impacto social e histórico.", answer: "Jubileo" },
  { id: "historia_J_009", topic: "historia", letter: "J", question: "Con la J: Material valioso en culturas antiguas .", answer: "Jade" },
  { id: "historia_J_010", topic: "historia", letter: "J", question: "Con la J: Deidad romana; referencia cultural en historia clásica.", answer: "Jano" },
  { id: "historia_J_011", topic: "historia", letter: "J", question: "Con la J: Emperador bizantino asociado a reformas y codificación legal.", answer: "Justiniano" },
  { id: "historia_J_012", topic: "historia", letter: "J", question: "Con la J: Sistema de escritura del Antiguo Egipto.", answer: "Jeroglífico" },
  { id: "historia_J_013", topic: "historia", letter: "J", question: "Con la J: Acto político-legal clave en monarquías, constituciones y ejércitos.", answer: "Juramento" },
  { id: "historia_J_014", topic: "historia", letter: "J", question: "Con la J: Conjunto de hechos en un día; también “jornadas” revolucionarias.", answer: "Jornada" },
  { id: "historia_J_015", topic: "historia", letter: "J", question: "Con la J: Estructura de rangos en Iglesia, ejército o administración.", answer: "Jerarquía" },
  { id: "historia_L_001", topic: "historia", letter: "L", question: "Con la L: Ideología que impulsa derechos y limitación del poder.", answer: "Liberalismo" },
  { id: "historia_L_002", topic: "historia", letter: "L", question: "Con la L: Unidad militar romana; también término moderno.", answer: "Legión" },
  { id: "historia_L_003", topic: "historia", letter: "L", question: "Con la L: Corriente protestante iniciada por Lutero.", answer: "Luteranismo" },
  { id: "historia_L_004", topic: "historia", letter: "L", question: "Con la L: Rebelión o sublevación contra un poder.", answer: "Levantamiento" },
  { id: "historia_L_005", topic: "historia", letter: "L", question: "Con la L: Gran propiedad rural; clave en historia agraria.", answer: "Latifundio" },
  { id: "historia_L_006", topic: "historia", letter: "L", question: "Con la L: Batalla naval de 1571 contra el Imperio Otomano.", answer: "Lepanto" },
  { id: "historia_L_007", topic: "historia", letter: "L", question: "Con la L: Sitio famoso durante la II Guerra Mundial.", answer: "Leningrado" },
  { id: "historia_L_008", topic: "historia", letter: "L", question: "Con la L: Ciudad clave del imperio británico e industrialización.", answer: "Londres" },
  { id: "historia_L_009", topic: "historia", letter: "L", question: "Con la L: Tratado de 1923 tras el colapso otomano.", answer: "Lausana" },
  { id: "historia_L_010", topic: "historia", letter: "L", question: "Con la L: Normas; códigos legales estructuran sociedades históricas.", answer: "Leyes" },
  { id: "historia_L_011", topic: "historia", letter: "L", question: "Con la L: Frontera fortificada del Imperio Romano.", answer: "Limes" },
  { id: "historia_L_012", topic: "historia", letter: "L", question: "Con la L: País con historia en Europa oriental y el siglo XX.", answer: "Lituania" },
  { id: "historia_L_013", topic: "historia", letter: "L", question: "Con la L: Región disputada entre Francia y Alemania.", answer: "Lorena" },
  { id: "historia_L_014", topic: "historia", letter: "L", question: "Con la L: Provincia romana; origen de términos ligados a Portugal.", answer: "Lusitania" },
  { id: "historia_L_015", topic: "historia", letter: "L", question: "Con la L: Organización de suministros; crucial en guerras e imperios.", answer: "Logística" },
  { id: "historia_M_001", topic: "historia", letter: "M", question: "Con la M: Forma de gobierno encabezada por un rey o reina.", answer: "Monarquía" },
  { id: "historia_M_002", topic: "historia", letter: "M", question: "Con la M: Modelo económico moderno basado en comercio y metales.", answer: "Mercantilismo" },
  { id: "historia_M_003", topic: "historia", letter: "M", question: "Con la M: Red de sociabilidad con presencia en historia moderna.", answer: "Masonería" },
  { id: "historia_M_004", topic: "historia", letter: "M", question: "Con la M: Figura histórica y religiosa fundacional del islam.", answer: "Mahoma" },
  { id: "historia_M_005", topic: "historia", letter: "M", question: "Con la M: Relacionado con el Imperio Mongol de GengisKan.", answer: "Mongol" },
  { id: "historia_M_006", topic: "historia", letter: "M", question: "Con la M: Explorador asociado a la primera vuelta al mundo.", answer: "Magallanes" },
  { id: "historia_M_007", topic: "historia", letter: "M", question: "Con la M: Región cultural de civilizaciones como maya y mexica.", answer: "Mesoamérica" },
  { id: "historia_M_008", topic: "historia", letter: "M", question: "Con la M: Región entre Tigris y Éufrates, cuna de civilizaciones.", answer: "Mesopotamia" },
  { id: "historia_M_009", topic: "historia", letter: "M", question: "Con la M: Elemento defensivo; símbolo moderno: Muro de Berlín.", answer: "Muro" },
  { id: "historia_M_010", topic: "historia", letter: "M", question: "Con la M: Proceso de cambios políticos, económicos y sociales .", answer: "Modernización" },
  { id: "historia_M_011", topic: "historia", letter: "M", question: "Con la M: Mezcla cultural en contextos coloniales.", answer: "Mestizaje" },
  { id: "historia_M_012", topic: "historia", letter: "M", question: "Con la M: Texto político programático en revoluciones y movimientos.", answer: "Manifiesto" },
  { id: "historia_M_013", topic: "historia", letter: "M", question: "Con la M: Guerrilla antifranquista en España tras la Guerra Civil.", answer: "Maquis" },
  { id: "historia_M_014", topic: "historia", letter: "M", question: "Con la M: Acuerdo de 1938 previo a la II Guerra Mundial.", answer: "Munich" },
  { id: "historia_M_015", topic: "historia", letter: "M", question: "Con la M: Movimiento de población a lo largo del tiempo.", answer: "Migración" },
  { id: "historia_N_001", topic: "historia", letter: "N", question: "Con la N: Ideología que centra identidad política en la nación.", answer: "Nacionalismo" },
  { id: "historia_N_002", topic: "historia", letter: "N", question: "Con la N: Ideología del TercerReich bajo Hitler.", answer: "Nazismo" },
  { id: "historia_N_003", topic: "historia", letter: "N", question: "Con la N: Periodo prehistórico con agricultura y sedentarismo.", answer: "Neolítico" },
  { id: "historia_N_004", topic: "historia", letter: "N", question: "Con la N: Líder francés que transformó Europa.", answer: "Napoleón" },
  { id: "historia_N_005", topic: "historia", letter: "N", question: "Con la N: Juicios a líderes nazis tras la II Guerra Mundial.", answer: "Nuremberg" },
  { id: "historia_N_006", topic: "historia", letter: "N", question: "Con la N: Río clave para la civilización egipcia.", answer: "Nilo" },
  { id: "historia_N_007", topic: "historia", letter: "N", question: "Con la N: Modo de vida de pueblos sin asentamiento fijo.", answer: "Nómada" },
  { id: "historia_N_008", topic: "historia", letter: "N", question: "Con la N: Estamento privilegiado en sociedades medievales y modernas.", answer: "Nobleza" },
  { id: "historia_N_009", topic: "historia", letter: "N", question: "Con la N: Política de no participar en guerra.", answer: "Neutralidad" },
  { id: "historia_N_010", topic: "historia", letter: "N", question: "Con la N: Reacción política contra inmigración; fenómeno histórico.", answer: "Nativismo" },
  { id: "historia_N_011", topic: "historia", letter: "N", question: "Con la N: Comunidad política; concepto clave desde s. XVIII–XIX.", answer: "Nación" },
  { id: "historia_N_012", topic: "historia", letter: "N", question: "Con la N: Dirección/polo; también referencia a regiones y frentes históricos.", answer: "Norte" },
  { id: "historia_N_013", topic: "historia", letter: "N", question: "Con la N: Práctica/tecnología que permitió exploraciones oceánicas.", answer: "Navegación" },
  { id: "historia_N_014", topic: "historia", letter: "N", question: "Con la N: Proceso diplomático para pactos, tratados o paz.", answer: "Negociación" },
  { id: "historia_N_015", topic: "historia", letter: "N", question: "Con la N: Líder egipcio del siglo XX asociado al panarabismo.", answer: "Nasser" },
  { id: "historia_Ñ_001", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: País europeo.", answer: "España" },
  { id: "historia_Ñ_002", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Unidad temporal para fechar hechos.", answer: "Año" },
  { id: "historia_Ñ_003", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Territorio feudal bajo un señor.", answer: "Señorío" },
  { id: "historia_Ñ_004", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Roca emblemática; p. ej., Gibraltar.", answer: "Peñón" },
  { id: "historia_Ñ_005", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Escenario de fronteras, guerras y refugios.", answer: "Montaña" },
  { id: "historia_Ñ_006", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Tema de historia social: infancia y trabajo infantil.", answer: "Niñez" },
  { id: "historia_Ñ_007", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Artillería que transformó guerras modernas.", answer: "Cañón" },
  { id: "historia_Ñ_008", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Empresa histórica; p. ej., CompañíaDeIndias.", answer: "Compañía" },
  { id: "historia_Ñ_009", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Palabra común en diarios y crónicas.", answer: "Mañana" },
  { id: "historia_Ñ_010", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Adjetivo en apodos y títulos .", answer: "Pequeño" },
  { id: "historia_Ñ_011", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Educación como política pública en historia contemporánea.", answer: "Enseñanza" },
  { id: "historia_Ñ_012", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Vía/itinerario rural; historia agraria.", answer: "Cañada" },
  { id: "historia_Ñ_013", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Motivo en discursos y memorias.", answer: "Sueño" },
  { id: "historia_Ñ_014", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Señales y bandos; comunicación en guerras.", answer: "Señal" },
  { id: "historia_Ñ_015", topic: "historia", letter: "Ñ", question: "Contiene la Ñ: Sentimiento ligado a exilios y migraciones.", answer: "Añoranza" },
  { id: "historia_O_001", topic: "historia", letter: "O", question: "Con la O: Relacionado con el Imperio Otomano.", answer: "Otomano" },
  { id: "historia_O_002", topic: "historia", letter: "O", question: "Con la O: Resistencia política frente a un gobierno o régimen.", answer: "Oposición" },
  { id: "historia_O_003", topic: "historia", letter: "O", question: "Con la O: Gobierno de pocos; concepto político histórico.", answer: "Oligarquía" },
  { id: "historia_O_004", topic: "historia", letter: "O", question: "Con la O: Institución; órdenes militares y religiosas medievales.", answer: "Orden" },
  { id: "historia_O_005", topic: "historia", letter: "O", question: "Con la O: Referencia geográfica-cultural en historia euroasiática.", answer: "Oriente" },
  { id: "historia_O_006", topic: "historia", letter: "O", question: "Con la O: Bloque cultural/político; clave en GuerraFría.", answer: "Occidente" },
  { id: "historia_O_007", topic: "historia", letter: "O", question: "Con la O: Control militar de un territorio.", answer: "Ocupación" },
  { id: "historia_O_008", topic: "historia", letter: "O", question: "Con la O: Recurso histórico en imperios y colonización.", answer: "Oro" },
  { id: "historia_O_009", topic: "historia", letter: "O", question: "Con la O: Corriente política francesa ligada a la Casa de Orleans.", answer: "Orleanismo" },
  { id: "historia_O_010", topic: "historia", letter: "O", question: "Con la O: Institución religiosa antigua .", answer: "Oráculo" },
  { id: "historia_O_011", topic: "historia", letter: "O", question: "Con la O: Civilización mesoamericana temprana.", answer: "Olmeca" },
  { id: "historia_O_012", topic: "historia", letter: "O", question: "Con la O: Rama cristiana; Bizancio y Europa oriental.", answer: "Ortodoxia" },
  { id: "historia_O_013", topic: "historia", letter: "O", question: "Con la O: Punto clave en rutas caravaneras y comercio del desierto.", answer: "Oasis" },
  { id: "historia_O_014", topic: "historia", letter: "O", question: "Con la O: Relacionado con la ONU y el orden internacional de posguerra.", answer: "Onusiano" },
  { id: "historia_O_015", topic: "historia", letter: "O", question: "Con la O: Acuerdos de Oslo; proceso de paz contemporáneo.", answer: "Oslo" },
  { id: "historia_P_001", topic: "historia", letter: "P", question: "Con la P: Periodo anterior a la escritura.", answer: "Prehistoria" },
  { id: "historia_P_002", topic: "historia", letter: "P", question: "Con la P: Movimiento religioso iniciado en la Reforma.", answer: "Protestantismo" },
  { id: "historia_P_003", topic: "historia", letter: "P", question: "Con la P: Epidemia histórica; la peste negra marcó Europa medieval.", answer: "Peste" },
  { id: "historia_P_004", topic: "historia", letter: "P", question: "Con la P: Periodo de relativa paz en el Imperio Romano.", answer: "PaxRomana" },
  { id: "historia_P_005", topic: "historia", letter: "P", question: "Con la P: Forma geográfica; península ibérica en historia europea.", answer: "Península" },
  { id: "historia_P_006", topic: "historia", letter: "P", question: "Con la P: Estructura emblemática del Antiguo Egipto.", answer: "Pirámide" },
  { id: "historia_P_007", topic: "historia", letter: "P", question: "Con la P: Líder argentino asociado al peronismo.", answer: "Perón" },
  { id: "historia_P_008", topic: "historia", letter: "P", question: "Con la P: Movimiento político argentino del siglo XX.", answer: "Peronismo" },
  { id: "historia_P_009", topic: "historia", letter: "P", question: "Con la P: Clase trabajadora industrial; concepto clave en marxismo.", answer: "Proletariado" },
  { id: "historia_P_010", topic: "historia", letter: "P", question: "Con la P: Difusión persuasiva, central en guerras y regímenes.", answer: "Propaganda" },
  { id: "historia_P_011", topic: "historia", letter: "P", question: "Con la P: División territorial; p. ej., partición de India .", answer: "Partición" },
  { id: "historia_P_012", topic: "historia", letter: "P", question: "Con la P: Territorio bajo control de una potencia .", answer: "Protectorado" },
  { id: "historia_P_013", topic: "historia", letter: "P", question: "Con la P: Hostigamiento sistemático de grupos .", answer: "Persecución" },
  { id: "historia_P_014", topic: "historia", letter: "P", question: "Con la P: Votación directa sobre una cuestión política.", answer: "Plebiscito" },
  { id: "historia_P_015", topic: "historia", letter: "P", question: "Con la P: Bienes culturales e históricos protegidos.", answer: "Patrimonio" },
  { id: "historia_Q_001", topic: "historia", letter: "Q", question: "Contiene la Q: Caballero andante protagonista de la novela más famosa de la literatura española del Siglo de Oro, escrita por Miguel de Cervantes.", answer: "Quijote" },
  { id: "historia_Q_002", topic: "historia", letter: "Q", question: "Contiene la Q: Dinastía china que unificó China.", answer: "Qin" },
  { id: "historia_Q_003", topic: "historia", letter: "Q", question: "Contiene la Q: Sistema andino de cuerdas y nudos para registro.", answer: "Quipu" },
  { id: "historia_Q_004", topic: "historia", letter: "Q", question: "Contiene la Q: Deidad mesoamericana; referencia histórico-cultural.", answer: "Quetzalcoatl" },
  { id: "historia_Q_005", topic: "historia", letter: "Q", question: "Contiene la Q: Número mínimo para decisiones en asambleas.", answer: "Quorum" },
  { id: "historia_Q_006", topic: "historia", letter: "Q", question: "Contiene la Q: Recaudación; en historia cultural y propaganda.", answer: "Taquilla" },
  { id: "historia_Q_007", topic: "historia", letter: "Q", question: "Contiene la Q: Balance de poder entre estados.", answer: "Equilibrio" },
  { id: "historia_Q_008", topic: "historia", letter: "Q", question: "Contiene la Q: En exilios, símbolo de desplazamiento.", answer: "Equipaje" },
  { id: "historia_Q_009", topic: "historia", letter: "Q", question: "Contiene la Q: Acto de destruir mediante fuego, como la quema de libros durante la Inquisición o en regímenes autoritarios.", answer: "Quema" },
  { id: "historia_Q_010", topic: "historia", letter: "Q", question: "Contiene la Q: Ruptura histórica o institucional.", answer: "Quiebre" },
  { id: "historia_Q_011", topic: "historia", letter: "Q", question: "Contiene la Q: Modelo o estructura de organización temporal usado en periodización histórica para dividir el tiempo en etapas.", answer: "Esquema" },
  { id: "historia_Q_012", topic: "historia", letter: "Q", question: "Contiene la Q: Sistema de reclutamiento militar.", answer: "Quinta" },
  { id: "historia_Q_013", topic: "historia", letter: "Q", question: "Contiene la Q: Reunión nocturna de brujas y demonios según la tradición popular, asociada a la persecución de brujería en la Edad Media y Moderna.", answer: "Aquelarre" },
  { id: "historia_Q_014", topic: "historia", letter: "Q", question: "Contiene la Q: Término ligado a ritos; aparece en historia cultural.", answer: "Requiem" },
  { id: "historia_Q_015", topic: "historia", letter: "Q", question: "Contiene la Q: Idea imposible; metáfora en discursos políticos.", answer: "Quimera" },
  { id: "historia_R_001", topic: "historia", letter: "R", question: "Con la R: Periodo cultural europeo  de recuperación clásica.", answer: "Renacimiento" },
  { id: "historia_R_002", topic: "historia", letter: "R", question: "Con la R: Movimiento religioso del s. XVI asociado a Lutero.", answer: "Reforma" },
  { id: "historia_R_003", topic: "historia", letter: "R", question: "Con la R: Cambio radical; p. ej., Francesa o Industrial.", answer: "Revolución" },
  { id: "historia_R_004", topic: "historia", letter: "R", question: "Con la R: Proceso medieval en la península ibérica.", answer: "Reconquista" },
  { id: "historia_R_005", topic: "historia", letter: "R", question: "Con la R: Forma de Estado sin monarca.", answer: "República" },
  { id: "historia_R_006", topic: "historia", letter: "R", question: "Con la R: Civilización e imperio central en historia de Europa.", answer: "Roma" },
  { id: "historia_R_007", topic: "historia", letter: "R", question: "Con la R: Estado con historia imperial, soviética y contemporánea.", answer: "Rusia" },
  { id: "historia_R_008", topic: "historia", letter: "R", question: "Con la R: Ideología/discriminación con impacto histórico.", answer: "Racismo" },
  { id: "historia_R_009", topic: "historia", letter: "R", question: "Con la R: Sistema de raciones en guerras y posguerra.", answer: "Racionamiento" },
  { id: "historia_R_010", topic: "historia", letter: "R", question: "Con la R: Figura influyente en la Rusia zarista previa a 1917.", answer: "Rasputin" },
  { id: "historia_R_011", topic: "historia", letter: "R", question: "Con la R: Elemento clave del ferrocarril en industrialización.", answer: "Riel" },
  { id: "historia_R_012", topic: "historia", letter: "R", question: "Con la R: Ciudad histórica; también ruta de control  en guerra.", answer: "Ronda" },
  { id: "historia_R_013", topic: "historia", letter: "R", question: "Con la R: Caída económica; p. ej., GranDepresión.", answer: "Recesión" },
  { id: "historia_R_014", topic: "historia", letter: "R", question: "Con la R: Votación directa sobre cuestiones políticas.", answer: "Referéndum" },
  { id: "historia_R_015", topic: "historia", letter: "R", question: "Con la R: Movimientos contra ocupaciones o dictaduras.", answer: "Resistencia" },
  { id: "historia_S_001", topic: "historia", letter: "S", question: "Con la S: Periodo cultural español .", answer: "SigloDeOro" },
  { id: "historia_S_002", topic: "historia", letter: "S", question: "Con la S: Ideología política centrada en igualdad social.", answer: "Socialismo" },
  { id: "historia_S_003", topic: "historia", letter: "S", question: "Con la S: Derecho a votar; luchas por sufragio universal.", answer: "Sufragio" },
  { id: "historia_S_004", topic: "historia", letter: "S", question: "Con la S: Régimen español de 1931–1939.", answer: "SegundaRepública" },
  { id: "historia_S_005", topic: "historia", letter: "S", question: "Con la S: Relacionado con la URSS.", answer: "Soviético" },
  { id: "historia_S_006", topic: "historia", letter: "S", question: "Con la S: Región clave en colonización y rutas históricas.", answer: "Sahara" },
  { id: "historia_S_007", topic: "historia", letter: "S", question: "Con la S: Ciudad asociada al inicio de la I Guerra Mundial.", answer: "Sarajevo" },
  { id: "historia_S_008", topic: "historia", letter: "S", question: "Con la S: Esclavo rebelde de la Roma antigua.", answer: "Spartaco" },
  { id: "historia_S_009", topic: "historia", letter: "S", question: "Con la S: Civilización antigua de Mesopotamia.", answer: "Sumer" },
  { id: "historia_S_010", topic: "historia", letter: "S", question: "Con la S: Institución política; Roma y sistemas modernos.", answer: "Senado" },
  { id: "historia_S_011", topic: "historia", letter: "S", question: "Con la S: Organización de trabajadores; historia laboral.", answer: "Sindicato" },
  { id: "historia_S_012", topic: "historia", letter: "S", question: "Con la S: Nombre histórico de Tailandia.", answer: "Siam" },
  { id: "historia_S_013", topic: "historia", letter: "S", question: "Con la S: Separación de religión y Estado en vida pública.", answer: "Secularización" },
  { id: "historia_S_014", topic: "historia", letter: "S", question: "Con la S: Movimiento político ligado a la creación de Israel.", answer: "Sionismo" },
  { id: "historia_S_015", topic: "historia", letter: "S", question: "Con la S: Sistema de dependencia campesina en Europa.", answer: "Servidumbre" },
  { id: "historia_T_001", topic: "historia", letter: "T", question: "Con la T: Acuerdo formal entre estados.", answer: "Tratado" },
  { id: "historia_T_002", topic: "historia", letter: "T", question: "Con la T: Sistema defensivo típico de la I Guerra Mundial.", answer: "Trinchera" },
  { id: "historia_T_003", topic: "historia", letter: "T", question: "Con la T: Régimen que busca controlar sociedad y vida privada.", answer: "Totalitarismo" },
  { id: "historia_T_004", topic: "historia", letter: "T", question: "Con la T: Cambio de régimen; en España, transición democrática.", answer: "Transición" },
  { id: "historia_T_005", topic: "historia", letter: "T", question: "Con la T: Pago impuesto por un poder; común en imperios.", answer: "Tributo" },
  { id: "historia_T_006", topic: "historia", letter: "T", question: "Con la T: Capital mexica; centro del imperio azteca.", answer: "Tenochtitlan" },
  { id: "historia_T_007", topic: "historia", letter: "T", question: "Con la T: Sistema político donde autoridad religiosa gobierna.", answer: "Teocracia" },
  { id: "historia_T_008", topic: "historia", letter: "T", question: "Con la T: Uso de violencia con fines políticos; historia contemporánea.", answer: "Terrorismo" },
  { id: "historia_T_009", topic: "historia", letter: "T", question: "Con la T: Reinos de taifas en AlAndalus tras fragmentación del califato.", answer: "Taifa" },
  { id: "historia_T_010", topic: "historia", letter: "T", question: "Con la T: Suspensión temporal de hostilidades.", answer: "Tregua" },
  { id: "historia_T_011", topic: "historia", letter: "T", question: "Con la T: Relacionado con la guerra de Troya .", answer: "Troyano" },
  { id: "historia_T_012", topic: "historia", letter: "T", question: "Con la T: Pueblos de la estepa euroasiática .", answer: "Tártaro" },
  { id: "historia_T_013", topic: "historia", letter: "T", question: "Con la T: Valor debatido en guerras de religión y derechos civiles.", answer: "Tolerancia" },
  { id: "historia_T_014", topic: "historia", letter: "T", question: "Con la T: Inquisidor general español; figura histórica polémica.", answer: "Torquemada" },
  { id: "historia_T_015", topic: "historia", letter: "T", question: "Con la T: Símbolo del poder monárquico.", answer: "Trono" },
  { id: "historia_U_001", topic: "historia", letter: "U", question: "Con la U: Proceso de formar un solo Estado .", answer: "Unificación" },
  { id: "historia_U_002", topic: "historia", letter: "U", question: "Con la U: Estado soviético del siglo XX .", answer: "URSS" },
  { id: "historia_U_003", topic: "historia", letter: "U", question: "Con la U: Crecimiento de ciudades; clave en industrialización.", answer: "Urbanización" },
  { id: "historia_U_004", topic: "historia", letter: "U", question: "Con la U: Ideal político; influyó en pensamiento moderno.", answer: "Utopía" },
  { id: "historia_U_005", topic: "historia", letter: "U", question: "Con la U: Término para territorios de ultramar en imperios.", answer: "Ultramar" },
  { id: "historia_U_006", topic: "historia", letter: "U", question: "Con la U: Institución clave para élites y conocimiento desde la Edad Media.", answer: "Universidad" },
  { id: "historia_U_007", topic: "historia", letter: "U", question: "Con la U: Alianzas y uniones políticas .", answer: "Unión" },
  { id: "historia_U_008", topic: "historia", letter: "U", question: "Con la U: Recurso central en historia nuclear del s. XX.", answer: "Uranio" },
  { id: "historia_U_009", topic: "historia", letter: "U", question: "Con la U: Territorio clave en historia europea del siglo XX.", answer: "Ucrania" },
  { id: "historia_U_010", topic: "historia", letter: "U", question: "Con la U: Toma ilegítima del poder.", answer: "Usurpación" },
  { id: "historia_U_011", topic: "historia", letter: "U", question: "Con la U: Límite; se usa en periodizaciones históricas .", answer: "Umbral" },
  { id: "historia_U_012", topic: "historia", letter: "U", question: "Con la U: Clase religiosa islámica con influencia histórica.", answer: "Ulema" },
  { id: "historia_U_013", topic: "historia", letter: "U", question: "Con la U: Región asociada al conflicto en IrlandaDelNorte.", answer: "Ulster" },
  { id: "historia_U_014", topic: "historia", letter: "U", question: "Con la U: País con historia de independencia y reformas sociales.", answer: "Uruguay" },
  { id: "historia_U_015", topic: "historia", letter: "U", question: "Con la U: Relacionado con vida en ciudades .", answer: "Urbano" },
  { id: "historia_V_001", topic: "historia", letter: "V", question: "Con la V: Pueblos nórdicos conocidos por exploración y comercio.", answer: "Vikingos" },
  { id: "historia_V_002", topic: "historia", letter: "V", question: "Con la V: Unidad administrativa colonial en América.", answer: "Virreinato" },
  { id: "historia_V_003", topic: "historia", letter: "V", question: "Con la V: Sede del papado; influencia histórica europea.", answer: "Vaticano" },
  { id: "historia_V_004", topic: "historia", letter: "V", question: "Con la V: Relación feudal entre señor y vasallo.", answer: "Vasallaje" },
  { id: "historia_V_005", topic: "historia", letter: "V", question: "Con la V: Ciudad clave en congresos y diplomacia .", answer: "Viena" },
  { id: "historia_V_006", topic: "historia", letter: "V", question: "Con la V: Tratado que cerró la I Guerra Mundial .", answer: "Versalles" },
  { id: "historia_V_007", topic: "historia", letter: "V", question: "Con la V: País central en una guerra clave del siglo XX.", answer: "Vietnam" },
  { id: "historia_V_008", topic: "historia", letter: "V", question: "Con la V: Movimientos culturales/políticos de ruptura en s. XX.", answer: "Vanguardia" },
  { id: "historia_V_009", topic: "historia", letter: "V", question: "Con la V: Acto electoral; base de democracia moderna.", answer: "Voto" },
  { id: "historia_V_010", topic: "historia", letter: "V", question: "Con la V: Enfermedad con impacto histórico y en vacunación.", answer: "Viruela" },
  { id: "historia_V_011", topic: "historia", letter: "V", question: "Con la V: Filósofo ilustrado influyente.", answer: "Voltaire" },
  { id: "historia_V_012", topic: "historia", letter: "V", question: "Con la V: Venganza familiar; práctica histórica en algunas sociedades.", answer: "Vendetta" },
  { id: "historia_V_013", topic: "historia", letter: "V", question: "Con la V: Apellido presente en nobleza y administración histórica .", answer: "Velasco" },
  { id: "historia_V_014", topic: "historia", letter: "V", question: "Con la V: Término alemán ligado a nacionalismo étnico .", answer: "Volkisch" },
  { id: "historia_V_015", topic: "historia", letter: "V", question: "Con la V: Explorador; de su nombre deriva “América” .", answer: "Vespucio" },
  { id: "historia_X_001", topic: "historia", letter: "X", question: "Contiene la X: Salida forzada de un país por razones políticas.", answer: "Exilio" },
  { id: "historia_X_002", topic: "historia", letter: "X", question: "Contiene la X: Viaje organizado militar/científico.", answer: "Expedición" },
  { id: "historia_X_003", topic: "historia", letter: "X", question: "Contiene la X: Crecimiento territorial.", answer: "Expansión" },
  { id: "historia_X_004", topic: "historia", letter: "X", question: "Contiene la X: Viajes para conocer territorios.", answer: "Exploración" },
  { id: "historia_X_005", topic: "historia", letter: "X", question: "Contiene la X: Desaparición de pueblos/linajes.", answer: "Extinción" },
  { id: "historia_X_006", topic: "historia", letter: "X", question: "Contiene la X: País de América del Norte que logró su independencia de España en 1821 y vivió la Revolución Mexicana de 1910.", answer: "México" },
  { id: "historia_X_007", topic: "historia", letter: "X", question: "Contiene la X: Hostilidad hacia extranjeros; fenómeno histórico.", answer: "Xenofobia" },
  { id: "historia_X_008", topic: "historia", letter: "X", question: "Contiene la X: Método de ejecución romano.", answer: "Crucifixión" },
  { id: "historia_X_009", topic: "historia", letter: "X", question: "Contiene la X: Marco histórico, social y político que rodea y da significado a un hecho o evento histórico específico.", answer: "Contexto" },
  { id: "historia_X_010", topic: "historia", letter: "X", question: "Contiene la X: Documento escrito que sirve como fuente primaria para el estudio histórico, como crónicas, cartas o tratados.", answer: "Texto" },
  { id: "historia_X_011", topic: "historia", letter: "X", question: "Contiene la X: Archiduque austriaco que fue nombrado emperador de México entre 1864 y 1867 durante la intervención francesa.", answer: "Maximiliano" },
  { id: "historia_X_012", topic: "historia", letter: "X", question: "Contiene la X: Toma legal de bienes; usada en reformas.", answer: "Expropiación" },
  { id: "historia_X_013", topic: "historia", letter: "X", question: "Contiene la X: Salida masiva de población.", answer: "Éxodo" },
  { id: "historia_X_014", topic: "historia", letter: "X", question: "Contiene la X: Descripción del aspecto físico de una persona que aparece en retratos históricos, crónicas y documentos biográficos.", answer: "Complexión" },
  { id: "historia_X_015", topic: "historia", letter: "X", question: "Contiene la X: Instrumento de navegación usado en exploraciones.", answer: "Sextante" },
  { id: "historia_Y_001", topic: "historia", letter: "Y", question: "Contiene la Y: Conferencia de 1945 entre Aliados.", answer: "Yalta" },
  { id: "historia_Y_002", topic: "historia", letter: "Y", question: "Contiene la Y: Estado del s. XX cuya disolución marcó los Balcanes.", answer: "Yugoslavia" },
  { id: "historia_Y_003", topic: "historia", letter: "Y", question: "Contiene la Y: Dinastía china fundada por los mongoles.", answer: "Yuan" },
  { id: "historia_Y_004", topic: "historia", letter: "Y", question: "Contiene la Y: Península mexicana entre el golfo de México y el Caribe, donde floreció la civilización maya y ocurrió la Guerra de Castas en el siglo XIX.", answer: "Yucatán" },
  { id: "historia_Y_005", topic: "historia", letter: "Y", question: "Contiene la Y: Civilización mesoamericana que desarrolló escritura jeroglífica, calendarios precisos y grandes ciudades como Tikal y Chichén Itzá.", answer: "Maya" },
  { id: "historia_Y_006", topic: "historia", letter: "Y", question: "Contiene la Y: Título de soberanía masculino que designa al jefe de estado en una monarquía, con poder hereditario o electivo.", answer: "Rey" },
  { id: "historia_Y_007", topic: "historia", letter: "Y", question: "Contiene la Y: Norma jurídica de carácter obligatorio aprobada por el poder legislativo que regula la vida social y política de un Estado.", answer: "Ley" },
  { id: "historia_Y_008", topic: "historia", letter: "Y", question: "Contiene la Y: Tapiz bordado del siglo XI que narra la conquista normanda de Inglaterra, importante fuente visual de la historia medieval.", answer: "Bayeux" },
  { id: "historia_Y_009", topic: "historia", letter: "Y", question: "Contiene la Y: Estado federado alemán conocido como Baviera, que fue un ducado y luego reino independiente dentro del Sacro Imperio Romano Germánico.", answer: "Bayern" },
  { id: "historia_Y_010", topic: "historia", letter: "Y", question: "Contiene la Y: Cordillera más alta del mundo en Asia que ha sido escenario de rutas comerciales históricas y conflictos entre imperios.", answer: "Himalaya" },
  { id: "historia_Y_011", topic: "historia", letter: "Y", question: "Contiene la Y: Asistencia internacional prestada por países o organizaciones a otros estados en situaciones de crisis, guerra o desarrollo económico.", answer: "Ayuda" },
  { id: "historia_Y_012", topic: "historia", letter: "Y", question: "Contiene la Y: Poeta romántico británico del siglo XIX que participó en la guerra de independencia griega y murió en Missolonghi.", answer: "Byron" },
  { id: "historia_Y_013", topic: "historia", letter: "Y", question: "Contiene la Y: Ciudad ecuatoriana donde se encontraron Simón Bolívar y José de San Martín en 1822 para coordinar la independencia sudamericana.", answer: "Guayaquil" },
  { id: "historia_Y_014", topic: "historia", letter: "Y", question: "Contiene la Y: Barco que transportó a los peregrinos puritanos desde Inglaterra a América del Norte en 1620, estableciendo la colonia de Plymouth.", answer: "Mayflower" },
  { id: "historia_Y_015", topic: "historia", letter: "Y", question: "Contiene la Y: Ciudad australiana fundada como colonia penal británica en 1788, primera colonia europea permanente en Australia.", answer: "Sydney" },
  { id: "historia_Z_001", topic: "historia", letter: "Z", question: "Con la Z: Título del monarca ruso.", answer: "Zar" },
  { id: "historia_Z_002", topic: "historia", letter: "Z", question: "Con la Z: Templo escalonado mesopotámico.", answer: "Zigurat" },
  { id: "historia_Z_003", topic: "historia", letter: "Z", question: "Con la Z: Ciudad española con asedios famosos .", answer: "Zaragoza" },
  { id: "historia_Z_004", topic: "historia", letter: "Z", question: "Con la Z: Dirigible usado en la I Guerra Mundial.", answer: "Zeppelin" },
  { id: "historia_Z_005", topic: "historia", letter: "Z", question: "Con la Z: Nombre histórico de la RDC; historia africana contemporánea.", answer: "Zaire" },
  { id: "historia_Z_006", topic: "historia", letter: "Z", question: "Con la Z: Religión antigua persa asociada a Zaratustra.", answer: "Zoroastrismo" },
  { id: "historia_Z_007", topic: "historia", letter: "Z", question: "Con la Z: Isla/puerto clave en comercio del Índico y colonización.", answer: "Zanzibar" },
  { id: "historia_Z_008", topic: "historia", letter: "Z", question: "Con la Z: Género escénico español como documento cultural.", answer: "Zarzuela" },
  { id: "historia_Z_009", topic: "historia", letter: "Z", question: "Con la Z: Metal con historia industrial y de metalurgia.", answer: "Zinc" },
  { id: "historia_Z_010", topic: "historia", letter: "Z", question: "Con la Z: Moneda polaca; historia económica moderna.", answer: "Zloty" },
  { id: "historia_Z_011", topic: "historia", letter: "Z", question: "Con la Z: Ciudad suiza ligada a reformas y exilios políticos.", answer: "Zúrich" },
  { id: "historia_Z_012", topic: "historia", letter: "Z", question: "Con la Z: Movimiento político asociado al EZLN.", answer: "Zapatismo" },
  { id: "historia_Z_013", topic: "historia", letter: "Z", question: "Con la Z: Sistema político autocrático del Imperio ruso donde el zar ejercía poder absoluto, abolido tras la Revolución de 1917.", answer: "Zarismo" },
  { id: "historia_Z_014", topic: "historia", letter: "Z", question: "Con la Z: Provincia neerlandesa que dio nombre a Nueva Zelanda y fue importante en la expansión marítima holandesa del siglo XVII.", answer: "Zelanda" },
  { id: "historia_Z_015", topic: "historia", letter: "Z", question: "Con la Z: Punto más alto en el cielo sobre el observador, usado como metáfora para describir el momento de máximo esplendor de imperios o civilizaciones.", answer: "Zenit" },
];
